### ISSUE TITLE
Ok, this is getting ridiculous...

### ISSUE THREAD

**Issue by vnjery1** [yairm210/Unciv#10001]
**Platform**
Operating system type, major version, architecture (64/32 bit).

**Version**
Where you got the game and the exact version number.

**Describe the bug**
Another out of memory bug again...

**To Reproduce**

**Platform:** Android
**Version:** 4.7.17-patch1 (Build 905)
**Rulesets:** [the Coexistence in harmony_music, Taube s Australia, Dimensiondogs governments, Modern Russia, 3rd and 4th Unique Component, Classical  World Scout Sapper plus Promotions, Warfare Expanded Lite, American Civil War mod, Unciv City State Icons, Czechoslovakia, Resourceplus, AbsoluteUnits, Empire of the SEA, Ice Breakers, Uncivilized Expansion, Civ Army Color Style Sheet, Warfare Edited, Hyperborea, Future Expansion, WW1 Nations, UnCiv Freeroads, BetterMountainFH, Alliance of Atlantic States Unciv, Civ6 Stat Icons, Assyria buffed for Unciv, Urban Area, Better Workers, Kazan Khanate, Scout Plus, Great Farmer, Unciv America Buff, Dutch Republic Unciv, Community Maps, Yet Another Civilization Mod, Knights of Malta mod, unciv trebizond mod, Dimensiondogs scaling difficulties, Super Sandbox, Byzantium Buffed, Greece plus The Middle East, Yet Another Music Pack, AquaExtension GAK, LostTec, Greater Improvements, MaOr Difficulties, Unciv Nigeria mod, Dimensiondog s Districts, All units can be automated, Civ5 CityState Music, Ancient Civilizations, Nusantara Civilizations, Yet Another Resource Mod, Illyrian Civilization, Extra Resources, Leader Mission 2 Rising Power, Extra Promotions, B2.1 Project, Soviet Union, Horses and Iron mod, Policy mod, AbsoluteUnitsXL, Brave New World, RekMODTR, LM DLC War or Peace, Fix Iroquois, wonders in different eras mod, moREsources, Nat5 Design, Future Edited, More Luxuries, Algeria, Hodgepodge mod, Unciv WWII, Papers Please=, ReSound, Samurai Expension, Civ style set by Bucketeer, Greek Civ Split, Slow Tech, Civ6 Tileset, More Challenges, New American Empire Unciv, Ukraine Mod, New England Republic Unciv, Better Pantheons, Palengke, Civ V - Gods & Kings, Greece and The Middle East Music, Additional Music Various, Outpost Mod, Civ5ExpansionMod, PolyCiv, RekMOD, City Focuses, Leader Mission, useful allres, Barbarian xp farm, Uncivilized Enhancer, Grand California Federation Unciv, Latin American_Civs, Mitteleuropa and Balkans, Congress RP, Only Mod Civilizations, Three Countries of CH, Fall of Rome, Strategic Resource Visibility, The Netherlands mod, MAP OF INDIAN SUBCONTINENT, Chronicle_Files, Rome Improvements, Chariot Archers are Mounted, Project Lantaka, Civ6 Nations for Unciv, Dogs, More Natural Wonders, Uncivilized Awakening, Victoria II Music, Modern Civilizations, Medieval Civilizations, Project Holy Roman Empire, ph bonifacio unciv, Grand Duchy of Luxembourg Unciv, Extra Units, North Korea, Project Montenegro, Unciv Fermentation, Quebec Unciv, Drug mod, Better ruins Lite, Caravans, Policies and Wonders plus, More Fauna And Flora, Extra Wonders, vox populi pantheons, Canada, Raze anything, United Nations of Europe Unciv, Icon Reskin, Malacca mod, Diminishing Returns, Great Person Wonders, Expanded Warfare, Russian Republic Unciv, Han Dynasty China, capture GP, Extra Religions, Project Manchuria, Project Felipe, BabylonUI, Pakistan Nation Unciv, Agony In Anatolia Mod, Glorious Rome, Samnites, Power to People GnK, the Coexistence in harmony, Holy Warriors, ReligionPlus, 6 Eras, Deminishing Returns Brutal Edition, Military and Religion Specialists, Project Tondo, Turkic Civilizations, Unciv Vanilla Music Pack, Peacemaker, ComplexHistory, Upgradable Scouts, Territory of Ontario Unciv, philosophy mod, WW2 Nations, Chaos Generation, Barbarians but Better, WW2FleetEurope, 5HexNBNB, The Great Unciv Rework, Swamp Expansion, 5Hex Tileset, Better ruins, Modern Russia unciv mod, Higher quality builtin sounds, More Speeds, Empire of Kosovo Unciv, Enlightenment, Scouty Scout, Historica, Extra Buildings, Project Kaigun, croatia civ, Civ6 Icons, Re Add National Treasury BNW Unciv, Difficulty_Sandbox, useful alltech, Capital Domination, Pix5 Tileset, Honor Wonders, Civ5Nations, Tyretes Tileset, Additional Music Ambient, Repairing Improvements in older mods, No Fog Of War, Resource Recyclers, Useful Mountain, Civ6 mod, Better Pantheons Lite, unciv finland mod, High Explosives Lite, Settlers Plus, Super Quick Speed, Leaders Plus, BB 2 m.crzr, Great Lake Republic Unciv, The Barbarians, China Plus, Classical Harbors, Boosted Settler, Project Serbia, Longer Victories, Earth, Singapore Nation Unciv, Higher Quality City Ambience Sounds, Dacia Unciv mod, Better Units and Natural Wonders, Unciv Religion Plus, Military Desperate Actions, Civ V - Vanilla, Alliance of American States and more  Unciv, hexatopia, Civ6 NLB Edition Tileset, Vichy France, CS Rework, Togglemod Sightbonus, Arial expanded, Cheaper National Wonders, Extra Difficulties for Religion enthusiasts, Closer Cities Distance of 0, Project Rikugun, Closer Cities Distance of 1, Unciv The New Order The Great World War, Civ 5 Icons, Mapping Tools for Unciv]
**Last Screen:** `com.unciv.ui.screens.mapeditorscreen.MapEditorScreen`

--------------------------------

Device Model: V2110
API Level: 33

--------------------------------

**Message:**
```
java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 84640 free bytes and 82KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at com.badlogic.gdx.utils.DelayedRemovalArray.<init>(DelayedRemovalArray.java:34)
	at com.badlogic.gdx.scenes.scene2d.Actor.<init>(Actor.java:60)
	at com.badlogic.gdx.scenes.scene2d.ui.Widget.<init>(Widget.java:35)
	at com.badlogic.gdx.scenes.scene2d.ui.Image.<init>(Image.java:82)
	at com.badlogic.gdx.scenes.scene2d.ui.Image.<init>(Image.java:72)
	at com.unciv.ui.images.ImageWithCustomSize.<init>(ImageWithCustomSize.kt:15)
	at com.unciv.ui.images.ImageGetter.getImage(ImageGetter.kt:188)
	at com.unciv.ui.components.tilegroups.layers.TileLayerOverlay.<init>(TileLayerOverlay.kt:19)
	at com.unciv.ui.components.tilegroups.TileGroup.<init>(TileGroup.kt:51)
	at com.unciv.ui.components.tilegroups.TileGroup.<init>(TileGroup.kt:20)
	at com.unciv.ui.screens.mapeditorscreen.EditorMapHolder.addTiles(EditorMapHolder.kt:73)
	at com.unciv.ui.screens.mapeditorscreen.EditorMapHolder.<init>(EditorMapHolder.kt:46)
	at com.unciv.ui.screens.mapeditorscreen.MapEditorScreen.newMapHolder(MapEditorScreen.kt:180)
	at com.unciv.ui.screens.mapeditorscreen.MapEditorScreen.applyRuleset(MapEditorScreen.kt:235)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorModsTab.applyControls(MapEditorModsTab.kt:98)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorModsTab.access$applyControls(MapEditorModsTab.kt:24)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorModsTab$5.invoke(MapEditorModsTab.kt:66)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorModsTab$5.invoke(MapEditorModsTab.kt:66)
	at com.unciv.ui.components.input.ActivationActionMap.activate(ActivationActionMap.kt:56)
	at com.unciv.ui.components.input.ActorAttachments.activate(ActorAttachments.kt:42)
	at com.unciv.ui.components.input.ActivationExtensionsKt.activate(ActivationExtensions.kt:17)
	at com.unciv.ui.components.input.ActivationListener.tap(ActivationListener.kt:15)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener$1.tap(ActorGestureListener.java:52)
	at com.badlogic.gdx.input.GestureDetector.touchUp(GestureDetector.java:209)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener.handle(ActorGestureListener.java:125)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:87)
	at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:426)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:472)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1582)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)

```

**Expected behavior**
Uh... mod acceptance... maybe...

**Screenshots**

**Additional context**
I gotta admit that yes, the lists that I have for mods are gargantuan and gigantic but I still got a ton of memory left and it is kinda ridiculous that Unciv is taking quite a small percentage in terms of memory in my phone. Why did it appear again tho, I don't want to delete it and reinstall it again, I have done this several times before and after a while, this OutOfMemory error keeps showing, and the first time I play Unciv, this error showing up like 6 times before I delete it and reinstall it.

**Comment by vnjery1** [comment]
It was ended abruptly again... Strange.

**Comment by yairm210** [comment]
@vnjery1 Looks like you tried to add a tile overlay, what size of file were you trying to add?
