### ISSUE TITLE
[mod][DeCiv Redux] crash when reordering construction queue

### ISSUE THREAD

**Issue by ferrosa** [yairm210/Unciv#10064]
**Platform**
OS: Linux (amd64, 5.15.0-79-generic)
Ubuntu 22.04.3 LTS

**Version**
Unciv 4.8.1 from github release page.
DeCiv Redux updated as of 5. Sept 2023.

**Describe the bug**
Game crashes upon reordering the construction queue and exiting the city screen. No crash reporter / dump collection screen is shown, straight back to the desktop. Launching from terminal and triggering the issue gives:
```
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
Exception in thread "main" java.lang.NullPointerException
	at com.unciv.ui.screens.cityscreen.ConstructionInfoTable.updateSelectedConstructionTable(ConstructionInfoTable.kt:91)
	at com.unciv.ui.screens.cityscreen.ConstructionInfoTable.update(ConstructionInfoTable.kt:51)
	at com.unciv.ui.screens.cityscreen.CityScreen.updateWithoutConstructionAndMap$core(CityScreen.kt:169)
	at com.unciv.ui.screens.cityscreen.CityScreen.update$core(CityScreen.kt:153)
	at com.unciv.ui.screens.cityscreen.CityConstructionsTable.getQueueEntry$selectQueueEntry(CityConstructionsTable.kt:350)
	at com.unciv.ui.screens.cityscreen.CityConstructionsTable.access$getQueueEntry$selectQueueEntry(CityConstructionsTable.kt:70)
	at com.unciv.ui.screens.cityscreen.CityConstructionsTable$getQueueEntry$2.invoke(CityConstructionsTable.kt:356)
	at com.unciv.ui.screens.cityscreen.CityConstructionsTable$getQueueEntry$2.invoke(CityConstructionsTable.kt:356)
	at com.unciv.ui.components.input.ActivationActionMap.activate(ActivationActionMap.kt:56)
	at com.unciv.ui.components.input.ActorAttachments.activate(ActorAttachments.kt:42)
	at com.unciv.ui.components.input.ActivationExtensionsKt.activate(ActivationExtensions.kt:17)
	at com.unciv.ui.components.input.ActivationListener.longPress(ActivationListener.kt:20)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener$1.longPress(ActorGestureListener.java:58)
	at com.badlogic.gdx.input.GestureDetector$1.run(GestureDetector.java:58)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:208)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:82)
```

**To Reproduce**
1. Open attached savegame
2. Open the city screen for _Everest Peak_
3. Rearrange the three queued buildings with 3-4 clicks to the up/down arrows (it often doesn't crash with just 1 click)
4. Hit Escape to exit the city screen

<details><summary>Saved game</summary>

```
This part of the issue template still doesn't fulfill its purpose.
"There was an error creating your Issue: body is too long, body is too long (maximum is 65536 characters)."
```
</details>

[Seaworld.zip](https://github.com/yairm210/Unciv/files/12523156/Seaworld.zip)

**Expected behavior**
No crash.

**Additional context**
Could of course be an issue with the mod. No other mods loaded.

**Comment by ferrosa** [comment]
Tried to reproduce with current master, no bug. Deployed release 4.8.3 also works without this issue.

I'd close this, but I don't know why this works now. `stage` on line 91 looks like an undefined variable.
Up to you.
