### ISSUE TITLE
Crash when selecting unit in civilopedia

### ISSUE THREAD

**Issue by Skekdog** [yairm210/Unciv#10209]
**Platform:** Android 13
**Version:** 4.8.9-patch1 (Build 918)
**Rulesets:** [Higher quality builtin sounds, Unciv Vanilla Music Pack, Higher Quality City Ambience Sounds, Civ V - Vanilla, Civ5 CityState Music, Civ V - Gods & Kings, Civ V Leader portraits, Yet Another Music Pack, North Korea]
**Last Screen:** `com.unciv.ui.screens.civilopediascreen.CivilopediaScreen`

--------------------------------

Device Model: SM-A526B
API Level: 33

--------------------------------

**Message:**
```
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/Rectangle;
	at com.unciv.ui.screens.civilopediascreen.FormattedLine.getContentSize(FormattedLine.kt:361)
	at com.unciv.ui.screens.civilopediascreen.FormattedLine.cropToContent(FormattedLine.kt:354)
	at com.unciv.ui.screens.civilopediascreen.FormattedLine.render(FormattedLine.kt:248)
	at com.unciv.ui.screens.civilopediascreen.MarkupRenderer.render(MarkupRenderer.kt:49)
	at com.unciv.ui.screens.civilopediascreen.MarkupRenderer.render$default(MarkupRenderer.kt:30)
	at com.unciv.ui.screens.civilopediascreen.ICivilopediaText$DefaultImpls.renderCivilopediaText(ICivilopediaText.kt:51)
	at com.unciv.ui.screens.civilopediascreen.SimpleCivilopediaText.renderCivilopediaText(SimpleCivilopediaText.kt:4)
	at com.unciv.ui.screens.civilopediascreen.CivilopediaScreen.selectEntry(CivilopediaScreen.kt:184)
	at com.unciv.ui.screens.civilopediascreen.CivilopediaScreen.access$selectEntry(CivilopediaScreen.kt:39)
	at com.unciv.ui.screens.civilopediascreen.CivilopediaScreen$selectCategory$3.invoke(CivilopediaScreen.kt:149)
	at com.unciv.ui.screens.civilopediascreen.CivilopediaScreen$selectCategory$3.invoke(CivilopediaScreen.kt:149)
	at com.unciv.ui.components.input.ActivationActionMap.activate(ActivationActionMap.kt:56)
	at com.unciv.ui.components.input.ActorAttachments.activate(ActorAttachments.kt:42)
	at com.unciv.ui.components.input.ActivationExtensionsKt.activate(ActivationExtensions.kt:17)
	at com.unciv.ui.components.input.ActivationListener.tap(ActivationListener.kt:15)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener$1.tap(ActorGestureListener.java:52)
	at com.badlogic.gdx.input.GestureDetector.touchUp(GestureDetector.java:209)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener.handle(ActorGestureListener.java:125)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:87)
	at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:426)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:472)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1593)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1287)
Caused by: java.lang.ClassNotFoundException: java.awt.Rectangle
	... 28 more

```

Happens if Size of Unitset art is not 0. Apparently, only on Android. Also happens in 4.8.9

**Comment by yairm210** [comment]
@SomeTroglodyte
