### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by gurkleffe** [yairm210/Unciv#10205]
**Platform:** Desktop
**Version:** 4.8.9 (Build 917)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

OS: Linux (amd64, 6.2.0-33-generic)
	Ubuntu 23.04
Java: Eclipse Adoptium Temurin-11.0.19+7
	Max Memory: 1024 MB
System default encoding: UTF-8

--------------------------------

**Comment:** I simply played the game causually. After some hours of gameplay, the game crashed when I clicked the next turn button. No mods or anything, this was my first time playing the game. Attatching error files as it is too big to paste.

--------------------------------

[crash report.txt](https://github.com/yairm210/Unciv/files/12776941/crash.report.txt)

**Comment by gurkleffe** [comment]
After restarting the game and loading it back, the same thing happens when I press the next turn button.

**Comment by yairm210** [comment]
@SeventhM regression from #10142 , I currently don't have time to debug this so I'm just going to revert that commit and release a patch

Problem is in endless loop 

```

	at com.unciv.logic.city.CityConstructions.addBuilding(CityConstructions.kt:547)
	at com.unciv.models.ruleset.Building.postBuildEvent(Building.kt:656)
	at com.unciv.models.ruleset.INonPerpetualConstruction$DefaultImpls.postBuildEvent$default(IConstruction.kt:38)
	at com.unciv.logic.city.CityConstructions.constructionComplete(CityConstructions.kt:459)
	at com.unciv.logic.city.CityConstructions.addCheapestBuildableStatBuilding(CityConstructions.kt:693)
	at com.unciv.logic.civilization.CivConstructions.addFreeStatBuildings(CivConstructions.kt:114)
	at com.unciv.logic.civilization.CivConstructions.addFreeStatsBuildings(CivConstructions.kt:105)
	at com.unciv.logic.civilization.CivConstructions.tryAddFreeBuildings(CivConstructions.kt:66)
	at com.unciv.logic.city.CityConstructions.addBuilding(CityConstructions.kt:547)
```

**Comment by yairm210** [comment]
@gurkleffe 4.8.9-patch1 rolling out now, should be available in ~10 minutes, tested locally and your game will work :)

**Comment by SeventhM** [comment]
Interesting... loop isn't technically my code, it's looping in addFreeCheapestBuilding which I didn't touch besides having it go through there instead of just free buildings
