### ISSUE TITLE
Auto save error 

### ISSUE THREAD

**Issue by fahrurx** [yairm210/Unciv#10302]
**Platform:** Android
**Version:** 4.8.11 (Build 921)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: RMX3511
API Level: 33

--------------------------------

**Message:**
```
com.badlogic.gdx.utils.GdxRuntimeException: Error writing file: SaveFiles/Autosave (External)
	at com.badlogic.gdx.files.FileHandle.writeString(FileHandle.java:386)
	at com.unciv.logic.files.UncivFiles.saveGame(UncivFiles.kt:162)
	at com.unciv.logic.files.UncivFiles.saveGame(UncivFiles.kt:151)
	at com.unciv.logic.files.UncivFiles.saveGame$default(UncivFiles.kt:149)
	at com.unciv.logic.files.UncivFiles.autoSave(UncivFiles.kt:416)
	at com.unciv.logic.files.UncivFiles$requestAutoSaveUnCloned$job$1.invokeSuspend(UncivFiles.kt:408)
	at com.unciv.logic.files.UncivFiles$requestAutoSaveUnCloned$job$1.invoke(Unknown Source:8)
	at com.unciv.logic.files.UncivFiles$requestAutoSaveUnCloned$job$1.invoke(Unknown Source:4)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher.$r8$lambda$GFMOlD6QMgmLfgwAvPAW33Ob6HE(Unknown Source:0)
	at com.unciv.utils.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Error writing file: SaveFiles/Autosave (External)
	at com.badlogic.gdx.files.FileHandle.writer(FileHandle.java:363)
	at com.badlogic.gdx.files.FileHandle.writeString(FileHandle.java:383)
	... 21 more
Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.unciv.app/files/SaveFiles/Autosave: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
	at com.badlogic.gdx.files.FileHandle.writer(FileHandle.java:355)
	... 22 more
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7919)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 24 more

```
**Save Mods:**
```
[Civ V - Gods & Kings]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```
H4sIAAAAAAAAAO1dXZPbNpb9K116md0q0yt+iaTf2s547Jk49sZO/DDlB0pid2uiFnspyY4n5f++4AdIig1AwD0gu5NJzVSSlkTi4gI4uLjnAPhttkwL9v9NutvPnv02y3ar9PbuNtsd2J///G22yo+7wzr/sps9c90ns7t8vzls8l35019nz5zoyewr+5frf3sy29+lX3bZ+qfdpnx2/u3JydPxvYeT6ll3fvbR5H65pS1lwefLdef3no7rZ0PKs05dcCR49hP7bLX5vNlu/p2WTzQO3Hx+wf77UBxXzYe/1b/7Ib3NZs9mzzv3P5ll+zv2m/Q6e5OW/yzqH2e/3m3zIlv/mF3XhrDPrvPtOttdXmdVq+0P5fev0ru7zS7bs49cr/xNkaWHd1l+t83qh+7y7Wa1yRob/u+Y7Q8nBRXZdlMWcfrhcbPbn3xySFlVVun28nXzd7a6Ka0o/73/MdtnabG6ydas+rPL62KzOm4PxyKblf75vFkxU7/2Xle5nHk44+46fB36a7Y8braH5+wf683uuvzd7F26TVfslcyTvR//7zE7ZuXXH/PiF/Z69vVm967ImSP2+3tvbX70LPz2rXrNLlsdsvWH/EV6tzmk2/eH9HBkP5yxh7J+27SNwtqs6RhNFd9XzcC8z76/2qbXrMy2L/02Y57Jj8Uq+y67TXfsV35Q/oz9oqzVi81nVtRfd9fb8jtmN/vBzA2XsXsVrR1vFc2dIEtDJ577gXPlZ9F6uXDdKJmXv92/LVi77dJtY/rsWWnzk9mu7mLf57s1s7Ns/7vjNuW9+SrP19xir9f6TaNutnWTlA3UdXzHbf6u/6z+aj/mH/za/Zt9wVrhS+nq9Qf+yvoHn8pv6qZ/UfbUynNPzg6Yzkeao2W2zA+H/PbHzfXNgY9iv65M2QKH/O777Ip/41VfLL41Q2z2LDg/1uaisXaT7v/6OSvelhAhaZ5tuj+8z7Ld69u7Iv+claBbdSb2ednvVvnt0+OOVfzpv/b57umrdH/zJr37OStHkFdWf3co6mFTNxJ/7l/p5/Qpc9H10/fsB7tr9tPP6bYcGLMXbHRdrNiDzFnfPpUDcpcfNldsMFeu/j6/rprn5MN6WLLmuWYDl72Djad13TSzcuj/ymyuhtIFq/HF/pAWrCEv8t3FP+vx9ansoKv6PbNyTL0u//if3ltYL0hXXVGljZerppN+K3tJ2U/utunXrPjw9a6sxqsjG0GzEzyb7W/y43b99i7bvSs//fpus6pGd+3qutFeNEhUDVDm8183t6yw8unn2fa6SNfly1+mBXv1e+a49C4vKq9t832JAG/+8jzd/Tt1/pHvrvPe53+9/np3aJ+83B2+ZMVd+/eHm+zi1bGsXPPBd9nuNi1+6b3g53S7zQ6HtP3Jz9lus+qKRsCatchh/2pTOqCqqVv+4z3r6Kyn/1ANuBdVr3/HgPDJ7G9Vh//AJrgns5fsczZVvqrnwY/Vby/LiU4xBexZc+xW2dur71nfjj8ci6pRgyfz/v8+1b/fv26xuXz0HRulWWlj0LxPNZU0v/iQ899Uk0Lzhk/VqGYDrWnvl3nBEOXAHLivKvEfNAmdzi5VP23mlnWUXS2Y+c5iHadOcHW1cBJ3ETt+tghXaeyvlvFSNbds81Xaj4vqoKqMx5pZh/X7ZbZXzjq+fNY5fWf9Zx0wevzPOvYM+J/x6bfx6beR6FW+ZG5qS6JOUY2jzcK5UeeaiaCy/mQIlGJg5BO5ACg5MHZQ2eDihEA5b4AyqHByXuHkvMLJeYWT8won532c/BMm/wgw2fbDBimzyJsnqyBgILleOEEYM6SMAt9Zrtn/Es+fX3mhAVLWEabbQ8rLA4O99C/7C7ZcKA4IYnbv7sfoHBProNflmOidfuudfusLXyVDzPbXRMTs+dwUNMPfGWj+kLGFyDIv9gbQySNMjovnoFQfN8s/x0DN2BQ1vVFR881mV66EpKC529ymW9YD90vmRlaTJxo42rzzTxgVwyjvgw2Khss0DuOrpXMV+SzeXM9TJ16vVs4Vg093vY6DII0MULRcklQL9RZFX+RsbN4wY9WZjjMI2r23l6MMOQi2yb/+b8PTP6PTH5++aSHLhvBXEfGzc/YfPebkEHgeOvtAq16id/DJ335v0d5D0P57R8fRRxZ93gNKehh671W/RyBdTACkbddrkDT2k2QRuGsnjtl6PYiD1Fkusitn4S79NAjXwXqxMkFSny+cOZL2CiRljE/fWv/pPTnJDgcny/Hmx+7pn/7pjwev8mRIykuSIunha9k82bus2LM22VYQM3tdFFU1mZt6v/lpt2EjumR4yqxj+ssv6R2r8qb2zTlM7rnRFJT93xko6yYCKJB8Nos6Ch4/QAz6Ows436/y4+EMTNa/YTUeHyVPuxoPOtfeKl6sPYdBo+sESy9x4qU7d2IvyMIgXC7iyDeAyrilwDhUDksl42X36urPhlfnmJc0/45PP45PYsvhwzLmrX2JGUK+yvelxVJ4/Ee2v9n8ooGLQ5/9p4IjHJNKIHDkSPVPZLSIjFMsxJuWbyBxuViGnrd0nWUQhk6QuQsnXUees05dz/XCOPCWqQnvk3RiGh4+8vLoxE/30kZEUC+PHb6YbtgdJzjlc7rvk8H3seSFoYwB6v2AtiJvvfBHX5Dfh7c+7JjmM1tO3QT+hEnOR4ZxlyWcYQvm5g1/opwI5XgX4tKpxSqOltHcYWjHIr80YcvldH3lzJNVso6jcJUFsQnMcTw44W3aIslh38l7T6WN7hDcWqameyi494k3fOj+e6Wsd++1ZqHhy4INi/X2az825Go39vXfsy/ZtviqERp2Hh0hKAz/KKhpvEIenzz/k+j+3QFm1/e4IihdBevEdR1/FV05wVXMIHO5Dp31fL70g5XvpfHaBDIXNZrEHWD2i6QHh917TzTofI3shPXfnIfhv08Gf0eD3w/fF8tgsvv+YUCy78URgstHCJM6cNiFkCdJRjiM7MFk9+JHBpX/AazMIwPPtos22LmKS3V+GrFIc7Vm2On6Trpy585VmKzidOm7WWCyqm62xvQW1b0CycFm99ZeHrCNIZvozz0lrNuvk9Nv+a8HL5Otp7uX2006vmO4kBUaoNnz3x8y32iqJDJmXfqoaqJgf4RL8QdMN5Z9/1gU2e7wrtrQMOvvZ2m+KevyvtxH8WFTdl13kSwSbx4k8TwqtW6sP7+uuI0rBi7+OnDW/pqtcMPMc2Iv8Z0sjq7S5XoVzNNSllj+/l1asH+yWLiq/npzdVVVsBxgL2422dUh3VSimcqkeswK9luwkd78/1Nbt/IH+xqfWXNUu0bYi2p/VFTqd/kt6/fNbpHvNmyM3bK/yh9VtStdeFOrHuoqs7pXSoZy1L9J70p7b9O70wqsatz4uDnc/Mw+qobrLHgaP3Xdi/+qJpWLxHP/m5XBHn2/+Xc5Hmc3Wb3/x0s68iZbb4637GcMGDbl1OCxgr9s1gfWyEHZOfZZhU5NA8ThwvNqqUZxYO3/fd7tkPlUW/w9q0rlvmW6zz5kRVE69tnsb0W63/NGZj2EwUa51Wfeoc7zr6UTeVf41DplVktB/tnrJS8qp236e4ZO9vWw6uTpukSdfu8qYfrUqBc5Gzgzkgk/VCaId0ZW7FjRxbUvN/sbbZusOqq28nbDppK0+FpPGL/xQfamdZ7HftP88Sa7zQsetwyqx/e7lUbLvvrUdq2PaVFs8rIx8gb5h5Vn39z7hDXpbd5OX/dd3O656zv4fbo9SBxcglfl2pdswDCAqkYqQymGUKVvRu0RaFdg+Lip9MCW+sHAtsq0h+qTw2Y9dRMbzMVxb6dJxzfe0fekQf8SlONx2tpyLe8XxQVG9wt6u8qqjYe0GriT1cBtJV33gcKo/9ArLKspfVzfL8D7Nh7CyZzquOM3n9OfbCzWYNT2+LUWpkyIT7KRO0ULecJg5+2mjHn5B5e35fb/So8jcMqbtGDToaKTKsv3+fkXo1e1FWPSkEPHixPUwlPV4u9H9pKMXAuXUovzSGPfWItWfuV5+m56ucmyO/H88mqz3VK9q5g0rUJXN2Va7+YeZeLQGDeiF+rYI+oCEl+qMcj2/ORLq2W1qf0Ou43Gl4W6GXRjnSqoYlTl8wHXR9Gmn6DZXE8s3ZeXThsQPt/sf7KOSg+HbSZYh5hMTfZs9Fob7c+jrm1jXZWxZDi3aKPl5lZM4ZTh2U3gfQPzVD86RKZM0kpZYzBIJkcsevKtT47tZiL7A03UeSn9g4qcgekEqTMJUMOIwOqMFsg7rf6MpIpIdEqXhNyXh5w+Grm+JCTaFjY7g7GZnlp6gJXuy0tXjO50/7w6sq08l+3HzeeOBW2/qQ5zk33V//Qs8pCr5pGqdha2wzEDBHvGuq2xIy8Bzc0+Dc9752ueySZKPF9Z/gRsAOsBmuOKQt7vsooAHGsFay/D4XjiCIkN4B0xhFMsiaBAgrrGUsyu9PlREtVY6aOiUUaxdAAKz9Md+99e3C2x2DGUhkPfZfusOkrJxG5hSvc965HUVUVoNUIKsTV/KI2QAGeJXqdvDDX9wEsfoN/Hm7SUnOkmbjrJ1LmE0YLvLrPSkAt+Lsyp7WxUjGB6aNX0UGT6T0W6a3Q0g6VtYIVt1K9sYLWyQVNZLPQVPa8R+hpGsWQrPchKVYCuab+H2e8+tP3tKU/Wo16DbqwMeeWVVZRuu0JdDDxBMN91DElMj4Ud1lPDjicK5qGEJokf1sAz6oSvSO8Q7WlPBbIbrVkL2OXBqY4xhoCmjF6oJhDEFDphlDHvpm+srVB7wXvrSed6lRf76kTre3EOYrOtiHyBReQLLCJfYITiQpqLMyld9LzEldQQM2o3D5pMj4T2rAuK9OANqWSt8uxvKhTrPLttkydyz/6D43pk0XgEXCTp1jfs1fecwiuQ+cRKxUNpxS0tmESvJi+YBg6TLWxN1lAi+zTnoNN9Epe7apvKRbXNaCYJmlSO1llLWfKmhxnjGhtDDbVdUbOPlfUz7w5UOoDqecWKFHX8Lq22VX3Md+taar+9+C4v0nV+vys7fF0KLXEmWqt50tnfYKljcTnmS2Mhg6WOxaWXnNw2WNdYXHrxvLbR0uu0d5zuTj3TQdqFg83oXrUyA2wF5qp7sabFfECELuaMJtL2Xkhil42kqzmqK4ULOnnm2hthiRpJR7HWvNDsqNZcoFDBIpJCn9Yaw8xI6moxks4XupOTmZ3UdWkknYOxbmyYnLW8BG7OUoxHMEI/ZqiNiC0v+HXXhlHnAoO18Nt0v9lbTQ+M0Qbarjm/EV2SQjB0m/UUQvwNVS2NmXAYWCfYND1KesGwK6G8dMArazHzIHqZSZrBkjE+Zoxn1RhP1ONNGXs7++NENbK/mHRVvRlMPExQA6DnKDI+Fow8xfn2hxfdhfEze4dttLesl1WRftcdt/G8OB5KYB0etnFyuXou+vDckRsnlpDzKGMkg8S4QU34kITaZFu59FqPXvOgPIzFvBC27U0hmYPyMEMR7bk0AZ6IsUuzqrZ8aNtaB1nDqyWEgVabmziNqk6fJY7X+ni1vurGxk4Fh2dvaOLfMZ05jOXPeVF7W3/rSOVS9LTrX26Pt5udMLCJJ3KdbKWKnElhAKy9G2pIW5vPVwQ5vca8IsZbDsUNxg8s1GoqA0EGKakUn8/QAdZbTd3VQNBeZSFet3Z3cZwgQfPUKE1kO/VnUs9Qt55aE4ZRtTU145aToLE8hiVkG2JpPE2JIGJYIDB8Y3NvQiIGHvlMYTm/WZuRAP3cOKH70FWOmyqjyTmtcWcnATww9uWxGJ7bdya3OZlzI6FzN9vPsg2D0+SQlVKzRJontpgMFg0xy4RJyKtzv6Q3ZXRa/qfS8KHu46ftsTjez6+H0gqZ7IEXPU9OyRpjisnhZ8PRV2bKLWZwRY4wyeAaOJI6qj3RqB5xwyVP5U5QNVdUNbKYUGa0/ewttdcokuS2M4U8RQ6lNCcQFjqYBFKxAc+2odgmPMURHSOsrPmJHlMc3tfu0zUKz62mzvhOYwvsJiVVSpb76CXA+BYS8j6VCRKt3lSJVrNsqiS1BK0qjP1mrKHoJfjGTbsqBuH5teTwRHPZuR66Ztnpj4NgQpEt9lXeNeo21CwEFTaMMCo5SysgRzZXXemJydSU9Dp3v/fc3SlXqaoEPmFdmIjUzZKTnUdft3OfiNLuWkVpJhgTLPV9wqlr5hUT+QwJpYgTLA9+tipayeLuAmpRmCXIH1uIT4T+qa3lX8mQsYsJe5bxh8YjFMwlhL3rxlEn0oePgU8X5ztA954RUBjtwIsHdbTMq6IloU2KLpGvcUfJ85sJy3RMtyQf7O6Enk+Q8qnLoheln5JN2lrRwgq05pOq6ZK+W6XfTaGmSyZr4Hi6bhvLKzXO4QNTVCrilRqDtjI+ec3EueeTMrbe1p4YaNAe57NlMp/LM/cU0wO7pgdyx5owOsIXIFcCVM60fSeAoZUYuWM+BE2IHIsOd+VdQIuesdIVyRZ0DMwE3JZjl9zqSJlptlg4njRoNeBlpiCQsAM9FMdJEp1qnqvmh1CORc0gpBOSg+en2mOyXA0CZpCBkZzfM6bc+3x8Y3CtBHIygX1GqrkhtMn0qqRS/iCPwJ8Zk5QzkbH3qCrl3svxiBbF8Zw6bubq7LPpJoLnJ6ZphCyAQFunQctYuHlSo6GsEtajkjJGgEFf0hK4H2UqZroaT7lZo82taa5RbOZRm7INSfARnTA2wdWUY4Ph0q0SuSyzKt07BV+8jBiNx+PVNdTYjEy/NFbJOC0rB3RYolq4A01ILcxULbcak3NNPYaUEYnfmsbjA3bu9Y5VbZ+JCVqbG3xMevDgFLC/5dv1xdtiaOS0Tla4VOu8VIFuwsiZJpFFY5jh+SbUW5nm8kSM5WmmKWqQRHpd5DuBwxfWa2hpm4Dj8kzkSBGvgUObDKahIVod93J3+JIVd/ohIXWv9whumT+8WxK1V6Z0R9J5Y4JtaroOinsOgjfEj8B3iylT4+akMF0RDV8IWBYJuwblTj7bK5IFzQd0hlVSEBa1GlQ4bCtsk5kdtKzhSkuLj7V0mV3ADQb5WEvm+HJzjIhXA3NOu86Hm+zi1VGbcyUb6k5lqDpWkY4zPSbWYNQQrCcEEwb0rS1Fg4Pw2R0ja7bpUGMQUPcX2j3j0MEOObR774TDL56ggZ3iisQHv6Pa4Tcu6tJh+nOk4s4cIvepf8FcF5OojlbGtGvCXYfWakZvZH3OdJjYZfYKubwpyOP20KIR9wopqGXzjQL8LKfHQH5KOU7kMC0iHS/c3dRQTnqda0zmTXZymb0ONhFut0wieWeu9g6PdLvNDof0fHoLY3PPpq5Gajr9+lGIc8parU1ZIqeQmdXqEfC0bieRsaFOpjGebovqE149MPHRx26fPVZ8O83xxyfWjN6ykv2SD3fPROsA8n5SmQOGHUanc7QMq6BruPzG417H+JgWxSYvBF2jY9Lye5+c6xRtSaM2jL7+oL1Y+lHpD7qLwUUnrj0u7ra9s84+KQB7cHjhqNJb4DRk6C/DW2BtHgjqEu85QChaQwrd9u7QbtOEUY2pPHe7HeSR0NJzeGoEPWG+Me3DcbcuUsPSeK7f3u1vzSvdMU780Sb23bZaRkZID4jU7k7DwyOrN178I91s00rdLuluIvf3jNHwQg3y/KtzUix3eEwUf9BaL5iTesHZOsu1SHoOSIzrT8DwBGhUIxl3bH30xlM3m0JDYCBS1hAKGFZpLFGAZM/IuFqJxaNwQSh2gYzYpysHLHWcViagdTqVPzIHHZDa0Eh/QN4VoFsHn1QHI9GCnTrobDCsJ5z2McmM04uGzmwV673JtnPccRpYzwNuzwPa1X25zfP1xV0NAWRphcHVSURphagEE/2ErVu2aWpaA2mFNaVHe9ACpKywJYjGDh+3e6+mwy/WhM+X1RBgGF7iQdVSjHQ/olhdMdxgIlbni28bp6iaNQK+Cc7DVlybPcXZAvLrwQm6CJN1Qu8mpDG1+0Tmn98PpbVfxEw2Me2OBMXBoZOIJwxEJeAJcvSu2G2rnUhPIR+eFKLL6V/FJkkZeXpMF2+dfPD3eerz/BZpyycPd8KCcXZx2L18UUNwYX61orYuwtaK+t466JDvRJs9MWFHsyuVfydbl3gi0VCzgeRkS2r3otH3z7QJeetqFyOnDBdrahdMpg7w5EI+PcZRu78/hPJFVt3R1SBeG6s8gtpal36Ia4tfyUIItfRVFt55lQV8Yq6ZwwxWMlpVm0z+IK2RoaCASui2Vzg9dH0HiYWz9xHS1hlazhhD3GDmDJXSgDCytGptKWnltim0h9IodDnBUwvSrfHKDBMZmIVJepUyzKGSZBeccTGMMAhlNUW5g1urmmte6LOathTDm66qXlfVUc4tQIQXbs8NIuHB6M5xuXO0X0eovPnOoVaR8mCOmSt7DRr92Rau+GLQhz2nHc1m2+siXZ8NYZMH9qpCLTOSTbqeiUme+X1tq4haV4tSir1vJ9lWET2Oho/kCGy3dS93qw37r4viWIeWMi3SAEssCnEWD9LHZYIjiRnY+Si6mpfQpiu05EqSKcJ2QxgKlwZW6R+dZiRhGpSifQD56CqYfhiurYKhnyzSl0SRAUdXEqW1B79XU+Mo0aM4z4piyo7vaIopjVBvJA+MUXWBeMoQE010VQbKLx1dFa7aNZFa2RKFtUkS65bav0HIGeEKocCuViyAtGKhXCtG9FgoyupKb3+2dIINUTemOgDC7Awb1cFDoIRKQklcHnLj9CnxhpKo3cY64da/SZeGcV+tJv1uimXhiSW2hDk2+nlM2fCNDoH2CuWxhSz8wugH3d0658y62d3nVMs0JT7zs6qDkSRQeHgzyk088jy68bkoOotIlfZGPLw025ULjeSBA1GmorrN/QwBpV1HSE3kdxIrkZqIbL28oQAd0L06md/J4I+vntLyjGWFlFFrayxbH4mczBfOAtqXKNiVnPmqeVGaCEKn/dYJA6V6dRnbyEIsnxLnjHHYli+PBK0qT3xKdG+EiOTtJmZVGFw7MvbB91pVt3S8reu3q+qxGknybukyk14LUa7CyFRbiiVxcmeaze9duIAXDwhw8DssIKWR9j0JZ9cZgA/wdYZO4WZkaOshbyRQ0xtwnLwTLcC1Fi8NzUZ9vvMD2QJfboHd03281tKpJGWBYPQ8rI5sYFGbunhIbZmd9rB/2JGo9XSP/9EyUlcBwrVmho4aVRWVKIY9poCpW6n9TnkB8bCN5LveTxuuffskK4WYBjxTuDHuuVHkn4dMt7YCLPt9TMblDPtTc6G1/U3DhCOghsfulqr5kTU4C6FTJoq/Q9qoGUOFZbC5TEtqNWmVKFu7W+WMgG7rIkadnd09qUl+/6NzZFtAmviMpF8WM1gjnQXlC0ehMHQbUdrkKcCY7h0FjWN0UNZwAhv5mKi+1suOQ86Kk4bt/7fsdhT9lg2sszNpmAi3zM4Z0dFu4XJYE+2WLeGZ+Nw4BohCcmI0gZctKVovCWYUgxnIvGyK0QKer4S0XraEZyEkPFvIhWcUYxZNflyXzDZWYT2gwixq2Y0JlTexMXWjsUYlkkygesiAQSPqPxIKZziSekgSzGIiFJ61ImdhFVfIQCIWfhkQpq0RTY8WtDXkYzgVShK92JErXIjli5pZr2DVk0QJQgDVpeMwptEWBWqtDUjEkI+OtVCn4Vap3Srb7YcXBtqq6KAwZNls2NHurYOFsa0/HtlmKRvUvI4o2NWyVDSx0i1VXXCrZY6lWMUN2nirv0A7dy4N6sxIq8dTeDDhAb4SstDIZFG4TTeQevaNkcmi5QrdZNl1OFa1Et1CUuuQQqA2oikSMvlh5R29uwl6RvxUpLuNUEBBPLq6q65odgYMNz4xxsxaUdCsF1Fx6kSE/1rxZcN7UJ/v6kC2IJBbYKZLob6Bh+j6l58bC1HIpnly0+jqCJVsJNQdoqanpNvVSbjcLxMJSlTqEYkRo7hCj+vnMpLQCtmvZ665oITcqTVdY7w7I3nMXos1oMS6WmSABlUk/JD6mmicriMViVjbe6Cl+xh4e4zr6Q31IORJWRWX2Ltgp9Nt2En4akk6DJbaoGhAqpIYI5OgiqJGYf2l8gfD2hlpGuzU7izNO0odXPMxpSE2sG0pPd6VTTiYXoCud5crwkz4fot6hf4pRxontZrQ+PYuCHXarRwYWW9LWNAmVEYQFvBZztbVZ6GtXVAGtL8tDcIC0iBEdjUI0WgahNiyBuF8yD/IRkujQs9+ZRN5Nl8LQhOV1EC6nRHVGvCFud5cYsK5D9748SbdsrpgPDyd4HWlOgCt+VFxeYhe+fwOFIxZp84TTnuWApR3BJh9jA0HUq5oshfONttXFoRQW7aW6atHDC2DM/ToeSpSy+j4EcoBSAvAwgYTwfLJufFQylUblS96AYUqCkWz9UixW2u86rA7DWtVEZJW+aIXGJRPDRfb8qkHGLjiUBuKEVSrAXqHEjK3qImW6GVuogp29QyivoFbgDOoZOGiYueYmQX0N/AEMhULmxeQn+/qQLYgRC0IUAsC1AIftcCXW6A3mjyFBSZ0M3XFpkcxq6zD6GC65+aWbDPjZxeC2UebXjNYgU9Vr0RYLckZ+3YrGrcV1ZnQ3+/yL5aYwlg5ZCBKJlI0HmG2jsazVDUBYXSf0Vk9C2H/M98/aURx2q+zmOIkg5tqZjQ3lH7Ng5TOVPVIlRJRa1pWzcoEhbQv7GJjLfNUEzohL66e3q2Qk+TQA4i+6FEXEvCp6FgDl5GfV23T18KF3oZ6k2DPhFa0SH6Kr6mU65jtbBkmr2xbxTPGLFq8v1ScTpBp1w0YRJv7qhc8LQPRiORjLSMoKxVjObEmhh3sDtG+oUrHwgTLGjbLCdHjWog5l2dc9RBzDqV8+QqUjtgulPJW3WBvQrmRKb/2PGssxUGm/BRbJ02SPGTKT4O/0klzkSk/esdHM3twahErn97iC6zLNM/Te/wCGzLN83BqlzzkFyBJt8Ags3ke6PiYBMWV3wllVD6ZZ1uI5nRA1thaRKXuXEyo1ZZPfYELhngdJIneYNAmwtjazALVQQY6FsCwSOfNehfwWu6YZC6O24TzYCBaAkv6bisH9Q086UsOsps0Lwx5dAsWqAUhakGIWhCgFgSoBT5qgY9a4KEWeKgFroYFGGNIt20+nm1z0LZEYRpGtCagZbGGZRpkG7l8FbjqlI9iqwpadcpvkdXarK2CWh2Lws4i20lkRwXCOrahGKyCYJ3yUQRWAbBO+TD+ohMAUD69YKTKKhbLhNOhPq/apmjQZcjPo1e8OIorXkxoF/K9le15LRjtQqZ9WkGkLYBGl5oOuNjlMyZ1sd1MuZpCWwOWhZzAiKH8R4JlX5rYjJy8mcvTUSZhKxkfXZTBcTEGx0MZHA9jcNrLMLFlHTlB0Z7JiC1sySkaxT4bk6U9mM4HGByMDwFiKTSfAyeUsPLpLR6BDE4EMjgRyOBEIIMTgQxOBDI4EcjgRCCDE2FThhtBM1ZbPjj+6DulFFvbDcqn8zUKTYwJ/tD5GlUIaWIBDoEgBgJ8DbcAREFgnxO3AMRBgJ1RXfJmYgHOrYBYCKQHVJJ+vTfwFCoZT5ocKgxodAsi1IIFasECtSBELQhRCwLUggC1wEct8FELPNQCD7XARS1wUQvmqAVz0IIENCABy0cBEcVDFA5RNETBEMVCFApRJESBEMVBFAZRFERBEMZAFICA8ukFI1VGeTEHFB+odoWZsETU51VHhRoMGfLz3eW6EGSQn1cdGWEAmeTnVeI/gymD/Dy6nHbABT2f8ckpiRhLaSQgA5VAGR0e8aEhIxiyAhyUi3FQHspBeRgH5aMclI9xUIrLqUyWjuQ0jOJEM5PFMygTBjgobE8KSqjwBAo5GUkf+GjOCE5aYeXTWzwGOagY5KBikIOKQQ4qBjmoGOSgYpCDiiHEbssnQ34MzVht+eQpL4Zm7LZ8cPzTOShQs+OCAVsHQGQOKkY5KG4BiIEAB8UtAFEQ4KC4BSAOAhwUtwBEQoCDUt3jY2IBziCBaAikP1TbAPTewJPOZERpss4wpNEtiFELItSCCLVggVqwQC0IUQtC1IIAtSBALfBRC3zUAg+1wEMtcFELXNSCOWrBHLQAhUQUEVFARPEQhUMUDVEwRLEQhUIUCVEgRHEQhUEUBVEQhDEQBSCgfHrBSJVR5tEBxRfoBmkH3KCHHjjtKA6cNuHhyIshxdXPJjwceTkIHt2OHnjhtIdwYDwcOSUAylrRlIYDJlV4xENOCyVYWonHfGjQCAatABPoYkyghzKBHsYE+igT6GNMYIAygQHGBCpu8DFZPoPH5QBMIHY6G7q1iKdQwIQowARivBoQK6J5Mzhxh5VPb/EEZAITkAlMQCYwAZnABGQCE5AJTEAmMIEQuy2fDPnYCbht+eQpD9s/3pZPnvIx7VJbPoo/dCYQDRq5BTgEghgIMIHcAhAFASaQWwDiIMAEcgtAJASYQG4BiIUAE6i6HcjEApzHA/EQSAGh21ccr1kFelREaV5Afr4LakBMAyyIUQti1IIItSBCLVigFixQC0LUghC1IEAtCFALfNQCH7XAQy3wUAtc1AIXtQDFRBfFRBQSUUREARHFQxQOUTREwRDFQhQKUSREgRDFQRQGURREQRDGQBSAgPLpBSNVRvlfB5TAoPtQHXAjKnpgtgMe14peQMzZUOrznA0lL0hDbEGLHr7P2VDq8+gBNw54xA4qr3ZAgTeaVnLAxFargEOjRnpqzkX5WBfjYz2Uj/UwPtZH+Vgf42MDlI8NMD42RPnYEONjwcuaeAoBPCAL4GOxsxbRbXY8jQSmpQE+FmM3gWgZzB2Sa8yTl/QqY3xsmzzFyif3eF4+9QXN8+QRz8unvqB5nn5e/ByDTA+7kbMtn3xgPnaedVs++SgW7CyFtnyyBBVTkLXlkxd9YMjWARCKgDgEghhID/xbC0AUpC99WgtAHKQv/loLQCQErs7gFoBYCBzLxC0A0RAQpHe3Wgnv83m9yqi3+XDbYKiky/XRHVatBewNn0oHHYvdvkq8fc6KffPDVcH8la0/bg435Z+74+0yKxhCe27p0V8PrLDgafzUdWfsDfxbNuz+H4WnKcr78wEA
```
</details>

**Comment by fahrurx** [comment]
It works, only when I unplug my micro SD.

Pada tanggal Min, 15 Okt 2023 05.23, SomeTroglodyte <
***@***.***> menulis:

**Comment by yairm210** [comment]
I'm closing this as niche - looks like the IO bridge to the micro SD doesn't allow opening filehandles (???), not something we can really debug :/
