### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by megyumi** [yairm210/Unciv#10379]
**Platform:** Desktop
**Version:** 4.8.13 (Build 923)
**Rulesets:** [Civ V - Gods & Kings, Civ V - Vanilla, Latin American_Civs, RekMOD, Civ6 Tileset, Alpha Frontier]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

OS: Windows 10
	Windows 10 Pro Version 22H2 (Build 19045)
Java: Eclipse Adoptium Temurin-11.0.20+8
	Max Memory: 1024 MB
System default encoding: windows-1252

--------------------------------

**Message:**
```
java.lang.NumberFormatException: For input string: "amount"
	at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at com.unciv.logic.civilization.diplomacy.DiplomacyTurnManager.nextTurnFlags(DiplomacyTurnManager.kt:140)
	at com.unciv.logic.civilization.diplomacy.DiplomacyTurnManager.nextTurn(DiplomacyTurnManager.kt:21)
	at com.unciv.logic.civilization.managers.TurnManager.endTurn(TurnManager.kt:295)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:357)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:597)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```
**Save Mods:**
```
[RekMOD, Civ6 Tileset]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```

**Comment by yairm210** [comment]
One of those mods has an error in a unique, your can check the mod checker in options menu
Chances are, updating the mods will fix the problem

**Comment by yairm210** [comment]
Solved by https://github.com/ravignir/RekMOD/issues/136
