### ISSUE TITLE
Null pointer exception on android

### ISSUE THREAD

**Issue by Noire-Black-Heart** [yairm210/Unciv#10378]
**Version**
Game downloaded from google play store

**Describe the bug**
**Platform:** Android
**Version:** 4.8.14 (Build 924)
**Rulesets:** [Civ V - Gods & Kings, Civ V Leader portraits, RekMOD, 5Hex Tileset, Civ V - Vanilla, Civ 5 Icons, Brave New World]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: SM-N9005
API Level: 21

--------------------------------

**Message:**
```
java.lang.NullPointerException
	at com.unciv.models.ruleset.unique.Unique.conditionalApplies$ruleset(Unique.kt:143)
	at com.unciv.models.ruleset.unique.Unique.conditionalApplies(Unique.kt:180)
	at com.unciv.models.ruleset.unique.Unique.conditionalsApply(Unique.kt:65)
	at com.unciv.models.ruleset.unique.IHasUniques$getMatchingUniques$1.invoke(IHasUniques.kt:34)
	at com.unciv.models.ruleset.unique.IHasUniques$getMatchingUniques$1.invoke(IHasUniques.kt:34)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:171)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:316)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at com.unciv.models.ruleset.validation.RulesetValidator.checkUnitRulesetSpecific(RulesetValidator.kt:663)
	at com.unciv.models.ruleset.validation.RulesetValidator.addUnitErrors(RulesetValidator.kt:456)
	at com.unciv.models.ruleset.validation.RulesetValidator.getErrorList(RulesetValidator.kt:61)
	at com.unciv.models.ruleset.Ruleset.checkModLinks(Ruleset.kt:438)
	at com.unciv.models.ruleset.RulesetCache.checkCombinedModLinks(RulesetCache.kt:170)
	at com.unciv.models.ruleset.RulesetCache.checkCombinedModLinks$default(RulesetCache.kt:162)
	at com.unciv.ui.screens.newgamescreen.ModCheckboxTable.runComplexModCheck(ModCheckboxTable.kt:110)
	at com.unciv.ui.screens.newgamescreen.ModCheckboxTable.setBaseRuleset(ModCheckboxTable.kt:95)
	at com.unciv.ui.screens.newgamescreen.ModCheckboxTable.<init>(ModCheckboxTable.kt:68)
	at com.unciv.ui.screens.newgamescreen.GameOptionsTable.getModCheckboxes(GameOptionsTable.kt:455)
	at com.unciv.ui.screens.newgamescreen.GameOptionsTable.<init>(GameOptionsTable.kt:58)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.<init>(NewGameScreen.kt:77)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.<init>(NewGameScreen.kt:50)
	at com.unciv.ui.screens.worldscreen.WorldScreen.openNewGameScreen(WorldScreen.kt:232)
	at com.unciv.ui.screens.worldscreen.mainmenu.WorldScreenMenuPopup$5.invoke(WorldScreenMenuPopup.kt:32)
	at com.unciv.ui.screens.worldscreen.mainmenu.WorldScreenMenuPopup$5.invoke(WorldScreenMenuPopup.kt:30)
	at com.unciv.ui.popups.Popup$addButton$2.invoke(Popup.kt:301)
	at com.unciv.ui.popups.Popup$addButton$2.invoke(Popup.kt:301)
	at com.unciv.ui.components.input.ActivationActionMap.activate(ActivationActionMap.kt:56)
	at com.unciv.ui.components.input.ActorAttachments.activate(ActorAttachments.kt:42)
	at com.unciv.ui.components.input.ActivationExtensionsKt.activate(ActivationExtensions.kt:17)
	at com.unciv.ui.components.input.ActivationListener.tap(ActivationListener.kt:15)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener$1.tap(ActorGestureListener.java:52)
	at com.badlogic.gdx.input.GestureDetector.touchUp(GestureDetector.java:209)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener.handle(ActorGestureListener.java:125)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:87)
	at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:426)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:472)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1531)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)

```
**Save Mods:**
```
[Civ 5 Icons, 5Hex Tileset, RekMOD]
```

**To Reproduce**
1. Download Rekmod from ingame workshop
2. Click on new game

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**
Expected to open menu

**Comment by Noire-Black-Heart** [comment]
> RekMod again. Actually, the steps are not enough - you need to actually select RekMod as base ruleset, or have it as default from a previous start in your settings. Same RulesetValidator.kt:663 "critical point". (Wow - did you know you can paste that into Android Studio's Shift-Shift search everywhere and it works?) - wait I already fixed that!

Yeah, if the ruleset is saved selected as a previous game, then the game crashes as soon as I click new game button on main menu. Loading a save from a previous Rekmod game is fine, but not when I use the new game button during the game.
