### ISSUE TITLE
Random crash report

### ISSUE THREAD

**Issue by Martinvlba** [yairm210/Unciv#10405]
**Platform**
Operating system type, major version, architecture (64/32 bit).
* Android ( Custom ROM: LineageOS 20 )
* Version 13
* Aarch64 | ARM64

**Version**
Where you got the game and the exact version number.
* FROM: Google Play Store
* Version: 4.8.15 ( build 925 )

**Describe the bug**
* Random crash when selected city center

```
**Platform:** Android
**Version:** 4.8.15 (Build 925)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: SM-A525F
API Level: 33

--------------------------------


**Message:**

java.lang.NullPointerException
	at com.unciv.logic.automation.unit.AirUnitAutomation.getNukeLocationValue(AirUnitAutomation.kt:131)
	at com.unciv.logic.automation.unit.AirUnitAutomation.automateNukes(AirUnitAutomation.kt:83)
	at com.unciv.logic.automation.unit.UnitAutomation.automateUnitMoves(UnitAutomation.kt:184)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateUnits(NextTurnAutomation.kt:1012)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:88)
	at com.unciv.logic.civilization.managers.TurnManager.automateTurn(TurnManager.kt:327)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:375)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:603)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:8)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:4)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher.$r8$lambda$GFMOlD6QMgmLfgwAvPAW33Ob6HE(Unknown Source:0)
	at com.unciv.utils.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)


**Save Mods:**

[Civ V - Gods & Kings]


**Save Data:**
<details><summary>Show Saved Game</summary>
* String was too big, so removed this part ( lemme know if its needed ( gonna hold a backup just in case )
</details>

```

**To Reproduce**
* Would tell if i knew how, but this is probably uncommon error and the first ever for me.

**Comment by Martinvlba** [comment]
* btw cool game and its open source too :)

**Comment by Martinvlba** [comment]
### In game crash report ( only )

* https://katb.in/hipayedayak

**Comment by tuvus** [comment]
Thanks for reporting! It should be fixed in the next update. Please let me know if that isn't the case.
