### ISSUE TITLE
Crash unciv

### ISSUE THREAD

**Issue by Compucter** [yairm210/Unciv#10403]
****Platform:** Android
**Version:** 4.8.14 (Build 924)
**Rulesets:** [Civ V - Vanilla, RekMOD, Dimensiondogs governments, Brave New World, Resource Recyclers, Hyper Civilizations, Medieval Civilizations, Community Maps, Yet Another Civilization Mod, philosophy mod, Nextgen Maps, Alpha Frontier, Blue Archive Mod Balanced, Latin American_Civs, Ancient Civilizations, Civ V - Gods & Kings, Yet Another Resource Mod, Hodgepodge mod, hack land, AquaExtension GAK]
**Last Screen:** `com.unciv.ui.screens.newgamescreen.NewGameScreen`

--------------------------------

Device Model: SM-M315F
API Level: 31

--------------------------------

**Message:**
```
java.lang.RuntimeException: Actor: TranslatedSelectBox
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:192)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
	at com.badlogic.gdx.scenes.scene2d.utils.Selection.fireChangeEvent(Selection.java:228)
	at com.badlogic.gdx.scenes.scene2d.ui.SelectBox$1.fireChangeEvent(SelectBox.java:71)
	at com.badlogic.gdx.scenes.scene2d.utils.Selection.choose(Selection.java:53)
	at com.badlogic.gdx.scenes.scene2d.utils.ArraySelection.choose(ArraySelection.java:24)
	at com.badlogic.gdx.scenes.scene2d.ui.SelectBox$SelectBoxScrollPane$1.clicked(SelectBox.java:448)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:87)
	at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:426)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:472)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1593)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1287)
Caused by: java.lang.NullPointerException
	at com.unciv.models.ruleset.unique.Unique.conditionalApplies$ruleset(Unique.kt:143)
	at com.unciv.models.ruleset.unique.Unique.conditionalApplies(Unique.kt:180)
	at com.unciv.models.ruleset.unique.Unique.conditionalsApply(Unique.kt:65)
	at com.unciv.models.ruleset.unique.IHasUniques$getMatchingUniques$1.invoke(IHasUniques.kt:34)
	at com.unciv.models.ruleset.unique.IHasUniques$getMatchingUniques$1.invoke(IHasUniques.kt:34)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:171)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at com.unciv.models.ruleset.validation.RulesetValidator.checkUnitRulesetSpecific(RulesetValidator.kt:663)
	at com.unciv.models.ruleset.validation.RulesetValidator.addUnitErrors(RulesetValidator.kt:456)
	at com.unciv.models.ruleset.validation.RulesetValidator.getErrorList(RulesetValidator.kt:61)
	at com.unciv.models.ruleset.Ruleset.checkModLinks(Ruleset.kt:438)
	at com.unciv.models.ruleset.Ruleset.checkModLinks$default(Ruleset.kt:438)
	at com.unciv.ui.screens.newgamescreen.GameOptionsTable.addBaseRulesetSelectBox$onBaseRulesetSelected(GameOptionsTable.kt:369)
	at com.unciv.ui.screens.newgamescreen.GameOptionsTable.access$addBaseRulesetSelectBox$onBaseRulesetSelected(GameOptionsTable.kt:40)
	at com.unciv.ui.screens.newgamescreen.GameOptionsTable$addBaseRulesetSelectBox$1.invoke(GameOptionsTable.kt:393)
	at com.unciv.ui.screens.newgamescreen.GameOptionsTable$addBaseRulesetSelectBox$1.invoke(GameOptionsTable.kt:393)
	at com.unciv.ui.screens.newgamescreen.GameOptionsTable$addSelectBox$1.invoke(GameOptionsTable.kt:350)
	at com.unciv.ui.screens.newgamescreen.GameOptionsTable$addSelectBox$1.invoke(GameOptionsTable.kt:349)
	at com.unciv.ui.components.input.OnChangeListener.changed(ActivationExtensions.kt:132)
	at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
	... 18 more

```

**Comment by yairm210** [comment]
Please update to .15
