### ISSUE TITLE
Some conditionals crash at game start with a lateinit error

### ISSUE THREAD

**Issue by SeventhM** [yairm210/Unciv#10425]
**Platform**
Windows

In current games, it seems as though you cannot have a unit with the following unique: `Ignores terrain cost <in [tileFilter] tiles>` as a starting unit. This follows for any other unique seen [here](https://github.com/yairm210/Unciv/blob/14cc6cc3a7b9e80608fc10de46eb56f2446879fa/core/src/com/unciv/logic/map/mapunit/MapUnitCache.kt#L77) with that conditional. This is due to this conditional checking for the unit's current tile when looking for the relevant tile. Since the the unit has not finished initializing, you get a lateinit error

An example of this error in action is in the current version of [the Zelda 2 mod](https://github.com/hackedpassword/Z2/tree/b886b28d3402d8771b6b5c80e52dd796b0c54279)
<details><summary>Error</summary>

```
kotlin.UninitializedPropertyAccessException: lateinit property currentTile has not been initialized
	at com.unciv.logic.map.mapunit.MapUnit.getCurrentTile(MapUnit.kt:45)
	at com.unciv.logic.map.mapunit.MapUnit.getTile(MapUnit.kt:203)
	at com.unciv.models.ruleset.unique.Unique$conditionalApplies$relevantTile$2.invoke(Unique.kt:151)
	at com.unciv.models.ruleset.unique.Unique$conditionalApplies$relevantTile$2.invoke(Unique.kt:149)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.unciv.models.ruleset.unique.Unique.conditionalApplies$lambda$9(Unique.kt:149)
	at com.unciv.models.ruleset.unique.Unique.conditionalApplies(Unique.kt:258)
	at com.unciv.models.ruleset.unique.Unique.conditionalsApply(Unique.kt:64)
	at com.unciv.models.ruleset.unique.UniqueMap$getMatchingUniques$1.invoke(Unique.kt:402)
	at com.unciv.models.ruleset.unique.UniqueMap$getMatchingUniques$1.invoke(Unique.kt:402)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:171)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequenceBuilderIterator.yieldAll(SequenceBuilder.kt:172)
	at kotlin.sequences.SequenceScope.yieldAll(SequenceBuilder.kt:92)
	at com.unciv.logic.map.mapunit.MapUnit$getMatchingUniques$1.invokeSuspend(MapUnit.kt:215)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at kotlin.sequences.SequencesKt___SequencesKt.any(_Sequences.kt:1218)
	at com.unciv.logic.map.mapunit.MapUnit.hasUnique(MapUnit.kt:227)
	at com.unciv.logic.map.mapunit.MapUnit.hasUnique$default(MapUnit.kt:222)
	at com.unciv.logic.map.mapunit.MapUnitCache.updateUniques(MapUnitCache.kt:78)
	at com.unciv.logic.map.mapunit.MapUnit.updateUniques(MapUnit.kt:244)
	at com.unciv.logic.map.mapunit.MapUnit.setTransients(MapUnit.kt:482)
	at com.unciv.models.ruleset.unit.BaseUnit.getMapUnit(BaseUnit.kt:83)
	at com.unciv.logic.map.TileMap.placeUnitNearTile(TileMap.kt:535)
	at com.unciv.logic.civilization.managers.UnitManager.placeUnitNearTile(UnitManager.kt:79)
	at com.unciv.logic.GameStarter.placeStartingUnits(GameStarter.kt:506)
	at com.unciv.logic.GameStarter.determineStartingUnitsAndLocations(GameStarter.kt:427)
	at com.unciv.logic.GameStarter.addCivStartingUnits(GameStarter.kt:400)
	at com.unciv.logic.GameStarter.access$addCivStartingUnits(GameStarter.kt:29)
	at com.unciv.logic.GameStarter$startNewGame$8.invoke(GameStarter.kt:118)
	at com.unciv.logic.GameStarter$startNewGame$8.invoke(GameStarter.kt:117)
	at com.unciv.logic.GameStarter.runAndMeasure(GameStarter.kt:152)
	at com.unciv.logic.GameStarter.startNewGame(GameStarter.kt:117)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invokeSuspend(NewGameScreen.kt:304)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invoke(NewGameScreen.kt)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invoke(NewGameScreen.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.startNewGame(NewGameScreen.kt:295)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.access$startNewGame(NewGameScreen.kt:50)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$7.invokeSuspend(NewGameScreen.kt:229)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$7.invoke(NewGameScreen.kt)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$7.invoke(NewGameScreen.kt)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

**Comment by SeventhM** [comment]
> Or write RulesetValidator checks forbidding any conditionals on any starting units

Definitely not a solution I support

Tbh I also was looking into how to stuff `isInitalized` in there but I ran out of time to check. There definitely should be a better option, though. It's annoying that we always find the ruleset indirectly via Civs rather than leaving an easy to access version to make this easier

**Comment by hackedpassword** [comment]
Maybe #10427 might add some color to 'lateinit' issues? 🤔 Am I pushing the engine too hard on making units more interesting?? o_O

**Comment by SeventhM** [comment]
Yep, same crash, same reason. Confirms my suspicion that this is not related to the fact it was in GsmeStarter. Instead, it's just that `currentTile` doesn't count as initialize until we're done with `setTransients`

**Comment by SeventhM** [comment]
Wait... No, I'm silly. `getMapUnit` never initializes the tile. That doesn't happen until the unit is moved to its final location
