### ISSUE TITLE
Unique spectator in a multiplayer

### ISSUE THREAD

**Issue by DeStup** [yairm210/Unciv#10460]
Version 4.8.17 (Build 927)
Windows, Android

My previous ticket was closed. I am incredibly grateful to the persons who fixed the freezes in a multiplayer game during spectate.

But, is this possible to add the ability to spectate for an individual (Player ID) in multiplayer game, while prohibiting everyone else from watching the game?

At the moment, you can only “allow anyone to spectate” or “not allow anyone to spectate” And when you try to add a player as an Spectator, prohibiting others, a crash occurs, and the player (spectator) can't connect to the game because spectate is not allowed.

![image](https://github.com/yairm210/Unciv/assets/59770002/fb049a08-f563-4868-81e2-88b5a295a035)

![Unciv_wjzUf3r3Eu](https://github.com/yairm210/Unciv/assets/59770002/29a32fda-8ade-4851-b309-a326c7c3f013)

**Platform:** Desktop
**Version:** 4.8.17 (Build 927)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings, RekMOD iron]
**Last Screen:** `com.unciv.ui.screens.newgamescreen.NewGameScreen`

--------------------------------

OS: Windows 10
	Windows 10 Enterprise Version 22H2 (Build 19045)
Java: Eclipse Adoptium Temurin-11.0.20+8
	Max Memory: 1024 MB
System default encoding: windows-1251

--------------------------------

**Message:**
```
com.unciv.logic.UncivShowableException: You are not allowed to spectate!
	at com.unciv.UncivGame$loadGame$2.invokeSuspend(UncivGame.kt:264)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```
**Save Mods:**
```
[RekMOD iron]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```
H4sIAAAAAAAAAO1dW3PbuJL+K1o97VZZGesupWofHGeSeI499saeuLZSfoAoyGJCkRpenHhS/u8L8KIrWwQaDdpnk5qqiUxKAPpDA2h0f2j8aD7wMHIDv/n6R9NPFhMeNl93j5pOyFnMp7duPJdvYv49br5u9l6NXrWHzaPVN8ed4dOT+Lb74HruPywWBUXN159/yCd/sgUXv3nDwgkLXSZeHIlyHFme+Mky8FzH5VH2l/j6qfhpHCZOXoZ8+nfCo/iC+exe1iWfhNxz78UXth7eB96U+yf3RWH3su1XPFh6PHvAo6X4jfjB1s8eXCcOwsft8hPXj7aexEy0yGHeyVle1velF4R8+pHfZ6gJ+X80lx575OHN41JK/CFZMF8Imz08m4pHg3ZnMj4edlsz7jit3pQPW6PppNfqTkeT0XDQ7s3a3ebRJmoh+8f11oil/0YfecRZ6My5KPNz8+Q+dJ3Ei5OQN+/+jSBdBstkeeLxMM50Jc5gu45ZGJ/5cRgIsR+Yl8iHzac7oW1MyMi828CfCmWVol8EiR83rl2fuc27/U7yg9idiQdrfcwV+JY35uyBN6Zu5ARC8/m08XmjrLv/EFW7TvYj2aD4TP7x2we2XLo+jyJZGXPWxZ4HWSUn6TPZT17+RH7+3nzdGhw1H8U/o6enpzspy57+NONgec5ncf6DTvb9sZBiEsRxsPjo3s+Ll61u9rY9foLVbq1E10vuCBmCcEOPQr4UXen69ze7CtU+KlOyd15a/1Hzd08UFga+68iBfLmMsw/XMWeLxlXwjctaTpwgifI3p8FiIv8IZKP+TBxPlNp4l0TZg4tg4nq8cZP2nPz6x0DIm328cH3RQPmMuV4YsGlakficPf19muQYHzXPWSRVQtQsWxw+ynqTMOS+Iz++YZ7nFu15l8iR0pByi7/eJ/4y+DZNW/1OqKKcv9I/LnjMvMYpi+K8NqEBwaIQaT2g8jpdgVk6AsWfsfxe42bOgzCr3f+alXHDBXjBYpH4K6VM8VmyKBWdi450OJsIQK6YHBZHzQ9BGPEJc742PrrTrBQJqNDCaeMkXKQFzPlCSJfWdeZPBdZimi2m4RSxmAv5Yy6//EZ03T+8cRuEeZtkx3mxhOJaTBp+OmDWbb+au14QBct5+odok+vIxs0fo1XnLpM4g/5tyBaswfypUAOeNedCwCmG82MjLduR6FyFri8hbVyFPJX6gsVCAJb3zvvE9dJ+fuMGXnD/mGqE87Uojwmk/ax/f/fvxUceZmLIPmC8+EmmpGIWjOVfbx99thDyp5o0ZbJ3r8SYyorZnD0FfgKeDXA+urNc2SQieeF/sgf3nu0qtBvlGv3eCyab8J8yj/tZraJ2N8h0KS/rgkWBn7ZD9AP3UsQLbG/CdLpJpZs+MAHftLGlyadzV8yP6a9F8xq386yEE99dCNX9kEQT0Rnp69vQzdX4VC7RjWseijmaF2ruJWGGNJ+Frpifi6Zfeayo6ySSgz5YZACIiVUMH7+Q4mrOwoXQ3CSdfaPdVajJpsFSWBFXq0efm2fTDM+G1CCPp51TPEt//3LXrf1l6NKbNt4xYSPNEi+d03Cr0o//DZLGPXP9hhgRjc8FHHeNFLjHpx+Npx/ThDfioCEGaqr52TcvAtESvyE67u6pfOU6XdkHCmtPu5cuL93j0sWn3c8WH/FavJcacs25f7ZYhmIlXYiGye85npzSXjfFbPcq8UVfvvoiFP3VBxbNL9jyE5c4d0RTxdfDTCM+p4WP8oVNrmpFGV/YA3vlMf/+1XWcj/bCLDjx0zmrkXaStBGyUlrjrJieQTFpM47N2tE+TtsxMJSm3TEsIDMXTKVp5XrRaht2Tzszbtp9ZDF3qdGztm/ESiB+OP3/aSWrbTzWYJzOmRMIu8V/TKfwX4g0xeY15r7Yp97/rHjI1sePcjXgV2LJEhV50jISe4VArO+iDduAnbPGJzHe2M8K1w4aX5KJ90WU8AsOCccNF/sr9tNOLeBQOgszs5l5O6PpQjxzgl94qeL1nvv84acdbCBe74Sd7E+9xx20buSG0P81HEG4Nr4hQAmS0JGw/cG/cblz3l347oPoF5R6UF4F4l9P7Fp3wXQXv0ax8qz3IRCb+X8F/i8bFbJRy7Xvfbp93Mbyf5JZ8rPCuLOWskkQBj7/WdEgVKq3X9xJkMTuzwrlNhqX4SL5tVIq2mgf3ftfK6HySng2+zVdqZsNTAaJfmmXwvz+l+8KocT/ZajlIom+8piLmrbxvBZ4fuEPP+12fRuNN+zrT2tIKUzyd0fNyZrVlP5m6s5mKSDym7csFIWmcQmhixdsKUFcsOWVULIFT6Pmr1e0lzPf52HjmsuxLL5z7f4jxWyGbOqKlTaNun1zp5KG1e0eNec8i8h12jIemanugnlyepC/LmwZGVg55/dp/PmxkTJrRPHfgtCb3oayPaJr+BbL61NBA8tJXo3/fCMj8o1xZ/hf4qcRTykig/G43+91jwfj9lBW+P00YFH8+/eY+9mvRRO/iSLDm3nIo7noyebr41fHI6lLi6UMMAuFuZ67MuR4/Kr7lCF07kZxGg+dsIjfcDHnubIhadnNdR+9ecyoP7lbbc1uuZOatDLi3rmRZDXMRaGSy5Ar9zKI3E1eTnsVcNyp9X0obMA8rKRZs9CXWbLg25ULlANJfEgDpMclTclast+QS4en7laVRhwQtlxKJLaXKSeteHCykAHv5uteVQPI6lfqW1IoM2oj87P140cz+ObLuWT94yAUU5iYJC53XxTDk8exlzKLnJSYFF+swuUdMW+GwSLYmCMX+csLvgjyAHmJ7kou2VHJY1Nd1lHbVs5U69Tat1ml+3WW97DqGNmYEMzEqVBMrcajRrpq8/GdYFOCFUYlukzVw2ZzUYV2Wmj1fpkGK1TKKowqp/DKwd/RWrO0xIX6n66XChZtVwNZCNALJu01PfCy6vdrJwMPLZi+CtiQoq0vxYaTDi1Q24pA5ZKUKzMkhbkBZqGbwPWSSgFsrjLgLEM1Buu1eG2MQlWlxcDftbZ8dC1s6/4Kme8mi5Jx18FM/DZGTLfKeI2zJ+94ugNPScInceB5smyCFbW34t0egL2kDX8k/r3H9xsBdcUb5ov/Is0FN2vdfuPIcCeTm2Id61qTtqMiLb1AHWsCtZ9HoLYVgcolQVsapyGbVO4ELXQKaP2Vl6zQH3DPW1g3Qa8I1fCzUDK4aFJNkKrWkEbJNqYDnXkAPfh71myfnr7tQ7mt7VmzbnrQmLLWPTYM6h40sRmPhVZ+Mqu/V/RbHvFQvexKdLKK9ushQ2e/aH3lfeNG6REY/W63IVjXUDB908+GFB0VKUoM3Q9u2R6DziqkkBUK8Wy0cjfIs/HKYpinwLw82qOvV3S2K7WKlUuCtl2Vohiq9enbroRWuE4w24JJBDqUqWYUCyWDvhCqudx+jG21ICFs8qOMdqi64lJYi6dMzn2aK67+FKIs2X7R5+xrGvZCd33fmtXep7Pacf1gzWzv60XUtXvDxqzUNzDSdYd435pfqw+tQ1fyvE5Ubqq9E3UJEQ/4Yo+KtFR3dvzjRbKkAbyPKWu3FwTTxjKTTL/1t3NRluwrFr3Jc148SBsvY8jpNH9QJH2w1Z/7Ra/6k3R/Z0OEHiRCxQbigoViKB3oVtT+3oaEXRUJbbn7bQjUoRPI0LXUAWS0MCkX+6q6u7FtpRvLJdHbjRwuXrX0/FSo/mbKdFuo1N2qxqi+FGDMjGp8qpas33SQJkU1V1ooGXQVE2+brBm1ysw3zL6IbMdHxSPUn9LXwmrP7PuVGW8LB8jwlnKXDVR2h8p+V/TqNLCl9IWAtfhUBsCsY8OMGNBsJE+DkHmKgqm6HUkEq6WyAbA4W5RLvzJgX6nWc61hVu3Q+pZ3tb+VCR/Re9ysufut1esRDIt1o49qBCtNgGnoEdhvLplH4AASpB4BGyL0IBGonRo9ayJ0NUVQ2B6DlhWKa2o6UNWmzg4EQx28QJSIaj6AugVqVwikTuLV8Q/oSLldrvmKUioukjtbusGlmccRPqFK95exu7kFuYzUHTC405cIGwk/q6jWRSEeyOY2n1EgUjaVswxNLtP0e9QYGEPsCQ2cA1AYFLXP3kzqBiFxIgb334kbPzausysKDo59iKOUpxja5Sflj61xk1ZuiTJqkpLPQksfVSOHOlWCfaS1HTKU0Th5RMXqrbF8wngcWEPLFzHCnaZF19qQ1LVGo0718YsK8W3PePri2yBID1WOFOPcqBvAX885X2oO4CGJ6+6Ks9CLlDu9FufdEO+8U5OiZlfdEB+EVpMHEwwplUdtAsivXBlZd6YdJtuY7MsyEfYlqPQgHa3uDrHjfSm61D64+quz9uS0L0S1XpbDeztnHleYpgYQeukNS/KjGjhbNzYVP88vaMJ4cvWRwG9FDukOqW93vx4y3659EXr4flHz7R6YXDQ4lHREr3pUsAMJ/8zHfQ43qF7uQuElpgcpz2Nu6EdGY6XjvdUcH6noR+AwKRN8o+fe8tSJ8RwbUpyZcUexCIPBCM3qTQytFhSawEyGFa7aope1JwckP5piaoDcc7mou+65/LG9o4MFYbb05CDEpgXAqnBGK65bVEdHNw29VdJmE89q+bqvc6yyQp9xjj1sRp1q1FD+VSiFjh4q+sYpMpddqYf1Os5uxNASHDpqpNIN8EK36S7TjVta9LmCZDw05qgjaS2IbvjcrknjmMaW04mVkaC6KEcDSeBjc6Puao8UnBkMD5EK+D6wcPotCKbYwNkmCrvL8+Y7e2v0qHx11jHbVWI25JPESEHj6luYRvoDU2UAkJ1pHFFOZVRo6UzwJNPnCFhFNe1z3GoygiwJ0JuoIjMo5b6RRO30KiTSO9+rlGvR/sRhP0lRAc9+TQauCcD7ri3+gbPNikFGjBU7whysrp6DqNnlI4uk1YUwA2IWPu4aArkM+1bA6kVuAtyyMHQDWhOgcO2klgBkqii30IaRstVC8O2/dZSrNc7EGOvPFwTN12ho1s4DzdSPx+XhWMRcgmqGycy5XyE2DKlFkNmvlkK5bev0kBgyzcjtAdBITyTqC4gTq28i1qZrcjHRdm73SSRV0/leXd3Xq7X7uugpS1OsbtUMjbLLj5qnc+YEjVPmP4qqdM3hDiQ9ag9qGpzsABCpOdJ2gTBMLFLEcJU1oyJCiVlQ2/hVHa0WSHMHHbkt/IkkgVgaqEhPBulFwU124vrKbRy3rjMCAR4lNM1cBsQKEcHmFnTu0EIsnPjqEUyEHIQO54yD0lWh1iLTGKNS0mnkkg2ghrvBpAXlp7Yef7UVgD5qnn9JJt4XAYa2QQMlTqTTIaJcgMbRa0TUVDtUrZRhj2a1VDpzQowKdKamlohHvYfgVCJz+qEw1DxPtNkomzbYfRBpQ6PdHmBUPEvEdazdr/jYyRjSW8BQUNEgzM5srD1sjWXer0xXZn0BD4REUYYuUnRcZFZf3Bpio+PK2KhmrNldLMNVHKV54juu+NQIk6ywZ9onjQ1iqRtCnoWBX7K5GOAwPxBwJdUi2jDmNiKYM5yF/ES7GvOAybhqh6rqXkWEh8ZourqZtKanADFCkh5+UDim6gSMxouWeoeO86X+mNxBpONAy1qBaYRx92ElP1QVRDMomrofxV+/sUY0GBcYH+QZaDSRnmmw3UToJW4ztakmROdhRjRjh4KISYEK4mjzIdFNJr/tOe/ESxauX+oBHRG7JWoHcgACaWGTM1CREekdqszsOUQ5+AyQMdx89iGwLMbcbSxGpe7ukoqUjtUfCDYeiLmri2UaWO5C0plxHClC74capRVHJYsHdSrBQsXgy4d/1ZkWyCDJwdi1RvLH1i9eBIyRjdd0zDCaI984K/pAf+qeA6oHF2vEOTIIrXL7QM4KHZ+H9NQ4knZFySewm6UADPaqHlIrXzaQxA19VgDKVwPFtxGXL7egZNV2DCBSFgSKdQZdQlbvpR7greHGXst1aH8bN8QmgKh1pmwI8NYLtS0inusAXe1BnnmaMGknmvawBZONlD1QhkkLG27EUUvTE2/ap0z1c8Fqu+XxF9siPLq15//FWYs4CoN6XS8tlW/h47ew0BRImkbwVsEQ60PIxm4+b309c00B1cuabfJW2ScyrOQ3Ps2OOixwXBePohATR6QgnThwvAJjqnKBAJLWQBofPbBlwW0UKlgtGJworkfBnG7P69fOhE+8nVrhQJaS35wakTfJfirITflRTAwj+UyPRKPENHRrWbCzWu3CNa1txmiG+U6D2Yxrj9PcSX2AW4ocHBYC/CuDkOK6XNT6U1jNylTc6lPc10vX4TusRXotHIPI2aEDIruoXG3MRB8ZiV5mG9oMJIzI4DPNTzOsxg1Hn2RfE12lGpqgArjcMLQQbLdgZB7YmZm30UAefes/Ax599NSL8rLoxw4IphjUotSDgLFJIdmvDceeICEndSEEaGkmpg6tTjV2ZiFiDKFjS8h9YsfOa2sEj07RhWX0jk5l/1riCsG2O02PlWkUjZemnhGhR0LRmKHwDIgy/ogeDBr5ouq2DmGaE7zumtKYWtU8JtSxuIPzK3AICsWoq2DlULlaoCQ6BqyWvQj5UfOGeZ7ra89k4M059rIqXHpCy7UtS+hGHbtHMKHFcSXa/sK48craotgrnJdli+LqpSFxBmHp4q8n16fCWDjAR0iF0W6dWp4hfRaMThoSFXoHijM2wNGDyDEBr9S0zQyCbg6tAEBlsXzPJkEo3Th3oCFBeIKJnC6EckFBKcoJFi0ATvNUsPoxeJXex6ukStIGjUaVEwN28NT3qOuTPJRQK6GimN1EhKXN6MEJD3Gt0A6x5xBNkqLwIKP4U4hAGHbaK9E0XPLLNjQeNF2JmNrzyg8kXTFjhKGQUE4BA/q4EaZMXrleKhhy8kK7rkwweU11UJjakG1GXVVe03MRldqVRCX0TpbGQ9hGkJjILfUVTmiiEu38b/+8y0riWjbR7cp8s7h5zJjbi72o195dMO3Kk3GoxQ9NadJNg21h+dP0+erSglB2EfJIvlWKVxHY2zdVbhJ/GjLC8ZyHwuzXtEb8QF1WnLGALlJbpYoENYKU38dG6kEeFSn2sLgL8NSSZZlmgdLrbL3k7RR5Py1cHoiFbFQNmeZCQWNRjepAytQOGeLBW7OYDHfdQ8z8Rm+JDyigQBDccHqLoqtRLyElCnAgOZbmNcJ9G8searGjsZJ6hJ1gymnoQdgaJi1FhLpRgGglwsCMza4NgOwx6vTaibkQjiDjiXU0UdQ2+jFAeYuPhelPi7JmbFRpHyi1PecbMs9MOHxHzffc5w+7McwDnDNa/qLmEIETxdEkdQLgUJ31yJ0zqCWCKuUVASyYi/6qG7NBuNsY1jfBhDlOoLle9ZBOz+pWGhK6cIdRIXAwHsc+8pyuhk+CkPZls5nlmJ4GjOCgxMAk2AKTe3RTEq63m7Xn24KYnpvKsUv13Hxnjes5LOKFZVzP1cvnIbRh690kBRlywUYqlD5DNijBhmSkQADUxmsdgSZ0YSIZfuYzfQu6ZcfcbgDUbfdkzbNkWjrEY6mDS6KSjsgYdURc5xDTqT6OjeGpUjMFIdcM4+g8tafinDU+ierYM/ofi8gp8faALttZBxoOh6C/ZJFb6cNC2UOpXCW2UP7cmh2U49AptYNWLxEhCiQLsWNp9t6y7fNLhPTVeX8VNR2oJYxpspDGCs0aGI0dwBKj53N1INNUX0Nu3Tjm/oSHZnn3OgbMR5TsylXBAm4oHFVq2bx1tHnajppnM21bZwUU0X73gJ5QLpZ696lr+DhMILSSU44oZlGZJB5LmNoYHW95ut6isMN5HhWviEIgRXpa2nwaw/my9W/QonHmtV9GHGBtueo1RGdYklj++5b1IR4jjuxG3slrdOn3yVRp+Qoiw75VVwnwQVxv+JyHTDu0nbeHuDmUWzy9ltmafEua8VI0ql0NlLXFsvAI2UOH6I7YGjZRx5UjiWoRGRsJpcliNWZDjF/oDDPCo4jjiY0qxwqVggwpRKNh6hrrqNqRQsg1lwqz75nLH9u7gm+w6oHSK/gGdevewNY8jaEW07bCKEMmOSDVRm3X9hmaXm1rXq/WMQ5xghF9WBcnuIa5HraTLXJTjZUUtKrrJJXDlnONrai2oMkIuvbreAlQ0h9dQXIsQVY21cCkuFlU/6oFa3iBrqd670GBL/5WJCatpCda4dAtQea/7Kk4eDXlR5GfeoDf21hBkcD0LVGSlcxGXV9o3wJZGaXFA0uhKPNbSS00CalZQztc4wM7EH13goXkolg63EiF4luzSo0U2L+oEBPI1SS7fnGswhemJk2thNr3zmy8suehGeecl1L/TPHSrsZbzX4O3vJoLMNluEgw17/WTGVGHLQwS6OHCdvY5BjvUEn1g17IxIqYOB/qkrBN8UyOkX7XdgRaoFXo7ZxVj2VXg0RDG+iaMMNRAXTSXbU661ofFAtDHEnP7b6AwxV5IywsA2V0XNQ9jyugLMwJm8xNFk6/iVGsPVNVkXVNiJpqVOYRElBEo2FPPRH/t2t0ag9FzuzaIAJf8XCWLLQtnq7C3s6O+BRUY1IdeP4LmLukrhJScMizoqKQqeUi6LaN5Ah3BJQ4MIuEIZMGY+nt+6Q12WaYg81r6+9A9fVhcIAkS27u2mO0khj+FvKemtL4FVKGvSCWXKtd0Db2jaRKrdqi/xoyOnNOx34rrv3gW72z/SEoTEnS9CcMuhBwhMtGLfefr7w/tPDjfFAWGkGEUvtFoNS2hJKxsXIMwvMyFq7jFwrcuBo3+6cKxmhw4P36Bxay5XL7jk4bE/GK2K2neSqBOAPWtx6UeAyRXqUVZZzar1TCJkc55YaY1RXq02oY3wfetHEZIjN11QIjZnYZ0Nko1Riipr8+CCCYO7NihMLkb4sw1MPwtgoSuBEgj+nA5r6COHeSJCA6iXm3gT9N+QOXYuy+Y248nyWeaogL5nDXAABscNe45oP2dk2pzmB7un42tuU+N+hscv5PubhW8ygBtG3qY0FmtG3qbEEo1gycs71uLi6Ylt2sj1ao6NoNIK0sk7iEVFa8sEYpW7tqyzhlsCP3eXNA22hQ1qumBHSqZOIEUPVUiPh1Eob7VBx91CArGr0/ytZv7DE3+3l4rpS5Wbx8KR01qDFwme8+7SUuMuW3v6gzAEOFoL+aIYY5Hj8yY/yvx5kpY/0F0frH1mj9SLXNnbEUKb3pGN0WWOmG63Xh7LfJl8cu3fC94Gp9iCS7Q1eivwBAwCStdAcDNuZG4BrOAS4miUpmW7oJIsubCfKRzbii5WgaECGsEqa1CAZwQ6jPGK3aWJabefXKnqXaBo4XYTAwQdyCAmjPiD1onFjg7ZtFhnt2aPtYxKzd13foNIjhyYeewvJHjRNpGhiAOwsep6E5aZuLYsGOQhG1e5WsfSuE4179jPwe6c5Dia9Plyk+b70hh1/XQQytuVvC7666Wy9trrvF7hpYfl/cCYSerYQEWud6tK8o6EF+HYzxqzRs8JRWm24xk0lHxzWoBBEmvtOGcq3UesoDzDxT5wFF0NdfI61zbS7vN+N5T6EU8CAShFtt1xox8pa5C7EIFUtS88R3XPGpESZZL2DA0zstYS+Vv8E184rhgo2s5JSbs5LofH48gRwb0m2F+pENUv4YGMfLm1ASx1u9sWilFVy/8ns8N9+bnYjRUrCcG7hfpy0FOyAdLtahc8gFt9WoAZ2uFXQI1r8uHoGNqi9d0vsuyFHCnNQBIXnuZXd9VufFaVPbCnS4kzo2walIJlFDJiwS8SC2N+aAD2JV21E4xAnqcSUWuix/TEhqhNI4cgN49CLAGIJg2Nz1QibhWsZdk3D9xvK97oA9OKTpLdRxnv1KCQ9aDCDBYD9QtSaSJYdswVY4nSeCLtcQaL6DHVatJ4eO4OAuDjX01oFWuGbdGOJaC7bMa/TSgVb4C8jQ1YKtciLXgdUgJGjNayoXFcOmBRvv9UbkQVu9vkyRdnAAFQq1pbF0AhbLfoHvR3mO00VwUppnOtoAe801Oa7YBhTmhY3DHqVtI/FDD1TOX9RKnh6qRBPtT5Ija0x/Asr7WIV0T9m4TRNXtOzvxI0fG9durJ2m8filUeMLl5o2V0md+opvW4eI873JkHOrfS3QnroQZ3dHXTy3tp9eZ/wt21Ar5AMm5sXbIoGWdRghv2p/1NV5Ir1fxd615y1ch+AwKgIYlchEtX0DVq7qrgqVVbtfOYpeCrG5b+dQCuE6t0LzWS8qzRtBTsPFqhZ9CjV9MJ57870Co06OLnB4SdODmrdc2+pUyUi2T+/ETa8reA9wYkmIr5CNJAXZt5Cyp/bso35Ouy01j4qXFgxcFF+0D22t9OOYStqP8v6oXDtHwrU1PRUHXuZHiSYCumfN7r2C5XlzjPcrKbhqtgjV4VPYR0VIxk3umTazvY8m4yrySbeCReFE/wrTFXbktFwMUC8wTXmBj4WmYRACibU1Tj7EvnrC7efzpkWHc2OabTXLGaPVy7/4fhSzUDy4Pw8clhtfn6UtdS9MtisWiv+LFkmLrDl1ZzPXSbz4UXrTWCjaIm2Bpcce028I68yZBxH3T90HGRYP2T8pRzL7ws3jMo0pJouUlJw9PJuKR4N2ZzI+HnZbM+44rd6UD1uj6aTX6k5Hk9Fw0O7N2t1manlulP67sKylLbL7fBOVqoono+5sPO71WrP27FhUPJ62RqN2p9Xt92a9dmc6dSa8KTHyk4WwDS5np2JTfC1Kl93SORZYM2Hr3r8R0yoLhUUcFXv6B9eRgMua0w68TpmPrkBPNOBUICiTXYqPb4OFsJVTDRF/uKJ3F+Iv+aUbd5HaSG506Xuiuy7Ej9ys6UUli/Wjax4+8PCv0BNCzeN4+fq331xHtIfzmdAX8epVmLweHY96omTmPwY+P2V+jpTAZsa8iGcK+THxeMQlXfMj/3px+bbhygX4aWWwX+VNWPeu1JOsGzk7dvhw1Dp2nFGrx5x2a9Ifz1pDx+GdIePj9lSOWWfOna9RshC/WP5x/kfv9vzTl0+/u73l7fLk/OZx6vz59ZN/8t9rtb2WCnqThL5U2P8DxHa2Py6qAQA=
```
</details>

**Comment by SeventhM** [comment]
Interestingly, this isn't an issue of how we check the setting. It just isn't logging spectator ids. Which is funny because we actually would've checked this correctly if it did
