### ISSUE TITLE
I cant Next turn

### ISSUE THREAD

**Issue by riverajusko** [yairm210/Unciv#10461]
**Platform:** Android
**Version:** 4.8.15 (Build 925)
**Rulesets:** [Unciv Religion Plus, Ark s UNCIV Evolved, Civ V - Vanilla, =GeneCiv=, Ark s UNCIV Expansion, Uncivilized Enhancer, Unciv Rebalance Mod Beta, A Religion For Everyone, Ancient Civilizations, Advance Wars Mod, Civ V - Gods & Kings, Warframe Civs, AquaExtension GAK]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: Infinix X6835B
API Level: 33

--------------------------------

**Message:**
```
java.lang.Exception: Unit Eumycetozoa of Burgess at Tile @(3.0,10.0), Plains, {2} {Coal} can't be put in tile Tile @(4.0,12.0), Lakes, Eumycetozoa - Burgess!
	at com.unciv.logic.map.mapunit.MapUnit.putInTile(MapUnit.kt:720)
	at com.unciv.logic.map.mapunit.movement.UnitMovement.swapMoveToTile(UnitMovement.kt:530)
	at com.unciv.logic.automation.unit.UnitAutomation.trySwapRetreat(UnitAutomation.kt:281)
	at com.unciv.logic.automation.unit.UnitAutomation.automateUnitMoves(UnitAutomation.kt:198)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateUnits(NextTurnAutomation.kt:1012)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:88)
	at com.unciv.logic.civilization.managers.TurnManager.automateTurn(TurnManager.kt:327)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:375)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:603)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:8)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:4)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher.$r8$lambda$GFMOlD6QMgmLfgwAvPAW33Ob6HE(Unknown Source:0)
	at com.unciv.utils.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```
**Save Mods:**
```
[=GeneCiv=]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```
</details>
I can't next turn

**Comment by hachchch** [comment]
Is it a problem in geneciv that game.png is larger than 2048,2048?
I'm a noob so I don't really understand the Unciv github pages.

**Comment by tuvus** [comment]
I'll look into it. It would be very nice if you could add the save game. I have seen this type of error before but I thought I had solved them.

**Comment by tuvus** [comment]
Okay, something must be wrong within the movement.canSwapTo/swapToTile.
```
if (unit.movement.canUnitSwapTo(swapTile)) { 
    unit.movement.swapMoveToTile(swapTile) <-------
    return true
}
```
This should not be causing a problem if I directly call a method that is responsible for determining if the other method that is causing problems is valid or not. 
This might take me a day or two to figure this out.

**Comment by tuvus** [comment]
Are you still having this problem? If so could you send the save game file? I have ran some simulations on Vanilla G&K but I haven't found anything yet.

**Comment by yairm210** [comment]
Closing as researched, inactive and unworkable
