### ISSUE TITLE
fail to memorize a new file

### ISSUE THREAD

**Issue by doyouean** [yairm210/Unciv#10483]
**Platform:** Android
**Version:** 4.8.15 (Build 925)
**Rulesets:** [LOTR Unciv, Civ V - Vanilla, Brave New World, Civ V - Gods & Kings, DeCiv Redux, Community Maps, Civ6 mod, 5Hex Tileset, Alpha Frontier]
**Last Screen:** `com.unciv.ui.screens.savescreens.SaveGameScreen`

--------------------------------

Device Model: SM-M115F
API Level: 31

--------------------------------

**Message:**
```
java.lang.OutOfMemoryError: Failed to allocate a 9443680 byte allocation with 3728728 free bytes and 3641KB until OOM, target footprint 268435456, growth limit 268435456
	at java.lang.StringFactory.newStringFromChars(StringFactory.java:112)
	at java.lang.StringBuffer.toString(StringBuffer.java:671)
	at java.io.StringWriter.toString(StringWriter.java:218)
	at com.badlogic.gdx.utils.Json.toJson(Json.java:239)
	at com.badlogic.gdx.utils.Json.toJson(Json.java:227)
	at com.unciv.logic.files.UncivFiles$Companion.gameInfoToString(UncivFiles.kt:380)
	at com.unciv.logic.files.UncivFiles$Companion.gameInfoToString$default(UncivFiles.kt:376)
	at com.unciv.logic.files.UncivFiles.saveGame(UncivFiles.kt:161)
	at com.unciv.logic.files.UncivFiles.saveGame(UncivFiles.kt:151)
	at com.unciv.ui.screens.savescreens.SaveGameScreen$saveGame$1.invokeSuspend(SaveGameScreen.kt:122)
	at com.unciv.ui.screens.savescreens.SaveGameScreen$saveGame$1.invoke(Unknown Source:8)
	at com.unciv.ui.screens.savescreens.SaveGameScreen$saveGame$1.invoke(Unknown Source:4)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher.$r8$lambda$GFMOlD6QMgmLfgwAvPAW33Ob6HE(Unknown Source:0)
	at com.unciv.utils.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```
**Save Mods:**
```
[Civ V - Gods & Kings]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```
No save data: java.lang.OutOfMemoryError: Failed to allocate a 9443680 byte allocation with 3599504 free bytes and 3515KB until OOM, target footprint 268435456, growth limit 268435456
```
</details>

**Comment by yairm210** [comment]
We've done all we can here - memory limits *will* be hit by players with huge maps on Android, and we *do* warn against it, but this is better than artificially limiting sizes for those players who can effectively run gigantic maps.
