### ISSUE TITLE
Possible Concurrent Modifications in AI tributes

### ISSUE THREAD

**Issue by SeventhM** [yairm210/Unciv#10486]
Not sure how it happened tbh, but it looks as though if the AI decides to demand a gold tribute in some cases, you get a concurrent modification error. I'm still newish to debugging these, so I wouldn't know where the fix would be. Game from Discord. Save is massive, so ~~splitting to a separate message~~ I can't even post it that way, I guess (there's 20 something major civs, and 95 civs overall, counting Spectator)

<details><summary>Stack trace</summary>

```
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
	at java.base/java.util.HashMap$ValueIterator.next(HashMap.java:1625)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.bullyCityStates(NextTurnAutomation.kt:187)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:66)
	at com.unciv.logic.civilization.managers.TurnManager.automateTurn(TurnManager.kt:327)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:380)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:602)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

**Save Mods:**
```
[Ancient Total War]
```

**Comment by SeventhM** [comment]
I did some calculations. It'll take me around 6 messages to send the whole save (it's over 300000 characters long even when it's in the compressed (?) form. Should I still send it?

**Comment by Framonti** [comment]
You can save the file on some external tool (e.g., pastebin) and then link it here.

**Comment by SeventhM** [comment]
> Placing a Worker on the map

Actually, I ran through it and it actually chose to do a good tribute before crashing. But yeah, probably still have the same solution of a `.toList()`. I'm kinda curious about these crashes, though, so... How does that actually fix things here? I saw that was the solution to another concurrent modification crash too

**Comment by yairm210** [comment]
No idea *why* this happens but I do know how to fix i
t
