### ISSUE TITLE
error

### ISSUE THREAD

**Issue by user-145580717118795958879** [yairm210/Unciv#10628]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Game Version

4.9.3

### Describe the bug

https://wwpk.lanzouy.com/iw3CZ1geb2lg

### Steps to Reproduce

Tap the space.

### Expected Behavior

Proceed to the next round.

### Operating System

Android

**Comment by yairm210** [comment]
**Platform:** Desktop
**Version:** 4.9.3 (Build 938)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

OS: Windows 11
	Windows 10 Home China Version 22H2 (Build 25330)
Java: Eclipse Adoptium Temurin-11.0.20+8
	Max Memory: 1024 MB
System default encoding: GBK


--------------------------------


**Message:**
```
java.lang.NullPointerException
	at com.unciv.GUI.getWorldScreen(GUI.kt:45)
	at com.unciv.ui.screens.worldscreen.unit.actions.UnitActions.addSwapAction(UnitActions.kt:110)
	at com.unciv.ui.screens.worldscreen.unit.actions.UnitActions.getAdditionalActions(UnitActions.kt:98)
	at com.unciv.ui.screens.worldscreen.unit.actions.UnitActions.invokeUnitAction(UnitActions.kt:27)
	at com.unciv.logic.automation.unit.CivilianUnitAutomation.automateCivilianUnit(CivilianUnitAutomation.kt:82)
	at com.unciv.logic.automation.unit.UnitAutomation.automateUnitMoves(UnitAutomation.kt:154)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateUnits(NextTurnAutomation.kt:339)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:68)
	at com.unciv.logic.civilization.managers.TurnManager.automateTurn(TurnManager.kt:330)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:376)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:619)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```
**Save Mods:**
```
[Civ V - Vanilla]
```

For so we don't need to go through the zip download every time

The game save is still there

**Comment by user-145580717118795958879** [comment]
> **Platform:** Desktop
> **Version:** 4.9.3 (Build 938)
> **Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
> **Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`
> 
> --------------------------------
> 
> OS: Windows 11
> 	Windows 10 Home China Version 22H2 (Build 25330)
> Java: Eclipse Adoptium Temurin-11.0.20+8
> 	Max Memory: 1024 MB
> System default encoding: GBK
> 
> 
> --------------------------------
> 
> 
> **Message:**
> ```
> java.lang.NullPointerException
> 	at com.unciv.GUI.getWorldScreen(GUI.kt:45)
> 	at com.unciv.ui.screens.worldscreen.unit.actions.UnitActions.addSwapAction(UnitActions.kt:110)
> 	at com.unciv.ui.screens.worldscreen.unit.actions.UnitActions.getAdditionalActions(UnitActions.kt:98)
> 	at com.unciv.ui.screens.worldscreen.unit.actions.UnitActions.invokeUnitAction(UnitActions.kt:27)
> 	at com.unciv.logic.automation.unit.CivilianUnitAutomation.automateCivilianUnit(CivilianUnitAutomation.kt:82)
> 	at com.unciv.logic.automation.unit.UnitAutomation.automateUnitMoves(UnitAutomation.kt:154)
> 	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateUnits(NextTurnAutomation.kt:339)
> 	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:68)
> 	at com.unciv.logic.civilization.managers.TurnManager.automateTurn(TurnManager.kt:330)
> 	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:376)
> 	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:619)
> 	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
> 	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
> 	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
> 	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
> 	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
> 	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
> 	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
> 	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
> 	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.base/java.lang.Thread.run(Unknown Source)
> 
> ```
> **Save Mods:**
> ```
> [Civ V - Vanilla]
> ```
> 
> For so we don't need to go through the zip download every time
> 
> The game save is still there

I'm sorry, but this game suddenly reported a long list of errors, and I'm not sure which steps were helpful, and the GitHub feedback bar doesn't allow you to paste something that long, so I had to save it as a file.

Also, the previous archive seemed to give an error every time I got to this step, and I'm not sure exactly what that was, but luckily it didn't report any more errors once I deleted the game and rezipped it aside.

Translated with DeepL.com (free version)

**Comment by user-145580717118795958879** [comment]
> CivilianUnitAutomation.automateCivilianUnit ends up calling GUI.getWorldScreen? Curious. Haven't got Studio here, was just curious whether this is a new one. Hoster safe with third party scripting and cookies off, can't recommend without such protections.

I'm not sure what process this is or how to update it.

If this is the game's GUI process then unfortunately all I can say is that I haven't modified any of the game files.

If this is the system's GUI process then my system does have some bugs lately for which I'm struggling.

As for third party cookies and scripts I didn't set them subjectively, but it can't be ruled out that the software or system automatically installed or modified them when I did something else.

p.s. Since this archive is newly opened, it doesn't affect me much, but I think this error may help the development of the game in some way, that's why I'm submitting this feedback.

Translated with DeepL.com (free version)

**Comment by yairm210** [comment]
Solved :)
