### ISSUE TITLE
Error on game start with units that have "Only available <after discovering [tech]>" without a required tech

### ISSUE THREAD

**Issue by SeventhM** [yairm210/Unciv#10626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.9.3

### Describe the bug

Perhaps we shouldn't be doing stuff halfway

[Example mod](https://github.com/prod0ad/Ancient-Total-War/tree/5d6e8bcde849517608613a9671d23745c543e80f)

Explanation in title. #10593 included the entirety of #10587 which included implying "Only available <after discovering [tech]>". However, line 55 of CityStateFunctions wasn't updated with this assumption, so it's not guaranteed anymore that the required tech isn't null

There's already the question of whether that's a valid assumption in the first place (given a modder did this by accident, see the discussion in #10585) but both instances of this should've been updated if it was going to be pushed forwards 

<details>
<summary>Stacktrace</summary>

```
java.lang.NullPointerException
	at com.unciv.logic.civilization.diplomacy.CityStateFunctions.initCityState(CityStateFunctions.kt:55)
	at com.unciv.logic.GameStarter.addCivilizations(GameStarter.kt:358)
	at com.unciv.logic.GameStarter.access$addCivilizations(GameStarter.kt:29)
	at com.unciv.logic.GameStarter$startNewGame$4.invoke(GameStarter.kt:82)
	at com.unciv.logic.GameStarter$startNewGame$4.invoke(GameStarter.kt:78)
	at com.unciv.logic.GameStarter.runAndMeasure(GameStarter.kt:152)
	at com.unciv.logic.GameStarter.startNewGame(GameStarter.kt:78)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invokeSuspend(NewGameScreen.kt:304)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invoke(NewGameScreen.kt)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invoke(NewGameScreen.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.startNewGame(NewGameScreen.kt:295)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.access$startNewGame(NewGameScreen.kt:50)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$7.invokeSuspend(NewGameScreen.kt:229)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$7.invoke(NewGameScreen.kt)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$7.invoke(NewGameScreen.kt)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)```

</details>

### Steps to Reproduce

Download example mod
Start a new game with example mod

### Expected Behavior

Mod should work. Why do we have this field require to fill in if it's always effectively blank?

### Screenshots

_No response_

### Link to save file

_No response_

### Operating System

Windows

### Additional Information

_No response_

**Comment by dHannasch** [comment]
I think I see what happened. https://github.com/yairm210/Unciv/pull/10585/files changed a `it.requiredTech != null` check to a `it.requiredTechs().any()` check. In retrospect those obviously don't mean the same thing if we're not completely removing the `requiredTech` variable. (Replacing `building.requiredTech == null` with `building.requiredTechs().none()` still seems valid; those don't mean the same thing either, but the check for *no* required techs should not fire if there is a tech required via Unique.)

https://github.com/yairm210/Unciv/commit/d840b4fd4df0d733351e2f08aabca88517bc01be fixed this on the other end, by reorganizing the code so that the check itself was unnecessary, and removing the check entirely.
