### ISSUE TITLE
[mod][Fantasia] Spread religion button disappeared.

### ISSUE THREAD

**Issue by ferrosa** [yairm210/Unciv#10748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.9.8, 4.9.9

### Describe the bug

In 4.9.9, missionaries don't have the "spread religion" button any more.
In 4.9.8, the "spread religion" button crashes the game.

### Steps to Reproduce

1. Load saved game in 4.9.9
2. Select the only missionary unit (Overview -> Units) next to the southeastern city state.
3. Do nothing, since the missionary can't spread religion.
4. Close the game and open it in 4.9.8
5. Select the missionary unit
6. Click the "Spread Butterfly Effects" button
7. Game crashes with attached log

### Link to save file

[Autosave.zip](https://github.com/yairm210/Unciv/files/13686412/Autosave.zip)

### Operating System

Linux

### Additional Information

**Platform:** Desktop
**Version:** 4.9.8 (Build 943)
**Rulesets:** [Civ V - Vanilla, 5Hex Tileset, Civ 5 Icons, Fantasia]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

OS: Linux (amd64, 5.15.0-89-generic)
	Ubuntu 22.04.3 LTS
Java: Eclipse Adoptium Temurin-11.0.19+7
	Max Memory: 1024 MB
System default encoding: UTF-8

--------------------------------

**Message:**
```
java.lang.NullPointerException
	at com.unciv.ui.screens.worldscreen.unit.actions.UnitActionsReligion.useActionWithLimitedUses(UnitActionsReligion.kt:73)
	at com.unciv.ui.screens.worldscreen.unit.actions.UnitActionsReligion.access$useActionWithLimitedUses(UnitActionsReligion.kt:14)
	at com.unciv.ui.screens.worldscreen.unit.actions.UnitActionsReligion$addSpreadReligionActions$1.invoke(UnitActionsReligion.kt:112)
	at com.unciv.ui.screens.worldscreen.unit.actions.UnitActionsReligion$addSpreadReligionActions$1.invoke(UnitActionsReligion.kt:115)
	at com.unciv.ui.screens.worldscreen.unit.actions.UnitActionsTable$getUnitActionButton$1.invoke(UnitActionsTable.kt:57)
	at com.unciv.ui.screens.worldscreen.unit.actions.UnitActionsTable$getUnitActionButton$1.invoke(UnitActionsTable.kt:56)
	at com.unciv.ui.components.input.ActivationActionMap.activate(ActivationActionMap.kt:56)
	at com.unciv.ui.components.input.ActorAttachments.activate(ActorAttachments.kt:42)
	at com.unciv.ui.components.input.ActivationExtensionsKt.activate(ActivationExtensions.kt:17)
	at com.unciv.ui.components.input.ActivationListener.tap(ActivationListener.kt:15)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener$1.tap(ActorGestureListener.java:52)
	at com.badlogic.gdx.input.GestureDetector.touchUp(GestureDetector.java:206)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener.handle(ActorGestureListener.java:125)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:354)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:87)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:70)
	at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:189)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:378)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:193)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:167)
	at com.unciv.app.desktop.HardenGdxAudio.<init>(HardenGdxAudio.kt:46)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:76)

```
**Save Mods:**
```
[Fantasia]
```

**Comment by yairm210** [comment]
I already *did* deprecate this, no?
In any case this is a clear cut deprecation issue, deprecated since 4.8.8 iirc she only finally reminded now, so definitely time to upgrade in mod
