### ISSUE TITLE
Crash on selecting mod

### ISSUE THREAD

**Issue by krijnsent** [yairm210/Unciv#10743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.9.8

### Describe the bug

Game crash in Start Game screen

### Steps to Reproduce

Click "start new game"
Select installed mod "The great unciv rework"
Select the Extension mod "Brave new world"
Game crashes

### Link to save file

**Platform:** Desktop
**Version:** 4.9.8 (Build 943)
**Rulesets:** [Civ V - Vanilla, RekMOD, Brave New World, Community Maps, DeCiv Redux, 3rd and 4th Unique Component, Civ6 mod, Barbarian xp farm, Alpha Frontier, Outlaws of the Wastes, Civ V - Gods & Kings, The Great Unciv Rework, 5Hex Tileset]
**Last Screen:** `com.unciv.ui.screens.newgamescreen.NewGameScreen`

--------------------------------

OS: Windows 11
	Windows 10 Home Version 22H2 (Build 22621)
Java: Eclipse Adoptium Temurin-11.0.20+8
	Max Memory: 1024 MB
System default encoding: windows-1252

--------------------------------

**Message:**
```
java.lang.RuntimeException: Actor: CheckBox: Brave New World
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:192)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:125)
	at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:93)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:354)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:87)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:70)
	at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:189)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:378)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:193)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:167)
	at com.unciv.app.desktop.HardenGdxAudio.<init>(HardenGdxAudio.kt:46)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:76)
Caused by: java.lang.NullPointerException
	at com.unciv.models.ruleset.unique.IHasUniques$requiredTechnologies$1.invoke(IHasUniques.kt:66)
	at com.unciv.models.ruleset.unique.IHasUniques$requiredTechnologies$1.invoke(IHasUniques.kt:66)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at com.unciv.models.ruleset.unique.IHasUniques$DefaultImpls.techColumn(IHasUniques.kt:108)
	at com.unciv.models.ruleset.IRulesetObject$DefaultImpls.techColumn(RulesetObject.kt:10)
	at com.unciv.models.ruleset.RulesetStatsObject.techColumn(RulesetObject.kt:28)
	at com.unciv.models.ruleset.Ruleset.updateBuildingCosts(Ruleset.kt:409)
	at com.unciv.models.ruleset.RulesetCache.getComplexRuleset(RulesetCache.kt:154)
	at com.unciv.models.ruleset.RulesetCache.getComplexRuleset(RulesetCache.kt:134)
	at com.unciv.models.ruleset.RulesetCache.checkCombinedModLinks(RulesetCache.kt:168)
	at com.unciv.models.ruleset.RulesetCache.checkCombinedModLinks$default(RulesetCache.kt:162)
	at com.unciv.ui.screens.newgamescreen.ModCheckboxTable.runComplexModCheck(ModCheckboxTable.kt:115)
	at com.unciv.ui.screens.newgamescreen.ModCheckboxTable.checkBoxChanged(ModCheckboxTable.kt:146)
	at com.unciv.ui.screens.newgamescreen.ModCheckboxTable.access$checkBoxChanged(ModCheckboxTable.kt:27)
	at com.unciv.ui.screens.newgamescreen.ModCheckboxTable$2.invoke(ModCheckboxTable.kt:61)
	at com.unciv.ui.screens.newgamescreen.ModCheckboxTable$2.invoke(ModCheckboxTable.kt:60)
	at com.unciv.ui.components.input.OnChangeListener.changed(ActivationExtensions.kt:131)
	at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
	... 18 more

```

### Operating System

Windows

**Comment by yairm210** [comment]
Solved by #10744
