### ISSUE TITLE
AutoPlay Military Bug

### ISSUE THREAD

**Issue by MTS2313** [yairm210/Unciv#10801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.9.11

### Describe the bug

It got to a point in the game where there was already so much going on that I decided to leave my military decisions to the AI, but whenever I put it on autoplay for military decisions now I get this error

### Steps to Reproduce

The error is happening in the attack on Japan, just use autoplay military

### Operating System

Android

### Additional Information

```**Platform:** Desktop
**Version:** 4.9.11 (Build 947)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

OS: Windows 10
Java: Oracle Corporation 25.391-b13
	Max Memory: 1584 MB
System default encoding: windows-1252


--------------------------------


**Message:**
```
java.lang.IllegalArgumentException: Can't capture our own unit!
	at com.unciv.logic.battle.BattleUnitCapture.captureCivilianUnit(BattleUnitCapture.kt:118)
	at com.unciv.logic.battle.Battle.conquerCity(Battle.kt:517)
	at com.unciv.logic.battle.Battle.attack(Battle.kt:147)
	at com.unciv.logic.battle.Battle.attackOrNuke(Battle.kt:89)
	at com.unciv.logic.battle.Battle.moveAndAttack(Battle.kt:44)
	at com.unciv.logic.automation.unit.BattleHelper.tryAttackNearbyEnemy(BattleHelper.kt:29)
	at com.unciv.logic.automation.unit.BattleHelper.tryAttackNearbyEnemy$default(BattleHelper.kt:15)
	at com.unciv.logic.automation.unit.UnitAutomation.tryAttacking(UnitAutomation.kt:243)
	at com.unciv.logic.automation.unit.UnitAutomation.automateUnitMoves(UnitAutomation.kt:209)
	at com.unciv.ui.popups.AutoPlayMenu.autoPlayMilitary(AutoPlayMenu.kt:59)
	at com.unciv.ui.popups.AutoPlayMenu.access$autoPlayMilitary(AutoPlayMenu.kt:20)
	at com.unciv.ui.popups.AutoPlayMenu$createContentTable$3.invoke(AutoPlayMenu.kt:38)
	at com.unciv.ui.popups.AutoPlayMenu$createContentTable$3.invoke(AutoPlayMenu.kt:38)
	at com.unciv.ui.popups.AnimatedMenuPopup$getButton$1$1.invoke(AnimatedMenuPopup.kt:155)
	at com.unciv.ui.popups.AnimatedMenuPopup$getButton$1$1.invoke(AnimatedMenuPopup.kt:153)
	at com.unciv.ui.components.input.ActivationActionMap.activate(ActivationActionMap.kt:56)
	at com.unciv.ui.components.input.ActorAttachments.activate(ActorAttachments.kt:42)
	at com.unciv.ui.components.input.ActivationExtensionsKt.activate(ActivationExtensions.kt:17)
	at com.unciv.ui.components.input.ActivationListener.tap(ActivationListener.kt:15)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener$1.tap(ActorGestureListener.java:52)
	at com.badlogic.gdx.input.GestureDetector.touchUp(GestureDetector.java:206)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener.handle(ActorGestureListener.java:125)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:354)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:87)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:70)
	at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:189)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:378)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:193)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:167)
	at com.unciv.app.desktop.HardenGdxAudio.<init>(HardenGdxAudio.kt:46)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:76)

```
**Save Mods:**
```
[Civ V - Vanilla]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```
</details>
```

**Comment by yairm210** [comment]
We need the saved game in order to debug this, please attach :)

**Comment by yairm210** [comment]
Closing as unworkable without saved game as example
Chances are we've diced this by now

**Comment by SeventhM** [comment]
Fair to close given its probably fixed by now, and this was before you added the github action, but kinda would've preferred a stale label on this one
