### ISSUE TITLE
Game crashes with automateWorkerAction - SOLVED in 4.9.16

### ISSUE THREAD

**Issue by wondalfo** [yairm210/Unciv#10870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.9.14

### Describe the bug

**Platform:** Android
**Version:** 4.9.14 (Build 950)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: AC2003
API Level: 31
System Memory: 7396 MB
    Available (used by Kernel): 2805 MB
    System Low Memory state: false
    Java heap limit: 512 MB
    Java heap free: 10 MB

--------------------------------

**Message:**
```
java.lang.NullPointerException
	at com.unciv.logic.automation.unit.WorkerAutomation.automateWorkerAction(WorkerAutomation.kt:312)
	at com.unciv.logic.automation.unit.CivilianUnitAutomation.automateCivilianUnit(CivilianUnitAutomation.kt:35)
	at com.unciv.logic.automation.unit.UnitAutomation.automateUnitMoves(UnitAutomation.kt:175)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateUnits(NextTurnAutomation.kt:348)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:68)
	at com.unciv.logic.civilization.managers.TurnManager.automateTurn(TurnManager.kt:338)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:390)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:617)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:8)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:4)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher.$r8$lambda$GFMOlD6QMgmLfgwAvPAW33Ob6HE(Unknown Source:0)
	at com.unciv.utils.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```
**Save Mods:**
```
[Civ V - Gods & Kings]
```

Ich removed Savegame, because larger than 65k Charakters. 

### Steps to Reproduce

Click New round

### Operating System

Android

**Comment by yairm210** [comment]
Already solved leaving open for others to see

**Comment by Marcel1605** [comment]
> Already solved leaving open for others to see

What day is version 4.9.16 available in the playstore and will old savegames also be fixed?

**Comment by yairm210** [comment]
Already available and yes
