### ISSUE TITLE
follow a pantheon 

### ISSUE THREAD

**Issue by yoolenyoolen** [yairm210/Unciv#10898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.9.17

### Describe the bug

Hi,
i just installed unciv on manjaro (latest stable version as of today 8th of january 2024), and it seemed to work fine but when comes the time to follow a pantheon, i get a fatal error message when i click on "follow [...] ", [...] being whatever i selected in the pantheon list.

If anyone knows why it happens ?

### Steps to Reproduce

start a new game, and play turns until  "found pantheon" appears, select one, and then click on "follow ..." on the right bottom of the screen.

### Operating System

Linux

### Additional Information

this is the error message
**Platform:** Desktop
**Version:** 4.9.17-patch1 (Build 954)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.screens.pickerscreens.PantheonPickerScreen`

--------------------------------

OS: Linux (amd64, 6.1.69-1-MANJARO)
	Manjaro Linux
Java: N/A 21+35
	Max Memory: 7956 MB
System default encoding: UTF-8

--------------------------------

**Message:**
```
java.lang.NullPointerException
	at com.unciv.logic.civilization.managers.ReligionManager.chooseBeliefs(ReligionManager.kt:379)
	at com.unciv.ui.screens.pickerscreens.PantheonPickerScreen$3.invoke(PantheonPickerScreen.kt:36)
	at com.unciv.ui.screens.pickerscreens.PantheonPickerScreen$3.invoke(PantheonPickerScreen.kt:35)
	at com.unciv.ui.screens.pickerscreens.ReligionPickerScreenCommon$setOKAction$1.invoke(ReligionPickerScreenCommon.kt:68)
	at com.unciv.ui.screens.pickerscreens.ReligionPickerScreenCommon$setOKAction$1.invoke(ReligionPickerScreenCommon.kt:67)
	at com.unciv.ui.components.input.ActivationActionMap.activate(ActivationActionMap.kt:56)
	at com.unciv.ui.components.input.ActorAttachments.activate(ActorAttachments.kt:42)
	at com.unciv.ui.components.input.ActivationExtensionsKt.activate(ActivationExtensions.kt:17)
	at com.unciv.ui.components.input.ActivationListener.tap(ActivationListener.kt:15)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener$1.tap(ActorGestureListener.java:52)
	at com.badlogic.gdx.input.GestureDetector.touchUp(GestureDetector.java:206)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener.handle(ActorGestureListener.java:125)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:354)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:87)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:70)
	at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:189)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:378)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:193)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:167)
	at com.unciv.app.desktop.HardenGdxAudio.<init>(HardenGdxAudio.kt:46)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:76)

```
**Save Mods:**
```
[Civ V - Gods & Kings]
```

**Comment by yoolenyoolen** [comment]
Hello,that was really fast and accurate. I just don't know what to do with the information you gave me ? I'm supposed to change some code somewhere ?


    Le lundi 8 janvier 2024 à 14:55:26 UTC+1, SomeTroglodyte ***@***.***> a écrit :  
 
 


Another case of #10888

**Comment by yoolenyoolen** [comment]
Got it


Thanks a lot again !     Le lundi 8 janvier 2024 à 19:11:03 UTC+1, SomeTroglodyte ***@***.***> a écrit :  
 
 


That means a fix is underway, and likely to be included in the next release. It's in the second stage of about 5 until it reaches you.
