### ISSUE TITLE
Weird crash when creating Huge vertical map

### ISSUE THREAD

**Issue by Caballero-Arepa** [yairm210/Unciv#10908]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Game Version

4.9.16

### Describe the bug

It hasn't happened ever before, and I'm on PC which is even weirder, with which I've generated maps larger than 57x88.

### Steps to Reproduce

I go to the Map Editor and want to make a new map, a huge map, but vertical instead of horizontal.
I click it, and it crashes, but only with that size or above. I can get perfectly fine a Huge map from the pre-set sizes, but when I use the Huge dimensions with the Custom size option, it crashes.

### Link to save file

<details><summary>Details</summary>
<p>

**Platform:** Desktop
**Version:** 4.9.16 (Build 952)
**Rulesets:** [New Building Icons, Policy mod, RekMOD, Iron and Blood, Vaalmaseda RP game, Belle Cartographie, 3rd and 4th Unique Component, Latam Scenarios, UncivRpGame, New minimal, Latin American_Civs, Star Wars for Alpha Frontier, Community Civs, Inverted World, Difficulty_Sandbox, More Fauna And Flora, Civ V - Vanilla, FantasyHex UI, Countryball Units, Community Civs Extra, Civ6 Tileset, Alpha Frontier, Naciones pa Unciv ES, Tactical unit set, Civ V - Gods & Kings, RyteakoRpGame]
**Last Screen:** `com.unciv.ui.screens.mapeditorscreen.MapEditorScreen`

--------------------------------

OS: Windows 10
Java: Oracle Corporation 25.232-b09
	Max Memory: 910 MB
System default encoding: windows-1252

--------------------------------

**Message:**
```
java.lang.IllegalStateException: TileMap.setTransients called on existing tileMatrix of different size
	at com.unciv.logic.map.TileMap.setTransients(TileMap.kt:469)
	at com.unciv.ui.screens.mapeditorscreen.MapEditorScreen.newMapHolder(MapEditorScreen.kt:175)
	at com.unciv.ui.screens.mapeditorscreen.MapEditorScreen.loadMap(MapEditorScreen.kt:216)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorGenerateTab.generate$freshMapCompleted(MapEditorGenerateTab.kt:94)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorGenerateTab.access$generate$freshMapCompleted(MapEditorGenerateTab.kt:36)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorGenerateTab$generate$2$1.invokeSuspend(MapEditorGenerateTab.kt:119)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorGenerateTab$generate$2$1.invoke(MapEditorGenerateTab.kt)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorGenerateTab$generate$2$1.invoke(MapEditorGenerateTab.kt)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:209)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:167)
	at com.unciv.app.desktop.HardenGdxAudio.<init>(HardenGdxAudio.kt:46)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:76)

```

</p>
</details> 

### Operating System

Windows

**Comment by Caballero-Arepa** [comment]
Well, Idk what happened, but now it's completely fine.
It was very weird for a few days.
Sorry for bothering.

**Comment by Caballero-Arepa** [comment]
Well, all that I did was to generate a Rectangular Empty custom dimenssion map (Width: 57 Height: 87) and it crashed.

**Comment by SeventhM** [comment]
I believe I've seen issues in the past with odd dimensions for rectangular maps, so it definitely could be something related to that
