### ISSUE TITLE
App Crash when i presa next round

### ISSUE THREAD

**Issue by Choosit** [yairm210/Unciv#11070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.5

### Describe the bug

**Platform:** Android
**Version:** 4.10.5 (Build 964)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: SM-N975F
API Level: 31
System Memory: 11418 MB
    Available (used by Kernel): 6659 MB
    System Low Memory state: false
    Java heap limit: 512 MB
    Java heap free: 0 MB

--------------------------------

**Message:**
```
java.lang.Exception: Can't reach this tile!
	at com.unciv.logic.map.mapunit.movement.PathsToTilesWithinTurn.getPathToTile(UnitMovement.kt:801)
	at com.unciv.logic.map.mapunit.movement.UnitMovement.moveToTile(UnitMovement.kt:403)
	at com.unciv.logic.map.mapunit.movement.UnitMovement.moveToTile$default(UnitMovement.kt:370)
	at com.unciv.logic.automation.unit.BattleHelper.tryAttackNearbyEnemy(BattleHelper.kt:32)
	at com.unciv.logic.automation.unit.BattleHelper.tryAttackNearbyEnemy$default(BattleHelper.kt:15)
	at com.unciv.logic.automation.civilization.BarbarianAutomation.automateCombatUnit(BarbarianAutomation.kt:60)
	at com.unciv.logic.automation.civilization.BarbarianAutomation.automateUnit(BarbarianAutomation.kt:23)
	at com.unciv.logic.automation.civilization.BarbarianAutomation.automate(BarbarianAutomation.kt:13)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:37)
	at com.unciv.logic.civilization.managers.TurnManager.automateTurn(TurnManager.kt:339)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:391)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:599)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:8)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:4)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher.$r8$lambda$GFMOlD6QMgmLfgwAvPAW33Ob6HE(Unknown Source:0)
	at com.unciv.utils.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

```
**Save Mods:**
```
[Civ V - Gods & Kings]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```


### Steps to Reproduce

1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
4. See error


### Screenshots

_No response_

### Link to save file

_No response_

### Operating System

Android

### Additional Information

_No response_

**Comment by yairm210** [comment]
Copy of #11062, solved 4.10,6
