### ISSUE TITLE
The game crashes and generates a report saying "Can't reach this tile"

### ISSUE THREAD

**Issue by YouLanjie** [yairm210/Unciv#11089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.4 (Build 963)

### Describe the bug

When I clicked the "Next Round" button, the game unexpectedly crashed. The following is the generated report:

**Platform:** Android
**Version:** 4.10.4 (Build 963)
**Rulesets:** [Civ V - Gods & Kings, Community Maps, Civ V - Vanilla, WW2 Nations]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: SM-N9500
API Level: 28
System Memory: 5215 MB
    Available (used by Kernel): 1473 MB
    System Low Memory state: false
    Java heap limit: 512 MB
    Java heap free: 0 MB

--------------------------------

**Message:**
```
java.lang.Exception: Can't reach this tile!
	at com.unciv.logic.map.mapunit.movement.PathsToTilesWithinTurn.getPathToTile(UnitMovement.kt:801)
	at com.unciv.logic.map.mapunit.movement.UnitMovement.moveToTile(UnitMovement.kt:403)
	at com.unciv.logic.map.mapunit.movement.UnitMovement.moveToTile$default(UnitMovement.kt:370)
	at com.unciv.logic.automation.unit.BattleHelper.tryAttackNearbyEnemy(BattleHelper.kt:32)
	at com.unciv.logic.automation.unit.BattleHelper.tryAttackNearbyEnemy$default(BattleHelper.kt:15)
	at com.unciv.logic.automation.unit.UnitAutomation.tryAttacking(UnitAutomation.kt:259)
	at com.unciv.logic.automation.unit.UnitAutomation.automateUnitMoves(UnitAutomation.kt:225)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateUnits(NextTurnAutomation.kt:390)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:71)
	at com.unciv.logic.civilization.managers.TurnManager.automateTurn(TurnManager.kt:339)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:391)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:599)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:8)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:4)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher.$r8$lambda$GFMOlD6QMgmLfgwAvPAW33Ob6HE(Unknown Source:0)
	at com.unciv.utils.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```
**Save Mods:**
```
[Civ V - Gods & Kings, WW2 Nations]
```

### Steps to Reproduce

1. Enter the game save I provided
2. Click on "Next turn"
3. See error

### Link to save file

[save222.txt](https://github.com/yairm210/Unciv/files/14175734/save222.txt)
[save223.txt](https://github.com/yairm210/Unciv/files/14175738/save223.txt)
[save224.txt](https://github.com/yairm210/Unciv/files/14175741/save224.txt)

Doing nothing or attempting to enter turn 225 after entering the 223rd or 224th save will cause a crash. However, if you enter the 222nd round and enter the 225th round by automating, it will not crash. I hope the above information will help you solve the problem.

### Operating System

Android

### Additional Information

After exiting the game on the Android platform and re entering, you will get stuck in the game's startup interface and cannot enter the main interface. You need to exit the game again to re-enter. Although it does not affect normal use, it greatly affects the user experience.

**Comment by yairm210** [comment]
Copy of #11062, please update :)
