### ISSUE TITLE
Null pointer in automateWorkerAction upon clicking next turn

### ISSUE THREAD

**Issue by Zykr** [yairm210/Unciv#11088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.9.16 (Build 952)

### Describe the bug

Null pointer exception in automateWorkerAction upon clicking next turn.
The issue is repeatable with the attached save file.

### Steps to Reproduce

1. Launch Game
2. Copy Save File to Clipboard
3. Click Load Game
4. Click Load Copied data 
5. Click on 'Next turn'
6. See error

### Link to save file

[unciv_crashing_save.txt](https://github.com/yairm210/Unciv/files/14174197/unciv_crashing_save.txt)

### Operating System

Android

### Additional Information

**Platform:** Desktop
**Version:** 4.9.16 (Build 952)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

OS: Linux (amd64, 5.10.0-26-amd64)
	Debian GNU/Linux 11 (bullseye)
Java: Eclipse Adoptium Temurin-11.0.19+7
	Max Memory: 1024 MB
System default encoding: UTF-8

--------------------------------

**Message:**
```
java.lang.NullPointerException
	at com.unciv.logic.automation.unit.WorkerAutomation.automateWorkerAction(WorkerAutomation.kt:313)
	at com.unciv.logic.automation.unit.CivilianUnitAutomation.automateCivilianUnit(CivilianUnitAutomation.kt:35)
	at com.unciv.logic.automation.unit.UnitAutomation.automateUnitMoves(UnitAutomation.kt:154)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateUnits(NextTurnAutomation.kt:350)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:68)
	at com.unciv.logic.civilization.managers.TurnManager.automateTurn(TurnManager.kt:338)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:391)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:617)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```
**Save Mods:**
```
[Civ V - Gods & Kings]
```

**Save Data:**

Too Large, see attached file.

**Comment by tuvus** [comment]
Please update. I cannot replicate your error on 4.10.7. Your current version is 4.9.16, which is unsupported, we may have solved the problem since then.

**Comment by Zykr** [comment]
I can confirm that in 4.10.7 the crash doesn't seem to happen. Thank you for the quick response. For some reason, I was sure I had the latest version, but apparently not.
