### ISSUE TITLE
Current master does not load **any** game

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#11202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

from current source

### Describe the bug

2024-02-26T10:24:38.783250200Z [main @Load game#52] [LoadGameScreen] [ERROR] Error while loading game | kotlin.UninitializedPropertyAccessException: lateinit property baseUnit has not been initialized
	at com.unciv.logic.map.mapunit.MapUnit.getBaseUnit(MapUnit.kt:100)
	at com.unciv.logic.map.mapunit.MapUnitCache.updateUniques(MapUnitCache.kt:76)
	at com.unciv.logic.map.mapunit.MapUnit.assignOwner(MapUnit.kt:963)
	at com.unciv.logic.map.tile.Tile.setUnitTransients(Tile.kt:757)
	at com.unciv.logic.map.TileMap.setTransients(TileMap.kt:486)
	at com.unciv.logic.map.TileMap.setTransients$default(TileMap.kt:448)
	at com.unciv.logic.GameInfo.setTransients(GameInfo.kt:636)
	at com.unciv.logic.files.UncivFiles$Companion.gameInfoFromString(UncivFiles.kt:394)

### Steps to Reproduce

1. Run unit tests - or run and load any game
2. Check console output

### Operating System

Linux

### Additional Information

Copied from #11199 where I started the analysis:

"...I can fix the unit test fail (and loading that game directly) with:
<details>

```patch
Index: core/src/com/unciv/logic/map/mapunit/MapUnit.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/core/src/com/unciv/logic/map/mapunit/MapUnit.kt b/core/src/com/unciv/logic/map/mapunit/MapUnit.kt
--- a/core/src/com/unciv/logic/map/mapunit/MapUnit.kt	(revision 2d49838f130cff76f469a0e3bfc272f8d10c4c3d)
+++ b/core/src/com/unciv/logic/map/mapunit/MapUnit.kt	(date 1708941925745)
@@ -602,29 +602,26 @@
     //endregion
     //region state-changing functions
 
-    fun setTransients(ruleset: Ruleset) {
-        promotions.setTransients(this)
+    fun setTransients(ruleset: Ruleset, unitCivTransients: Boolean = false) {
         baseUnit = ruleset.units[name]
             ?: throw java.lang.Exception("Unit $name is not found!")
 
+        if (unitCivTransients)
+            // Note This will call cache.updateUniques(), and below updateUniques() will call it again.
+            // Since placeUnitNearTile also calls assignOwner(civ, false) we can't just skip the call in assignOwner without side effects???
+            assignOwner(currentTile.tileMap.gameInfo.getCivilization(owner), false)
+
+        promotions.setTransients(this)
         updateUniques()
         if (action == UnitActionType.Automate.value) automated = true
     }
 
     fun updateUniques() {
-        val uniques = ArrayList<Unique>()
-        val baseUnit = baseUnit()
-        uniques.addAll(baseUnit.uniqueObjects)
-        uniques.addAll(type.uniqueObjects)
-
-        for (promotion in promotions.getPromotions()) {
-            uniques.addAll(promotion.uniqueObjects)
-        }
-
-        tempUniquesMap = UniqueMap().apply {
-            addUniques(uniques)
-        }
-
+        val uniqueSources =
+            baseUnit.uniqueObjects.asSequence() +
+            type.uniqueObjects +
+            promotions.getPromotions().flatMap { it.uniqueObjects }
+        tempUniquesMap = UniqueMap(uniqueSources)
         cache.updateUniques()
     }
 
Index: core/src/com/unciv/models/ruleset/nation/CityStateType.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/core/src/com/unciv/models/ruleset/nation/CityStateType.kt b/core/src/com/unciv/models/ruleset/nation/CityStateType.kt
--- a/core/src/com/unciv/models/ruleset/nation/CityStateType.kt	(revision 2d49838f130cff76f469a0e3bfc272f8d10c4c3d)
+++ b/core/src/com/unciv/models/ruleset/nation/CityStateType.kt	(date 1704275904459)
@@ -9,9 +9,9 @@
 class CityStateType: INamed {
     override var name = ""
     var friendBonusUniques = ArrayList<String>()
-    val friendBonusUniqueMap by lazy { UniqueMap().apply { addUniques(friendBonusUniques.map { Unique(it, sourceObjectType = UniqueTarget.CityState) }) } }
+    val friendBonusUniqueMap by lazy { UniqueMap(friendBonusUniques.asSequence().map { Unique(it, sourceObjectType = UniqueTarget.CityState) }) }
     var allyBonusUniques = ArrayList<String>()
-    val allyBonusUniqueMap by lazy { UniqueMap().apply { addUniques(allyBonusUniques.map { Unique(it, sourceObjectType = UniqueTarget.CityState) }) } }
+    val allyBonusUniqueMap by lazy { UniqueMap(allyBonusUniques.asSequence().map { Unique(it, sourceObjectType = UniqueTarget.CityState) }) }
 
     var color:List<Int> = listOf(255,255,255)
     private val colorObject by lazy { colorFromRGB(color) }
Index: core/src/com/unciv/models/ruleset/unique/Unique.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/core/src/com/unciv/models/ruleset/unique/Unique.kt b/core/src/com/unciv/models/ruleset/unique/Unique.kt
--- a/core/src/com/unciv/models/ruleset/unique/Unique.kt	(revision 2d49838f130cff76f469a0e3bfc272f8d10c4c3d)
+++ b/core/src/com/unciv/models/ruleset/unique/Unique.kt	(date 1708940891777)
@@ -204,10 +204,13 @@
     }
 }
 
-class UniqueMap: HashMap<String, ArrayList<Unique>>() {
+class UniqueMap() : HashMap<String, ArrayList<Unique>>() {
     //todo Once all untyped Uniques are converted, this should be  HashMap<UniqueType, *>
     // For now, we can have both map types "side by side" each serving their own purpose,
     // and gradually this one will be deprecated in favor of the other
+    constructor(uniques: Sequence<Unique>) : this() {
+        addUniques(uniques.asIterable())
+    }
 
     /** Adds one [unique] unless it has a ConditionalTimedUnique conditional */
     fun addUnique(unique: Unique) {
Index: core/src/com/unciv/logic/map/tile/Tile.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/core/src/com/unciv/logic/map/tile/Tile.kt b/core/src/com/unciv/logic/map/tile/Tile.kt
--- a/core/src/com/unciv/logic/map/tile/Tile.kt	(revision 2d49838f130cff76f469a0e3bfc272f8d10c4c3d)
+++ b/core/src/com/unciv/logic/map/tile/Tile.kt	(date 1708941799651)
@@ -753,9 +753,7 @@
     fun setUnitTransients(unitCivTransients: Boolean) {
         for (unit in getUnits()) {
             unit.currentTile = this
-            if (unitCivTransients)
-                unit.assignOwner(tileMap.gameInfo.getCivilization(unit.owner), false)
-            unit.setTransients(ruleset)
+            unit.setTransients(ruleset, unitCivTransients)
         }
     }
 
@@ -847,15 +845,8 @@
         val terrainNameList = allTerrains.map { it.name }.toList()
 
         // List hash is function of all its items, so the same items in the same order will always give the same hash
-        val cachedUniqueMap = tileMap.tileUniqueMapCache[terrainNameList]
-        terrainUniqueMap = if (cachedUniqueMap != null)
-            cachedUniqueMap
-        else {
-            val newUniqueMap = UniqueMap()
-            for (terrain in allTerrains)
-                newUniqueMap.addUniques(terrain.uniqueObjects)
-            tileMap.tileUniqueMapCache[terrainNameList] = newUniqueMap
-            newUniqueMap
+        terrainUniqueMap = tileMap.tileUniqueMapCache.getOrPut(terrainNameList) {
+            UniqueMap(allTerrains.flatMap { it.uniqueObjects })
         }
     }
 
```
</details>
... but the entire 'what happens when' in the `setTransients` card house still feels not quite transparent to me."

That patch, besides cleaning stuff that irked my eyes, essentially ensures baseUnit is set first, then civ, then the uniques including the cache. With less reorg, you get to the point where Tile.setUnitTransients fails as seen here if assignOwner is done first, and fails with civ not initialized if you reverse the order...

I still don't get why this didn't start crashing months ago...

**Comment by yairm210** [comment]
Looks good! Adding a sequence-based constructor to UniqueMap makes things much more readable :D
