### ISSUE TITLE
Can't create window

### ISSUE THREAD

**Issue by Inter360** [yairm210/Unciv#11364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.22

### Describe the bug

Creates all necessary files, can even read mods, but crashes at creating window

[LWJGL] GLFW_API_UNAVAILABLE error
        Description : WGL: The driver does not appear to support OpenGL
        Stacktrace  :
                org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:2058)
                org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:2229)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:527)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:463)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:449)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:163)
                com.unciv.app.desktop.HardenGdxAudio.<init>(HardenGdxAudio.kt:46)
                com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:76)
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't create window
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:530)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:463)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:449)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:163)
        at com.unciv.app.desktop.HardenGdxAudio.<init>(HardenGdxAudio.kt:46)
        at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:76)

### Steps to Reproduce

1. Download and unzip unciv into desktop
2. Open cmd, and open unciv through unciv
3. See an error in cmd

### Screenshots

![image](https://github.com/yairm210/Unciv/assets/74828594/1d9d33b4-a78a-42ab-a1ad-49da9e638b4a)

### Link to save file

None

### Operating System

Windows

**Comment by yairm210** [comment]
A google of the error message shows this is a problem with your Windows drivers, not with Unciv.

See [here](https://answers.microsoft.com/en-us/windows/forum/all/my-drivers-dont-support-opengl/a1ee0267-4dc8-4385-a185-6ed322d78329) - please update your graphics drivers

**Comment by Inter360** [comment]
Ok, thanks
