### ISSUE TITLE
Game crash on starting new game after deleting mod

### ISSUE THREAD

**Issue by Muro81** [yairm210/Unciv#11506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.11.5

### Describe the bug

I deleted ancient total war mod, which I didnt use at all. When I go to create new game I get a crash report. The last selected play option was a mod Fantasia that worked fine.
Crash report:
**Platform:** Android
**Version:** 4.11.5 (Build 988)
**Rulesets:** [Civ V - Vanilla, RekMOD, Civ V - Gods & Kings, DeCiv Redux, Epic of Fantasy, Barbarian xp farm, Civ6 Tileset, Fantasia]
**Last Screen:** `com.unciv.ui.screens.mainmenuscreen.MainMenuScreen`

--------------------------------

Device Model: M2101K6G
API Level: 33
System Memory: 5570 MB
    Available (used by Kernel): 1995 MB
    System Low Memory state: false
    Java heap limit: 512 MB
    Java heap free: 19 MB

--------------------------------

**Message:**
```
kotlin.UninitializedPropertyAccessException: lateinit property baseRuleset has not been initialized
	at com.unciv.ui.screens.newgamescreen.ModCheckboxTable.deselectIncompatibleMods(ModCheckboxTable.kt:199)
	at com.unciv.ui.screens.newgamescreen.ModCheckboxTable.updateSelection(ModCheckboxTable.kt:79)
	at com.unciv.ui.screens.newgamescreen.GameOptionsTable.update(GameOptionsTable.kt:77)
	at com.unciv.ui.screens.newgamescreen.GameOptionsTable.<init>(GameOptionsTable.kt:70)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.<init>(NewGameScreen.kt:77)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.<init>(NewGameScreen.kt:50)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen$newGameButton$1.invoke(MainMenuScreen.kt:150)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen$newGameButton$1.invoke(MainMenuScreen.kt:149)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen$getMenuButton$1.invoke(MainMenuScreen.kt:103)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen$getMenuButton$1.invoke(MainMenuScreen.kt:101)
	at com.unciv.ui.components.input.ActivationActionMap.activate(ActivationActionMap.kt:56)
	at com.unciv.ui.components.input.ActorAttachments.activate(ActorAttachments.kt:42)
	at com.unciv.ui.components.input.ActivationExtensionsKt.activate(ActivationExtensions.kt:17)
	at com.unciv.ui.components.input.ActivationListener.tap(ActivationListener.kt:15)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener$1.tap(ActorGestureListener.java:52)
	at com.badlogic.gdx.input.GestureDetector.touchUp(GestureDetector.java:206)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener.handle(ActorGestureListener.java:125)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:354)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:87)
	at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:423)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:503)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1590)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)

```
Able to provide any additional info needed. 

### Steps to Reproduce

1. Install ancient total war mod.
2. Don't use it.
3. Also have fantasia installed.
4. Make new game of Fantasia mod.
5. Delete ancient total war.
6. Go to new game
7. Crash

### Operating System

Android

**Comment by Muro81** [comment]
Deleting the map that was in the mod, solved it.

**Comment by Muro81** [comment]
Not sure, I pressed from mods menu delete mod. And I go to maps editor screen, load map, and delete the map that was leftover.

**Comment by Muro81** [comment]
I never touched the map in map editor tho, only time i viewed it was in the star game screen.

**Comment by Muro81** [comment]
Not sure about the file manager, I have one that came with phone.

**Comment by Muro81** [comment]
Yeah device explorer, but in like an hour or two.

**Comment by Muro81** [comment]
I tried this but I cant access any files under the com.unciv.app, run as: package not debuggable, Is what it says.

**Comment by Muro81** [comment]
Its possible to view debuggable aps, but id need to build it in debug mode on my phone to view that. Should it be possible if I git clone the project?

**Comment by Muro81** [comment]
Wel I have some apps that were built by myself on Windows machines. I can acces the debug ones but not the release ones that were signed? Or it could be the shrinking or minifying of resources as well I guess?

**Comment by AdityaMH** [comment]
Also editing base ruleset even just add "a" will lead you permanent crash.
