### ISSUE TITLE
Map editor crash placing any improvement

### ISSUE THREAD

**Issue by Randombot777** [yairm210/Unciv#11739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.11.18-patch1 (build 1004 )

### Describe the bug

In map editor when i want to put an improvement, any of them, an unrecoverable error occurs and the editor closes.
I erased the game and reinstalled but the issue remains.
No mods installed, just Gods & Kings.

### Steps to Reproduce

1.Enter map editor
2.Generate a map
3.Put an improvement, ancient ruins, farm, any of them.
4.An unrecoverable error has ocurred.

### Screenshots

**Platform:** Android
**Version:** 4.11.18-patch1 (Build 1004)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.screens.mapeditorscreen.MapEditorScreen`

--------------------------------

Device Model: SM-A235M
API Level: 34
System Memory: 3589 MB
    Available (used by Kernel): 931 MB
    System Low Memory state: false
    Java heap limit: 512 MB
    Java heap free: 16 MB

--------------------------------

**Message:**
```
kotlin.UninitializedPropertyAccessException: lateinit property gameInfo has not been initialized
	at com.unciv.logic.map.TileMap.getGameInfo(TileMap.kt:71)
	at com.unciv.logic.map.tile.TileImprovementFunctions.changeImprovement(TileImprovementFunctions.kt:221)
	at com.unciv.logic.map.tile.Tile.changeImprovement(Tile.kt:831)
	at com.unciv.logic.map.tile.Tile.changeImprovement$default(Tile.kt:830)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorEditImprovementsTab$addImprovements$2$2.invoke(MapEditorEditSubTabs.kt:235)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorEditImprovementsTab$addImprovements$2$2.invoke(MapEditorEditSubTabs.kt:234)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorEditTab.paintTile(MapEditorEditTab.kt:303)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorEditTab.paintTilesWithBrush$core(MapEditorEditTab.kt:265)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorEditTab.tileClickHandler(MapEditorEditTab.kt:216)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorEditTab.access$tileClickHandler(MapEditorEditTab.kt:33)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorEditTab$activated$1.invoke(MapEditorEditTab.kt:196)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorEditTab$activated$1.invoke(MapEditorEditTab.kt:196)
	at com.unciv.ui.screens.mapeditorscreen.MapEditorScreen$newMapHolder$newHolder$1.invoke(MapEditorScreen.kt:186)
	at com.unciv.ui.screens.mapeditorscreen.MapEditorScreen$newMapHolder$newHolder$1.invoke(MapEditorScreen.kt:185)
	at com.unciv.ui.screens.mapeditorscreen.EditorMapHolder$addTiles$1.invoke(EditorMapHolder.kt:99)
	at com.unciv.ui.screens.mapeditorscreen.EditorMapHolder$addTiles$1.invoke(EditorMapHolder.kt:99)
	at com.unciv.ui.components.input.ActivationActionMap.activate(ActivationActionMap.kt:56)
	at com.unciv.ui.components.input.ActorAttachments.activate(ActorAttachments.kt:42)
	at com.unciv.ui.components.input.ActivationExtensionsKt.activate(ActivationExtensions.kt:17)
	at com.unciv.ui.components.input.ActivationListener.tap(ActivationListener.kt:15)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener$1.tap(ActorGestureListener.java:52)
	at com.badlogic.gdx.input.GestureDetector.touchUp(GestureDetector.java:206)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener.handle(ActorGestureListener.java:125)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:354)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:87)
	at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:423)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:503)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1584)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1283)

```

### Operating System

Android

**Comment by Satavahana** [comment]
İ have the same issue i using unciv potato (2nd unciv) to solve problems temporary i download it from itch. İo
