### ISSUE TITLE
Game crashes when I put a tile improvement

### ISSUE THREAD

**Issue by Bishopoftheimmaculateconception** [yairm210/Unciv#11763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.11.18-patch1

### Describe the bug

In map editor when I go to the edit tab and go to tile improvements. Every single tile improvements I use from there on a map I am editing the crashes right away 

### Steps to Reproduce

1. Go to 'map editor'
2. Click on 'edits'
3. Scroll to 'tile improvements and use any of them on a map'

### Screenshots

**Platform:** Android
**Version:** 4.11.18-patch1 (Build 1004)
**Rulesets:** [The Undead, Civ V - Vanilla, Latin American_Civs, Civ V - Gods & Kings, Community Maps, 5Hex Tileset, Better ruins Lite, Barbarian xp farm, Better ruins]
**Last Screen:** `com.unciv.ui.screens.mapeditorscreen.MapEditorScreen`

--------------------------------

Device Model: SM-A127F
API Level: 33
System Memory: 3703 MB
    Available (used by Kernel): 667 MB
    System Low Memory state: false
    Java heap limit: 512 MB
    Java heap free: 13 MB

--------------------------------

**Message:**
```
kotlin.UninitializedPropertyAccessException: lateinit property gameInfo has not been initialized
	at com.unciv.logic.map.TileMap.getGameInfo(TileMap.kt:71)
	at com.unciv.logic.map.tile.TileImprovementFunctions.changeImprovement(TileImprovementFunctions.kt:221)
	at com.unciv.logic.map.tile.Tile.changeImprovement(Tile.kt:831)
	at com.unciv.logic.map.tile.Tile.changeImprovement$default(Tile.kt:830)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorEditImprovementsTab$addImprovements$2$2.invoke(MapEditorEditSubTabs.kt:235)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorEditImprovementsTab$addImprovements$2$2.invoke(MapEditorEditSubTabs.kt:234)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorEditTab.paintTile(MapEditorEditTab.kt:303)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorEditTab.paintTilesWithBrush$core(MapEditorEditTab.kt:265)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorEditTab.tileClickHandler(MapEditorEditTab.kt:216)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorEditTab.access$tileClickHandler(MapEditorEditTab.kt:33)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorEditTab$activated$1.invoke(MapEditorEditTab.kt:196)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorEditTab$activated$1.invoke(MapEditorEditTab.kt:196)
	at com.unciv.ui.screens.mapeditorscreen.MapEditorScreen$newMapHolder$newHolder$1.invoke(MapEditorScreen.kt:186)
	at com.unciv.ui.screens.mapeditorscreen.MapEditorScreen$newMapHolder$newHolder$1.invoke(MapEditorScreen.kt:185)
	at com.unciv.ui.screens.mapeditorscreen.EditorMapHolder$addTiles$1.invoke(EditorMapHolder.kt:99)
	at com.unciv.ui.screens.mapeditorscreen.EditorMapHolder$addTiles$1.invoke(EditorMapHolder.kt:99)
	at com.unciv.ui.components.input.ActivationActionMap.activate(ActivationActionMap.kt:56)
	at com.unciv.ui.components.input.ActorAttachments.activate(ActorAttachments.kt:42)
	at com.unciv.ui.components.input.ActivationExtensionsKt.activate(ActivationExtensions.kt:17)
	at com.unciv.ui.components.input.ActivationListener.tap(ActivationListener.kt:15)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener$1.tap(ActorGestureListener.java:52)
	at com.badlogic.gdx.input.GestureDetector.touchUp(GestureDetector.java:206)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener.handle(ActorGestureListener.java:125)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:354)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:87)
	at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:423)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:503)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1593)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1287)

```
![Screenshot_20240616_151851_Unciv](https://github.com/yairm210/Unciv/assets/172957574/859b10c7-4679-4dad-a491-6de3f28ea2d2)
![Screenshot_20240616_151858_Unciv](https://github.com/yairm210/Unciv/assets/172957574/e65ae72d-a195-4ce4-94f9-58c168bb2351)

### Link to save file

**Platform:** Android
**Version:** 4.11.18-patch1 (Build 1004)
**Rulesets:** [The Undead, Civ V - Vanilla, Latin American_Civs, Civ V - Gods & Kings, Community Maps, 5Hex Tileset, Better ruins Lite, Barbarian xp farm, Better ruins]
**Last Screen:** `com.unciv.ui.screens.mapeditorscreen.MapEditorScreen`

--------------------------------

Device Model: SM-A127F
API Level: 33
System Memory: 3703 MB
    Available (used by Kernel): 667 MB
    System Low Memory state: false
    Java heap limit: 512 MB
    Java heap free: 13 MB

--------------------------------

**Message:**
```
kotlin.UninitializedPropertyAccessException: lateinit property gameInfo has not been initialized
	at com.unciv.logic.map.TileMap.getGameInfo(TileMap.kt:71)
	at com.unciv.logic.map.tile.TileImprovementFunctions.changeImprovement(TileImprovementFunctions.kt:221)
	at com.unciv.logic.map.tile.Tile.changeImprovement(Tile.kt:831)
	at com.unciv.logic.map.tile.Tile.changeImprovement$default(Tile.kt:830)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorEditImprovementsTab$addImprovements$2$2.invoke(MapEditorEditSubTabs.kt:235)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorEditImprovementsTab$addImprovements$2$2.invoke(MapEditorEditSubTabs.kt:234)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorEditTab.paintTile(MapEditorEditTab.kt:303)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorEditTab.paintTilesWithBrush$core(MapEditorEditTab.kt:265)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorEditTab.tileClickHandler(MapEditorEditTab.kt:216)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorEditTab.access$tileClickHandler(MapEditorEditTab.kt:33)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorEditTab$activated$1.invoke(MapEditorEditTab.kt:196)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorEditTab$activated$1.invoke(MapEditorEditTab.kt:196)
	at com.unciv.ui.screens.mapeditorscreen.MapEditorScreen$newMapHolder$newHolder$1.invoke(MapEditorScreen.kt:186)
	at com.unciv.ui.screens.mapeditorscreen.MapEditorScreen$newMapHolder$newHolder$1.invoke(MapEditorScreen.kt:185)
	at com.unciv.ui.screens.mapeditorscreen.EditorMapHolder$addTiles$1.invoke(EditorMapHolder.kt:99)
	at com.unciv.ui.screens.mapeditorscreen.EditorMapHolder$addTiles$1.invoke(EditorMapHolder.kt:99)
	at com.unciv.ui.components.input.ActivationActionMap.activate(ActivationActionMap.kt:56)
	at com.unciv.ui.components.input.ActorAttachments.activate(ActorAttachments.kt:42)
	at com.unciv.ui.components.input.ActivationExtensionsKt.activate(ActivationExtensions.kt:17)
	at com.unciv.ui.components.input.ActivationListener.tap(ActivationListener.kt:15)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener$1.tap(ActorGestureListener.java:52)
	at com.badlogic.gdx.input.GestureDetector.touchUp(GestureDetector.java:206)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener.handle(ActorGestureListener.java:125)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:354)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:87)
	at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:423)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:503)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1593)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1287)

```

### Operating System

Android

### Additional Information

This is not a bug in a game I am already playing this is a bug when editing maps and it is quite annoying when putting tile improvements in a map.

**Comment by Yair-Morgenstern-Forter** [comment]
Solved in 4.12.0

**Comment by yairm210** [comment]
Solved in 4.12.0

**Comment by tuvus** [comment]
Ahh, thats why I couldn't replicate it.

**Comment by Bishopoftheimmaculateconception** [comment]
Thank you!
