### ISSUE TITLE
Crash after the city was founded

### ISSUE THREAD

**Issue by SchoeniosX** [yairm210/Unciv#11845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.2

### Describe the bug

When I created a new multilayer server it crashed. At the start of the round I usually use the settler to found a city. However, this led to the game crashing with an error message. Mods are used!

### Steps to Reproduce

1. Go to 'New Game'
2. Click on 'Start Game'
3. Use Settler 

### Screenshots

(-)

### Link to save file

**Platform:** Android
**Version:** 4.12.2-patch1 (Build 1011)
**Rulesets:** [Policy mod, temp--694ce0aa, Project Allciv, Medieval Civilizations, DeCiv Redux, 3rd and 4th Unique Component, Extra Buildings, Extra Units, Uniques From Chubz, Tech Stopper _Renaissance _, Warfare Expanded Lite, more Victory Types mod, supply ship, CS Unique Components=, Inverted World, More Luxuries, Better ruins Lite, More Fauna And Flora, Resourceplus, Resource Recyclers, Slow Tech, Better Pantheons Lite, Extra Wonders, era event, Uncivilized Expansion, Warfare Edited, DeepSky, Unciv Training the Leader, Disease mod, Better Pantheons, Spaciv, Civ V - Gods & Kings, Better Workers, capture GP, Great Farmer, Ark s Unciv Lost Homes, Classical Harbors, Extra Religions, temp--753cd0ab, Leader Mission, Ark In Unciv, Ark s Unciv Animated, Beach mod, Old Ancient Civilizations, Power to People GnK, Taxation System, ReligionPlus, Better Great Merchant, Ark s UNCIV Evolved, Civ V - Vanilla, Ark s UNCIV Expansion, other historical civs, Warfare Expanded Rework, Dimensiondogs expansion mod, philosophy mod, Atheism mod, Barbarians but Better, Compound Interest Mod, CS Rework, Ancient Civilizations, Yet Another Resource Mod, More Natural Wonders, The Great Unciv Rework, Leader Mission 2 Rising Power, Horses and Iron mod]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: SM-A105FN
API Level: 30
System Memory: 1743 MB
    Available (used by Kernel): 162 MB
    System Low Memory state: false
    Java heap limit: 512 MB
    Java heap free: 0 MB

--------------------------------

**Message:**
```
java.lang.Exception: No building by the name of Cuddly toy factor exists!
	at com.unciv.logic.civilization.Civilization.getEquivalentBuilding(Civilization.kt:569)
	at com.unciv.models.ruleset.Building$notMetRejections$1.invokeSuspend(Building.kt:421)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at kotlin.sequences.SequenceBuilderIterator.yieldAll(SequenceBuilder.kt:172)
	at kotlin.sequences.SequenceScope.yieldAll(SequenceBuilder.kt:92)
	at com.unciv.models.ruleset.Building$getRejectionReasons$1.invokeSuspend(Building.kt:290)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at kotlin.sequences.SequencesKt___SequencesKt.none(_Sequences.kt:2130)
	at com.unciv.models.ruleset.Building.isBuildable(Building.kt:455)
	at com.unciv.logic.automation.city.ConstructionAutomation$filterBuildable$1.invoke(ConstructionAutomation.kt:106)
	at com.unciv.logic.automation.city.ConstructionAutomation$filterBuildable$1.invoke(ConstructionAutomation.kt:103)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:171)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at com.unciv.logic.automation.city.ConstructionAutomation.addBuildingChoices(ConstructionAutomation.kt:264)
	at com.unciv.logic.automation.city.ConstructionAutomation.chooseNextConstruction(ConstructionAutomation.kt:116)
	at com.unciv.logic.city.CityConstructions.chooseNextConstruction(CityConstructions.kt:714)
	at com.unciv.logic.civilization.Civilization.addCity(Civilization.kt:885)
	at com.unciv.ui.screens.worldscreen.unit.actions.UnitActionsFromUniques$getFoundCityAction$foundAction$1.invoke(UnitActionsFromUniques.kt:58)
	at com.unciv.ui.screens.worldscreen.unit.actions.UnitActionsFromUniques$getFoundCityAction$foundAction$1.invoke(UnitActionsFromUniques.kt:55)
	at com.unciv.ui.screens.worldscreen.unit.actions.UnitActionsFromUniques$getFoundCityAction$1.invoke(UnitActionsFromUniques.kt:85)
	at com.unciv.ui.screens.worldscreen.unit.actions.UnitActionsFromUniques$getFoundCityAction$1.invoke(UnitActionsFromUniques.kt:96)
	at com.unciv.ui.screens.worldscreen.unit.actions.UnitActionsTable.activateAction(UnitActionsTable.kt:175)
	at com.unciv.ui.screens.worldscreen.unit.actions.UnitActionsTable.access$activateAction(UnitActionsTable.kt:21)
	at com.unciv.ui.screens.worldscreen.unit.actions.UnitActionsTable$getUnitActionButton$1.invoke(UnitActionsTable.kt:167)
	at com.unciv.ui.screens.worldscreen.unit.actions.UnitActionsTable$getUnitActionButton$1.invoke(UnitActionsTable.kt:166)
	at com.unciv.ui.components.input.ActivationActionMap.activate(ActivationActionMap.kt:56)
	at com.unciv.ui.components.input.ActorAttachments.activate(ActorAttachments.kt:42)
	at com.unciv.ui.components.input.ActivationExtensionsKt.activate(ActivationExtensions.kt:17)
	at com.unciv.ui.components.input.ActivationListener.tap(ActivationListener.kt:15)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener$1.tap(ActorGestureListener.java:52)
	at com.badlogic.gdx.input.GestureDetector.touchUp(GestureDetector.java:206)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener.handle(ActorGestureListener.java:125)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:354)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:87)
	at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:423)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:503)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1591)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)

```
**Save Mods:**
```
[The Great Unciv Rework, 3rd and 4th Unique Component, Ancient Civilizations, Atheism mod, Barbarians but Better, Beach mod, Better Great Merchant, Better Pantheons Lite, Better Workers, Better ruins Lite, CS Rework, CS Unique Components=, Compound Interest Mod, Disease mod, Extra Buildings, Extra Units, Extra Wonders, Great Farmer, Horses and Iron mod, Inverted World, Medieval Civilizations, More Fauna And Flora, More Luxuries, More Natural Wonders, Old Ancient Civilizations, Power to People GnK, ReligionPlus, Resource Recyclers, Resourceplus, Slow Tech, Tech Stopper _Renaissance _, Unciv Training the Leader, Uncivilized Expansion, Uniques From Chubz, Warfare Edited, Warfare Expanded Rework, capture GP, era event, philosophy mod, supply ship]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```
H4sIAAAAAAAAAO1dbW/bOBL+K4I+7QHxwpLltwL3IXGbNrtx40uyKO4WxYKWmZiILGr1kjRb5L/fkNSbHdmhHUlkgABFY1ESNXo4MxzOQ1I/zTkK4R9BfmR++Pl0ZLpL7N5Fycr8YH6cTn+bjK6P76+Pz0/+fvjbGf9neTf7cv/xf//9twlXknvikX9QTCi7+c+frGQCv+MwcdNCXiO5/4pWGCo8KZ51ZOIogGvQLZ4i9n8oLsY/Ao+GeHGJb+GsKLul3gL7x7c4rfA2xCieYRp4UOlPM6DEj6NTGn7FP+LP7Nxn7OMQeROa+DGv2OTFRlpufrC73SeoKKAecUlW7d8JjuI1YULsESbGemFC/GitJEbwui7yjs/SY+wuxa974sY0fCxd/XQEMCEAeTFFMfyJTokHMl7iKPFiJuk3xEW+QV6Ej8xjD6QFPOHnF8J+p+VXPn3ID05DHC2Nh7Ubz9Edzg+mFJHiVoJvi1PH4YrBnR9fLzGU+InrYRQaUxJFxCtdHdMVcY0TuprnZROKorj0KMAcET8v+LqlKn5h6cFT0KUYhY95gWiys1UQ0nu8wn7xjC/QLC4Nyq878+CZUSEnKU5NSPzYuYoBneL8b4l/W5IFdAeX3uEjjnBYHH4GhY2NjyDN0rikc1qcuU78RYjSQ67pMdcmbgrx46YtmPMEGvsE/lsQ/5ZdZ86Qh1xsfmc3U9/HLkByTScoACw8JnQCl5lMAcoWk5sKWFJuJTcAKKt3Qu7hluMQzQmCmwhAbN6Mhot5d9TvLLoLu+OgYa+DxgPcucF218a9YW8+H7Fro4sQFN4H0xESZLrnUZebOXuJH+aHTv/IhIay4am+sOwpdl32tIAGiZddWrKg1DBAAQQ8a5WIwwE/tLJDhx/2ssP++tn++lmnqir76fuR+UDDO4C04sHW03d2gWizCVM2po3W0YteLIdW0oOZoDJgN5fkdhlnAI65CJ0RA4UG5/gmP+OkwjXp95Yo+nSPw4sHHy+2tTgY9RXG/pr9/TR/AWy7/wIQTlG4Agh+AXltdvyFeo9GRGKcFvY2LrLYMeCU3CDuEnnxQBSv3zsQFeb3Djce2Bc3lc53eMF5sprj0FgxNymu6z2vvC8qZz7BcDFHifUDHnrE4RmzlJGNx+6ojzr9/mAEloLmnTlaoM68h4Y3N87Y7fUsM7vj+jFgCvElWSHfXOtOzGhJE29xEWB/xkofZ8S9Y03C0GVPDOkPsgIp2LVX7mO8BI36YH6lPpPzOFqCyyFFwdmtR6Gau9Il3i3BYVQUQBvTUhUnCRxHBjhCXLrodzRPvOywgS6P/42gMwOPz/o45uKOb0PiQueWhMLPvbpP3N1FVbn7ig6jqieT7arKvcv2zuFZh7ar43162e1kWqJh5LSmzal7bFfJpsSHro/ZBSvi7mUGXlf8OvbJCnnGlySaI+iwedG7UtailJmnelfKXUqprSqmI4u3oYnxIxd7Bt0eKJrHWxa694hFlWbpAsCFJqHL1PM3/IA9jvKLipz2p++K/K7IShT5NCTYX3gyuroW270r7LvCqlfY5653RuEvy8pIKLQYu7xr8rsmK9HkszDkKSvkSehqPhR/V9d3dVXveHcrq8j3vGtqk5rKcshJGGI/nvGkYDlDvCA3N/x+1m6/i+fdQtPwVCOa3zg2y8fbzgJ1nO5o3Bkj1O8MR5bdxWO73+v30+tnKIT/Y57w+2nOUYQvEw9eB3SL6b4hIP/Dh5Y3LjHLeW95eK4In3w09xgSwh5IdOF7xMdTuJwE6XuIUyu64FRFL1wYAIvhgF7/4RNoI2NCVwE0mR9z8KB1QfEna6wgM6slJtHKgGpYWjJnAI15EhsnmGHPyjEYe3YNL0zfaYqhxRB/Qlo+g6MlhsqNc5HVTcu/sUw/H8GlBVw9sosmVwUw8HvzBSJGaPKjBF7xjKkyqKAx5QJ9JKA4EU7F+/QjDpFRsDhZCVQZF0ffqL8Q0oj3YOlq/qZfaBjhiCN5FlI/rfTMv8cheBT2Fh4rmOIFwfegjZt4TsFiobbER8Yx1HEKFoyy4vPkRxISnF/2FYHiQh2FMBfewtjWUjP6AKjF1BDmbnz2f4fSy9TyZl4S8UMR4QGa7iM4x7BcGIhrrjz6YFwz0wPPDH+Mq5gGAdT91yX2EbhS5EMFf8FZobHXIeLGaEC7GucYLThQ/BwTEFD5lFNdrJw1XWSchnRlTJbJ/B8o/IbCGwRv/GlBmF8uFbA7F1BF3vouCpg5G59nzB6gqfC90OBgSTwa0WD5mDZKlAQBIw+WJDDBytPu5RtGoDNRbkCp9/Y5/XBxM8mcNhhNPyMKOPfE+7QljbC/QdHVQj9A7cwVRQFmQpmfAuKaub9iV3IjvuJNT274yQl3bDzq+Qh9ny94O6bv0C+s4MjlPm9JIlYHvFQYXychdBRdwQ8xjWdSW31B7U1RwNzTCgUH+Su47wpam90BLoOTZazmlGG8Jj5zyCFaEMaJWiDDA1nE4N7t3tO7l3r3Uu9eSngpYS6iIqjxms1sgKu4W7CG1mBodx2r3x0PwGiFA5kkYOArMyXozwmbCvGnMNtrHIZ8Nkc6zSP3BiK+IgU7fObPQgrRYgRm6CeeB5WBr4iu6RqD3GVOUKLigEakPOHAEny51eIzrWzGQTtPbOL1sgD/5JETsSlX8323FBYPt/M8zimJmIW0hroSCEi5Nv7KzNBPKOK+8pkyriM04WbYminYwhTsxprpc4iiyAN/ZPJJSTHxxZWbYOaZkF0KBRLb+WShtt1FXc+URaRgQ2WxsXJsSm15AqNLHzHNi4UIp5h1kSKCS6eufW/RLamC8QVH1aZG1dz/1IlEoe/NS7fTzJUrcRO+fuOtLmA4FfDwUV9Paz1ph/mWPqzNcK7TE8/stWzCsm3Xy2a06toTlNqtbQyLqW+SCma/BTAtNWBKQmjlELYWZ+iIRJsYFHFGIxEXz1Mgn2WA2NNS0mKa32+LxQJjlkwTZVO8omG2oqFafW1OgKRJB5HcgmfRdFI5m2Eerk0TpM9K4A1WNGevng5rslVKrb30cixtePDboTAk9NWvt+1J7SlZqfctucfrJIz5RDpVijeUbJosyik1zRWOQXatNW90+Ns1pHi2BoOGun1rE0OAjTBCZaZlY12HVEj5BoYDPTWj6/1C80Y99J4aWZkCvFqGUE1dY9PqFhUz9V5qT7GGrePo0p7r6E7AXy+w9xxXIXZdUr8GwJ5mAFYaRN1AyYw8HeW+OBuLSo1Am9WlbM2CXHawdW3ae9Ru5Zip6q8kANUfyZZNU+80RqflPEYxvFJHPqUTi+SSsOrS9pIjho3QSCz7ruyQNODPi8677WB258BgIwDi8z0iY0mTCFeEQZpasrJo6IVRl4yCOrXqRJOjXacyOVTv2KLmgH4X5BqN2pzKUVt9s0cOyblZjlxaKtuNRSrnVjIc+rxor6xbDRrQZteftXGzaS25MaTY5abT13QMKcTrVwf76YZMjQb71SgeZNL9VkxaaoAgC7+jJ/xbEiFtK7HkIL+Xg6h+kG9rjZStEVKW1khZtSIlHYNLZj50BE1TuIrUiN7posIkWsm8XbiYb5YmkUHRNaVk1xpX1p8GqWvMk+6DWXPaqV42rUb0nHqTSLXl7dZlX99DsTogVZp7ynYZ3P0a67s1bo4N2ghLpdtHTq3b7oJenZLqt6QqMoNUZcz/Xqm9nabXV+HWtsDZNvUgS7zvzjv320/X9DWbEy5vtypmKeyXG+nrwthLvUwl1OlG0p2BUqsWQjQig2yWuCc5ebGf4SWVJ862/aIbx3tliPdKhg7UBhYv50Ob17TabMNpyzbkMgJ7hJdODnXjupCNdqvTB0f7ZUF1gbpy1FmXcLsRk8yCqnSWfTlfaaeoySyfKBI69FnJXs5yW4vKTmIfHPxuX+kKLYhrbJ/LvtdLbnmgwi7S2mthiWwXWXgK+qxkr5bfZkBSrt7S2v9YSnpO2Yy54pDjoHT6Fpnbmv71mly7jgRFYUJbEltK5tVV59yb5yok+u+2CROZhOXOjHtdCQS5jPs+efa2UxuHQ+nUm7s6GEqzWzpzZH7le+Ctv0D5m0LVwyI+yYuiRd6P55/j0jstvyvl1D4zcljrbAliiny3Xg3zqpxp61GPDEW1LZmmMjy35cLz7CN0UsH5hn3R6uK9wvQaNUMHemegxnG8mhsb5E5cPXjKyJwapr0PVMyU2ILjmyJ5BnkcXJ5XiuKGdmjYG0xtVqbKg9ns5EO5RO5AzSBVTrihEG6oL0ciJBxqgd4efEPW7BojO8iRLfkbsQm0WZQdr9hXHkRQpVkD7Az6O82rzMvUno5qu5vaa1tiyVyaU6Wred+omNKTpPLqgjb97rn8QEiSye+lGEuNg7ShpyQXs1W8XLP0VC/XWG2YgFfxQXZTSlzXQpO2PVcd7JqOaFpVrhZACZofhRzGtrXc0a+37wwGBuxDUc/E2gDwBCRpfim1BFmmdl5bpy3iVoL2an5EJkF7bSwjvU7CO/zYsqFVkwTVrFddSYD6Wa+3QyDWvGC8SdZr52BhY5PEb0uIcEwNqJZXk17185GylMVec25tyflEWRvQzYK9AnUJDZpUaBD7NprhYv6hSPmoXpK6qQJix86p8kBse44G2l0bw1szUaOKfC9IL72a5pAmqSuUfU3vKtUBDKtd/9sCW8m6SSnUd6eWh4XhapNbqI/EHurAww6LQEAbiA8jaXeq0jCP4zTlKLKG0HDh/bClUYcMPC1LIQ+P1qyn4iXnL7Oegy18h3pE5YIEJRknKdFGQrSRUusVQqiVIWukke620DxMda8gVtuwg7eGWr8t1A5iRfoqbHUf4r4u0eqkkpxaQauFhNcRpp4SU62DDdYCTRlCLmd9Rhsh1ZK4d9hve5PjOrjjhrF/mUrcgPL4nrpoQRWSnIo73eeQnHrohw6cr9qpcJ1iRoGmEWaTOwi8biJB4Ws3xoIzctu209qHJtZ4aN2pdwffWtGr+SNadZLs9X4o66D1XJK7bOQbfEmxo6JdCk4wOw724UalGrfmjcdU8W3Flm3K+TYp2GteUqVgtkWxMu3tzLaozOGo55q3JsDULppsfewnB43ipGDNfO9Ig4bOEs9buNtzdNf6Xis14aqYsB2pWTi7z6d5R9qTrSNtydaRDmTrSIftcka7NhXSSYvUTq8etbffY3trSkfa72g6amkpzsGM77YlhLqJOxbijpUakRCiZRn2ac2x+tasNAAdIRvqoFHDluB5xUYNY536DEkGcZDDqku/sA/lX5c61MnJ9t8moo6+iDraesaevqD1tAXNbgW0w4n+jdDgcwKVIqMV2kyCDG0Vt0pSeAOfWbIK7kgLEyF2svcKg5PnkHzB4VyLJdsaz83sFFNBNJWw5n0rGuH2nw1Kg8c5CpsnciSIfMXbBRTfmSjjQ0NfR5LL0SHx1Sm+8lyC7JK4bS8c2IcT13HCQ/HNrTXTXGFPRyBr3vCyTiDb2hD0cFpa+dyArbS0WlatRFYq5xO2MKZTFEZLtRGG2oyaFilixRoy1kFPxxoYbIaEWinGLTl8GSQ0ptvHOnDaYw0WEO8kPcfa891jHcL+sQ58twxMageUYxX89BYk1Eox1nZB41iH5bMdq5sGFV2lcqRitC3FPg2lGKGxvgCNtABopC9AQy0AGuoL0EALgAb6AtSvGaAD+LS+vug46tFx9EWnpx6dXoFOmXmkgWKW2lYPjV0JzWRJPKIHha86MqzE54Ko3GZcNSwVgEyRf0t1YPEVp4mLWR/KuXjFIztbxci3ml1XnIgovlFSnglEYxSrtRhHh1RRGjxtzD04DgIPa7nzQl+HNGQaj2u5uUJrnzGUYMP1+FhBNRuumLgp9qRVnTJRTKN1dFhYqwW12tGBZVYc7isfbnQ1aIMiK68DFordQ4aFWjFSKRR3GhkWasVIpVAcYWRYqBUjlUJxOJphsTEdVoOFoqlkqj/H1tVhqJVKoXqbwq4Og/JUCqXE/O5dCDKcNF70kYqoOuXWfVXmj+0Pdo/DKK3RDQFkvPhG4iU79HkbsVe1LNYOP1jDOb9a9q92J0Cxu7RMuD+7ynl6+j8D6Shx9/cAAA==
```
</details>

### Operating System

Android

### Additional Information

(-)

**Comment by yairm210** [comment]
Solved in 4.12.2-patch1

**Comment by yairm210** [comment]
Actually no! Looking at the stack trace this is a mod specific error, interesting

**Comment by SchoeniosX** [comment]
Hallo Yair,

Das Problem ist bereits behoben worden. Der Mod Ersteller hat es aufgrund
eines Tippfehler verursacht. Jetzt erscheint keine Fehlermeldung oder
Abstürze mehr!

Grüße Laurin S.

Yair Morgenstern ***@***.***> schrieb am Di., 25. Juni 2024,
18:24:
