### ISSUE TITLE
Crash: Can't reach this tile

### ISSUE THREAD

**Issue by joba03** [yairm210/Unciv#11920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

**Version:** 4.12.6-patch1 (Build 1017)

### Describe the bug

Game crashes after next turn with "can't reach tile" error. 

### Steps to Reproduce

1. Go to 'press next turn'

**Platform:** Android
**Version:** 4.12.6-patch1 (Build 1017)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings, 5Hex Tileset]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: SM-G990B2
API Level: 34
System Memory: 7358 MB
    Available (used by Kernel): 2332 MB
    System Low Memory state: false
    Java heap limit: 512 MB
    Java heap free: 6 MB

--------------------------------

**Message:**
```
java.lang.Exception: Can't reach this tile!
	at com.unciv.logic.map.mapunit.movement.PathsToTilesWithinTurn.getPathToTile(UnitMovement.kt:849)
	at com.unciv.logic.map.mapunit.movement.UnitMovement.moveToTile(UnitMovement.kt:423)
	at com.unciv.logic.map.mapunit.movement.UnitMovement.moveToTile$default(UnitMovement.kt:389)
	at com.unciv.logic.map.mapunit.movement.UnitMovement.moveToTile(UnitMovement.kt:467)
	at com.unciv.logic.map.mapunit.movement.UnitMovement.moveToTile$default(UnitMovement.kt:389)
	at com.unciv.logic.map.mapunit.movement.UnitMovement.headTowards(UnitMovement.kt:244)
	at com.unciv.logic.map.mapunit.MapUnit.doAction(MapUnit.kt:739)
	at com.unciv.logic.civilization.managers.TurnManager.startTurn(TurnManager.kt:83)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:425)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:583)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:8)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:4)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:89)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at com.unciv.utils.Dispatchers$CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:190)
	at com.unciv.utils.Dispatchers$CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:190)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.Dispatchers$CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:190)
	at com.unciv.utils.Dispatchers$CrashHandlingDispatcher.$r8$lambda$1exBTjTJ644h9iUU94EW5nQQXpM(Unknown Source:0)
	at com.unciv.utils.Dispatchers$CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```
**Save Mods:**
```
[Civ V - Gods & Kings]
```
**Permanent audiovisual Mods**:
```
[5Hex Tileset]
```

### Link to save file

https://gist.github.com/joba03/081416224a75c1407421a29ced70f17e

### Operating System

Android

**Comment by tuvus** [comment]
Thanks for reporting this!

The idea I had in #11810 would have solved this, however I didn't account for `getMovementCostBetweenAdjacentTiles` returning early.

Writing a test for this on the other hand was unusually hard. I have to replicate the environment to get the test to fail without the fix, but for some reason it doesn't work. So I guess I won't have unit test coverage over this specific bug.

It should work once #11810 goes in.
