### ISSUE TITLE
Crash Editor

### ISSUE THREAD

**Issue by SchoeniosX** [yairm210/Unciv#11965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.10

### Describe the bug

Crash after clicking on  Mod

### Steps to Reproduce

1. Go to 'Editor'
2. Click on 'Mod'
3. See error

### Screenshots

Crash by clicking on Mod

### Link to save file

**Platform:** Android
**Version:** 4.12.10-patch1 (Build 1022)
**Rulesets:** [Uncivilized Awakening, Project Allciv, Medieval Civilizations, DeCiv Redux, 3rd and 4th Unique Component, Extra Buildings, Extra Units, Uniques From Chubz, Tech Stopper _Renaissance _, The Ultimate Modpack II, Warfare Expanded Lite, supply ship, Elysium for DeCiv Redux, CS Unique Components=, Inverted World, More Luxuries, Better ruins Lite, More Fauna And Flora, Resourceplus, Resource Recyclers, Endless Legend Civilizations, Slow Tech, Better Pantheons Lite, Extra Wonders, era event, Uncivilized Expansion, Warfare Edited, Unciv Training the Leader, Disease mod, Better Pantheons, Civ V - Gods & Kings, B2.2 Project, Better Workers, Outpost Mod, RSCekMOD, capture GP, Great Farmer, Classical Harbors, Extra Religions, Outlaws of the Wastes, Beach mod, Latin American_Civs, Old Ancient Civilizations, 4th Unique Component, Emperors and Deities, Power to People GnK, Taxation System, Test 1, ReligionPlus, Better Great Merchant, Ark s UNCIV Evolved, Civ V - Vanilla, other historical civs, Warfare Expanded Rework, Dimensiondogs expansion mod, philosophy mod, Brave New World Updated, Atheism mod, Barbarians but Better, Compound Interest Mod, CS Rework, Ancient Civilizations, Yet Another Resource Mod, =Geneciv Extension AkashicRecords, More Natural Wonders, The Great Unciv Rework, Leader Mission 2 Rising Power, Horses and Iron mod]
**Last Screen:** `com.unciv.ui.screens.mapeditorscreen.MapEditorScreen`

--------------------------------

Device Model: SM-A105FN
API Level: 30
System Memory: 1743 MB
    Available (used by Kernel): 256 MB
    System Low Memory state: false
    Java heap limit: 512 MB
    Java heap free: 5 MB

--------------------------------

**Message:**
```
java.lang.RuntimeException: Actor: TranslatedSelectBox
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:192)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
	at com.badlogic.gdx.scenes.scene2d.utils.Selection.fireChangeEvent(Selection.java:228)
	at com.badlogic.gdx.scenes.scene2d.ui.SelectBox$1.fireChangeEvent(SelectBox.java:71)
	at com.badlogic.gdx.scenes.scene2d.utils.Selection.choose(Selection.java:53)
	at com.badlogic.gdx.scenes.scene2d.utils.ArraySelection.choose(ArraySelection.java:24)
	at com.badlogic.gdx.scenes.scene2d.ui.SelectBox$SelectBoxScrollPane$1.clicked(SelectBox.java:448)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:354)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:87)
	at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:423)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:503)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1591)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property type has not been initialized
	at com.unciv.models.ruleset.tile.Terrain.getType(Terrain.kt:17)
	at com.unciv.models.ruleset.unique.UniqueParameterType$BaseTerrain.getKnownValuesForAutocomplete(UniqueParameterType.kt:368)
	at com.unciv.models.ruleset.unique.UniqueParameterType.isKnownValue(UniqueParameterType.kt:602)
	at com.unciv.models.ruleset.unique.UniqueParameterType.getErrorSeverityViaKnownValue(UniqueParameterType.kt:621)
	at com.unciv.models.ruleset.unique.UniqueParameterType.getErrorSeverityViaKnownValue$default(UniqueParameterType.kt:618)
	at com.unciv.models.ruleset.unique.UniqueParameterType.getErrorSeverity(UniqueParameterType.kt:594)
	at com.unciv.models.ruleset.validation.UniqueValidator.getParamTypeErrorSeverityCached(UniqueValidator.kt:251)
	at com.unciv.models.ruleset.validation.UniqueValidator.getComplianceErrors(UniqueValidator.kt:231)
	at com.unciv.models.ruleset.validation.UniqueValidator.checkUnique(UniqueValidator.kt:76)
	at com.unciv.models.ruleset.validation.UniqueValidator.checkUniques(UniqueValidator.kt:52)
	at com.unciv.models.ruleset.validation.RulesetValidator.addTerrainErrors(RulesetValidator.kt:439)
	at com.unciv.models.ruleset.validation.RulesetValidator.getBaseRulesetErrorList(RulesetValidator.kt:77)
	at com.unciv.models.ruleset.validation.RulesetValidator.getErrorList(RulesetValidator.kt:35)
	at com.unciv.models.ruleset.Ruleset.checkModLinks(Ruleset.kt:501)
	at com.unciv.models.ruleset.RulesetCache.checkCombinedModLinks(RulesetCache.kt:172)
	at com.unciv.models.ruleset.RulesetCache.checkCombinedModLinks$default(RulesetCache.kt:164)
	at com.unciv.ui.screens.newgamescreen.ModCheckboxTable.runComplexModCheck(ModCheckboxTable.kt:133)
	at com.unciv.ui.screens.newgamescreen.ModCheckboxTable.setBaseRuleset(ModCheckboxTable.kt:111)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorModsTab$2.invoke(MapEditorModsTab.kt:45)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorModsTab$2.invoke(MapEditorModsTab.kt:42)
	at com.unciv.ui.components.input.OnChangeListener.changed(ActivationExtensions.kt:131)
	at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
	... 18 more

```

### Operating System

Android

**Comment by SchoeniosX** [comment]
My fault (:

**Comment by yairm210** [comment]
There's no such thing, a crash is our fault :)
How did this happen?

**Comment by SchoeniosX** [comment]
From what i remember, it was my mistake because I entered the wrong parameter. However, from what you know, this must have been a mistake in the game.
