### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by HaveCake** [yairm210/Unciv#12147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.19

### Describe the bug

**Platform:** Android
**Version:** 4.12.19 (Build 1,037)
**Rulesets:** [Civ V - Gods & Kings, AbsoluteUnits, Community Maps, Civ V - Vanilla]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: ANY-AN00
API Level: 33
System Memory: 7482 MB
    Available (used by Kernel): 1742 MB
    System Low Memory state: false
    Java heap limit: 512 MB
    Java heap free: 0 MB

--------------------------------

**Message:**
```
java.lang.Exception: Can't reach this tile!
	at com.unciv.logic.map.mapunit.movement.PathsToTilesWithinTurn.getPathToTile(UnitMovement.kt:846)
	at com.unciv.logic.map.mapunit.movement.UnitMovement.moveToTile(UnitMovement.kt:427)
	at com.unciv.logic.map.mapunit.movement.UnitMovement.moveToTile$default(UnitMovement.kt:393)
	at com.unciv.logic.map.mapunit.movement.UnitMovement.moveToTile(UnitMovement.kt:471)
	at com.unciv.logic.map.mapunit.movement.UnitMovement.moveToTile$default(UnitMovement.kt:393)
	at com.unciv.logic.automation.unit.HeadTowardsEnemyCityAutomation.headTowardsEnemyCity(HeadTowardsEnemyCityAutomation.kt:77)
	at com.unciv.logic.automation.unit.HeadTowardsEnemyCityAutomation.tryHeadTowardsEnemyCity(HeadTowardsEnemyCityAutomation.kt:23)
	at com.unciv.logic.automation.unit.UnitAutomation.automateUnitMoves(UnitAutomation.kt:239)
	at com.unciv.logic.map.mapunit.MapUnit.doAction(MapUnit.kt:764)
	at com.unciv.logic.civilization.managers.TurnManager.startTurn(TurnManager.kt:83)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:427)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:585)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:8)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:4)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:89)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at com.unciv.utils.Dispatchers$CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:190)
	at com.unciv.utils.Dispatchers$CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:190)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.Dispatchers$CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:190)
	at com.unciv.utils.Dispatchers$CrashHandlingDispatcher.$r8$lambda$1exBTjTJ644h9iUU94EW5nQQXpM(Unknown Source:0)
	at com.unciv.utils.Dispatchers$CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1033)

```
**Save Mods:**
```
[Civ V - Gods & Kings, AbsoluteUnits]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```
H4sIAAAAAAAAAOy925YbN5Oo+Srcupl/rym6E+eE72T52G1ZakndXj1evsgis6rYZpH18yBbv5eu53rmTeax9lsMDgEkgASSYB1ku3ev5UORzPwSCCACgUAA+fuzy26n/ll1m/2zz3//ePFssXq/Wq/+0R1WW/3VT7/rb16ovw+74wK+hOt+6G77Z58/+2IgXDzr93fqmu66f9np/+7sxf1vd+vtrl++6a/Vr/a76+162W+eX/ca+GxzvL3sd6+uvgm+pRfP9gd927fd3d1q0+/VdwgzrG/e9d3hdb+9W/f67rvtanPYf73d/dD/dvhG//ZNv+l33frF9rg5mFI8M1/P4Ptnn+Om+ahAd9v1arHqoVJ/P/b7Q1TyXb9e6TLHXx5Xm330zaFTsll06+ffwed+caMfqv+/f9Pv+263uOmXSp7Pnuu/dh+UrF5vDwf71/PN6rZbz7497i+7zdJ+db1bLY7rw3HXP/tZEd+vFkoWH4KnfrzQbXMwhTfNdPiQttOzy+NqffhC/We52lzr65693CpR95uDfsTt3c3qcKPEooDqo5LFejt7vdte77pb9cX3q+ubw832uO/Vh3c3/cyKMPr6xXa93e/7o77+m50q/Oxdf6tb5eLZ2w/LTf9h9upOCXz2LVz/pl98WKxVYWYv+g08V0l9qcqs/vxxtVnertZr9ee3W9WTDp3+86XqkIdu92H2RWcY+jmdEdIXu223XHT7w+zd9lcDe92tu4Up2Gq3OO5nL7vfVrdH3TO/Wl1d9Wt/oYc+X3TL/lbTXna7X3pdDNWjd93iF31XXPq3NzvVD9Uf/7ZZve93eyVy/ajdSvXT2Zte9VzVRlZY3WFn62vbfvZ9d6kfcQRZve27u+3uYKR8ubO1+bFbr/Uz3x665cpc9UW3+UXLQmmY4X7dmU6gQf1S9zfAvj5eqm48e7u42W61xJ7v9v3GyO61KlJ3rXROVeW3q+1uOYuK/uN298v+Znuny9z9p5LWTWfvv7WPeXvYLn6ZffXb4qbbXBvZdztVS/XHD8ZCqBJ8dbda6DJ+WO5U51l3pmupKlyaTuAvUx1l3RvEF7qb9JvL4+569o3qe6bmqivMXtqW9x3ohWpY9cfPytgE/fpfj/2x1z35S6Wru+0H1Zrqiqtd3/t+rrrw+9WyX369296+u1ntX+jKKm3AuOsvr1A7v2J9M6eYd3MpEJqjpkMLzpZXmHZWl9adNjbP/rN7332mqnT92duDavlrVaj33Vo/PlSOj1o/VxujOMpIjZRwKOjnmBmro+qz6ReHfvlu+6Iz3VwJ7HDUj1R36rqrLqmlpCzmfnvcLfQTVfe0MvU21htXZXutXX0GJuOtsZvKXDIp1SVXygxqybxYvVegrzbXqk5LRVLddH1Qhopgpmqgrq8Tkbp2/2qn7KJqWCj/s891wS+erbcL0+K6LL+p+l48U5KfC1UGVZ+jquddv1h1a6Uwe3fLxg4j3283S9NP77Z3x7WHXG23S1cbgXn8M0VqiPDE52v3dCP2t8qubw7qe1W/C11ppbq6DejHwK6b0UO3mhKauUvbOffjbHs1U5+/V/12s8RCVYc0jdKB7VL/8mOnGxTrb/75uOxW+1slb8pEe/Hsu/1aWVA1xnDKtGZt7Y+cq0FneLbumt/t1QO+3a4/6D766krJAa4eLts/P7zd3vav9Rj3fLm9O9hxxF8XFEd3xMNqDSOCkj+38m/1WKH/QFj/9ZuRiP5M448tfIRm4/FHf/McJV+g+Pro5/AH5ruD+Ujj26AQMv5VOIiIL2Nx4ZJfUROXRcQlcBUV2RIgFF/tSsSDq0MKiSk0li3Ofmzj8iUFSiTUxuVh8b3SlUfGj0gEmXz0EsL5zyyunG+GVLJJYfzPLBYKz1aMeSpKMCgpHfqorPyvarhSRjPs4UnPzTdFG38sNBSZbKi8TtB8y7BEaKMuk9eYNtOw4/YkhWZPFcY3xTxRgnzLiUJD0nJ/KGpj8tGyMnrI9dj5CL7r93230U6l8e60NXy92utx6rvddqM7jXWrtpt+9iN8Ch3XaafUDM29hipXrd8drKu4uekOh26j3eX/7Cec19dbNXqvu9Vm7HmO3Nnnm+tftjtlyQ9Z31bNby5XS+U6zbyX+3JlpPGIzuzgun7b77bKqQT/ruTI1riv/e5WFc84f4MHG04oHOLbTo/S2i3UXuYernr9Qc1HVsv9GW5v4Nee48u+U+VRnoCZWqyuZ1+YX70vW+uYvuwWN0qys2+Om2rXlC6JuMKinTe9QHMql2Le4iWeN1eXSF5eiSXrZa1rCvUyilXjyFrpGy/2brdd2tq8Ul3iar39VdmD5pN6rI0k/CyXtUp0Jc8UVXim/6E606RfygmLfybyPn6p7t473TvVL+j+Tmo78lFR7KOShgc+qio8HXxUSduPJ11Pe+uAnPBBtYyJG4aSIdR9791E7wPEIw+JP+L4I4oHIhJ/TPzdxKvA8UfiChLfFRcHwUXu/94FoMn4GQ++iX+TeM4kGS/jXxMnI/ZOUSJdph0lpVGb54u/H1emfxKUdZ18Dci4gqPKz5Nq0bARw0LO8zWcrj/NiMPfFbXUJ+0LIyH7Frin2zKMjYkDA0OljVrpn9c33a0yzHrM2+7/fhyPna/UqG7jbN4/+b/643mujR1/7QM04Mv/7DfGJageZwefJxhyJ2J3dgzVz3q+O/S3q33sABXH6hdqTIlikd9vj+93fdZPAqfIj9sZ7+jb1W3/n6sZDORneUtWZtrZGblOzj8ohv+G55Xcp8f0KbgaC68ob+dYkss5xUQNjAuJ5guCKG84WaBFW+tTQCes9CmgnpVX25qfiqKFEvgcSfpJ42gtavDIKdHd8Ide6fBO+yb7rHNS1Qb18bT5YNlOui3Pb/dK4ZdmpC77LlSQxHdB9/Y8WORnYCrZ4GegBmF5Mvg1eBQnXJAvlWLtDrOvt+tf9MpS4IyMYmDzZF4/Twz+PAkDzJMowTyZ2895cj1Prh9GZPeH94CS8MQ8GbfmicczT4a5eTI4zXG+aumgnY7NJPk8Cuypz0mRUfIZJ59JIq30M02uZ0kVWXI9H7sxWMqsHzNqsFRKhSKnReKlKgdSvq+gC32u2AfTPlbogzV9Lu1TSYhm1CC8toEKDew7wD19pGioT9wk7x/5JbF0sM+sTh6noz/BkB9GffLRETfEpy5RMtAHw/rgFg1+jguVgL9THPS3l6qfz94+f6kvmRobhws/Rxh/0qGRsDMGRswaGBjbyyW/6unlnHVX3ZxSupi3lxLPcXfVMNRfNbSn41n7XNSPf2/M8vqp8Q/LNv4Z0/svD8XzbIT1zBrGP0JJc3pmfc6wxhO9bvMmBCe/++tFXu9Rcn16/zBW+RvdHzIhiqREIiGkliaZ37rPOP6MElxaIZx85kkF/ONQkw5V/s70EppUkSSf099xZhLe0PzolbZL2q4jH6HUwGkDusKzUUOlXeVUUxckm/6eDgm41LCuZPwMyaetV98S9xuG8hP0TCpGNOK8ulQK/L6Dn8JhJhhbzp1PZybI0SDpA9lTU97TU9wf+uN+cfOrsvSHfrUJx8AoP+O+c95yykvlpLd6cojEp02yyASsv+3X+9Xml1U4KWzc2NdjxuSib+e0W8o5bVsxl1ccz1uOKUbykl+KxTmTQmch9BQVBr/g+eWxD5EmGfuaurj1A6LTqIkHScZQG4SfjShPDJLlITEQROzJjyxRakRROsVCqWuO0hkNSscxlE44UDo0odFQx9LHjp

### Steps to Reproduce

1. Play Unciv
2. Reaching a certain number of turns
3. See error


### Screenshots

![Screenshot_20240823_162550](https://github.com/user-attachments/assets/3e9f907e-5fa6-4b2e-9562-7ef083792a65)


### Link to save file

_No response_

### Operating System

Android

### Additional Information

_No response_

**Comment by yairm210** [comment]
Can't load the game you uploaded, the game save in incomplete

**Comment by yairm210** [comment]
:(
Please do!
