### ISSUE TITLE
Polish translations cause crash in 4.13.7 - FIXED in 4.13.7-patch1

### ISSUE THREAD

**Issue by Janczesco** [yairm210/Unciv#12207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.13.7

### Describe the bug

**Platform:** Android
**Version:** 4.13.7 (Build 1 046)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.screens.mainmenuscreen.MainMenuScreen`

--------------------------------

Device Model: moto g(7) power
API Level: 29
System Memory: 3574 MB
    Available (used by Kernel): 778 MB
    System Low Memory state: false
    Java heap limit: 256 MB
    Java heap free: 5 MB

--------------------------------

**Message:**
```
java.lang.IllegalArgumentException: Invalid diacritic definition: "wyświetlanie" is not a single character or unicode codepoint notation
	at com.unciv.ui.components.fonts.DiacriticSupport$Companion.invoke$parseDiacriticEntry(DiacriticSupport.kt:116)
	at com.unciv.ui.components.fonts.DiacriticSupport$Companion.invoke(DiacriticSupport.kt:122)
	at com.unciv.models.translations.Translations.createTranslations(Translations.kt:127)
	at com.unciv.models.translations.Translations.tryReadTranslationForLanguage(Translations.kt:119)
	at com.unciv.models.translations.Translations.tryReadTranslationForLanguage$default(Translations.kt:87)
	at com.unciv.models.translations.Translations.tryReadTranslationForCurrentLanguage(Translations.kt:144)
	at com.unciv.ui.popups.options.LanguageTab.selectLanguage(LanguageTab.kt:22)
	at com.unciv.ui.popups.options.LanguageTab.updateSelection(LanguageTab.kt:29)
	at com.unciv.ui.popups.options.LanguageTab.access$updateSelection(LanguageTab.kt:11)
	at com.unciv.ui.popups.options.LanguageTab$1.invoke(LanguageTab.kt:36)
	at com.unciv.ui.popups.options.LanguageTab$1.invoke(LanguageTab.kt:34)
	at com.unciv.ui.components.input.ActivationActionMap.activate(ActivationActionMap.kt:56)
	at com.unciv.ui.components.input.ActorAttachments.activate(ActorAttachments.kt:42)
	at com.unciv.ui.components.input.ActivationExtensionsKt.activate(ActivationExtensions.kt:17)
	at com.unciv.ui.components.input.ActivationListener.tap(ActivationListener.kt:15)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener$1.tap(ActorGestureListener.java:52)
	at com.badlogic.gdx.input.GestureDetector.touchUp(GestureDetector.java:206)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener.handle(ActorGestureListener.java:125)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:354)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:87)
	at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:423)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:503)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1573)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)

```

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Operating System

Android

**Comment by nintyfan** [comment]
Same on Linux/Flatpak (under Steam Deck and OpenSUSE Tumbleweed).
