### ISSUE TITLE
'Illegal' bug

### ISSUE THREAD

**Issue by Janusz-max** [yairm210/Unciv#12210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.1.3.7

### Describe the bug

I can't open 'Unciv' because it founded a:'illegalDocumentexception'

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Screenshots

![Screenshot_20240915_081228_Unciv](https://github.com/user-attachments/assets/68d37185-f3e2-4203-9317-dd0b495008e8)

### Link to save file

![Screenshot_20240915_081228_Unciv](https://github.com/user-attachments/assets/45eae78a-5235-44d9-8dd0-252be0c701ba)

### Operating System

Android

### Additional Information

"**Platform:** Android
**Version:** 4.13.7 (Build 1 046)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.GameStartScreen`

--------------------------------

Device Model: SM-A137F
API Level: 34
System Memory: 3691 MB
    Available (used by Kernel): 1133 MB
    System Low Memory state: false
    Java heap limit: 256 MB
    Java heap free: 230 MB

--------------------------------

**Message:**
```
java.lang.IllegalArgumentException: Invalid diacritic definition: "wyświetlanie" is not a single character or unicode codepoint notation
	at com.unciv.ui.components.fonts.DiacriticSupport$Companion.invoke$parseDiacriticEntry(DiacriticSupport.kt:116)
	at com.unciv.ui.components.fonts.DiacriticSupport$Companion.invoke(DiacriticSupport.kt:122)
	at com.unciv.models.translations.Translations.createTranslations(Translations.kt:127)
	at com.unciv.models.translations.Translations.tryReadTranslationForLanguage(Translations.kt:119)
	at com.unciv.models.translations.Translations.tryReadTranslationForLanguage$default(Translations.kt:87)
	at com.unciv.models.translations.Translations.tryReadTranslationForCurrentLanguage(Translations.kt:144)
	at com.unciv.UncivGame$create$3.invokeSuspend(UncivGame.kt:146)
	at com.unciv.UncivGame$create$3.invoke(Unknown Source:8)
	at com.unciv.UncivGame$create$3.invoke(Unknown Source:4)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:89)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at com.unciv.utils.Dispatchers$CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:190)
	at com.unciv.utils.Dispatchers$CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:190)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.Dispatchers$CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:190)
	at com.unciv.utils.Dispatchers$CrashHandlingDispatcher.$r8$lambda$1exBTjTJ644h9iUU94EW5nQQXpM(Unknown Source:0)
	at com.unciv.utils.Dispatchers$CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by yairm210** [comment]
Copy of #12207, fixed in 4.13.7-patch1
