### ISSUE TITLE
Out of Memory (Only 512MB allowed??) 

### ISSUE THREAD

**Issue by xotikorukx** [yairm210/Unciv#12411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.14.2-patch1

### Describe the bug

According to the stack heap, only 512MB of memory is allowed for use?

Is this a design choice, or just a compatibility choice?

I'm not familiar with Java, but C# I am very familiar with, so if this is something I need to eventually look into, I will. It just seems ridiculous that 512MB is a cap with no option (or memory size auto adaption) to increase max allowed (my phone has 12GB!).

For context, I am playing an 80 size map with max Ai (and that's even too small for me!) because I really enjoy putting "grand" in "grand strategy"; and totally nothing like the masochism of playing a few minutes at a time on my phone during breaks waging full scale 3 pushing 4 digit unit wars.

Way off in a foxhole, I know unciv servers are (for the most part) glorified file hosts. If I ever get time to sit down at a computer again, I've thought once or twice about looking into fragmented saves for multi-player games. 

### Steps to Reproduce

Play 100 turns into an 80 size map wtih max AI on marathon with standard settings. 

### Operating System

Android

### Additional Information

**Platform:** Android
**Version:** 4.14.2-patch1 (Build 1,065)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: SM-S908U1
API Level: 34
System Memory: 11213 MB
    Available (used by Kernel): 3270 MB
    System Low Memory state: false
    Java heap limit: 512 MB
    Java heap free: 0 MB

--------------------------------

**Message:**
```
java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 1779952 free bytes and 1738KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at com.badlogic.gdx.scenes.scene2d.Group.<init>(Group.java:41)
	at com.unciv.ui.images.IconCircleGroup.<init>(IconCircleGroup.kt:16)
	at com.unciv.ui.components.extensions.Scene2dExtensionsKt.surroundWithCircle(Scene2dExtensions.kt:117)
	at com.unciv.ui.components.extensions.Scene2dExtensionsKt.surroundWithCircle$default(Scene2dExtensions.kt:111)
	at com.unciv.ui.components.tilegroups.YieldGroup.getIcon(YieldGroup.kt:34)
	at com.unciv.ui.components.tilegroups.YieldGroup.getStatIconsTable(YieldGroup.kt:46)
	at com.unciv.ui.components.tilegroups.YieldGroup.setStats(YieldGroup.kt:28)
	at com.unciv.ui.components.tilegroups.layers.TileLayerMisc.updateYieldIcon(TileLayerMisc.kt:302)
	at com.unciv.ui.components.tilegroups.layers.TileLayerMisc.doUpdate(TileLayerMisc.kt:386)
	at com.unciv.ui.components.tilegroups.layers.TileLayer.update(TileLayer.kt:39)
	at com.unciv.ui.components.tilegroups.TileGroup.update(TileGroup.kt:129)
	at com.unciv.ui.components.tilegroups.WorldTileGroup.update(WorldTileGroup.kt:22)
	at com.unciv.ui.screens.worldscreen.worldmap.WorldMapTileUpdater.updateTiles(WorldMapTileUpdater.kt:32)
	at com.unciv.ui.screens.worldscreen.WorldScreen.update(WorldScreen.kt:404)
	at com.unciv.ui.screens.worldscreen.WorldScreen.render(WorldScreen.kt:729)
	at com.badlogic.gdx.Game.render(Game.java:48)
	at com.unciv.UncivGame.access$render$s2211858(UncivGame.kt:60)
	at com.unciv.UncivGame$wrappedCrashHandlingRender$1.invoke(UncivGame.kt:83)
	at com.unciv.UncivGame$wrappedCrashHandlingRender$1.invoke(UncivGame.kt:83)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.UncivGame.render(UncivGame.kt:411)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:505)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1584)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1283)

```
**Save Mods:**
```
[Civ V - Vanilla]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```
No save data: java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 1071184 free bytes and 1046KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
```
</details>

**Comment by yairm210** [comment]
We explicitly set largeHeap to true, which seems to be the maximum we can do - the actual memory allocated is an Android internal setting
I'm not an Android dev myself, and I can't find how to override this seeing, if at all possible 🤔

**Comment by xotikorukx** [comment]
Clearly I'm not either or I would've known this.

It looks like the only "great" way to tackle this is multiprocessing, which for a project like this.... Sounds like an astonishingly bad idea.

Second initial thought far from a computer... Chunking? Possibly iterate chunks and render each Chunk before moving onto the next, loading and parsing a small portion of the save file at a time. If I poke around with a c# server at some point it might be manageable to test question mark? I tried decoding a save file to see if the theory holds water, butI'm assuming its a collection of bespoke structs/objects just base64 encoded?

Sorry, I guess I'm just barfing thoughts out loud that I can't test until I'm back at a desktop pc lmao

**Comment by SeventhM** [comment]
https://stackoverflow.com/questions/73262584/how-do-you-go-over-512mb-of-memory-in-an-android-app

As far as I can see:
1. > my phone has 12GB
   
   This is not really a great argument for most apps. I've seen devices with low amounts of memory and hitting the memory limit on Android is pretty bad (I've seen a device be unable to even open the keyboard). Maybe we can argue we shouldn't set an arbitrary limit, but your device manufacturer absolutely should to make sure your device functions
2. We can't really control what the limit is to make use of all of your memory, we can only really set ``largeHeap`` to true. This limit is in place by your device's manufacturer. And I don't see a good reason for looking for ways to bypass it
3. For better compatibility across devices, imo better memory efficiency would probably be a better solution regardless, not just constantly increasing the limit, since we aren't doing that much intensive stuff anyways
4. Pretty sure issues with the memory limit almost exclusively matters on extremely large games, which I'm pretty sure barely functions on desktop anyways. Kinda a low priority thing imo besides general memory optimizations

**Comment by metablaster** [comment]
I'm having similar problem on Desktop PC:

```java
**Platform:** Desktop
**Version:** 4.14.11 (Build 1.076)
**Rulesets:** [Higher quality builtin sounds, Victoria II Music, Unciv Vanilla Music Pack, Civ V - Vanilla, Community Maps, Civ V Leader portraits, unciv realistic earth maps, Civ6 Tileset, Civ IV Music, Higher Quality City Ambience Sounds, Civ 3 Audio, Civ V - Gods & Kings, Civilization II Music, 5Hex Tileset]
**Last Screen:** `com.unciv.ui.screens.LoadingScreen`

--------------------------------

OS: Linux (amd64, 6.11.5+bpo-amd64)
	Debian GNU/Linux 12 (bookworm)
Java: Eclipse Adoptium Temurin-21.0.5+11
	Max Memory: 1024 MB
System default encoding: UTF-8


--------------------------------
```

**Message:**

```java
java.lang.OutOfMemoryError: Java heap space
	at com.badlogic.gdx.scenes.scene2d.Actor.<init>(Actor.java:60)
	at com.badlogic.gdx.scenes.scene2d.Group.<init>(Group.java:36)
	at com.unciv.ui.components.tilegroups.layers.TileLayer.<init>(TileLayer.kt:13)
	at com.unciv.ui.components.tilegroups.layers.TileLayerCityButton.<init>(TileLayerCityButton.kt:14)
	at com.unciv.ui.components.tilegroups.TileGroup.<init>(TileGroup.kt:55)
	at com.unciv.ui.components.tilegroups.TileGroup.<init>(TileGroup.kt:21)
	at com.unciv.ui.components.tilegroups.WorldTileGroup.<init>(WorldTileGroup.kt:15)
	at com.unciv.ui.screens.worldscreen.worldmap.WorldMapHolder.addTiles$core(WorldMapHolder.kt:106)
	at com.unciv.ui.screens.worldscreen.WorldScreen.<init>(WorldScreen.kt:145)
	at com.unciv.UncivGame$loadGame$2$3.invokeSuspend(UncivGame.kt:222)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at com.unciv.utils.Dispatchers$CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:190)
	at com.unciv.utils.Dispatchers$CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:190)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.Dispatchers$CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:190)
	at com.unciv.utils.Dispatchers$CrashHandlingDispatcher$$Lambda/0x00007efc38118c30.run(Unknown Source)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:209)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:167)
	at com.unciv.app.desktop.HardenGdxAudio.<init>(HardenGdxAudio.kt:54)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:104)

```

**Save Mods:**

```java
[Civ V - Gods & Kings]
```

**Permanent audiovisual Mods**:

```java
[Victoria II Music, Civ IV Music, Higher Quality City Ambience Sounds, Unciv Vanilla Music Pack, Additional Music Ambient, Civ 3 Audio, Civilization II Music, Civ V Leader portraits, Additional Music Various]
```

**Save Data:**

[Autosave-Rome-667.zip](https://github.com/user-attachments/files/17966166/Autosave-Rome-667.zip)

** Possible steps to reproduce:**

I was switching display language on this save file when the crash occurred.
None of the mods listed are enabled per game, only enabled as permanent audio visual mods.

Is there anything I can to to increase memory and what is the default memory size for Desktops?

**Comment by yairm210** [comment]
Okay, that desktop issue is different and should not be happening

If it happened while switching languages that means you were probably temporarily with 2 screens - one active and one being built - thus double the memory for screen components.
We have a trick for dealing with this when passing turns, it's entirely possible we don't do this while changing other screen attributes and that should be rectified

In any case "max memory 1024 mb" is definitely changable in JVM with jvm args that tell it to consume more memory, but I'm hoping we don't need to get to that if we solve the screen issue correctly

This does mean that a map with twice the tiles will probably not work though, I currently don't have a good plan for limiting those memory assignments - very non-trivial

**Comment by metablaster** [comment]
> If it happened while switching languages that means you were probably temporarily with 2 screens - one active and one being built - thus double the memory for screen components.

I'm not 100% sure it's because of changing the language but you're on the right track...
I managed to reproduce the problem again with the following steps:

1. Switch from windowed to full screen display
2. Switch language
3. Repeat steps 1 & 2 until crash.

Map size is that which is in save file.

I'll go figure out how to adjust JVM heap setting on Linux, not sure how because I'm running the game from Lutris.

**Comment by metablaster** [comment]
I managed to fix the problem, just in case anyone is having this issue on Desktop PC simply open `Unciv.json` in game installation directory and modify line which says:

```json
  "vmArgs": [
    "-Xmx1G",
    "-"
  ]
```

This sets available heap memory to 1GB, but I changed it to 4GB like this:

```json
  "vmArgs": [
    "-Xmx4G",
    "-"
  ]
```

Applicable to Desktop PC's and laptop only, it fixed the problem in my case, currently after this fix the game is utilizing 2.4GB of memory:

![util](https://github.com/user-attachments/assets/af7da3d5-12cc-4241-a508-721b4b4453ed)



So far so good, in any case it's a proof that 1GB is not enough.



There is a chevat though, you need to modify this every time you update game because it will reset to 1GB
