### ISSUE TITLE
Feature request: Wayland support

### ISSUE THREAD

**Issue by mvforell** [yairm210/Unciv#12632]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

I have a HiDPI setup on Wayland, and apps with no Wayland support are blurry. This currently includes Unciv. Natively supporting Wayland would fix the blurriness, which I confirmed by running Unciv 4.14.1, which had Wayland support (before it got reverted) and looks great.

### Related Issue Links

https://github.com/yairm210/Unciv/issues/12379 was about problems with Wayland under Flatpak, which caused the commit that updated libgdx to a version that supports Wayland to be reverted.

### Desired Solution

Update back to libgdx >= 1.13.0 and disable Wayland for flatpak. I know that GLFW allows you to select the platform, I'm not sure if libgdx currently exposes it. If not, we should push for libgdx change that allows that. This of course depends on being able to detect whether we're running under flatpak, which I don't know how to do but I assume it should be possible.

### Alternative Approaches

Maybe it's also a general problem with running something libgdx-based under flatpak with Wayland, and this should be fixed in libgdx and no change is required in Unciv? I suppose this depends on what exactly is going wrong with Flatpak under Wayland.

### Additional Context

I'd be happy to help with investigating what exactly is causing the problems with Wayland under Flatpak. I  don't have much experience with Flatpak, but I have a lot of experience with Wayland development in general.

**Comment by yairm210** [comment]
There are several problems with  1.13.0 - some Wayland, and some AWT, and from what I see the the LibGDX discord also others which I have not personally encountered.
We're waiting on 1.13.1 which hopefully should fix most of the problems.

**Comment by yairm210** [comment]
@mvforell 
The day has come!!!
LibGDX 1.13.1 is out, [please test the new build](https://github.com/yairm210/Unciv/releases/tag/4.15.1-libgdx-1.13.1) :)

**Comment by mvforell** [comment]
Sorry for the delay - just tried it out, and it seems that build is still picking X11. It's blurry on my HiDPI monitor, and if I run `WAYLAND_DEBUG=1 ./Unciv` I see no output. For comparison, Unciv 4.14.1 isn't blurry, and running that with `WAYLAND_DEBUG=1` produces lots of output.

I also tried launching the build with `DISPLAY=` (i.e. unset), but then it crashes with this stack trace:
```
Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set,
or no headful library support was found,
but this program performed an operation which requires it,

	at java.desktop/sun.java2d.HeadlessGraphicsEnvironment.getDefaultScreenDevice(Unknown Source)
	at com.unciv.app.desktop.LinuxX11SaverLoader$Companion.isRequired(LinuxX11SaverLoader.kt:68)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:65)
```
fwiw, 4.14.1 crashes with `DISPLAY=` as well, but with a slightly different stack trace:
```
Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set,
but this program performed an operation which requires it.
	at java.desktop/sun.java2d.HeadlessGraphicsEnvironment.getScreenDevices(Unknown Source)
	at com.unciv.app.desktop.DesktopScreenMode$Companion.getMaximumWindowBounds$desktop(DesktopDisplay.kt:89)
	at com.unciv.app.desktop.DesktopScreenMode$Companion.getMaximumWindowBounds$desktop$default(DesktopDisplay.kt:84)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:82)
```

**Comment by yairm210** [comment]
Hmm
I think this is due to changes in how lwjgl [handles Wayland](https://github.com/LWJGL/lwjgl3/releases/tag/3.3.5), using EGL API, in the 3.3.5 version, which LibGDX 1.13.0 used

The reason that LibGDX downgraded from that is because is caused [audio problems and antivirus flagging](https://github.com/libgdx/libgdx/blob/f6fa6fe93908e17ca5edd05e22d207cd2a46abd9/CHANGES#L21)
So... This is a classic dep-of-deps issue... a solution for you would probably be to build Unciv with a hardcoded lwjgl3 3.3.5 dependency, perhaps?

I'm not going to be building Unciv with a different version than the 'official' LibGDX supported version because I do need to ensure all the different platforms continue to work, sorry :(

I also don't have any alternative ideas

**Comment by yairm210** [comment]
Closing this as "no viable solution", unfortunately :(
Hope that in time, with libgdx updates and with expanding Wayland support, it will be fixed

**Comment by calhix** [comment]
Hello, is it possible to revisit this with the latest version of LibGDX?
