### ISSUE TITLE
Just crashes when it's time to reveal the whole map.

### ISSUE THREAD

**Issue by ermnsg** [yairm210/Unciv#12729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.14.11

### Describe the bug

It just crashes.
I am playing on a 300x150 map, and as soon as I clicked on Next Turn, and the Satelites would finish the next turn, the whole map would be revealed.

The truth is that it was working for a long time, and the fan on my computer went full speed... and then it crashed.

I'm guessing the map is too large, and the game goes out of memory.  So not much you can do.. but I thought I'd report it anyway.

**Platform:** Desktop
**Version:** 4.14.11 (Build 1,076)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

OS: Windows 10
	Windows 10 Pro Version 22H2 (Build 19045)
Java: Eclipse Adoptium Temurin-21.0.5+11
	Max Memory: 1024 MB
System default encoding: UTF-8

--------------------------------

**Message:**
```
java.lang.OutOfMemoryError: Java heap space
	at com.unciv.ui.images.ImageGetter.getImage(ImageGetter.kt:219)
	at com.unciv.ui.images.ImageGetter.getImage$default(ImageGetter.kt:218)
	at com.unciv.ui.images.ImageGetter.getStatIcon(ImageGetter.kt:245)
	at com.unciv.ui.components.tilegroups.YieldGroup.getIcon(YieldGroup.kt:34)
	at com.unciv.ui.components.tilegroups.YieldGroup.getStatIconsTable(YieldGroup.kt:40)
	at com.unciv.ui.components.tilegroups.YieldGroup.setStats(YieldGroup.kt:28)
	at com.unciv.ui.components.tilegroups.layers.TileLayerMisc.updateYieldIcon(TileLayerMisc.kt:305)
	at com.unciv.ui.components.tilegroups.layers.TileLayerMisc.doUpdate(TileLayerMisc.kt:389)
	at com.unciv.ui.components.tilegroups.layers.TileLayer.update(TileLayer.kt:39)
	at com.unciv.ui.components.tilegroups.TileGroup.update(TileGroup.kt:129)
	at com.unciv.ui.components.tilegroups.WorldTileGroup.update(WorldTileGroup.kt:22)
	at com.unciv.ui.screens.worldscreen.worldmap.WorldMapTileUpdater.updateTiles(WorldMapTileUpdater.kt:32)
	at com.unciv.ui.screens.worldscreen.WorldScreen.update(WorldScreen.kt:403)
	at com.unciv.ui.screens.worldscreen.WorldScreen.render(WorldScreen.kt:728)
	at com.badlogic.gdx.Game.render(Game.java:48)
	at com.unciv.UncivGame.access$render$s2211858(UncivGame.kt:60)
	at com.unciv.UncivGame$wrappedCrashHandlingRender$1.invoke(UncivGame.kt:83)
	at com.unciv.UncivGame$wrappedCrashHandlingRender$1.invoke(UncivGame.kt:83)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.UncivGame.render(UncivGame.kt:411)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:193)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:167)
	at com.unciv.app.desktop.HardenGdxAudio.<init>(HardenGdxAudio.kt:54)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:104)

```
**Save Mods:**
```
[Civ V - Gods & Kings]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```
No save data: java.lang.OutOfMemoryError: Java heap space
```
</details>

### Steps to Reproduce

I just clicked Next Turn, one turn before the map is revealed.
I was on turn 1050 maybe?.. the closest saved file I have is from turn 999.
Would that help?

### Operating System

Windows

**Comment by ermnsg** [comment]
After running a batch file to give it more memory:
"C:\Program Files\Java\jdk1.8.0_251\bin\java.exe" -Xmx2048m -Xms1024m -jar "C:\Program Files (x86)\Unciv\Unciv.jar"

I got this error:

**Platform:** Desktop
**Version:** 4.14.11 (Build 1,076)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

OS: Windows 10
	Windows 10 Pro Version 22H2 (Build 19045)
Java: Eclipse Adoptium Temurin-21.0.5+11
	Max Memory: 1024 MB
System default encoding: UTF-8


--------------------------------


**Message:**
```
java.lang.OutOfMemoryError: Java heap space
	at com.badlogic.gdx.scenes.scene2d.Actor.<init>(Actor.java:61)
	at com.badlogic.gdx.scenes.scene2d.Group.<init>(Group.java:36)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.<init>(WidgetGroup.java:41)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.<init>(Table.java:92)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.<init>(Table.java:88)
	at com.unciv.ui.components.tilegroups.YieldGroup.getStatIconsTable(YieldGroup.kt:38)
	at com.unciv.ui.components.tilegroups.YieldGroup.setStats(YieldGroup.kt:28)
	at com.unciv.ui.components.tilegroups.layers.TileLayerMisc.updateYieldIcon(TileLayerMisc.kt:305)
	at com.unciv.ui.components.tilegroups.layers.TileLayerMisc.doUpdate(TileLayerMisc.kt:389)
	at com.unciv.ui.components.tilegroups.layers.TileLayer.update(TileLayer.kt:39)
	at com.unciv.ui.components.tilegroups.TileGroup.update(TileGroup.kt:129)
	at com.unciv.ui.components.tilegroups.WorldTileGroup.update(WorldTileGroup.kt:22)
	at com.unciv.ui.screens.worldscreen.worldmap.WorldMapTileUpdater.updateTiles(WorldMapTileUpdater.kt:32)
	at com.unciv.ui.screens.worldscreen.WorldScreen.update(WorldScreen.kt:403)
	at com.unciv.ui.screens.worldscreen.WorldScreen.render(WorldScreen.kt:728)
	at com.badlogic.gdx.Game.render(Game.java:48)
	at com.unciv.UncivGame.access$render$s2211858(UncivGame.kt:60)
	at com.unciv.UncivGame$wrappedCrashHandlingRender$1.invoke(UncivGame.kt:83)
	at com.unciv.UncivGame$wrappedCrashHandlingRender$1.invoke(UncivGame.kt:83)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.UncivGame.render(UncivGame.kt:411)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:193)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:167)
	at com.unciv.app.desktop.HardenGdxAudio.<init>(HardenGdxAudio.kt:54)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:104)

```
**Save Mods:**
```
[Civ V - Gods & Kings]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```
No save data: java.lang.OutOfMemoryError: Java heap space
```
</details>

**Comment by ermnsg** [comment]
Solved the issue with this UncivLaunch.bat:
setlocal
cd /d "C:\Program Files (x86)\Unciv"
"C:\Program Files\Java\jdk1.8.0_251\bin\java.exe" -Xmx4096m -Xms2048m -jar Unciv.jar

**Comment by yairm210** [comment]
That is one huge map... And you were displaying stats for all tiles on the map, which seems to have been a major factor here

Now that you're not getting errors, can you send a save file? Maybe we can find something to improve

**Comment by ermnsg** [comment]
Happy New Year!

btw.. when I started the game I tried a 400x200 and the game crashed.
So I turned it down a notch. 
The next one I am going to start, (now that I have allocated 4GB) is going to be a 500x250!
... after I obliterate the French, who attacked me out of nowhere...

Here you go :-)
[Autosave-Rome-1047.zip](https://github.com/user-attachments/files/18284997/Autosave-Rome-1047.zip)

**Comment by yairm210** [comment]
These are much bigger maps than we ever planned for -_-

**Comment by ermnsg** [comment]
Well, we're pushing it to the limits!  lol

**Comment by yairm210** [comment]
There's no limit set in-game

**Comment by ermnsg** [comment]
nooiice !!

**Comment by yairm210** [comment]
Closing this as "too big a map for your hardware"
