### ISSUE TITLE
can't run on raspberry pi 4B+

### ISSUE THREAD

**Issue by Greenfoot5** [yairm210/Unciv#1624]
**Describe the bug**

**To Reproduce**
1. Download the latest .jar from the releases page (3.8.6)
2. Run `java -jar Unciv.jar`
3. Get error

If game data is required, please add from menu, save game, copy to clipboard, paste here

**Expected behavior**
Unciv should launch.

**Error**
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'discord-rpc': Native library (linux-arm/libdiscord-rpc.so) not found in resource path (Unciv.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:303)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:427)
	at com.sun.jna.Library$Handler.<init>(Library.java:179)
	at com.sun.jna.Native.loadLibrary(Native.java:569)
	at com.sun.jna.Native.loadLibrary(Native.java:544)
	at club.minnced.discord.rpc.DiscordRPC.<clinit>(DiscordRPC.java:42)
	at com.unciv.app.desktop.DesktopLauncher.tryActivateDiscord(DesktopLauncher.kt:63)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:33)

**Screenshots**
![2020-01-05-215640_1450x161_scrot](https://user-images.githubusercontent.com/16924652/71786785-a8049b80-3007-11ea-8b18-e7515b5809bc.png)

**Comment by yairm210** [comment]
Okay I was completely not expecting ANYONE to run this on Raspberry Pi
It turns out there is no Discord RPC for ARM processors
https://www.reddit.com/r/discordapp/comments/blt3c8/rich_presence_and_discord_on_arm_processors/

I'll try to detect if you're using ARM processors and disable the Discord I guess...?

**Comment by yairm210** [comment]
Probably fixed in the latest commit but since I don't have a Pi I'll need you to check it out
https://github.com/yairm210/Unciv/releases/tag/3.4.8-raspberryPi

**Comment by Greenfoot5** [comment]
Well, it's a different error so it's progress.
```
pi@raspberrypi:~/Downloads $ java -jar Unciv-3.8.8.jar
Packing textures - 224ms
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'libgdxarm.so' for target: Linux, 32-bit
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:125)
	at com.badlogic.gdx.utils.GdxNativesLoader.load(GdxNativesLoader.java:33)
	at com.badlogic.gdx.backends.lwjgl.LwjglNativesLoader.load(LwjglNativesLoader.java:47)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:83)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:71)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:35)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Unable to read file for extraction: libgdxarm.so
	at com.badlogic.gdx.utils.SharedLibraryLoader.readFile(SharedLibraryLoader.java:133)
	at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:289)
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:121)
	... 5 more
```

**Comment by yairm210** [comment]
Huh
I guess the framework doesn't work for Raspberry Pi at all, sorry =/
So for now I'll put that in the main readme

**Comment by touhidurrr** [comment]
> I guess the framework doesn't work for Raspberry Pi at all, sorry =/

I think dealing with several errors like that will fix this issue. It shouldn't be that hard.
