### ISSUE TITLE
Music system improvements

### ISSUE THREAD

**Issue by Iver88** [yairm210/Unciv#2232]
1. Download more royalty free music
2. Shuffle music
3. Support for music from mods placed in "music" subfolder (should be great for traditional soundtrack from nation mod for example)

**Comment by rh-github-2015** [comment]
... or a nation 'theme' that only gets played on the player picker where one selects who to play. Yes, had similar ideas again.

Unfortunately, sound is very much hardcoded (Sound is an enum) and limited right now and I wouldn't want to presume how to expand the current system. When I noticed unit attacksound is dead I *did* get them to play (including from a mod, see [attack-sounds-experimental]( https://github.com/rh-github-2015/Unciv/tree/attack-sounds-experimental) ), but that's an ugly hack, will probably break on android due to threading issues, and, well, the decision on an appoach is political and in my view up to yair?

**Comment by Iver88** [comment]
Nice idea with nation theme. I got this idea from Civ5 nation mod, where there was classic songs from nation's best artists from history.

**Comment by rh-github-2015** [comment]
I tried something yesterday, and for me it's 'sexy', but I'm not sure about implementation details. If someone's curious, [go ahead and take a look](https://github.com/rh-github-2015/Unciv/tree/music-carousel).

I went to the homepages of the two main composers for civ5, one of them has a bunch of tracks freely accessible. Added some stuff from the 'Thatched Thingies' composer. Moved Inca-specific files into mods/Inca/music. Renamed nation-specific files to prefix <nationname>_. Prefixed generic tracks with 'Ambient_'. Made sure there's a suffix _Theme if track is good for player picker, _War if good for the declare war popup, _Peace if applicable for first contact or trade while at peace... 

Music selection in Trade screen not done, and needs some way to leave currently playing track alone if there's no match at all (so we'd be free do allow any 'war' mood track to start in a war declaration if a nation-specific one is missing, but leave music alone on first contact if there's no nation-specific file of any mood)...

Also not yet decided about fade-out duration, whether to put that in settings, or whether to begin fading in a new track while the old is still fading out.

**Comment by rh-github-2015** [comment]
Technical: I'd love to hear from the gurus. 

- That ticker firing 20 times per second is ugly, but I saw no other way to get a fade-out.
- thread("Music") is gone - Music.play() thread-decouples anyway as I understand the dox, so startSound() always returned quickly - or not? Breakpoints in the debugger seem to corroborate. timer("musicTimer") is the new decoupled thread, and all Music.play() calls are there anyway, so everything's fine, right?
- On the other hand, with unchanged calling site code, I managed to have the same track play twice in parallel with a shift of half a second - never with the new code.
- Lastly, I' not convinced this is thread-safe in all situations, especially some of the !! operators. Maybe ...

```
            if (<should stop>) {
                val temp = currentMusic!!
                currentMusic = null
                temp.stop()
                temp.dispose()
            }
```
would be safer than
```
            if (<should stop>) {
                currentMusic!!.stop()
                currentMusic!!.dispose()
                currentMusic = null
            }
```
...??? Are there atomic read-and-update patterns in kotlin?

**Comment by Iver88** [comment]
> I tried something yesterday, and for me it's 'sexy', but I'm not sure about implementation details. If someone's curious, [go ahead and take a look](https://github.com/rh-github-2015/Unciv/tree/music-carousel).

I'll test it in free time. You are amazing :)

**Comment by Iver88** [comment]
> I went to the homepages of the two main composers for civ5, one of them has a bunch of tracks freely accessible. Added some stuff from the 'Thatched Thingies' composer. Moved Inca-specific files into mods/Inca/music. Renamed nation-specific files to prefix _. Prefixed generic tracks with 'Ambient_'. Made sure there's a suffix _Theme if track is good for player picker, _War if good for the declare war popup, _Peace if applicable for first contact or trade while at peace...

You mean Inca mod on GitHub? I can' find it for testing.

**Comment by Iver88** [comment]
> Also not yet decided about fade-out duration, whether to put that in settings, or whether to begin fading in a new track while the old is still fading out.

No need for settings I thing. Gentle length should be enough. 3-4 seconds before end of previous  maybe?

**Comment by Iver88** [comment]
> Oh, and it searches _all_ mods, not just the currently selected, or I would have needed a way to pass the new ruleset from the new game screen to the track randomizer. Civname_ prefix was enough for first draft.

It's bad. Maybe in future. But it's small price for music system right now.

**Comment by Iver88** [comment]
> * That ticker firing 20 times per second is ugly, but I saw no other way to get a fade-out.

20 times per second isn't much for call. In Unity for example, you check it per frame. So 60 times + per second.

**Comment by rh-github-2015** [comment]
Thanks for the comments. 

> You mean Inca mod on GitHub? I can' find it for testing.
Maybe Yair already removed it because he merged them into main? The post meant only to quickly illustrate where it looks and how it chooses file names - without writing clear instructions. IOW, structure like this:
![image](https://user-images.githubusercontent.com/16001896/77698508-09a62780-6fb1-11ea-9498-28c8926ab1ab.png)

Allows some flexibility, as e.g. Greece_War.mp3 has the same frequency to be picked as Greece_is_hot_in_summer!_even_without_War.flac, and where in the (modcount+1) music folders it is is irrelevant. Best approach? Don't know. Just a quick hack. And I got distracted or the hooks in the trade dialogs would be in by now.

**Comment by Iver88** [comment]
1. When selecting nation with theme on new game screen, theme starts play and I select nation without theme song, last theme starts play again. It can be problem with mod without theme music. It should stops a music when picking another civ.

2. This happened to me when first civ meet:
`Music queued: mods/Lands of the Bohemian Crown/music/Ambient_The High Castle_Peace.mp3
AL lib: (WW) FreeDevice: (0x1316d4000) Deleting 6 Buffer(s)
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Error reading audio data.
	at com.badlogic.gdx.backends.lwjgl.audio.Mp3$Music.read(Mp3.java:91)
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALMusic.fill(OpenALMusic.java:251)
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALMusic.update(OpenALMusic.java:235)
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.update(OpenALAudio.java:227)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:222)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:128)
Caused by: java.lang.NullPointerException
	at com.badlogic.gdx.backends.lwjgl.audio.Mp3$Music.read(Mp3.java:82)
	... 5 more
Exception in thread "musicTimer" java.lang.UnsatisfiedLinkError: org.lwjgl.openal.AL10.nalBufferData(IIJII)V
	at org.lwjgl.openal.AL10.nalBufferData(Native Method)
	at org.lwjgl.openal.AL10.alBufferData(AL10.java:1099)
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALMusic.fill(OpenALMusic.java:268)
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALMusic.play(OpenALMusic.java:91)
	at com.unciv.UncivGame.musicTimerTask(UncivGame.kt:148)
	at com.unciv.UncivGame$startMusic$$inlined$timer$1.run(Timer.kt:149)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

`

[Ambient_The High Castle_Peace.mp3.zip](https://github.com/yairm210/Unciv/files/4390990/Ambient_The.High.Castle_Peace.mp3.zip)

**Comment by Iver88** [comment]
3. When ambient music is playing with _Peace and first civ contacted, it should continue playing because _Peace music is playing already.

**Comment by Iver88** [comment]
3. Theme should start when nation mod selected and nation was picked to empty player slot.
4. Music should stops when opening menu. Or new game menu at least.

**Comment by Iver88** [comment]
List of my songs here for more info.

<img width="286" alt="Snímek obrazovky 2020-03-27 v 3 23 18" src="https://user-images.githubusercontent.com/1991403/77714833-52260b00-6fda-11ea-94ed-05ee87b2fed0.png">

**Comment by rh-github-2015** [comment]
>     1. GdxRuntimeException: Error reading audio data.
Normally this would clearly say file is broken. Maybe I should catch that, rename the file so it doesn't get attempted again, log to console and move on...

But - is it broken? Can VLC play it? Can your non-VLC distro play it (or MPC should you be on windoze)? As a Mint-ie I remember the Distro gives you a choice to include non-open codecs, and I always pull them...

**Comment by Iver88** [comment]
VLC can play it. I'll test it further but it seems that this happens at random.

**Comment by rh-github-2015** [comment]
Well my Unciv can play your file. Mint 19.3. And you might want to check [my branch](https://github.com/rh-github-2015/Unciv/tree/music-carousel) for a more current state. Next thing I need to check is how best to tell it to finish playing one track, but afterwards not move to the next but stop. The small commit for TileEditorOptionsTable might be problematic - I inserted one line with copy& paste and three '.first()' calls way further down suddenly flagged red. A 'build' fails, but starting the debugger not - and it executes my line. Very strange.

Oh, I finally tested with more file types. GdX outright rejects m4a, flac and opus. Darn. And it does so early, and the message more or less says it only checks the extension. Doesn't even try to pass it to the next api which would probably be able to play those... Well, it tries be be multiplatform.

**Comment by Iver88** [comment]
1. Works
2. Works
3. Works
4. Works. I like fading out feature :) When you must go something for example, you pause game using menu and no music is playing. Which is great. But music can be paused instead of stopping it completely and playing next.
5. I don't understand much. This song version is with lyrics so for theme only. I have another version without lyrics for ambient when war.

This is how i understand it for "Lands of the Bohemian Crown_Ktož sú boží boží bojovníci_Theme" - not ambient (no prefix), play when nation is "Lands of the Bohemian Crown", song name, theme (triggers when choosing nation)

This is how i understand it for "Lands of the Bohemian Crown_Ktož sú boží boží bojovníci_War" - not ambient (no prefix), play when nation is "Lands of the Bohemian Crown", song name, war (triggers when war starts)

And when there is no theme music for selected civ, It should fade out and stop at least in my opinion. Right now, you select another civ and previous still playing. And when disabling of nation mod, music continue playing too.

6. When launch a game and starts with another player (autostart), mod civ related music is played. I though, that when mod name is before song name, it will play only when playing as civ from mod.

So

"Ambient_Mod-name_Song-name.mp3" should play should play for Mod-name civ only

and

"Ambient_Song-name.mp3" for every civ (when this mod is activated)

When starting game without activated mod or game is loaded without activated mod, nothing plays and music controller stays shut down.

**Comment by rh-github-2015** [comment]
mab.to: "Prior using the service you are required to provide your consent to the processing of your personal data." - no thanks
Headaches - trouble deciphering your english - but I think I get the gist: Mostly the answer is: Yes, this is how it's currently designed, and I tried to explain it: Put all music files including all present mods into a list, sort by prefix math, suffix match, nonpresence in recent history, then random and pick first. No fuzzy logic (which I considered).

No, I haven't included any provision to truly pause a playing track yet. Just a quick draft.
You convinced me it needs to ignore mod folders not currently in the ruleset. Later.

Don't get me wrong: I asked for feedback, and you delivered. I'm very thankful. But I'm not getting a clear idea where this should go - is the name matching a useful approach or should we drop it and go for something needing explicit declaration in some new json to map context to tracks? Perhaps when my head is clearer...

**Comment by Iver88** [comment]
> mab.to: "Prior using the service you are required to provide your consent to the processing of your personal data." - no thanks

Or you know better service for sending of files? This is just nonsese from EU. You can't run even personal website without this consent.

**Comment by Iver88** [comment]
> Headaches - trouble deciphering your english - but I think I get the gist: Mostly the answer is: Yes, this is how it's currently designed, and I tried to explain it: Put all music files including all present mods into a list, sort by prefix math, suffix match, nonpresence in recent history, then random and pick first. No fuzzy logic (which I considered).

Sorry for my english. I'm not native speaker I can deciper my english sometimes too. :D

**Comment by Iver88** [comment]
> mab.to: "Prior using the service you are required to provide your consent to the processing of your personal data." - no thanks
> Headaches - trouble deciphering your english - but I think I get the gist: Mostly the answer is: Yes, this

**Comment by Iver88** [comment]
> Don't get me wrong: I asked for feedback, and you delivered. I'm very thankful. But I'm not getting a clear idea where this should go - is the name matching a useful approach or should we drop it and go for something needing explicit declaration in some new json to map context to tracks? Perhaps when my head is clearer...

Your idea with suffixes and affixes is just brilliant. Simple and working solution. Don't get me wrong too… I know it looks like commanding you, but I'm not. I just testing it to pulp. These tasks was for me primary. After when I get to them. But you are hero for me. You are not afraid of any programming challenge. I'm completely new in Kotlin. It's hell language in my point of view :D So I believe, after few weeks, I'll be more beneficial and then now :)

**Comment by rh-github-2015** [comment]
Heh. Three or four weeks ago I had'n even heard the name.

The mod system opens holes once you look at getting them into the mod editor, and that's what interests me more right now. I think I'm getting somewhere, but I still get a situation where mod lists are out of synch.

What I'd really like to know - When you have several independent branches in your local git and its github fork, and the fork gets far behind its master, the branches would be presentable as pull requests without red flags if the master hadn't moved but would get red flags now, how do you get everything synchronized properly? The only way I know that would work reliably for me is to make a local file copy of your branches, delete all branches offline and online, then bring the fork up to date, then reopen branches and merge stuff in with an external merge tool.... I did that too often already.

**Comment by rh-github-2015** [comment]
Say, in the current codebase (not my fork), what happens if you
- open the new game screen, ensure some mods are selected
- ensure some players pick a modded nation and leave the new game screen
- open the map editor to a new map and close it
- open the new game screen again
for me, the mod and player nation selection is preserved, but the icons in the player picker are black.

**Comment by rh-github-2015** [comment]
> service for sending of files

We shouldn't endorse such here, but the most hassle-free I know is [we.tl](https://we.tl). Or does that play nice with me only because I have already let it set some cookies ages ago? (...) Oh, it does have one such button. So, no, I know of no bugme-free file services.

**Comment by rh-github-2015** [comment]
Another push, this time I wrote [instructions](https://github.com/rh-github-2015/Unciv/blob/music-carousel/docs/Music%20Chooser%20Tips.md).

I'll probably delete the whole thing soon, to re-create it based on a freshly synced fork master. If that goes smoothly, I'll pull-request it.

Ideas for a json-controlled system to support downloading music files are there, some notes, but will have to wait.

**Comment by Iver88** [comment]
I like it. I'll prepare my mods for it after you release first draft :) You are God :)

**Comment by rh-github-2015** [comment]
Possibly resolved by #2341? Please test and comment.

**Comment by AdityaMH** [comment]
This outdated?

**Comment by SomeTroglodyte** [comment]
> This outdated
Looking at dates and issue number - definitely.  I _might_ pull it out of some backup one day - unless I've lost those..
