### ISSUE TITLE
32-bit Linux version is not running

### ISSUE THREAD

**Issue by fedorov-ao** [yairm210/Unciv#2361]
**Bug description**

32-bit Linux version is not running because libdiscord-rpc.so library was not included in the Unciv.jar file.

**How to reproduce**

For example, trying to launch 3.7.0 jar-only version from shell yields the following:

```
$ java -jar Unciv.jar 
Packing textures - 49ms
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'discord-rpc': Native library (linux-x86/libdiscord-rpc.so) not found in resource path
```

Since jar file is in fact a zip archive, one can open it with a utility of choice and verify that there is indeed no linux-x86/libdiscord-rpc.so included in it.

**Temporary fix**

The issue was fixed by compiling libdiscord-rpc.so manually as described [here](https://gist.github.com/Swyter/98074d2d42cd7f7c0e5f86ef619969d3) and placing it in the jar file at the requested path.

**Comment by yairm210** [comment]
Hey, I'd be really glad if you can check if the latest version works iut-of-the-box, and if not then we'll keep working on it =)
https://github.com/yairm210/Unciv/releases/tag/3.7.1

**Comment by fedorov-ao** [comment]
Unfortunately, the 3.7.1 version does not start, but with a different error:

```
$ java -jar Unciv.jar 
Packing textures - 49ms
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/jna-97039/jna5978521028107015936.tmp: wrong ELF class: ELFCLASS64
        at com.sun.jna.Native.open(Native Method)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:288)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:427)
        at com.sun.jna.Library$Handler.<init>(Library.java:179)
        at com.sun.jna.Native.loadLibrary(Native.java:569)
        at com.sun.jna.Native.loadLibrary(Native.java:544)
        at club.minnced.discord.rpc.DiscordRPC.<clinit>(DiscordRPC.java:42)
        at com.unciv.app.desktop.DesktopLauncher.tryActivateDiscord(DesktopLauncher.kt:79)
        at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:38)
```

As far as I understand, "wrong ELF class: ELFCLASS64" error message means that java tries to load 64-bit version of libdiscord-rpc.so while running on 32-bit system and, as expected, fails. Since linux-x86/libdiscord-rpc.so and linux-x86-64/libdiscord-rpc.so inside Unciv.jar have the same size I suppose these are copies of the same file - the 64-bit libdiscord-rpc.so. 

The game starts normally if linux-x86/libdiscord-rpc.so inside Unciv.jar is replaced by 32-bit libdiscord-rpc.so that I have compiled myself according to instructions linked in the opening post. This 32-bit libdiscord-rpc.so is attached: [libdiscord-rpc.so.zip](https://github.com/yairm210/Unciv/files/4450731/libdiscord-rpc.so.zip)

**Comment by yairm210** [comment]
Thanks!
Please check https://github.com/yairm210/Unciv/releases/tag/3.7.1-linux32test - hopefully the last time =)

**Comment by fedorov-ao** [comment]
The jar version starts correctly, thank you for fixing it! 

I have also checked the jvm-bundled version of Unciv. Running game like jar version with `java -jar Unciv.jar` again works, but running bundled jvm does not:

```
$ ./Unciv
jre/lib/i386/server/libjvm.so: cannot open shared object file: No such file or directory
Error: failed to load VM runtime library!
```

Since in jre/lib does not have i386 directory at all - it has only amd64 directory with jvm dynamic libraries and such, I believe that 32-bit version of jvm was erroneously omitted.
