### ISSUE TITLE
game crashes while destroying a carrier with planes

### ISSUE THREAD

**Issue by Haeherfeder** [yairm210/Unciv#2508]
**Describe the bug**
like #2492 but while an carrier with planes were attacked.

**To Reproduce**
build a carrier, move a plane in it, ad let it be destroyed

if a savegame is needed ask:
error is below

**Expected behavior**
dont crash the game, may destroy the planes or move them to a city
**Screenshots**

**Additional context**
probably also with a city with planes/units in it.

Exception in thread "NextTurn" java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at kotlin.sequences.SequenceBuilderIterator.next(SequenceBuilder.kt:149)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:132)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156)
	at com.unciv.logic.map.MapUnit.destroy(MapUnit.kt:730)
	at com.unciv.logic.battle.MapUnitCombatant.takeDamage(MapUnitCombatant.kt:20)
	at com.unciv.logic.battle.Battle.attack(Battle.kt:61)
	at com.unciv.logic.battle.Battle.moveAndAttack(Battle.kt:32)
	at com.unciv.logic.automation.BattleHelper.tryAttackNearbyEnemy(BattleHelper.kt:26)
	at com.unciv.logic.automation.UnitAutomation.automateUnitMoves(UnitAutomation.kt:133)
	at com.unciv.logic.automation.NextTurnAutomation.automateUnits(NextTurnAutomation.kt:440)
	at com.unciv.logic.automation.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:44)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:92)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt:439)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt:40)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

**Comment by yairm210** [comment]
Should be solved in 3.8.1

**Comment by Haeherfeder** [comment]
sometimes with should not happend

in 3.8.1

Iroquois Artillery attacked Denmark Carrier
Exception in thread "NextTurn" java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at kotlin.sequences.SequenceBuilderIterator.next(SequenceBuilder.kt:149)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:132)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156)
	at com.unciv.logic.map.MapUnit.destroy(MapUnit.kt:731)
	at com.unciv.logic.battle.MapUnitCombatant.takeDamage(MapUnitCombatant.kt:20)
	at com.unciv.logic.battle.Battle.attack(Battle.kt:61)
	at com.unciv.logic.battle.Battle.moveAndAttack(Battle.kt:32)
	at com.unciv.logic.automation.BattleHelper.tryAttackNearbyEnemy(BattleHelper.kt:26)
	at com.unciv.logic.automation.UnitAutomation.automateUnitMoves(UnitAutomation.kt:133)
	at com.unciv.logic.automation.NextTurnAutomation.automateUnits(NextTurnAutomation.kt:440)
	at com.unciv.logic.automation.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:44)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:92)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt:449)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt:41)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

in 3.8.1 patch 1

Iroquois Artillery attacked Denmark Carrier
Exception in thread "NextTurn" java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at kotlin.sequences.SequenceBuilderIterator.next(SequenceBuilder.kt:149)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:132)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156)
	at com.unciv.logic.map.MapUnit.destroy(MapUnit.kt:731)
	at com.unciv.logic.battle.MapUnitCombatant.takeDamage(MapUnitCombatant.kt:20)
	at com.unciv.logic.battle.Battle.attack(Battle.kt:61)
	at com.unciv.logic.battle.Battle.moveAndAttack(Battle.kt:32)
	at com.unciv.logic.automation.BattleHelper.tryAttackNearbyEnemy(BattleHelper.kt:26)
	at com.unciv.logic.automation.UnitAutomation.automateUnitMoves(UnitAutomation.kt:133)
	at com.unciv.logic.automation.NextTurnAutomation.automateUnits(NextTurnAutomation.kt:440)
	at com.unciv.logic.automation.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:44)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:92)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt:456)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt:41)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
