### ISSUE TITLE
The game refuses to continue when Turn 11 is finished

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/Unciv#2676]
I just downloaded the Windows version of the game, and, when I end Turn 11, the game is stuck on Wating for other players and I cannot continue the game, because it says "Oh no! Something went terribly wrong!" so I am forced to start a new game. I tried both versions, 64x and 32x, and it works only in the latter, it keeps going after Turn 11, but not in 64x. In 32x version, the same problem happens when I end Turn 33

**Comment by dgasaway** [comment]
I got this on the new 3.9.0 for Linux 64-bit, except it was on turn 46.

Exception in thread "NextTurn" java.lang.Exception: Should never call this function on a non-neighbor!
        at com.unciv.logic.map.TileInfo.isConnectedByRiver(TileInfo.kt:351)
        at com.unciv.logic.map.UnitMovementAlgorithms.getMovementCostBetweenAdjacentTiles(UnitMovementAlgorithms.kt:27)
        at com.unciv.logic.automation.BarbarianAutomation.findFurthestTileCanMoveTo(BarbarianAutomation.kt:121)
        at com.unciv.logic.automation.BarbarianAutomation.automateScout(BarbarianAutomation.kt:89)
        at com.unciv.logic.automation.BarbarianAutomation.automateUnit(BarbarianAutomation.kt:26)
        at com.unciv.logic.automation.BarbarianAutomation.automate(BarbarianAutomation.kt:19)
        at com.unciv.logic.automation.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:24)
        at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:93)
        at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt:458)
        at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt:41)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

**Comment by yairm210** [comment]
Cool, could you send me the game data?

**Comment by dgasaway** [comment]
[Autosave.zip](https://github.com/yairm210/Unciv/files/4708619/Autosave.zip)

I had actually started another game, which hit this at turn 105.  It's attached.

**Comment by yairm210** [comment]
Solved, thanks!
Patch will be rolling out soon =)
