### ISSUE TITLE
Exception when Fighter attacks Destroyer.

### ISSUE THREAD

**Issue by dgasaway** [yairm210/Unciv#2689]
**Describe the bug**
Attacking an enemy Destroyer with a Fighter caused this exception.

```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.Exception: Should never call this function on a non-neighbor!
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:135)
Caused by: java.lang.Exception: Should never call this function on a non-neighbor!
        at com.unciv.logic.map.TileInfo.isConnectedByRiver(TileInfo.kt:351)
        at com.unciv.logic.battle.BattleDamage.getAttackModifiers(BattleDamage.kt:141)
        at com.unciv.logic.battle.BattleDamage.getAttackingStrength(BattleDamage.kt:276)
        at com.unciv.logic.battle.BattleDamage.calculateDamageToDefender(BattleDamage.kt:298)
        at com.unciv.logic.battle.Battle.tryInterceptAirAttack(Battle.kt:390)
        at com.unciv.logic.battle.Battle.attack(Battle.kt:43)
        at com.unciv.logic.battle.Battle.moveAndAttack(Battle.kt:32)
        at com.unciv.ui.worldscreen.bottombar.BattleTable$simulateBattle$2.invoke(BattleTable.kt:210)
        at com.unciv.ui.worldscreen.bottombar.BattleTable$simulateBattle$2.invoke(BattleTable.kt:23)
        at com.unciv.ui.utils.CameraStageBaseScreenKt$onClick$1.invoke(CameraStageBaseScreen.kt:150)
        at com.unciv.ui.utils.CameraStageBaseScreenKt$onClick$1.invoke(CameraStageBaseScreen.kt)
        at com.unciv.ui.utils.CameraStageBaseScreenKt$onClickEvent$1.clicked(CameraStageBaseScreen.kt:143)
        at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
        at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:59)
        at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:351)
        at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:360)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:221)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:128)
```

**To Reproduce**
Load the attached save, then use the Fighter in Pamplona to attack the Korean Destroyer to the southwest.

[Spain -  428 turns.zip](https://github.com/yairm210/Unciv/files/4727364/Spain.-.428.turns.zip)

**Comment by yairm210** [comment]
This has already been fixed by 3.9.0-patch2, specifically in b90690a =)
