### ISSUE TITLE
[Crash] Clicking on an unoccupied 'locked tite' from City which does not own the 'lock'

### ISSUE THREAD

**Issue by punnycoder** [yairm210/Unciv#2864]
**Describe the bug**
'City1' from my Civ has locked a tile that is 'occupied/purchased' by 'city2' from my Civ, and 'city2' is razed down. 'City1' lost the locked tile, because it belonged to another city which is now razed, but it somehow still keeps a lock on it. The crash takes place when 'City3' is founded, and you try to purchase that locked tile for expansion. However, the issue can be "fixed" in-game.

**Note: Unlike #2784, this issue doesn't simply get solved in the next turn.**

**Steps to reproduce:**
1. Purchase a nearby city **(Ardea)** from another civilisation.
2. Let neighbour city **'Hamburg'** work on **Ardea's** occupied tile
3. Raze down Ardea
4. Build new city: Ardea2
5. Try to click the tile from Ardea2 for expansion. (CRASH)
6. Purchase the tile from Hamburg (ALREADY LOCKED AFTER PURCHASE)
7. Now click the tile from Ardea2, it won't crash. (Issue Fixed IN-GAME)

**Expected behavior**
1) When a city is razed down, any other city that has locked a tile which belonged to the razed city, should **let go** of the lock, and the population should be re-assigned to a new tile/slot.
_Any of the following messages can be chosen to alert the player:_ 
a) 'You have lost occupation of a locked tile'
b) 'Population from locked tile had to be relocated'
c) '$city_name$ relocated population from locked tile after occupying city was razed' (cringe)

If you let the lock remain, after purchase, show the tile as 'worked by $city$'. 
But since the tile is not occupied by your civilization, you won't be able to relocate the population from that locked tile, thus allowing 'zombie population'.

**Console Output:**
```
Packing textures - 12ms
Loading game basics - 497ms
Loading translation file for English - 65ms
Loading percent complete of languages - 2ms
RNG seeded with 1595131347187
Natural Wonders for this game: [Krakatoa]
Exception in thread "LWJGL Application" kotlin.KotlinNullPointerException
	at com.unciv.ui.cityscreen.CityScreenTileTable.update(CityScreenTileTable.kt:56)
	at com.unciv.ui.cityscreen.CityScreen.update$core(CityScreen.kt:103)
	at com.unciv.ui.cityscreen.CityScreen$addTiles$1.invoke(CityScreen.kt:184)
	at com.unciv.ui.cityscreen.CityScreen$addTiles$1.invoke(CityScreen.kt:20)
	at com.unciv.ui.utils.CameraStageBaseScreenKt$onClick$1.invoke(CameraStageBaseScreen.kt:150)
	at com.unciv.ui.utils.CameraStageBaseScreenKt$onClick$1.invoke(CameraStageBaseScreen.kt)
	at com.unciv.ui.utils.CameraStageBaseScreenKt$onClickEvent$1.clicked(CameraStageBaseScreen.kt:143)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:59)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:351)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:360)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:221)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:128)
```

**Comment by punnycoder** [comment]
Haha, I was gonna attach the autosave file that I had zipped. Turns out it got deleted by the game :laughing:
