### ISSUE TITLE
Crash on Android F-Droid version upon clicking on "Next Turn"

### ISSUE THREAD

**Issue by nachoparker** [yairm210/Unciv#2943]
The game just crashes and exits. I captured the LogCat output

```
08-05 17:49:50.460  4224  4630 E AndroidRuntime: FATAL EXCEPTION: NextTurn
08-05 17:49:50.460  4224  4630 E AndroidRuntime: Process: com.unciv.app, PID: 4224
08-05 17:49:50.460  4224  4630 E AndroidRuntime: java.lang.IllegalArgumentException: Cannot round NaN value.
08-05 17:49:50.460  4224  4630 E AndroidRuntime:        at kotlin.math.MathKt__MathJVMKt.roundToInt(MathJVM.kt:1132)
08-05 17:49:50.460  4224  4630 E AndroidRuntime:        at com.unciv.logic.battle.BattleDamage.calculateDamageToDefender(BattleDamage.kt:297)
08-05 17:49:50.460  4224  4630 E AndroidRuntime:        at com.unciv.logic.battle.Battle.takeDamage(Battle.kt:99)
08-05 17:49:50.460  4224  4630 E AndroidRuntime:        at com.unciv.logic.battle.Battle.attack(Battle.kt:61)
08-05 17:49:50.460  4224  4630 E AndroidRuntime:        at com.unciv.logic.battle.Battle.moveAndAttack(Battle.kt:38)
08-05 17:49:50.460  4224  4630 E AndroidRuntime:        at com.unciv.logic.automation.BattleHelper.tryAttackNearbyEnemy(BattleHelper.kt:27)
08-05 17:49:50.460  4224  4630 E AndroidRuntime:        at com.unciv.logic.automation.UnitAutomation.automateUnitMoves(UnitAutomation.kt:137)
08-05 17:49:50.460  4224  4630 E AndroidRuntime:        at com.unciv.logic.automation.NextTurnAutomation.automateUnits(NextTurnAutomation.kt:454)
08-05 17:49:50.460  4224  4630 E AndroidRuntime:        at com.unciv.logic.automation.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:45)
08-05 17:49:50.460  4224  4630 E AndroidRuntime:        at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:101)
08-05 17:49:50.460  4224  4630 E AndroidRuntime:        at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt:486)
08-05 17:49:50.460  4224  4630 E AndroidRuntime:        at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt:41)
08-05 17:49:50.460  4224  4630 E AndroidRuntime:        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
08-05 17:49:50.463   614  2295 W ActivityManager:   Force finishing activity com.unciv.app/.AndroidLauncher
```

Here's the crash report:

[crash_report.txt](https://github.com/yairm210/Unciv/files/5031758/crash_report.txt).

Fantastic game, thank you for all your efforts!

**Comment by yairm210** [comment]
If this was in version 3.9.16, this was fixed in patch1, please update :)
If not, please attach the game data and we'll reopen this

**Comment by nachoparker** [comment]
I see, thanks.

I'll test out the new version once it comes out on F-Droid. I already attached the crash report which includes the saved game, so we'll reopen if the issue persists.

Cheers!
