### ISSUE TITLE
Unciv for Java Fails to run

### ISSUE THREAD

**Issue by PaxiTheAlchemist** [yairm210/Unciv#3283]
# Unciv for Java Fails to run

## Describe the bug
Unciv Fails to run as Java throws errors in relation to missing discord-rpc libraries

## To Reproduce
1. Grab the latest Version of `Unciv.jar` (in my case version 3.11.6)
2. Place `Unciv.jar` in its own directory (as recommended within the README.md due to files generating)
3. Open the terminal within the directory containing the `Unciv.jar`
4. Run `Java -jar Unciv.jar` within the terminal
5. See error

## Expected behavior
Seeing that the error occurs before the game can even launch, i'd assume the game is supposed to launch normally

## Screenshots
**Terminal:**
http://imgur.com/1oUqpk7l.png

Due to the error, no game window appears

## Additional context
**OS:** Linux (Running a modified version of Ubuntu)
**Arch:** armv7l
**Hardware:** Raspberrypi 3 B+ with no accessories or physical modifications
**Java version:** openjdk 11.0.8 2020-07-14 (OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1))

**Comment by PaxiTheAlchemist** [comment]
also it seems the output of the command was cut off within the screenshot, in anycase here is the raw output:
```
Packing textures - 317ms
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'discord-rpc': Native library (linux-arm/libdiscord-rpc.so) not found in resource path (Unciv.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:303)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:427)
	at com.sun.jna.Library$Handler.<init>(Library.java:179)
	at com.sun.jna.Native.loadLibrary(Native.java:569)
	at com.sun.jna.Native.loadLibrary(Native.java:544)
	at club.minnced.discord.rpc.DiscordRPC.<clinit>(DiscordRPC.java:42)
	at com.unciv.app.desktop.DesktopLauncher.tryActivateDiscord(DesktopLauncher.kt:176)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:60)
```

**Comment by yairm210** [comment]
LibGDX, and therefore Unciv, does not run on Raspberry pi.

**Comment by MayeulC** [comment]
I feel like this issue should be fixed, I encountered it today when launching on another ARM platform (pinephone).

As I prefer FLOSS, it annoys me that Unciv tries to load some native discord library, especially as it crashes right after because it hasn't been compiled on aarch64.

The game probably shouldn't crash if it can't find or load the discord library.

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'discord-rpc': Native library (linux-aarch64/libdiscord-rpc.so) not found in resource path (/app/data/Unciv.jar)
       ...
	at club.minnced.discord.rpc.DiscordRPC.<clinit>(DiscordRPC.java:42)
	at com.unciv.app.desktop.DesktopLauncher.tryActivateDiscord(DesktopLauncher.kt:193)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:64)
```

(That's using the flatpak build)
