### ISSUE TITLE
Crashes under Wayland

### ISSUE THREAD

**Issue by Begggs** [yairm210/Unciv#3302]
Linux, last release, swaywm, Xwayland working, tried to run with bundled java, openjdk8 and via bundled executable file, result is the same

1. Install Wayland-based WM/DE
2. Download latest release
3. `unzip Unciv-Linux64.zip`
4. `./Unciv` or `java -jar Unciv.jar`
5. See error

```
$ ls
Unciv  Unciv-Linux64.zip  Unciv.jar  config.json  jre
$ ./Unciv
Packing textures - 6ms
Exception in thread "LWJGL Application" java.lang.ExceptionInInitializerError
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setVSync(LwjglGraphics.java:592)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.lwjgl.opengl.LinuxDisplay.getAvailableDisplayModes(LinuxDisplay.java:951)
	at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:738)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
	... 2 more
AL lib: (EE) alc_cleanup: 1 device not closed
```

**Comment by HadeanLake** [comment]
install xrandr

**Comment by yairm210** [comment]
Indeed, LibGDX does not support Wayland, and I haven't seen any support plans for it either.

**Comment by Begggs** [comment]
> install xrandr

thanks, worked
