### ISSUE TITLE
Can't compile and run on macOS

### ISSUE THREAD

**Issue by lishaoxia1985** [yairm210/Unciv#3343]
These are some error informations:
Error in LSRegisterURL: -10811
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: com.badlogic.gdx.utils.Array.iterator()Lcom/badlogic/gdx/utils/Array$ArrayIterator;
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:135)
Caused by: java.lang.NoSuchMethodError: com.badlogic.gdx.utils.Array.iterator()Lcom/badlogic/gdx/utils/Array$ArrayIterator;
	at com.unciv.ui.utils.ImageGetter.reload(ImageGetter.kt:55)
	at com.unciv.ui.utils.ImageGetter.<clinit>(ImageGetter.kt:42)
	at com.unciv.logic.GameSaver.getGeneralSettings(GameSaver.kt:105)
	at com.unciv.UncivGame.create(UncivGame.kt:79)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:151)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:128)

**Comment by yairm210** [comment]
That's because of the gdx upgrade
You need to gradle clean, clear the gradle cache, and then it'll work out
I also restarted the Android studio a couple of times trying to figure this out, so it might be a part of the process but also might not be needed
