### ISSUE TITLE
Latest commit crashed.

### ISSUE THREAD

**Issue by ninjatao** [yairm210/UnCiv#382]
588 --------- beginning of crash
 589 12-27 23:12:46.911  4381  4413 E AndroidRuntime: FATAL EXCEPTION: GLThread 990
 590 12-27 23:12:46.911  4381  4413 E AndroidRuntime: Process: com.unciv.game, PID: 4381
 591 12-27 23:12:46.911  4381  4413 E AndroidRuntime: java.lang.ExceptionInInitializerError
 592 12-27 23:12:46.911  4381  4413 E AndroidRuntime:    at com.unciv.UnCivGame.create(UnCivGame.kt:31)
 593 12-27 23:12:46.911  4381  4413 E AndroidRuntime:    at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceChanged(AndroidGraphics.java:311     )
 594 12-27 23:12:46.911  4381  4413 E AndroidRuntime:    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1591)
 595 12-27 23:12:46.911  4381  4413 E AndroidRuntime:    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1293)
 596 12-27 23:12:46.911  4381  4413 E AndroidRuntime: Caused by: com.badlogic.gdx.utils.SerializationException: Error parsing JSON on line 3240 near: s
 597 12-27 23:12:46.911  4381  4413 E AndroidRuntime:
 598 12-27 23:12:46.911  4381  4413 E AndroidRuntime:
 599 12-27 23:12:46.911  4381  4413 E AndroidRuntime:    // Policy picker screen
 600 12-27 23:12:46.911  4381  4413 E AndroidRuntime:    *ERROR*"You have entered the [newEra] era!":{
 601 12-27 23:12:46.911  4381  4413 E AndroidRuntime:        Italian:"Sei entrato ne
 602 12-27 23:12:46.911  4381  4413 E AndroidRuntime:    at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:550)
 603 12-27 23:12:46.911  4381  4413 E AndroidRuntime:    at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:39)
 604 12-27 23:12:46.911  4381  4413 E AndroidRuntime:    at com.unciv.models.gamebasics.Translations.<init>(Translations.kt:10)
 605 12-27 23:12:46.911  4381  4413 E AndroidRuntime:    at com.unciv.models.gamebasics.GameBasics.<clinit>(GameBasics.kt:27)
 606 12-27 23:12:46.911  4381  4413 E AndroidRuntime:    ... 4 more
 607 12-27 23:12:46.912  1141  2614 V WindowManager: removeIfPossible: Window{5b600da u0 DividerMenusView} callers=com.android.server.wm.WindowState.re     moveIfPossible:1914 com.android.server.wm.WindowManagerService.removeWindow:2031 com.android.server.wm.Session.remove:218 android.view.IWindowSess     ion$Stub.onTransact:242 com.android.server.wm.Session.onTransact:161

**Comment by yairm210** [comment]
Shoot, it's the parsing of the Spanish translation I accepted yesterday
I'll deal with it tonight
