### ISSUE TITLE
Crash on arm64 (Samsung Tab S2) from F-droid - missing libgdx.so

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#3946]
Version: Fresh from F-Droid moments ago = 3.14.8
Symptom: None - doesn't launch, screen doesn't even flash
Platform: Samsung Tab S2 (SM-T813 = gts210vewifi) running Lineage 16.0 (should correspond to Pie, I keep forgetting), arm64
Logcat: java.lang.UnsatisfiedLinkError yada yada zip file "/data/app/com.unciv.app-garble/base.apk" yada yada ... /lib/arm64, /system/lib64, /system/vendor/lib64 ... couldn't find "libgdx.so"

Sounds like [this here](https://stackoverflow.com/questions/54414066/updating-android-app-with-libgdx-for-64-bit-devices)...

**Comment by Mape6** [comment]
How did you get the error message?
It seems that I have the same problem on my Pixel 4a with Android 11. The game crashes immediately after pressing the icon. The problem exist with version 3.14.7 and 3.4.18.

**Comment by SomeTroglodyte** [comment]
MatLog, my random choice of logcat viewer. You could probably also hook up Android Studio to the hardware and use its logcat viewer...

I have also checked the build scripts and tried building an APK from source and inspecting it - yes all libgdx.so variants are there. The folder name is different from the shorter ones in the logcat message, but that isn't necessarily significant. Next - inspect the specific apk from the tablet itself, when coffee is ready.

**Comment by SomeTroglodyte** [comment]
Hey [look here](https://github.com/trolley813/OpenFool/issues/45) - seems I can guess that I will find the other apk to be indeed defective...

**Comment by Mape6** [comment]
So the Fdroid builder is the troublemaker?

**Comment by SomeTroglodyte** [comment]
Seems so - the apk I pulled from /data/app left there by F-Droid does not have ***any*** lib folder at all... So how has shattered done it, that's libGdx too - well maybe in 092 he isn't using libGdx 1.9.x yet...

**Comment by SomeTroglodyte** [comment]
No, he *[is](https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/android/build.gradle)* using 64.bit libGdx, and for months now...

**Comment by yairm210** [comment]
Considering the versions, this is NOT a problem with the LibGDX version bump (that was way back in 3.14.3) 
It probably has to do with the Gradle upgrade in 3a22a11

Several things happened there:
- Upgrade Gradle version
- Bump compileSdkVersion and tarhetSdkVersion
- Upgrade androidx.core and androidx.work versions
None of these should have had any breaking changes though

**Comment by yairm210** [comment]
I have a sneaking suspicion that F-droid isn't 100% compatible with the new gradle version (4.2.0) but I can't find anything of substance on the matter

**Comment by SomeTroglodyte** [comment]
I just went mad and made an [issue](https://gitlab.com/fdroid/fdroidserver/-/issues/905) over there...

**Comment by yairm210** [comment]
For 3.14.9 I'm going to roll back the gradle version from 6.7.1 to 6.5 (which it was before 3.14.7) to 'black box' this and we'll see if that works.

**Comment by yairm210** [comment]
OKAY so the reason for this whole change in the first place is because the newer gradle plugin doesn't SUPPORT 6.5 and the minimum version is 6.7.1.
So basically that was a whole lot of work for basically nothing.

**Comment by linsui** [comment]
3.14.9 still craches on start.

**Comment by yairm210** [comment]
Nothing has changed, so the problem still exists

**Comment by SeSeLnx** [comment]
Same problem in my OP7Tpro :

FATAL EXCEPTION: main
Process: com.unciv.app, PID: 10695
java.lang.ExceptionInInitializerError
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1273)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3515)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3775)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2246)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8010)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'gdx' for target: Linux, 32-bit
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:126)
	at com.badlogic.gdx.utils.GdxNativesLoader.load(GdxNativesLoader.java:31)
	at com.badlogic.gdx.backends.android.AndroidApplication.<clinit>(AndroidApplication.java:44)
	... 16 more
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libgdx.so" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
	at java.lang.System.loadLibrary(System.java:1664)
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:120)
	... 18 more

**Comment by Maxwelldoug** [comment]
Sorry for the dupe. Same issue over here, is there any easy workaround?

**Comment by Maxwelldoug** [comment]
The crash started on v3.13.7, 3.14.6-patch2 works flawlessly.

**Comment by Maxwelldoug** [comment]
If I might make a suggestion, redefine the android build tools line from the fix github issues pull and revernt the android build tools cradle version to 4.1.3

**Comment by Maxwelldoug** [comment]
Or, give me a few hours and I'll try it myself if I can even get gradle to build at all

**Comment by Maxwelldoug** [comment]
nope, can't get gradle to build at all, much less after reverting the possibly offending changes. sorry I can't help.

**Comment by SomeTroglodyte** [comment]
> Nothing has changed, so the problem still exists
Sorry, for me something _did_ change - you expressed insight into possible causes and so I'm satisfied :grin: ...

Gradle is a really strange beast. I can run desktop using Gradle 7.0.2 and Gradle Plugin 7.0.0-alpha15 - after a few tweaks such as running under OpenJDK 14 and commenting out a pro-thingy line, but 'build APK' is silently ignored (And it can't sync either because it doesn't like that release versions of Android Studio have 5-part version numbers). Gradle 6.9 / Plugin 4.2.1 works and the APK it builds has the same libraries... So I can't repro what F-Droid does. Sigh. And why does the GPlay apk include only one architecture of libgdx but includes box2d and freetype which my local builds don't? Mysterious ways....

**Comment by SomeTroglodyte** [comment]
Any progress on this?

**Comment by yairm210** [comment]
Nope

**Comment by SomeTroglodyte** [comment]
There's some activity on [gitlab/fdroid](https://gitlab.com/fdroid/fdroiddata/-/issues/2385#note_594038193)... Maybe test again... !&%"$%&!  Timestamp and displayed version unchanged but it works?!?! And looking inside...
![image](https://user-images.githubusercontent.com/63000004/121241085-51099280-c89b-11eb-94e8-53d8fb43c912.png)
... all there. Now that makes me really curious.

**Comment by Maxwelldoug** [comment]
So they've marked it off as our problem then.

**Comment by linsui** [comment]
The gradle wrapper should be unrelated. The fdroidserver will remove those gradle wrappers on build time.

**Comment by relan** [comment]
Steps to reproduce (I was playing with 3.14.8):

```sh
$ cd android
$ rm -fR libs/*  # That's important!
$ gradle assembleRelease
$ unzip -l build/outputs/apk/release/Unciv-release-unsigned.apk lib/*/libgdx.so
Archive:  build/outputs/apk/release/Unciv-release-unsigned.apk
  Length      Date    Time    Name
---------  ---------- -----   ----
---------                     -------
        0                     0 files
$ gradle assembleRelease  # Run again
$ unzip -l build/outputs/apk/release/Unciv-release-unsigned.apk lib/*/libgdx.so
Archive:  build/outputs/apk/release/Unciv-release-unsigned.apk
  Length      Date    Time    Name
---------  ---------- -----   ----
   186280  1981-01-01 01:01   lib/arm64-v8a/libgdx.so
   177768  1981-01-01 01:01   lib/armeabi-v7a/libgdx.so
   177704  1981-01-01 01:01   lib/x86/libgdx.so
   194736  1981-01-01 01:01   lib/x86_64/libgdx.so
---------                     -------
   736488                     4 files
```

Looks like `copyAndroidNatives` task doesn't work as expected. @yairm210, I guess you didn't notice that because you compile incrementally, while F-Droid builds from scratch.

**Comment by SomeTroglodyte** [comment]
@relan  good hint, you're a hero. 

So, (unbeliavable) the [gradle upgrade](https://github.com/yairm210/Unciv/commit/3a22a1127e9c45ad3a02104bad79d4ed85be5614#diff-29975cf604616657790eec0ca6230bffea93b3d887470f8c0e2097b61db8d479) did this.... Indeed, just going to plugin 4.1.3 with gradle 6.5 (rest of codebase left current) produces a lib-sporting apk directly after `rm -Rf libs`, while plugin 4.2.0 (or 4.2.1) with gradle 6.7.1 omits the libs.

**Comment by Maxwelldoug** [comment]
In other words, either make f-droid use the old gradle and plugin, or, fix copyAndroidNatives. I have no idea on the feasibility of either.

**Comment by SomeTroglodyte** [comment]
Still poking at it. Gradle 6.9 or 7.02, with or without upgraded wrapper jar's changes nothing. Now to try and get copyAndroidNatives to run earlier...
"make f-droid" -> they use the version specified in our build scripts, no special "making them", I think.

**Comment by SomeTroglodyte** [comment]
Maybe I got it (`whenTaskAdded ... "assemble" in name`). Now to downgrade to 6.7.1 and test again...

**Comment by relan** [comment]
> In other words, either make f-droid use the old gradle and plugin, or, fix copyAndroidNatives. I have no idea on the feasibility of either.

We can force libraries copying before assembling in the F-Droid recipe:

     preassemble: copyAndroidNatives

**Comment by SomeTroglodyte** [comment]
You mean 
```kotlin
tasks.whenTaskAdded {
    if ("package" in name || "assemble" in name) {
        dependsOn("copyAndroidNatives")
    }
}
```
isn't a good approach?

With this and everything else reverted to current master, I do get lib-equipped apk's, as the task simply runs earlier.

**Comment by yairm210** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9153
They've merged the change, now we just need to wait for the F-droid autobuild to happen and we'll see if it worked!

**Comment by linsui** [comment]
According to my test it works. 👌 You can also test the apk from the CI.

**Comment by SomeTroglodyte** [comment]
[(not yet...)](https://f-droid.org/wiki/page/com.unciv.app/lastbuild_566)

**Comment by yairm210** [comment]
https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.unciv.app.yml
https://f-droid.org/wiki/page/com.unciv.app/lastbuild_576

![image](https://user-images.githubusercontent.com/8366208/121788923-36f0ec80-cbda-11eb-89e2-a5257bbf82f1.png)

**Comment by SomeTroglodyte** [comment]
![image](https://user-images.githubusercontent.com/63000004/121801982-718a7180-cc3a-11eb-83d1-41b8e0a94db9.png)
