### ISSUE TITLE
Unciv does not run under 32-bit linux because libgdx.so is missing

### ISSUE THREAD

**Issue by fedorov-ao** [yairm210/Unciv#4313]
**Describe the bug**
Unciv releases starting from [3.14.3](https://github.com/yairm210/Unciv/releases/tag/3.14.3) and up to [3.15.1-patch1](https://github.com/yairm210/Unciv/releases/tag/3.15.5-patch1) do not run under 32-bit linux (tested under Lubuntu 18.04), because `libgdx.so` library for this platform is not present in `Unciv.jar`. Opening `Unciv.jar` as zip file shows that versions of `libgdx` for other platforms are present in the root of the `Unciv.jar`, while `libgdx.so` for 32-bit linux is not. Last working release is [3.14.2](https://github.com/yairm210/Unciv/releases/tag/3.14.2), where `libgdx.so` is included in `Unciv.jar`.

**To Reproduce**
1. Run Unciv (i.e. [3.15.1-patch1](https://github.com/yairm210/Unciv/releases/tag/3.15.5-patch1)) from shell: `java -jar Unciv.jar`
2. Unciv does not start and the following output is printed:
```
Packing textures - 15ms
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'libgdx.so' for target: Linux, 32-bit
        at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:126)
        at com.badlogic.gdx.utils.GdxNativesLoader.load(GdxNativesLoader.java:31)
        at com.badlogic.gdx.backends.lwjgl.LwjglNativesLoader.load(LwjglNativesLoader.java:46)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:83)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:71)
        at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:67)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Unable to read file for extraction: libgdx.so
        at com.badlogic.gdx.utils.SharedLibraryLoader.readFile(SharedLibraryLoader.java:134)
        at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:290)
        at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:122)
        ... 5 more
```
**Expected behavior**
Unciv should start normally.

**Proposed solution**
Add `libgdx.so` (i.e. from [3.14.2](https://github.com/yairm210/Unciv/releases/tag/3.14.2)) to the root of `Unciv.jar`. After this the game runs normally.

**Comment by yairm210** [comment]
https://libgdx.com/news/2021/04/gdx-1-10

The latest version of the LibGDX framework no longer supports 32-bit Linux, and therefore neither does Unciv. As you can see, we have therefore also stopped providing a Linux32 zip in releases
