### ISSUE TITLE
NextTurn bug

### ISSUE THREAD

**Issue by WhitePr** [yairm210/Unciv#4873]
**Platform**
OS: Arch Linux x86_64
Kernel: 5.13.10-arch1-1

**Version**
The version compiled from this submission ‘df31fb2f0527be8481a146f933918847ebe782ea’

**Describe the bug**

NextTurn error

**To Reproduce**

Click 'Next Turn'

**Additional context**

This is the error message from the terminal:
Exception in thread "NextTurn" java.lang.NullPointerException
	at com.unciv.logic.city.CityInfoReligionManager.removeUnknownPantheons(CityReligion.kt:174)
	at com.unciv.logic.city.CityInfoConquestFunctions.moveToCiv(CityInfoConquestFunctions.kt:219)
	at com.unciv.logic.city.CityInfo.moveToCiv(CityInfo.kt:530)
	at com.unciv.logic.city.CityInfoConquestFunctions.puppetCity(CityInfoConquestFunctions.kt:47)
	at com.unciv.logic.city.CityInfo.puppetCity(CityInfo.kt:525)
	at com.unciv.logic.battle.Battle.conquerCity(Battle.kt:430)
	at com.unciv.logic.battle.Battle.attack(Battle.kt:84)
	at com.unciv.logic.battle.Battle.moveAndAttack(Battle.kt:44)
	at com.unciv.logic.automation.BattleHelper.tryAttackNearbyEnemy(BattleHelper.kt:28)
	at com.unciv.logic.automation.UnitAutomation.automateUnitMoves(UnitAutomation.kt:141)
	at com.unciv.logic.automation.NextTurnAutomation.automateUnits(NextTurnAutomation.kt:524)
	at com.unciv.logic.automation.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:53)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:130)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt:592)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt:56)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

**Comment by WhitePr** [comment]
This is the game archive file:
[test.txt](https://github.com/yairm210/Unciv/files/6991742/test.txt)

**Comment by WhitePr** [comment]
Java version:
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)

**Comment by xlenstra** [comment]
I'll look into this later today since based on the stack trace it seems to be a result of me implementating religious pressure

**Comment by WhitePr** [comment]
The last bug seems to have been fixed, but this time a new NextTurn bug appeared in the same place

The version compiled from this submission ‘8d49a84f78f1203d3fa9ff47625c41c90963737a’

This is the error code from the terminal:
Exception in thread "NextTurn" java.lang.ArithmeticException: / by zero
        at com.unciv.logic.city.CityInfoReligionManager.updateNumberOfFollowers(CityReligion.kt:131)
        at com.unciv.logic.city.CityInfoReligionManager.updatePressureOnPopulationChange(CityReligion.kt:92)
        at com.unciv.logic.city.PopulationManager.addPopulation$core(PopulationManager.kt:91)
        at com.unciv.logic.city.CityInfo.endTurn(CityInfo.kt:477)
        at com.unciv.logic.civilization.CivilizationInfo.endTurn(CivilizationInfo.kt:606)
        at com.unciv.logic.GameInfo$nextTurn$1.invoke(GameInfo.kt:106)
        at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:144)
        at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt:592)
        at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt:56)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Thread Autosave still running in UncivGame.dispose().

This is the game archive file:
[test.txt](https://github.com/yairm210/Unciv/files/6993757/test.txt)
