### ISSUE TITLE
New NextTurn Bug

### ISSUE THREAD

**Issue by WhitePr** [yairm210/Unciv#4880]
The bug from #4873 seems to have been fixed, but a new bug appeared in the same place

The version compiled from this submission ‘8d49a84f78f1203d3fa9ff47625c41c90963737a’

This is the error code from the terminal:
Exception in thread "NextTurn" java.lang.ArithmeticException: / by zero
at com.unciv.logic.city.CityInfoReligionManager.updateNumberOfFollowers(CityReligion.kt:131)
at com.unciv.logic.city.CityInfoReligionManager.updatePressureOnPopulationChange(CityReligion.kt:92)
at com.unciv.logic.city.PopulationManager.addPopulation$core(PopulationManager.kt:91)
at com.unciv.logic.city.CityInfo.endTurn(CityInfo.kt:477)
at com.unciv.logic.civilization.CivilizationInfo.endTurn(CivilizationInfo.kt:606)
at com.unciv.logic.GameInfo$nextTurn$1.invoke(GameInfo.kt:106)
at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:144)
at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt:592)
at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt:56)
at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Thread Autosave still running in UncivGame.dispose().

This is the game archive file:
[test.txt](https://github.com/yairm210/Unciv/files/6993789/test.txt)

**Comment by SomeTroglodyte** [comment]
Yup, you razed a city "to the ground" in that turn. Got that already. Fix method not decided upon though.
