### ISSUE TITLE
Exception in thread "NextTurn" java.lang.Exception: I can't go there!

### ISSUE THREAD

**Issue by SimonCeder** [yairm210/Unciv#5123]
**Platform**
Linux 64 bit

**Version**
Git version 69e2828a0edbb29ae628bc62326efbfa0e2f4a38

**Describe the bug**
On some turns this exception is generated. From the trace it seems to be related to units attempting to go into a forbidden tile (mountain? outside map?), I'm not really familiar enough with the pathfinding code to pinpoint it.

**To Reproduce**
1. Load save
2. End turn
3. Exception thrown

```
Exception in thread "NextTurn" java.lang.Exception: I can't go there!
	at com.unciv.logic.map.MapUnit.putInTile(MapUnit.kt:781)
	at com.unciv.logic.map.UnitMovementAlgorithms.moveToTile(UnitMovementAlgorithms.kt:431)
	at com.unciv.logic.map.UnitMovementAlgorithms.moveToTile$default(UnitMovementAlgorithms.kt:375)
	at com.unciv.logic.map.UnitMovementAlgorithms.headTowards(UnitMovementAlgorithms.kt:263)
	at com.unciv.logic.automation.UnitAutomation.headTowardsEnemyCity(UnitAutomation.kt:385)
	at com.unciv.logic.automation.UnitAutomation.tryHeadTowardsEnemyCity(UnitAutomation.kt:346)
	at com.unciv.logic.automation.UnitAutomation.automateUnitMoves(UnitAutomation.kt:168)
	at com.unciv.logic.automation.NextTurnAutomation.automateUnits(NextTurnAutomation.kt:636)
	at com.unciv.logic.automation.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:60)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:139)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt:606)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt:598)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

<details><summary>Saved game</summary>

```
H4sIAAAAAAAAAM1dW3PbuJL+K6p52d0q0iXeRFJvHs/ksptsvLGncrZSfqBFyOYZidRSlBOPy/99wRu6CTQo0Ioz5+SUhybBRqMBNL4P3aCfVtlDtsn+SqqsyPfLr0/89/9Otmz5a1LeJmWW5HurYqv75VP9c/+Z7VlSru5Zuvx6fldmq8OmOpTs5tnaFZtslbH98unZ+r8D21cfkzy5Y2X9e8k22R2Xj27dFZuU5ed39Qv7qihZ+i7Z7bKc7fdLz1vwAiVLqktW7DasLv+QrXipRyz0kOV79Dv7vtvUcq6zDasb8n25sB6X/rPFr3x+tWiuPH4VNVeuuOeIqwjuzfll2FyG/MqZN5fB4GbQXC2ExPoqFrW0V7F4YyHeCAZvdKJ9UdCDm6646QxqBm1D0DYSwqHqCB7H4u1QyI6EbFSwqzsSd2PxdjA0RSA0h+aAarF4GosKQbNAXHUCQ9FbgRDjw+PFwD5gikjUF4ir7pWmNQtREupePN9Y98n+9wdWfvqWs/RTyYdnnmwukl1WJZvlOtnsGS+92ySPrLx+3LHlu8M2yZtRu3Qc1+pnyfU9m707iDmy5zMgX7FP6w/JvoquD2U9pQKr/rew2v8GN5Yykz5meZbfWbWwL/eMbazz+kH5aJ3n2TbZ8Br2t0me1jfQnGvlXBe9pOXXX8si/4vLKMo/ubyuwPv8siz4bOIT62lYYOn6z3jitvPwohVfWy9Ji13F0su+xNd3RV6U1pekLLOinF0UKdciP2xvuR3X51Jh92Q/4Ea+5AeaX96ynJXJ5rLI8mrf9PVx55Bm3Dlsk9Xj8uljkfNKs2T5VFTcyBddT/a3+6JVtrqqkuqwX16yZMXQ7Y9Fmq0zVnKN/5cbfv9p3ZRYOh635ueCyxpKrm+dINU9C2qL1/qxkrfGds4CXhG38yO3ktIOcf+EKudc/psy4SNZEt7efLnkuFH9apdkuSS5uXeK7Yc2cuuKnq2cC+FD5UuRp/U7Xz8Wh7yavTn8M7vhU7hqxvTTplg1q9+Sewe79oXes5WlS/82XqRrP7J9P2K2v3ACOwkdZq8iN1x7LFx56S2vgOt+XmWbTfJvez4hDmVlrXklKZ9evGngH/qhv3za1VORTzDehPpp/2BWrGf89w/sjuWpGy6fVpuEz4F/Jg/J2SbJ787e5xV/VloPyebAlt58/txM3t1h02mPrnkLePMeL/iSXpWHVbu2P90esk31K/9Ra9dYg89dllfWZbLhRryxMuEqpDffFeWezVqvxP2fdc22fD7WKp+XFdtm+3rwW6tDWXJx+N33+z/2rLxi1ZLfYdYKPfqfA+Pt+IpFW4NflEpumkWeI5KmuZ0bvGqcxtLlbqASK3/fjfVlvexwX/TUry7NMxcu/eYZKuzBs3ZJsZsVma8Z37jfBIAxEOgPS2Z7eU2p2//cj7qL2o9xrR0CtTQybFdCK75QrL6yPbFwI227u55oH0AcG73VgI72bn1pO+KuL0EbpIkNUm0Q64FwkI0E2j7U4zR27tQB/W3UAE8CYRSMAkgUQDsCqBahp2CAKGxU1oGGDMFZ/ztAK4BbAWoQiAaU1eOgXrwv9HXElS90BIDjoh5CFu71deA+jFyAbAsYAwswJwJqnZwIBmnUS+/aI+pCHYdEomGHxgIaVzDYevP0TRVV+tDfaOqhS8DkNuocR4KQAP0CoZgrui6QcCSAwhD6PJSGgg3N6w3mivdsqAaVxSJ6yTC7UA/CfHTAcGicwgiB+QBjLRSKLaBfXOgXcBE28j4wwmwYdrbq3jyheN/V0BlQnyuuIjTGXDAqgPMYnMtc6NARHrCgC3YFKchQNnK5gTBK2L0FKsLkhO4BAuQK04VQX1d3T5BQP8EARgMcDYx+EINR/cGsjoT6vZ3F+IvQlHOFwwBbAT2BcY2aOXACMIngqht70DQbSJmN9HbgEigxGoo2GhYwr7A/6ozU1AdOCCuILtvJ3zdeWEMmgjDEgUsD34Vhg8ZmZxzofxhGUE8/k0Nog48GF1SICthDYfERjtis59ZTxwh9wQgFjxhhhAur/XeUEQ75GtDCURYok0aCB8pFlk4wwgQ9DRHUcz/ndO4Xei/YA0I078cTMc+6uk+4kr/nbFuPHxMOluVrjtZrImUv+Jjs6YBUXrCE07jnq1A2x3klxjaXzTlO16oySdln1gyrGiiX7WXHs8DiTbnlE9c04wNz3cjpuNSq2J4dcj5RzzbFXbY6a4qeXdc/m5Itm2vUm13XQ+/Rquq9n+465bo17KrxLlNEvj1sUivZ1q3hPRVwz8KJ4uspd/P8rKG3Habi7Da+jVInTUPOacOV7TPPtZNVGttRmMzTNApW63DVVvlfSZn8WZSH7YDYCjf3k4ktV6JIO84XG7Hco+T2alUcqqVXE1iVnjYPx4inE2HiCaAVllZYODHGAFQIS2cLz2SeiUsMuZ13ItMUpPCxh3+IUQ6rshGuRdC/A24IpLTiDGjecAfdB/SIgCaALaSUHUmmwIzZxspiCtqUiREadAS6QISjwRWPPbywhwwScT/7hbyy51Pw2jiBQmQLAGBrlGdgmjRtGiVdqBhJMNu7EbIMthIQF2zdUUqLWSWuGHfJkNBhktdWECIVWqvaCk8TDxGRU6khEEJvcNWrBndp+kSxLpkCwoySuRXeLcHmwWZboHYDp8PmxlZUWedQV7AnnjKYnSFKRvMwG+hY3xGYmoH+QMpsXBjzCcEckDKgLNpVUuiWjYgNomYuHq2irahlSHuVUoFXBu5it1s5uE9GiRNS8XQOhXTDu4suTBigMDZmNs6wqfg2NgawTtS8YArj8eeC8SDs9QqUZ1oEjOOlmkFQsa/+Ub1VPBL1clWyU4OwrMYEr0p4guh4sMt/tVgXgum/MY7QuG5fkvJT/seej57ozOWjR+IyOoK13iR3HGJxrJsW3/JWHG9i2sJ+z0Li61lCqiDHuyxVp/jMIZR6PYI1b0JXf0tUbNyiA+PUs/y4RV2NRb1QsegzTST6ZamOk61DJwkCx04Zc20/mcf2bRC4/NdolQTJyll4acsk6k2DzWFzGBAJ8B5/I5MIfwyTqJ1WEyAjqUT7dJRLOJhLeMMFCm/sKful0oYlfg1tCKMlZ0HQDLUMqvAkpgGaDUNUohIUUgIlEJSX2AAyAERBZAqBaAdwDTLDB+JMZO4NIHuB9wWsQaEmW2YKkPETDmvtNoLbn+J3fbxICpCAdBsiZhiSoI6DzU/YHUcZRwD4wM4eKIpSasQVoKBYKCen9ajRGRyNkfJyKEQOG8OoN2wQrkZiYktN50KgGuAwDDMF4EvhGQV3A16HqAxEatCcgYBJZGG+q4RLAEFTKH2YEzaA6yhsgqA3ir5QoZE2vQuURcljMHahL8GwEOpE0UQlbAIQ2B9IBJaPKBGE6ORgCUpRa59AN6GtfOQMkIeTSQREZ8jwg6h9mHIWwEzsjAmVKXEDhLPl3DPoePBSELgAQ3sTkHcEoYYOdxig7u6fHnX3kYXLoqp+RuKZNwLBYyLewNf8ZJPtt5YBFnet/X1x2KSfdixvbj5eZqt6XW5TUNpaxLJ+nqbcDk/z9PZ2Pl8wex2t1rYfpYEdpavYZpHH1uEqXqTuatknzDyfjvb9uUFqW3wc7nMEVF3cF3uWf2bfkjLltvrlF4uDp4fsoSj3s39P0nQ/A9wzq4pZMqvBzn/c/KS0OOc10uKivyMn7tXYxSvmxcnZg11mHJ391u+UcFhvMiG6mERSZvsBpu8c098I6KMfnAB3xapqw80Xcmu2ID8K6HhBW3AM5XvBIFUN7U61u4A4YwtvOXf7aHjTaSGXWaBrnLWA5eONILy7GhCUYKCRvN3VvHEKK7CGO8Vqo6TLsXCALgig5scBV0CvSPlxtkIh7GZFtyE9rDNKBFUBy2gTDyDFveu6GCTI8QR9NGIQZZBz0GyZaeAupk4KtPqGuEkRUnkhVIZklQgpH+EXAU51lAhhQzW2oIkLIMKCYwttmQhbCLCzmu9GUZS2qR1deUYBFFQN0gRJQ/EOHD3xodGtNXQzSU5RIyIWNIkBEgTEqO0YOaOtbVy/vTtHRoxlHyJnc0GsAdQOhmpjVwNTRU1iwwEHHIgAUj/KrBA/A57UZejNka6AnnEWGo4c6aIaNE3CAQ5/2HKUn2bjyhRWZSPRbXGZOKGIgCvriL2oEsxAKwKKYihrA2RryklkrW7gqmSGhYIOONIQD1sRo4EGGa44qxBZEyYO3OwCnTj+jaMuSCaKpuLhHQu9Y9RuMi2sd3kgU03wQiskDo6E0EAghEDVWsPLB47at4BGvozMua4j2FyL9I6eIwpGQignsriWCxLsrX2wdMN/tSSxGoQdZVHOv8wBoflrMKHwZUxoPKjgD4IK/k+Ms3ivF2dpZb/kVFDvRTgvCtbhLVsnsZ0GfmD7TpjaUZw4tr9exLfhOr71+2NBH5O0zNIBMWrn+I/mRe4oL3IxL3IWPybS8ZZ3RVJyF0lnTXWPzfOmcKZu6/sxxsOp+wOQIOGZ74NE6x4fEqyGqOH0TCqEdJQzM8rRHcwbBjQOMYcBKxrIxbBP5RYKzcOiVYaIOYWWHejQP84NUpgAfZIEohkKBkfZUBi96xKJEBdAyB5RD5S/5GDdWyjuoKYRUB4jbITBB2gbl0d4H2NwBIvpDCPMrpHdlJMeeNQiuIwKY4wPlQPikQ9N2DQ8RqlASt4QLtYaogetUCEekco2vwIDEajESTR4ItOZQEgUynTDJw9Qgkura99s1HqMSzGGpE8G0Ek1sdTzyuk8CG9if4ayHfFGA85gRBscdG6kmnOJcxKlTQQpiPkdZyqK/MX+BmwCtI3qDID0kln7oLtHj6+hE2SarEckAri9dlNAd7AMvYXd1eihMMHgcRxIzSjE/EI6C9ZXgzYTpATCwUPs4LG/w/2JooBK1iH2A5icDCg0hLeJzD4NH9ayYJrvSll9jkXRX+qQlcwRpVw7JbxHZ9WhtDvMWTGrVfdUCW6NuLPmgBPO38NEFTPFwbYrIp70MSTMQXtmOSEk6AkS2VCJkzikFBCcSCE75klwyO7JOImMiMhfxslj9fiqNDJ2Tztr9IqflPghbM4dsDn3Z7K51+Jy0evEy8KzYNqxJJIvdnvQNVt0GHPWfmw7XuLafhTN7ST1UjuNHWeVxvPVer5u2WKbO4m4YnPjJ1PFHxw16z4UU6/0VD5c+3Q0VIY5IuzsA4KNBldylj/gYQjYDL895BPsUJZ0coxLxm8ogKVjeBo8OEyTA1Q1OMMjBb8mHsZBoS0p+gbrsPxNhuExGXQeRv0mgwQ45XM0sH4i6GrycYZ+cAzwgoIwB+wU5dcjgAo75MpBGfroC+acx07cyId0ADqJhqqxLUjeo0NoKKVPJO2paXow7ocf2oJdCzLnDuHeYQAL3VGy+lCYSopzybl6GChT3zygz7/QwSjNaRrEv4ENA+6mg1To8wiDQz1IHSS390L4XA/1SThsE+i7LjET5OvTAPGBGorQ01l9KCtwmOBXP0bdoAtQmZ3BoZLuqOw/2AvQfeFAPY5DfOsATSolKxC3oBf2sgM3ohLl1I100mbszA2EqoYJgBBiN4oZ3TRr4cdkt3zaJrvLpOSwoWogDP/1KvuLQ6w6Oe5QfxPN+pal1f3S9ax7lt3dV0snaGHGdZY/Plt71uwFe/M48IJF6Hg+B+zbHStrpMN+/16VjK/wNTaenwVx879FuxR/yPYVX9hukz27ZmVZA7AGDvEL3ppttuH6lo9/5FnFgRlvStkhsqby5jCttSuLbdEhBHT99f1dztfOWdWKna2KfXXTYJV9Nvg8V917uP7LDf9Zf4Gv+fUNa9pQh5+yzYaDiycsoOtx4nX+SnEoOQT8cs8lWNmWq/ZQW6FavknKraZxAiI37esQTf8hrI+9ANdKGuCzfFOUVbZ+nLkDIwwaqbbvbckRHcdyqaaJoPpbTnJmn0o2aLTS4GPyZJNp3paKTdVafr2fyS/t2W6em6lK1HVkFA87evCdMrm3/b63rzaM7bTD/XzFX+T0cfb+psnHqz/DmuT6Ot/WKHPWxTb1Q0ytVJpDjmooczvr+kgqdLwMOGJNJygdNm18WXyqsdqBSKPErD5D+/znIb/bMGokTnFRA19zwfnXbMWvWEnOEFKwXLJf/17ehm4xP3lCe1p7UwNebJi03rRJtCRG+sjgdqfrjdwn2+5xZ6Dtq49Zzqyq3kO7Lt6j7vJJ12Joeqn6q3s+c4lJomuPPDHJWqVCx8sAfTF2pbqy02am8egm5tdIlZrxbeYHdOaiVghp8GqhwMjo9X6UmxO0iBbFoeavRVUV28/ZQ3cugpj/Urd+SP5ktKcx8faCMxjb0xRacbi24VA3ivsV8Jctf3hdzDzL+2Vg7X9ctik4WK+Ov2CtfmN7VlaGXs4jmtUKICzqG64+WlNNnlG+QR86RHUvG3aOWiPphaY0TsYfWkWFH71I6hT8wap6mexrkZSjm+KrKctpVxvNqm6VRZJ2u9Kf+SXlBqc5VHLl/SE+mfIikwxEODSZbr1/KMpH6b1pg1GpVfe6XMuItyW9lzPBT4CP/cDW1cDP/h30Qm73CURLbD1OAlloybm7r7Trjq/OqEnu2CemNOmORfj3R8P0bsvrJHQigsemwzggTTbc0iBXLnNNKXN72qonUARSAOEVDc0hNuZGnU7O+25PrQfki5pJ20ToXor2TDtYr5KylE1cVY9vObyEgdkECDCnYI3n05GwbhWneJir6SKIkP+YDUiK1OpZihFzg5TRsRFLkUObQOljXsJ0KddwCmK9JJtuOlFHypnzq5GRGExmU2ggnm8O2yw/bMllw1wqbcpA7bdJfjMgBoxOwJtNUaSzXdNRNxTzG0Eqss7mC+uUNRwN8mzzQC6oJgRLxJOPz80+3QuXvD7kaZmALr8xRZMuhqW+RWqyMJkqqsTjYAF0/JRtSOQgiaRYnz+pZj31JVtpOg88VQm6a12iKi1QMJLomEp0Rgwl01pS3hgMU0T3WwLDnKMlZBxR6/4UFEvZYSIIHG6YUvzVEIho1hli32J05TRh4AhF1NE8o63csT1wanU13gYbWbKPBFCP7oL5R0KN/7hcxsQyefKKZo8ttrIbNZmfhn5lZPNioWp0bJGlEDG2/kvg8GKaeamYwHQ4HBC2oPEC1FQVubzmizyaF2x7TAYYC/PpJrKjXoqgFkYblSgF7mjJhepHO0RhOoMWWlcul+wz1EkgQnmQLtnWzIUE8XEXgm98vbovVn/O3kOG9iU8dKTp0J1RPw6hFmNtlA1vJDHQSoRJ8OZQUhCNfmsKbzJqiq9WNRLfDU902Z6utkkLtayGFpUZNcwxleioEi8K7g9lRHZclplmFFyUKXq7d0E1acJiRoZFT95PJPbPpihBBbmOBjqoQWsQvCkSmdNQe7rkm3yJUWJpxIayNmREzPwJ+9wjwMgEGY7iBMo7OseG//fjM+S7MkNIMdORlLpeTQqeiI75mJS3SseEJ26fhETHjuuji+W9HO2E6rg0TBMhk/y+w1neF4hEm10UBEb73C9AwKEOa1E5lmqLjruMPzi6yZSdulAHyMhaDPcsQ9MdoJBYL+iS/VFFahJSWA79XfamS34tDxXTozk3mkwIu+8EYYWu8uKbYvBB/wm1ZixfJdtd85lMyiiapspWNigmTrweK7g41qCLYrdTF6yAEE/2YWCor68VOLrt6Kvipy9DHlH3iyCjTgYJDg2s4hoazyHkaaHaUYEmuhnpRSFWrf5UOUQ+sv09hf6027RjoMkmdkIpvagoMKk/EeulylFpXqNZFf5xmVRE4WVAzBvtgEuWlBsSl7mG3sigHAWGaGCmoq5PK5bICJcao6NjSh74pFAd4iNXL4PWRCPbnoaoLTLsiGgisiLrOU4Z3pdFfgzBREbQZ4QzRRNmU3TyDlRE+AJywYt0MGhaVSb4KFLd5nDtJvctI1Ov3H8c4tiE6L6HeFReZCgvMpQXGsoLDeUtCHk6yGQiLzCUF2jkjXsq31C6b6itZyjPM5Tn6uThmF+yUTaFXFU+1aniD+SNyFdDwI6JcJNRZaQjBcu0bTEoR+0pmpjUJvYYKflU0Fo7VhbH5VGZelrwHxyXRyUxGMwUIkmCkk7FTbR+wjNzO/KaTPY+sWWjc4synCDlEQCFdNsGogy9PwVyEAIvk1tybTFR0gw4iq9wmcgz6eNYNxjUVfy8KlSkFJuhd/EduGMFYzOGIb7XN22KxOp8HgKJGtCRVZnAlPgouyPJhfhq48S9idiQNMeEd6bZafN5vPojAUcdfvM3hAwKduPfoGRsKjEylRiZSgxNJYamEhdaieq0er9SQjUL03oCU80DU4m+qUTfVKJnKtEzleiaSnRNJTrGA99IopEwM9Uo9KdtgkE5akdOa2SDclQUWjsMDMpRqYvagWpQjjrhoZ1KBuWoXBCtCzAoRwVstE7KoBy1QaJ1o4Y4wgiMEfCIXjlMxrLxEmQkzLAJ/V9lNJRoULL/+2+GEg1K9h/0MZRoULL/WpShRIOS/TegDCAlsfbBl5WP4ZX+b3ca4hqDkk1BIx47J9zoFNjcCDBy6/1nttWSN9a+Ssoqy+8+dJ8d5LXxiu6SLcMfBkqz9br5Wufj8uI+Y+smtXi3SR6b7xg+rZo/HFd/bFCc+2kfXj/u2PLdYdsoNfg/ZHnV25b1OVbe0LlQ5/cyWZ7n9ZdHqxmrUXKTnFhHIbsI5WUjH+qrNX6fLm/DdJ36nmPfBp5n+67D7CiZO3bgBrEbePF8Ha+f/x9R/NnirJoAAA==
```
</details>

**Comment by xlenstra** [comment]
Found the problem, was introduced by me so I'll suppose I'll fix it too
