### ISSUE TITLE
Well. there is a bug in current, not yet released code.

### ISSUE THREAD

**Issue by ravignir** [yairm210/Unciv#5137]
Exception in thread "NextTurn" java.lang.Exception: I can't go there!
        at com.unciv.logic.map.MapUnit.putInTile(MapUnit.kt:781)
        at com.unciv.logic.map.UnitMovementAlgorithms.moveToTile(UnitMovementAlgorithms.kt:431)
        at com.unciv.logic.map.UnitMovementAlgorithms.moveToTile$default(UnitMovementAlgorithms.kt:375)
        at com.unciv.logic.map.UnitMovementAlgorithms.headTowards(UnitMovementAlgorithms.kt:263)
        at com.unciv.logic.automation.UnitAutomation.tryExplore$core(UnitAutomation.kt:34)
        at com.unciv.logic.automation.UnitAutomation.automatedExplore(UnitAutomation.kt:497)
        at com.unciv.logic.map.MapUnit.doAction(MapUnit.kt:518)
        at com.unciv.logic.map.MapUnit.endTurn(MapUnit.kt:646)
        at com.unciv.logic.civilization.CivilizationInfo.endTurn(CivilizationInfo.kt:673)
        at com.unciv.logic.GameInfo.nextTurn$switchTurn(GameInfo.kt:115)
        at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:128)
        at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt:606)
        at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt:598)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

**Comment by ravignir** [comment]
ok, looks like it was already reported.
