### ISSUE TITLE
Game Crash after Clicking Next Turn 

### ISSUE THREAD

**Issue by EclipsePlays** [yairm210/Unciv#5201]
**Platform**

- Android, Xiaomi Redmi 4X

**Version**
- From Google Play, v3.16.13-patch1

**Describe the bug**
- Game crashes immediately after tapping "Next Turn" 

**To Reproduce**
1. Go to 'Quick Start'
2. Click on 'Next Turn'
3. See error

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):

<details><summary>Saved game</summary>

```H4sIAAAAAAAAAOVdbZPbNpL+K779LPoEvlPfHDuJvWWvfbFTqdotf6A1nBlWNJSO0jieuPzfjyIBESS6wQfkbG05t7XlUJpWA2yg3x40gK/b8nO5K//MT+W+Om7+9bX5/I/8rti8qq7KfFV8Oez2dXH1odwV579+2SSrh42Ivq2ax+j8KNrHuP82PT8G/WPcPmb9ty3tun1Meg7tY9j/TPRNaLR+TxD1fP2eIO4f131rQc8s6Am07mithf2j1lrY02qPGoH/7ePqZr+7KqpnN42ovn5b3dRFfnpX7A+74vzxNj/++Lmo3/5RFVdv6/KmrPLd8/xQnvLd5jrfHYtVlZ/u63z32766KupG2j/kdV1WN0X95Hmdn4r646ran8rrcnsZrHx7ftp83e7y43Gz3d89va+aAXy629+U26f60D59ve9+9qz9yWq377lcRvLjt1W5bb97f8pPr86P//0yPxzKqjgeP65OxZfT5m+/FU9u88/Fk6vyuN03L1RcPTF7+l9/a8Rx2OUPRf3h4VBsXt7f5dXqsN+V27KTzv/eF8fTm7zKm1+dP9fFrpHJvtK/ui+ro/b5VGxvN1/P/x5/KY5FXm9vi6vNv57d1OX2ftfIrmhe4HO5Pe3rh/5nzRCpOf2+zO+IKe2JdfP+npwP6lMoP4n2Uyw/+YNPQqfM2g++/iEY0A35RwOO0YBy+Ldw8LtHmGj/6XH45f54JI2LCJpXzNrXFWGvw60c5NeaRWip055aPmr2pWPi99RS0VuGOrnQmPs9id6QzlLvi9Ba0thkf4Fh2t8VxCC1U7s3gl5ysahe1D/GFzPq9R7A6/2C/qgx632IfIx7DnFPm/SPaU+Q9HyjnkPWPX73w/Hhtnjyj+J0W9S7vLo6UoZME6ynichrpSEtUzymkc+azDv6UKPvJrYXjvn42vc6jc5fpw+1tvS+BRpNpP1W74/4/ofwVbWlzF773kkvPuleNKvTSiDuH7OeuDNjnj/8VntMeoK0Z5z1zJL+W41Wbznth0djkX7PA3J6OMc4xbsm0to33Wo+b17VdRsT5bvV5e8N2/19vS02fy/+KHb1w+qijQ81ZRy91ld4UrqiUwwpSRENPsU6YTL4U/dJKlTHMdU5pjrDVOc35D5kMeqH0DkOOyx0wr+AJ/u15ofK10Ski+QiOhWL6TIJBpLUP1zIBgLV4jkxGCD9Q6B/8LWfeMNhVJz1FgL9w3cdIo4V792++XeXl9VF9f6ZV3+Wn3JqTNOLmTwLok9T+2ikjx96uv6pj0T6NDC5fNdHGf13/VPfWh8G9eFMHyWll1/8vzKg5ji+b1LG/LAn7ai4DEFweeqH9KwUweWp/+6sNN2/+nD68kn9JrgMpVgp6mCl/zW6/DX4iw3RT3VZVFe73o+9zKt9SQyAZmp6y9jbRc0s9ULW/uRfJCgfpZj7r2Wu9BeT70AFOgk/293lpwfSAenOVs/1uz90s/nieQKNQFILSaGLVX0ntO+U419p7DoOgc7b18kGDamuDBgNfvvdKsrH1fa+rovq9K6FqyTwedOM3KurzXXo5/F19MmLRZh6YZElXr6OQi/froUfxdvkOuto3+V18+/pjNt9vSqvr9smHzbPb8vi+nQ2emei94ei6dH/3Jfb31fV/oe8bpxYmVfHzam+LyRc1mKwt/tjUT0vP8vOjIG0Ru6D/39Ur3UmaRg8b1+3mYIv9neNmFvA730j2apFD1cvymYmNnOy3DYCOTXT8U1+2Hy9yw/6SxS74nP7yx+/HPZV89PN+mm8aojel38243lblDe3p42frarzHH9TXJX3d6s6b/5z3Pjr1R/l1el2EzaT6Hh+ZxEHIlqncZJG0boZqbtDUZ/RzuLHL6e6uCvOAGPTQJS1/2uM8/GU16fGP7zuccqPbV9fl8dTI6JP+bH4UDTKVlabd2evcmwEYX7ZzKlj2WGkl2n7bZpStMZsiq4zYrVycL/WedUIYfpXUA80xi8eimMjs5b2p6IVWyOOnxpjcjx9RF4baM9TVtto52W5241b+bnOj8czCjHg0XlgdBwQSkFxpBqn+L3Ofy+GgodY9e7JEMXf76ubXQGJvPOG8wfN18b/t9vm98gQgqNHNQdN+Is7mN9Q5y0C7e1+aExxlRMTHJa2jN0uHF/Vjb1bMI+7lwwAcXRxKMZUoEwFxZQyPgaROePBzglO+en5Om5Hvh2n0d06VF79WpWnzVfpbd/sP5/tfuNCOg/yvjiddkW92jfxQS2j0kO9v9t31v8ccY0ljxs2hBAZmsHEfX9bFAdsdkIdDVxUix7HoMtnFhiuYLkb6BDgEJt5Mktb0lzQNbfA2HYppoNtMIjnz/Q+CZ6Y7dQbujkktttjU7CgKXTkYYHDZtMj7SYfqXi6i31b7tBXtswLJKRhtdxNRxGLggw3qThn5VvB2hOiBi5cGDuEi61b6GLdmB4EC4IfBdX2PuT+Jq+xCSZXNCHiDoR0sNYGMfPykdb3l/v6WIzTLpuNjkYx2uinL5qkvT4ZyhKNXe7y0E5n+Tw/W2Ms1IuWm2BwVMT4xQ/llkoCcausc/u5uEPGbeELS5djD5gswTLoIOhg3TL8iDMJxg7i1ed9/YDPdcQTsObQzZ7pSMGbvP60K2bbp2XzG7EhEeorIjS+j1CIoC+DgE0oOqvUkqAhvGY8jreI4B2iYFZauqo93+c7rO+yvoYlnhHSXtbnLBFtt5zmIF6QWC72LY0RjNYI5yRXDgcyX4iLIM0GzBu6OkFQoD41UKx7A5kKiqnxrig/rIPS/S4M84VTGGDxWC75JkgbuHjCMWiGxkHh2DM6ePUQ9Iyw8fdIf0K3TukMjqGDEzseOeTl4Kaqv5umjLv0qIeNy2o8njYf4A9M2elkxOf8G1vm3Az3Ma5zHHmRu4bfKa8frBx/Oxek70GOpixAJYodcKPYQeljh/QtfhSz1hacJaBXIZySrImZ7f1UIXFvVZr5N569RLtdBY5DGAESR5b3YZARW3pttMqEE7oEnu3u78rKWE+0JdjJVHbOhBOoBH2XWcL7PkQaXThh6Vh512ixVPpnVbu4/aStCDCc/nRz6LwYDhBhX7mwAw6gHIIyKN/yfNyUBC5hCQmZc+ECGpOEYHZO53FcfICva/HWeLDQ7wJ8jQMCAveif4nqJEiXoIl3goYbCRXMESuDiUPSnVATgOMJzqqEya3J3JxrC1SLxMFxq/0Nixx3MspBf97vrp68rcG4L3FI2bo9G6mbTzTFeeaSIvY/6ZrDQo/0UTHiGG06HjUtK4BmR1GequfvzUW1LaojNpxyo8aSNw/RNw9Hbz7Vz9v8+MM5p7h7XVyffik/N0F5V/NmxDDoGzChjNF5tohlmah8RtikVWHjG6O3PFwy/WLMO+HmhH4jOEemIzYu0kEIaZyKG1HQkAUOyzBeQBl0LsxBYyeXmgcu+nGBppcg07GD9/ZiJtpyzprgIMTr4polmgzqoKmrRHdSHI7q/KlBTJiKdITrMIkhJZ10PliXjvFBc0WBCJZSh7mZUikExxPUrZSBZ+nJJ4V9cU6cY1JbY022u/3+6smhlTygTKkF9tY6cXPLuki12XlYG+rWMToog5LydIwyzFhwxF603bSdLVLsM4tsdmycdh2AZGeQsQGtQcnbP4hpzInpbX4sjZFnQliwU15EvgHBNLIzhYLB0GUCMBEq0gfrLFR7eacjfKuBGYcf0ND647ZdcgF/NPfJ1R02LAUnhEDnzuhFHBdFaI4OfSTDYicQVzDRvvOqHwWe4otQ/ggixr15MPYbj7AwFeAxN11jZgmPKWfrEh6jobit8AKvgFS7ty/S/VDfX1/v8IKtN/v7qt0lZhh3B5CLLGx0XgWiIs3ZY0HHuBaPC9JOmjamCcTwZg4xfIbG8BkFltqYGsQMU2N+UEY9I6NyhqOhOixHhDJbjQoZy13jaqeD/oy0GEwDkzG1LdDIpGlcGENnFkyDDTYmM4/MZcWN7hSXty7slDPboUPtzjJbzzfzLYczg8vUelEU9RLvmskuTZNmXdMueb5BTWcSUPNeAvc0IXmymcRAntS2QyaDQH8HKWTkNDWY9IN96fnTPlzarxAejAAaDD7UG/yU3NsC49Q+Pdf4GHda8qPBnxS8cBI8nwfY3mJe52DR4PZCcHmvc8ICZkjWxRA8Bva4FRFn8NcoZWGAGy4nwXMsS7JCBQQoZi7PcIMX7eDMiNzWw+Ujy/YLyiOQHm9VVR01CA4NnRGR9QE8EmxG0c/3+ZHANIe77fOdUd1Bh1Zm6E/wd8gn4JgCNiZrZnnEreZ5jaY5LSWa53RsddH/dF/DB11wrQ/XLOAyVtkbaoLSsuLaHygNVsQo20bSqZYSSYskz8i9N+0PkY0IsolB+Qm2sUw2gq0Vr8fugFn/MlW0/SlUENA1glYEcNkI7rXHuZItHO76tmwpRJ0rjdqhNlqC1l+lbVi2BNuZKai9jG0ONhNZ1xi4ZmLN6pAup+S72SqyhLCvu3J5HtpIvFyG8UR7QDjtmH1FTvPsEj4MztTfjM+pN9NGzsthsEbIS9YCJnGpIuJxZaoopu0jsxYFzxrfaQCI1nypd+7eoj8ob2GSQts1ZskK0O7FSkBOI5Xv4rIhk2OXnMe3+Ri3DQ8+4wndTrFxKGXj8kCwsIfeoMGldXoggu8Jp3ewcgXr6O5OLvObCvq4fA9JLdWp8uMVcRC1XHbUD11dxOR0yEYCeqmFSeKgA+voVMmWc8AxGcrUKchbku+oqBLJW8jzwXie/oy8hTz/h28CIRVilNFhx5bIFqCETsAJHX1+CDUJse3VF57opm1sM9WFrUFKZGhYZfOFJV7IwYnaAEX5xpDFYkHjyjxT3K2rg3dH5B/uq6s6H3aijayAElF7coiei0T1QHQ9wBNG9CjONcw4Y18CDg8zsjFrBji5a5rLCNFmElpcku1wMzSx9VkeIMxveE7Gc8fhpJvY2rfh1m9io/dk3+IJQf27skz0jAJytk1Bq+A646yd/OF4MNFdwP0B4EtQkWDcvEttjm/qk8PRXLZpMuMMAnlmu+2gAEFPFcpJkP2jdiEvGwDQUl6S6V7QZTMLYeTdlodSOIRrxD+lIGpFevEROCQPl5URVR68EJVQ9zHZMD9L7jp70XWGXrQXWC0/kINiY9jAZRv0Im7ZYNkpWzpHuuDIGTFRN9zN7ldswQzss3DGDGgvBVw+Ayg2Bs6A7+Th8AYkXaL3FzGoAlhYTFdcMsBCMCzWwQNjCLpwWZNlEnpb3sBl/+D5HPBiMeRo5SU0PXSQ74AKtv6SrYEFng10C/IsYL5h2OlzbWGoB31QJseTQurQTsm2IPyDPKCE54mQim438IwoWPjjFW2Hsz6E3J4xH6GQ7SNgtODKrRyuBWErv/CKh+Vgv+zG0oo3QZceEliF0na0hMZYtnI4s1lcFs3sSQ3ZTXWvEiqY99X+j2HX23wsmLEaIHzHtllUylKt9fjZuxBsty2xkOw76LDEWKbnoqVHXwLUriS3myJK8OtxF8+BKj3qWK2/OYoceIbPGHa7um3KGCgaXq9lhdeQ90vGUnU8YxdqJEZ1ZiayNefEz2iuoJeW2oMTISRlxoNc46uCcGgrmFz35CvoKQGi8dSUJSVwKSjOM9wDtTmLxKmgzlCdZvGopae0eTTK9m90N8q3A4ZNxRBzU3y1HwTEkhaCY+zWe+eDLx+lokQdirWsO/J0rLH+PsLRgEvPPV3w+2ScrjjcY0NABePT5MhSeA5BGe3y/B2VLAO0IMiN3IVqNecM5oLePqSqwh3rMT1Vi74oOlG1EADIQ9ZXmIQK6XBIX6ZSH8qxwL4KvZ+OvPKIzKDV/UraJDZ3zhGCIW/t4FtYhNkEMGZDH+lOOVF5TfYcS8C3DCE440t6wH2jsonJzeFck1iBi3HwBZgCi8fYSSabh/CcgMFz3HbqyNJJsD2jwoXHITJ7OmlTWwyUYUIcKr+ly5YtXMXUHGNb8WdhwpauIPU8nujyH0P7qG622Q9CqXpg0DK4UWhdlbCgRvhVjCxq9Kj3K+Z3j7BeRbGhsCdozAT5jo4HZEmEKBwp5hLZr22ydzi3DZJCJifZYrwIOYY8Xd5Y4ji5+W2wtqEncCPk/WJ0Rs3EjZA+RJyMrWX7Lhtrwik01IzrwrEpe17nn2CoaHilFlbdF7iJgUeM7AbYfFXacrKHvEGkYiw+EDAb99/1QKzx24FvxmBfNsRoEWLN1Ojaao5wnMscYRXNTOeDLju7LueazEC2w+VoU8ShTQ43D1KxrAWxgSrOu8PdYaM+qDUioXUGcEGyA3XsKyTmt9siH52bQB48ywEq6Nl7DLIC7VCgN7xz1SsoWCPGYA1ROMuBJygSYVwdjY41XRXCIBE4REMiIwRX3Rq/K/J6N+07QRcxvoTUVm0xI4D/1XqPpMqVEAnACI9xxx292MO0MVgcLo+3cIvwEhGlUSGlJ3xb4QRgwzUxuEYYP5dHwLdMC/LwHJ4nAgOJkLKznEbBG0IFdgsGn+FDQA15kDHPUwdqiNIE+cM5hZ/3x6O5XWNO6SfJyDQpa1MBFyS3ylBACJPcfm+FvCxtINiUCMn1SgtXaCtYOF7T7azxAtyKWYsnabtk0VBzE2Fqc8VpOtU6wDHsOOpB7OFgDBrRQiBbsOY4DEZm9MtSb4Zc5+4Ik0E3wElgSm+e2R7IQlUTwll8oKiEshBpdhiV3qHuCgJgHDK4kWzcxkJgTQJVj8gxlT1cjGfhPIheJGM5ESd6cKmVS9NmoBWT058IYRmLZFLSFokKoBiTxGBPkT0a5Eo4oAZoG8QjSggpbVio5ADtpWFCCDGYeA/AGusoDnZ5BtpF7B+gcTfCQRIio+u4OJzHdxOZQn2AFJOJUgiORiAEdeRygq8NdWWU1QzQaO03t+dzlsYgNBnSlw0ygA1Al5IpBAPMGHQmP/aM8menPQzMGJkSoSvGoYGgyZLnEtqvpiDao8/JYMOYGQsAzLYXDqABCFUBCMCRLCoxpwGMYXgKbMEmAtGSYTCJSQlZ1WiE+mAWSmYIrpZBRBh2JvkjIo+wwZYckWnB3SVCDg0HPsjbSxYEdiIaqSJasUYfRcy1AFgTyRIBc0REGUI+x0zsGQmD3UaU9eYbQUgFufbA89ThGXNRj2uARS1m4DgfHmrrzlulo/iRcmyvBwjKw6KEV/UKP7WS7RWGuTAngXCW0AUfQWiFXE3HuY4LQQD17PIwJC5o8y2DkEBTIslyAofhxBjbPQoLEE1V+DFQPfRKASylgGRpwYQQ2g7qie2jawF+kI4LsuPcchzY7zUsjUyN4XzVzqSQZiMKEqOZLH/nwJh4Gl9j8gloiBJAOwj+MStZMHOgFZ8FWgxKM/KKUI6mZhPvbPKn9ZrJliHZ02rN5PcQR0OlyRVZKjRHpUxr9JgOYoYwUjALChwheYiqggJxldB1oqjdgCAi51ApRE9KvFCIXhqiVQncgUYfbm2yVNdAYabFJDQ50vfeMrbQoDP5pWRozmArAF2GYjXkDW+EIqzJpIdzpohq0Sd/cpUs0ZQLI1qgz+vgQBKDkOBI71yhTBq5G4YDSQCt8OhKDwYDMGEXEhFZEVU2BEdgNDHzHWMNqhge5AhJL0YhFPJ+UpYjMsQxNbnYzAWgFOS51ixHCP3gjtuCt1mKmLQQVAwt94fOWLmVrST21QyuTXy7Ld80BJ+QAD3Pc2IbEnHCMO2m+GwYqg+R118sl9EAIlle5CLoE1Mt7fszIRoOI8BwEOZADI4pbhIQUgEvHgu1UA3YuC6TQ+KDNpUDFn1U8wjPGOYZwTwjkicLwSRWZJPx5xD/wOAP12MGsFx8Wi7MghLGU9A8zWIi0bF0f0EFyCDQeQfIIB3PUFlkJEcmFsd6mUpRzE61PEYTLfuxkDdgdJFBTBL3GNyDNZNWTIJjiHKkVZHgGKAcacUjODJ6R8MBEEdG6xiMZJIOYoZ1DUZvPAy+URgJ4qDouh4OFUE8LrBLmANCkIVX+lgnDgRBFofp1R8OA0GW41UcaFvNZhARBDrx6Ou7GUwEwE5aOwzQ0Te8M5gIQKcucQQmPnkxJIeJQKpE3obCYSBQrEeeWcphIABY4snTO0AMBMq5QxBVQQsmPLoGg4lFMVQFBDkwqw+H3ng0D3KEpJegqAp5xzHLERniBJtckiMyDcmjtVmOSDlRgimp5IisaZJ7K6kIOiFtE8MRKRIUaDmhICFvliOCkwjpMhYshArlnyaWp9jWxxtnlvfF0EQzhTLvsYHOAhPM/TrMYJGLQK+2BupHoh7qrFErhMVZLQgDUWdUgDwdgA3E3SVg0Kp4QqRd5ojEGG3miAQtsnmEZwLzjGGeMcmTx2oQnhHMM4R5hjDPQPJ0XIDt0BlIuj7daw6dSecsrQu4DQH3ew3zXI/7DYlQQjUI1J6NG3A5pJGFdMBieEhajFoyxTAIR1gpaZ1kQRqAktZIFqQBKGl9ZEEagBLWP0b9GJAG0gzYDEEcIWZY12D4yMPwIwXSIN7OBz0os0OMmQsIIXPiHDNfEUKm1pXRKYSQuW6Q0XuEkIkuOSQGIExhbCcFsZ0MxXYyDNvpfBLsvRCNoa975Xwskqj7MLrjg+hOAKM7AYjuhDC6Q57NwWExUO5P7l7hsBi46gOFJzB0BwRbMHcBJwB4TgFyhKSXougOeTM5yxEZYvJWMpYjMg3J47dZjoiqkOdPsRwRdIfcOMlyhJZHu3pBx+RcNmBMzxagAK+U6UD5iR0TbNMAfiRSDhQCtw0qlYGKY9KVU3EM3xp0jEo6xn3cLjPlW0cgoZSMXKgUmbnahrNi1A5AAmbiW0L1HMOA1PkVIE8HYAdx3SkYZyueEGmXOCPxUps4IwGYbB7hmcI8E5hnAvOMYZ4xzDOCeUYwzxDmGcI8A5hnAPP0YZ4+zFPAPAXMc03z5NAoNOmAWEotcqsW8GCNghUK1idYnWBtgpUJ1iVYlWBNghUJ1iNYjWAtwpUI1iGII8QM6xoMf3ko1gzXUXloIRWzP44DmQBC5uQkDmQCCJnTyTmQCSBkSpM5kAkgZFYYOZAJIGTCYw5kAggzGLbKQNiqczawW0IdHQZcCRC4oq/b5Vw8AlwFMHBF3mHDwUxQlB6CwFUEA1cRCFyhG3w8dM8QXC7joRU4MOjjoTgS5oLgDANPWkCOkPQyFLjKUOAqQ4Er8ho2liMyDcnjx1mOiKqQ52axHBF1BneRSo5IWRJYgyk5ImvR4EqC5IjkE6jXUFMc2LDV8XRQG+SM8Az0wIonAhJlYJygeKK6A4U9grmQh+OJqw8EB2UwHKTOAAF5OmA81GYSAkvjWsJVC1tKb+MinwJjoU61v/dxVUJIO3cB8UxhninMM4F5JjDPGOYZwzwjmGcE8wxhniHMM4B5BjBPH+bpwzwFzFPAPNcwT1iPYDWCtQhWIliHYBWCNQhWIFh/YPWBtQdWHlh3YNWBNQdWHFxv4CkOcYSYYV2D8TYPxazhwjMPrTyDdzB66BZGdU4ViGqBR2RhOBl9ajmHaiEBI73hnkO1kLA2AeNfZtmVQ7UAQibu51AtJLFew0BZt4aCejcMKRMgUubDSJkPImX0RcZc9IEgZfTtPVyMhCQG9AG2XCSHpC/0MTNcvInuu8CQMnAfGFx65KHVTDDK5KHAFeYoER+5BpGyLsuCugYiZTJvAzkiI9xxBCh98g48liNA6a9BpMxfgzrlg2eZSY7I1nZwJ7DkiNRhg/WskiOy6AYuXUiOSMCDeg01xWGtcVAbVG8gZy15opoDhRSSJ6o7UODjq/u0QZ64+kCHXdKn5fI8UQ3CloTVKTJLQCkH+EtQ54s5tISrnKBulm1b+vjt2/8BrC3V0v0OAQA=
```
</details>

**Expected behavior**
A crash will immediately happen after you click the Next Turn button. 

**Additional context**

Summary of crash:
java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at com.unciv.logic.GameInfo.getCivilization(GameInfo.kt:469)
	at com.unciv.logic.GameInfo.getBarbarianCivilization(GameInfo.kt:101)
	at com.unciv.logic.civilization.CityStateFunctions.getNumThreateningBarbarians(CityStateFunctions.kt:416)
	at com.unciv.logic.civilization.CityStateFunctions.updateDiplomaticRelationshipForCityState(CityStateFunctions.kt:384)
	at com.unciv.logic.civilization.CivilizationInfo.updateDiplomaticRelationshipForCityState(CivilizationInfo.kt:945)
	at com.unciv.logic.automation.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:50)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:139)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt:606)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt:598)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

**Comment by xlenstra** [comment]
Thanks for your report. Based on the stack trace, this looks like a crash that was fixed in 3.16.14. If the crash does persist in that version, do please open a new issue :)

**Comment by EclipsePlays** [comment]
nice
