### ISSUE TITLE
`NotificationScroll` `ConcurrentModificationException` with obscene amount of units.

### ISSUE THREAD

**Issue by will-ca** [yairm210/Unciv#5861]
I was trying to make a reproducer for #5729, and got this instead.

This is with the commits from my CLI/scripting branch rebased onto latest master. But I don't think any of those really touch any part of the stack trace.

---

Platform: Desktop
Version: Desktop
Rulesets: [Civ V - Vanilla, Civ V - Gods & Kings]

java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList.checkForComodification(ArrayList.java:605)
	at java.base/java.util.ArrayList.hashCode(ArrayList.java:615)
	at com.unciv.ui.worldscreen.NotificationsScroll.update$core(NotificationsScroll.kt:29)
	at com.unciv.ui.worldscreen.WorldScreen.update(WorldScreen.kt:464)
	at com.unciv.ui.worldscreen.WorldScreen.render(WorldScreen.kt:841)
	at com.badlogic.gdx.Game.render(Game.java:46)
	at com.unciv.UncivGame.access$render$s2211858(UncivGame.kt:29)
	at com.unciv.UncivGame$wrappedCrashHandlingRender$1.invoke(UncivGame.kt:74)
	at com.unciv.UncivGame$wrappedCrashHandlingRender$1.invoke(UncivGame.kt:74)
	at com.unciv.ui.utils.ExtensionFunctionsKt$wrapCrashHandling$1.invoke(ExtensionFunctions.kt:410)
	at com.unciv.ui.utils.ExtensionFunctionsKt$wrapCrashHandlingUnit$1.invoke(ExtensionFunctions.kt:433)
	at com.unciv.ui.utils.ExtensionFunctionsKt$wrapCrashHandlingUnit$1.invoke(ExtensionFunctions.kt:433)
	at com.unciv.UncivGame.render(UncivGame.kt:217)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:403)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:143)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:61)

---

Save file:

[Autosave-Persia-121.zip](https://github.com/yairm210/Unciv/files/7781902/Autosave-Persia-121.zip)

Warning: Well. It's in the title. Multiple units on nearly every tile. Doing anything at all (including just loading the save) will take up to several minutes. Also, from a second test the crash may not even be reproducible. This may not be practically debuggable if it even is a bug…

**Comment by felipeforte** [comment]
I believe I have the same issue. Usually when you have large empires the size of Mother Russia it crashes, however, I wasn't able to check the contents of the crash log, because once the log displays, the app crashes immediately (using Android in my case)

**Comment by yairm210** [comment]
Cannot replicate, even with larger games - I believe the underlying problem was solved
