### ISSUE TITLE
Miscellaneous (upstream?) audio crashes with music mod.

### ISSUE THREAD

**Issue by will-ca** [yairm210/Unciv#6015]
**Platform**
`Linux 5.4.169-1-MANJARO`

**Version**

Release `3.18.17`, probably various preceding ones, and… Some recent-ish version of the mod mentioned below.

I tried to test on latest `master` and latest mod… But I'm only getting ~`200kb/s` download speeds for that 300MB mod, and then Unciv seemed to crash or disappear when I wasn't looking.

**Describe the bug**
OpenAL crashes with various exceptions with a certain version of https://github.com/NoviceCoder2000/UnCiv-Vanilla-Music-Pack installed.

<details><summary>Stack Trace 1</summary>

```
Exception in thread "main" java.nio.BufferOverflowException
	at java.base/java.nio.DirectByteBuffer.put(DirectByteBuffer.java:409)
	at com.badlogic.gdx.backends.lwjgl3.audio.OpenALMusic.fill(OpenALMusic.java:269)
	at com.badlogic.gdx.backends.lwjgl3.audio.OpenALMusic.update(OpenALMusic.java:237)
	at com.badlogic.gdx.backends.lwjgl3.audio.OpenALLwjgl3Audio.update(OpenALLwjgl3Audio.java:253)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:132)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:61)
```
</details>

**To Reproduce Stack Trace 1**
1. Install and enable https://github.com/NoviceCoder2000/UnCiv-Vanilla-Music-Pack.
2. Load the attached save.
3. Declare war on The Netherlands.

<details><summary>Stack Trace 2</summary>

```
Exception playing music: Error reading audio data.
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Error reading audio data.
	at com.badlogic.gdx.backends.lwjgl3.audio.Mp3$Music.read(Mp3.java:90)
	at com.badlogic.gdx.backends.lwjgl3.audio.OpenALMusic.fill(OpenALMusic.java:253)
	at com.badlogic.gdx.backends.lwjgl3.audio.OpenALMusic.update(OpenALMusic.java:237)
	at com.badlogic.gdx.backends.lwjgl3.audio.OpenALLwjgl3Audio.update(OpenALLwjgl3Audio.java:253)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:132)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:61)
Caused by: java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 1733 out of bounds for byte[1732]
	at java.base/java.lang.System.arraycopy(Native Method)
	at java.base/java.io.PushbackInputStream.unread(PushbackInputStream.java:232)
	at javazoom.jl.decoder.Bitstream.isSyncCurrentPosition(Bitstream.java:384)
	at javazoom.jl.decoder.Header.read_header(Header.java:160)
	at javazoom.jl.decoder.Bitstream.nextFrame(Bitstream.java:350)
	at javazoom.jl.decoder.Bitstream.readNextFrame(Bitstream.java:340)
	at javazoom.jl.decoder.Bitstream.readFrame(Bitstream.java:311)
	at com.badlogic.gdx.backends.lwjgl3.audio.Mp3$Music.read(Mp3.java:67)
	... 6 more
```
</details>

**To Reproduce Stack Trace 2**
1. Install and enable https://github.com/NoviceCoder2000/UnCiv-Vanilla-Music-Pack.
2. Load the save file from ##5944.
3. Don't take any actions until you meet Egypt.

Crash happened on the meeting player dialog, IIRC.
Not sure about this one. Didn't reproduce it when I tried again, and apparently I wrote down a blank for the turn number but not the actual turn number.

<details><summary>Stack Trace 3</summary>

```
Exception playing music: Unable to allocate audio buffers. AL Error: 40964
Exception playing music: Error reading audio data.
Exception in thread "main" java.nio.BufferOverflowException
	at java.base/java.nio.DirectByteBuffer.put(DirectByteBuffer.java:409)
	at com.badlogic.gdx.backends.lwjgl3.audio.OpenALMusic.fill(OpenALMusic.java:269)
	at com.badlogic.gdx.backends.lwjgl3.audio.OpenALMusic.update(OpenALMusic.java:237)
	at com.badlogic.gdx.backends.lwjgl3.audio.OpenALLwjgl3Audio.update(OpenALLwjgl3Audio.java:253)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:132)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:61)
```
</details>

**Additional context**

Also, I suppose this is a case where the GDX-based crash screen literally cannot be used to handle the error… Can we use Swing on the Desktop builds? Would it be worth it to show a simple error popup window? Boilerplate looks easy enough, `JOptionPane.showXDialog()`.

Not sure if anything can really be done here.

**Comment by yairm210** [comment]
Listen... (pun not intended)
The entire audio code needs to go through a revamp. PErhaps even starting from scratch. It's very convoluted, and from a practical standpoint has the most outstanding bugs (measured by number of open bug issues) out of any of the components.
I'm in favor of burning it all down and starting anew, but that will be a serious project.
