### ISSUE TITLE
ctrl crashes the game on Ubuntu

### ISSUE THREAD

**Issue by yairm210** [yairm210/Unciv#6391]
To reproduce:
Start Unciv on Desktop
Click ctrl+whatever (ctrl+v for example)
Behold

```
java.lang.NoSuchMethodError: 'int kotlin.CharCodeKt.access$getCode$p(char)'
	at com.unciv.ui.utils.KeyCharAndCode$Companion.ctrl(KeyPressDispatcher.kt:67)
	at com.unciv.ui.utils.KeyCharAndCode$Companion.ctrlFromCode(KeyPressDispatcher.kt:73)
	at com.unciv.ui.utils.KeyPressDispatcher$install$1.keyDown(KeyPressDispatcher.kt:184)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:53)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
	at com.badlogic.gdx.scenes.scene2d.Stage.keyDown(Stage.java:418)
	at com.unciv.CrashHandlingStage.access$keyDown$s80204510(CrashHandlingStage.kt:10)
	at com.unciv.CrashHandlingStage$keyDown$1.invoke(CrashHandlingStage.kt:30)
	at com.unciv.CrashHandlingStage$keyDown$1.invoke(CrashHandlingStage.kt:30)
	at com.unciv.ui.utils.ExtensionFunctionsKt$wrapCrashHandling$1.invoke(ExtensionFunctions.kt:329)
	at com.unciv.CrashHandlingStage.keyDown(CrashHandlingStage.kt:30)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:58)
	at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:189)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:394)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:143)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:60)
```

**Comment by xlenstra** [comment]
I'm unable to reproduce this on my end

**Comment by yairm210** [comment]
??
Really?
It happens to me on a clean jar file
Maybe it's an OS thing, I'm using Ubuntu

**Comment by xlenstra** [comment]
I'm on Kubuntu 20.04 so that should be the same. I am trying it on a version started by AS, I'll check if I do have the problem when I'm staring the jar manually

**Comment by xlenstra** [comment]
Nope, just downloaded the 3.19.18 jar and no crashes when I press either left or right control + any button in either the main menu or world map

**Comment by SomeTroglodyte** [comment]
Maybe a JVM issue? Kotlin has changed the way to get at ascii codes or build chars from codes in 1.5x, so maybe... A simple try catch might help. And on a system with the problem and the library sources you could step into the Char(Int) constructor and look around?

**Comment by SomeTroglodyte** [comment]
... no it says so "getCode", it's one step earlier in `letter.code` - which is `@WasExperimental @SinceKotlin("1.5")`

**Comment by SomeTroglodyte** [comment]
How about
```kotlin
        /** mini-factory for control codes - case insensitive */
        fun ctrl(letter: Char) = KeyCharAndCode(Char(
            try {
                letter.code and 31
            } catch (ex: NoSuchMethodError) {
                @Suppress("DEPRECATION")
                letter.toInt() and 31
            }
        ), 0)
```

- that's a brutish shot in the dark...

**Comment by SomeTroglodyte** [comment]
By the way, I'm on Mint 20.3 which is based on 'untu 20.04 as well. And I do Ctrl-L or Ctrl-O all the time when testing.

>  left or right control + any button

+ any key, with mouse clicks is not the issue

**Comment by SomeTroglodyte** [comment]
Holy mackerel, I got that on my box too, ***with*** the newer try-catch:
<details><summary>studio breakpoint screenshot</summary>

![image](https://user-images.githubusercontent.com/63000004/159590132-43f80efe-73a6-46b6-927f-d6579d47e996.png)

... leads to ...
```
java.lang.NoSuchMethodError: 'int kotlin.CharCodeKt.access$getCode$p(char)'
	at com.unciv.ui.utils.KeyCharAndCode$Companion.ctrl(KeyPressDispatcher.kt:67)
	at com.unciv.ui.mapeditor.SaveAndLoadMapScreen.<init>(SaveAndLoadMapScreen.kt:158)
	at com.unciv.MainMenuScreen$MapEditorMainScreenPopup$loadMapAction$1.invoke(MainMenuScreen.kt:177)
	at com.unciv.MainMenuScreen$MapEditorMainScreenPopup$loadMapAction$1.invoke(MainMenuScreen.kt:176)
	at com.unciv.ui.utils.ExtensionFunctionsKt$onClick$1.invoke(ExtensionFunctions.kt:74)
	at com.unciv.ui.utils.ExtensionFunctionsKt$onClick$1.invoke(ExtensionFunctions.kt:74)
	at com.unciv.ui.utils.ExtensionFunctionsKt$onClickEvent$1.clicked(ExtensionFunctions.kt:67)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.unciv.CrashHandlingStage.access$touchUp$s80204510(CrashHandlingStage.kt:10)
	at com.unciv.CrashHandlingStage$touchUp$1.invoke(CrashHandlingStage.kt:24)
	at com.unciv.CrashHandlingStage$touchUp$1.invoke(CrashHandlingStage.kt:24)
	at com.unciv.ui.utils.ExtensionFunctionsKt$wrapCrashHandling$1.invoke(ExtensionFunctions.kt:329)
	at com.unciv.CrashHandlingStage.touchUp(CrashHandlingStage.kt:24)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:70)
	at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:189)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:394)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:143)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:58)
```
</details>
</details>

Explanation: The debugger hits the breakpoint, one can step into the try block, then into the catch block, then two "F8" later the debugger halts in the `wrapCrashHandling` function - and meanwhile the debugger's evaluator can evaluate all involved expressions just fine. WTH????

**Comment by SomeTroglodyte** [comment]
... and if I """fix""" that by using a predefined lookup Ctrl-O for Options ***still*** refuses to work???

Anyway, if a one-operator expression throws an exception while the debugger with context _on that line_ can evaluate the same expression just fine says the ecosystem has some serious flaw. Kotlin is a fun toy on top of a rotten core after all... 

Escalate or
```kotlin
        //private val controlMap = ('A'..'Z').associateWith { Char(it.code and 31) } crashes!!!

        private val controlMap = mapOf(
            'A' to '\u0001', 'B' to '\u0002', 'C' to '\u0003', 'D' to '\u0004',
            'E' to '\u0005', 'F' to '\u0006', 'G' to '\u0007', 'H' to '\u0008',
            'I' to '\u0009', 'J' to '\u000A', 'K' to '\u000B', 'L' to '\u000C',
            'M' to '\u000D', 'N' to '\u000E', 'O' to '\u000F', 'P' to '\u0010',
            'Q' to '\u0011', 'R' to '\u0012', 'S' to '\u0013', 'T' to '\u0014',
            'U' to '\u0015', 'V' to '\u0016', 'W' to '\u0017', 'X' to '\u0018',
            'Y' to '\u0019', 'Z' to '\u001A'
        )

        /** mini-factory for control codes - case insensitive */
        fun ctrl(letter: Char) = KeyCharAndCode(controlMap[letter.uppercaseChar()] ?: Char.MIN_VALUE, 0)
```
???

**Comment by SomeTroglodyte** [comment]
Ummm... That dollar sign... There's name decoration... It's a static... Is that moron binding to a wrong library? Can we run that debugging session with verbosity for the class loader turned on?

**Comment by SomeTroglodyte** [comment]
Nothing new there. That's exactly the same place I can reproduce: Map Editor -> Load.

Go try that yourself in the debugger, and then tell me what we can _really_ do. The method is perfectly fine, the debugger uses it, and then the JVM it is debugging is too dumb to find it. If we fix that specific place by not calling that method, the same will happen elsewhere with _any_ method on a static from a Java library with Kotlin wrappers. Sooner or later. That's what I believe. There is something broken, but not that piece of source. _If_ that's our fault, then it's some compilation / class loader configuration thingy I don't understand. Heck, it might even be that we now have two main() functions and Kotlin is somehow marshalling that method separately for each and then gets confused...

**Comment by SomeTroglodyte** [comment]
Other question: Why to other calls to Char.code not crash too? `NativeBitmapFontData.getGlyph`, `IdChecker.getCheckDigit`, a few uses in `MayaCalendar`... Anyone can test the latter two, 1 works obviously?
