### ISSUE TITLE
Cannot start the game under Windows

### ISSUE THREAD

**Issue by JackRainy** [yairm210/Unciv#6717]
**Platform**
Windows 10

**Version**
Latest `master` sources, seems to be caused by `ceeb547fb8d9a32e992aa1e72d107cf0656c2ed6` commit

**Describe the bug**
Get the error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jna/platform/win32/User32
	at com.unciv.app.desktop.MultiplayerTurnNotifierDesktop.<clinit>(MultiplayerTurnNotifierDesktop.kt:15)
	at com.unciv.app.desktop.PlatformSpecificHelpersDesktop.<init>(PlatformSpecificHelpersDesktop.kt:8)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:49)
Caused by: java.lang.ClassNotFoundException: com.sun.jna.platform.win32.User32
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351
```

@Azzurite , any ideas of workaround?

**Comment by SomeTroglodyte** [comment]
> gradle reload

A gradle sync should do it, and that should run automatically. And it that breaks, I always invalidate caches and go get coffee

> `NoClassDefFoundError`

Merge my #6468 (which _necessitates_ a build:clean and preferrably a invalidate caches too) and see if it goes away?

**Comment by SomeTroglodyte** [comment]
Actually another proof that the double main() from UncivServer provoke NoClassDefFoundError in mysterious ways would allow a nice 'told you so'  victory dance, so pleeeeeaseeeee??? 🤪 :rofl:

**Comment by JackRainy** [comment]
No, gradle reload/sync does not help.
Clean project, Rebuild project, `gradle --refresh-dependencies` - all these things do not help.

**Comment by JackRainy** [comment]
Sorry, no victory dance for today :(
`git pull https://github.com/SomeTroglodyte/Unciv/ Test-UncivServer-Char` and Clean Project + Rebuild - it does not help as well.

**Comment by JackRainy** [comment]
Actually, the new libraries are downloaded and are present in the Gradle cache, including the missing class.
Something wrong with Android Studio, probably.
![Screenshot 2022-05-08 15-53-04](https://user-images.githubusercontent.com/27405436/167297162-b990d1fa-2797-4c17-aeaf-8bbbeabd13b7.png)

**Comment by JackRainy** [comment]
Gradle tools upgrade from 7.1.0 to 7.2.0-rc01 and Gradle service from 7.2.0 to 7.3.3 have resolved the issue.
Now even after downgrading back, it still works. Still do not know what was that.
