### ISSUE TITLE
Android warnings and errors (includes Logcat)

### ISSUE THREAD

**Issue by alexban011** [yairm210/Unciv#7233]
**Platform**
Android 12

**Version**
4.1.12 - GP

So I started logging the game when closing it and got the following results (app: Logcat Reader)
Might be good to address what can be addressed

Warnings:
- Letterbox_left_ActivityRecord{240c665 u0 com.unciv.app/.AndroidLauncher t4027} has FLAG_SLIPPERY. Please report this in b/157929241
- Application com.unciv.app can be debugged on port 8100...

Errors:
- USNET: appName: com.unciv.app 

Plus:
<pre>
- [DefaultDispatcher-worker-1] Uncaught throwable | java.util.concurrent.CancellationException: The task was rejected
	at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
	at kotlinx.coroutines.ExecutorCoroutineDispatcherImpl.cancelJobOnRejection(Executors.kt:169)
	at kotlinx.coroutines.ExecutorCoroutineDispatcherImpl.dispatch(Executors.kt:131)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch(Concurrency.kt:164)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:159)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:518)
	at kotlinx.coroutines.EventLoopImplBase$DelayedResumeTask.run(EventLoop.common.kt:494)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:108)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.util.concurrent.RejectedExecutionException: Task com.unciv.utils.concurrency.CrashHandlingDispatcher$$ExternalSyntheticLambda0@d970a29 rejected from java.util.concurrent.ThreadPoolExecutor@31e01ae[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 11]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2086)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
	at kotlinx.coroutines.ExecutorCoroutineDispatcherImpl.dispatch(Executors.kt:128)
	... 10 more
</pre>
<pre>
FATAL EXCEPTION: Thread-25
Process: com.unciv.app, PID: 1802
java.util.concurrent.CancellationException: The task was rejected
	at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
	at kotlinx.coroutines.ExecutorCoroutineDispatcherImpl.cancelJobOnRejection(Executors.kt:169)
	at kotlinx.coroutines.ExecutorCoroutineDispatcherImpl.dispatch(Executors.kt:131)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch(Concurrency.kt:164)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:159)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:518)
	at kotlinx.coroutines.EventLoopImplBase$DelayedResumeTask.run(EventLoop.common.kt:494)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:108)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.util.concurrent.RejectedExecutionException: Task com.unciv.utils.concurrency.CrashHandlingDispatcher$$ExternalSyntheticLambda0@d970a29 rejected from java.util.concurrent.ThreadPoolExecutor@31e01ae[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 11]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2086)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
	at kotlinx.coroutines.ExecutorCoroutineDispatcherImpl.dispatch(Executors.kt:128)
	... 10 more
</pre>

Full logcat:
[logcat_06-20-2022_17-40-24.txt](https://github.com/yairm210/Unciv/files/8941543/logcat_06-20-2022_17-40-24.txt)

**Comment by yairm210** [comment]
This looks to me like a non-issue, tasks opened by the app are closed when the app closes. Maybe we can add a nicer cleanup to the tasks somehow so that they *know* this is acceptable, but for now I'm not sure what we can do with it and it seems entirely harmless.
