### ISSUE TITLE
City sounds not played on release versions

### ISSUE THREAD

**Issue by Azzurite** [yairm210/Unciv#7264]
Reason probably being that Android doesn't support *.ogg files?

**Comment by alexban011** [comment]
I choose ogg because I read online that mp3s add a small delay, making them impossible to loop. I'll give it a go and see

**Comment by alexban011** [comment]
got any idea what this could mean? OGGs should load on android since there is ogg music right?

<pre>
E/Unciv CityAmbiencePlayer: [GLThread 48] Error while playing city sound:  | java.lang.ClassCastException: com.badlogic.gdx.files.FileHandle cannot be cast to com.badlogic.gdx.backends.android.AndroidFileHandle
        at com.badlogic.gdx.backends.android.DefaultAndroidAudio.newMusic(DefaultAndroidAudio.java:118)
        at com.unciv.ui.audio.CityAmbiencePlayer.play(CityAmbiencePlayer.kt:54)
        at com.unciv.ui.audio.CityAmbiencePlayer.<init>(CityAmbiencePlayer.kt:21)
        at com.unciv.ui.cityscreen.CityScreen.<init>(CityScreen.kt:118)
        at com.unciv.ui.cityscreen.CityScreen.<init>(CityScreen.kt:37)
        at com.unciv.ui.tilegroups.CityButton$setButtonActions$1.invoke(CityButton.kt:169)
        at com.unciv.ui.tilegroups.CityButton$setButtonActions$1.invoke(CityButton.kt:160)
        at com.unciv.ui.utils.extensions.Scene2dExtensionsKt$onClick$1.invoke(Scene2dExtensions.kt:281)
        at com.unciv.ui.utils.extensions.Scene2dExtensionsKt$onClick$1.invoke(Scene2dExtensions.kt:281)
        at com.unciv.ui.utils.extensions.Scene2dExtensionsKt$onClickEvent$1.clicked(Scene2dExtensions.kt:274)
        at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
        at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
        at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
        at com.unciv.ui.UncivStage.access$touchUp$s80204510(UncivStage.kt:15)
        at com.unciv.ui.UncivStage$touchUp$1.invoke(UncivStage.kt:66)
        at com.unciv.ui.UncivStage$touchUp$1.invoke(UncivStage.kt:66)
        at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
        at com.unciv.ui.UncivStage.touchUp(UncivStage.kt:66)
        at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:426)
        at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:472)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1593)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1287)

</pre>
