### ISSUE TITLE
New version crash on launch

### ISSUE THREAD

**Issue by Huymnsel** [yairm210/Unciv#7399]
**Platform**
Android 10

**Version**
Google play store 4.1.16

**Describe the bug**
Cannot launch the game and crash everytime

**To Reproduce**
1. Update to newest version from gps
2. Open game
3. Wait a while
4. Crash

**Expected behavior**
Not crash

**Screenshots**

**Additional context**
Was opening unciv while updating it (cleared the old version out of background then open the new version)

https://user-images.githubusercontent.com/107736312/177994702-5810e2c0-5708-4d42-bd57-8d69e54dd458.mp4

**Comment by Huymnsel** [comment]
Where to get the logs of the game?

**Comment by alexban011** [comment]
The error is written in this file:
`SDCard/Android/data/com.unciv.app/lasterror.txt`

Upload the file/its content here

**Comment by Huymnsel** [comment]
`com.badlogic.gdx.utils.SerializationException: Error reading file: MultiplayerGames/2v2 w
	at com.badlogic.gdx.utils.Json.fromJson(Json.java:803)
	at com.unciv.logic.UncivFiles.loadGamePreviewFromFile(UncivFiles.kt:233)
	at com.unciv.logic.multiplayer.OnlineMultiplayer.addGame$default(OnlineMultiplayer.kt:158)
	at com.unciv.logic.multiplayer.OnlineMultiplayer.updateSavesFromFiles(OnlineMultiplayer.kt:113)
	at com.unciv.logic.multiplayer.OnlineMultiplayer.access$updateSavesFromFiles(OnlineMultiplayer.kt:42)
	at com.unciv.logic.multiplayer.OnlineMultiplayer$updateSavesFromFiles$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda-0(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.$r8$lambda$wZEPzfc3ap1lx3h-gfSjlNGDZEw(Unknown Source:0)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: com.badlogic.gdx.utils.SerializationException: Error reading file: MultiplayerGames/2v2 w
	at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:79)
	at com.badlogic.gdx.utils.Json.fromJson(Json.java:801)
	... 18 more
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Cannot open a stream to a directory: MultiplayerGames/2v2 w (External)
	at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:149)
	at com.badlogic.gdx.backends.android.AndroidFileHandle.read(AndroidFileHandle.java:86)
	at com.badlogic.gdx.files.FileHandle.reader(FileHandle.java:169)
	at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:77)
	... 19 more
Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.unciv.app/files/MultiplayerGames/2v2 w: open failed: EISDIR (Is a directory)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileInputStream.<init>(FileInputStream.java:159)
	at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:146)
	... 22 more
Caused by: android.system.ErrnoException: open failed: EISDIR (Is a directory)
	at libcore.io.IoBridge.open(IoBridge.java:486)
	... 24 more
`

**Comment by Huymnsel** [comment]
Do you think I should upload the file instead? This is the content of the file

**Comment by Huymnsel** [comment]
[lasterror.txt](https://github.com/yairm210/Unciv/files/9075494/lasterror.txt)

**Comment by Huymnsel** [comment]
Ok, I was able to resolve the problem, thank you for your attention!
Game now open as normal

**Comment by alexban011** [comment]
What did you do?

**Comment by Huymnsel** [comment]
I typed in "game name" something in the line of "mods w/ ravig". It definitely interpreted it as a directory

**Comment by Huymnsel** [comment]
Just delete the directory and game open as normal
