### ISSUE TITLE
App crashes after update to 4.1.210-patch1

### ISSUE THREAD

**Issue by dmkoder** [yairm210/Unciv#7519]
**Platform:** Desktop
**Version:** 4.1.21 (Build 740)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.worldscreen.WorldScreen`

--------------------------------

OS: Linux (amd64, 5.13.19-2-MANJARO)
	Freedesktop.org 21.08.14 (Flatpak runtime)
Java: Flathub 21.9
	Max Memory: 3966 MB

--------------------------------

**Message:**
```
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at com.unciv.logic.map.TileInfo.getImprovementPercentageStats(TileInfo.kt:604)
	at com.unciv.logic.map.TileInfo.getImprovementStats(TileInfo.kt:519)
	at com.unciv.logic.map.TileInfo.getTileStats(TileInfo.kt:371)
	at com.unciv.logic.city.CityStats.updateTileStats(CityStats.kt:387)
	at com.unciv.logic.city.CityStats.update(CityStats.kt:490)
	at com.unciv.logic.city.CityStats.update$default(CityStats.kt:488)
	at com.unciv.logic.civilization.PolicyManager.adopt(PolicyManager.kt:207)
	at com.unciv.logic.civilization.PolicyManager.adopt(PolicyManager.kt:192)
	at com.unciv.logic.civilization.PolicyManager.adopt$default(PolicyManager.kt:172)
	at com.unciv.logic.automation.NextTurnAutomation.adoptPolicy(NextTurnAutomation.kt:489)
	at com.unciv.logic.automation.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:65)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:273)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:580)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
	at com.unciv.utils.concurrency.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda-0(Concurrency.kt:164)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
**Save Mods:**
```
[Civ V - Gods & Kings]
```

Check the attached file for the saved data.
[unciv-bug.txt](https://github.com/yairm210/Unciv/files/9173665/unciv-bug.txt)

**Comment by OptimizedForDensity** [comment]
This bug was fixed in version 4.1.21-patch2 so try downloading that and see if that fixes the issue.

**Comment by yairm210** [comment]
Already fixed

**Comment by dmkoder** [comment]
Thanks, indeed I noticed that there is patch2 after posting the issue.

However, I didn't get the update from the Flathub. 
But I just downloaded the new version manually.

Best regards,
Djordje
