### ISSUE TITLE
Game crashes during Diplomatic Mariage?

### ISSUE THREAD

**Issue by heipizhu4** [yairm210/Unciv#7680]
**Platform:** Desktop (in fact, it happened on adroid too)
**Version:** 4.2.4 (Build 747)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings, The Demon World, The-Demon-World, Difficulty_Sandbox]
**Last Screen:** `com.unciv.ui.worldscreen.WorldScreen`

--------------------------------

OS: Windows 10
Java: Oracle Corporation 25.232-b09
	Max Memory: 910 MB

--------------------------------

**Message:**
```
java.lang.NullPointerException
	at com.unciv.logic.civilization.CityStateFunctions.diplomaticMarriage(CityStateFunctions.kt:300)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.useGold(NextTurnAutomation.kt:285)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:80)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:273)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:580)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
	at com.unciv.utils.concurrency.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda-0(Concurrency.kt:164)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```
**Save Mods:**
```
[Civ V - Gods & Kings]
```

**Save Data:**
[中华的第214 回合.zip](https://github.com/yairm210/Unciv/files/9382486/214.zip)

**Expected behavior**
It should be able to enter the next round.

**Comment by xlenstra** [comment]
Something went wrong when uploading your save as I can't download it. I've added a likely fix for this issue, but I thus can't test whether it actually works

**Comment by heipizhu4** [comment]
> Something went wrong when uploading your save as I can't download it. I've added a likely fix for this issue, but I thus can't test whether it actually works

Probably because I used some Chinese symbols... Anyway, here's another one.
[CrashedSaveaboutcitystates.zip](https://github.com/yairm210/Unciv/files/9387547/CrashedSaveaboutcitystates.zip)

**Comment by xlenstra** [comment]
Yup, this one works, thanks! I've tested it and my fix seems to fix this problem.
