### ISSUE TITLE
Unable to create a game - crash "you are not allowed to spectate"

### ISSUE THREAD

**Issue by JackRainy** [yairm210/Unciv#7689]
**Platform:** Desktop
**Version:** 4.2.5 (Build 749)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.newgamescreen.NewGameScreen`

--------------------------------

OS: Windows 10
	Windows 10 Pro Version 21H1 (Build 19043)
Java: Oracle Corporation 11.0.12+7-b1504.28-7817840
	Max Memory: 2018 MB

--------------------------------

**Message:**
```
com.unciv.logic.UncivShowableException: You are not allowed to spectate!
	at com.unciv.UncivGame$loadGame$2.invokeSuspend(UncivGame.kt:185)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda-0(Concurrency.kt:164)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```
**Save Mods:**
```
[Civ V - Gods & Kings]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```
H4sIAAAAAAAAAN1d247bSJL9FWNedhYQB0qKEkm92e6LvWiPjbZ7/dDwA62iq4hVSVpKsl1j+N+XN0m0eDLzRDILmG1g0EOryMjIS0RGnIyI/LYqPhfr4l/Zodhu9ss/v1X//md2ny+fZeXHrCyyzX5yyFd3y2/fJ7vtulgV+b5+rl57Xn1wKI+r9svqt/895vvDq2yT3eZl/e8yXxe31R97P91u1zf55ultS+S2zLPDm3y7W+f1P/P9rnq7erX3wediddiWD32qx2Kz7/37Ltv//DkvX3/Z5Devy6rBTbZ+nu2KQ7ZefsrW+/z75NtunT3k5buHXb58cbzPNpNTL3/e3K6zzU3Xxfq/+9/zfZ6Vq7v8Zvnn09uyWB3Xh2OZf/h37f9uuzvunq7z8lBP36Hu49tDVh5ebg7ldvI5Wx/z5d/+9v3DJP+6W2/L/OZdsc7rV78ulZo8VP+pBqh6ntbP0/Z5Vj2nl5/j9jGsHpPmMb38XZ1/bP6eXgh0xNILAXV5Iey1Nv2BbnJ5t9fuiUt19V1adYxZAacJf56vD/v/z9M9nMWgHp9Ahe2g1M/tEAaz8++X31Tv3aD3cvOYtq+mvb92z+Hk6vduDrq2p+2Hpx9nvTd+eLv9g+rTUd2nqk9PCWf17S4rNn+xWV3UK70dlKT32P5f/cfo8hhe3ptdfp1dfu1eiLv/u/wxvpCeX2jOe5/8+Nh7oaOQXiikl19C4Qw+y9e3ZXaT/7UmsVFdweyiroL5RaUFUe+5HeJ6qoLFRdN1r6S9L1WPorr6ct5rKOo9h73nRe95dqHee4x6xOeXnxfMjFazcXiotp9D/semqGah+u9h+eJLtrr7j6yvhbNd/uTd9stfTWbnl92p0XV9RXt6DnvPUe+5eX92Ea++Rjz9HvWeVe+5+TbqvR/13u/zM+3R7/MW9d5RvW/7PFBK+bIA3uTlvhrUdfXv5cuybAzMbF3R+Hi2LOtRvCk+fWqm+mH5piw2q0oDVOP5Ktstv91nuzdZWa2XQ0Wq+efb4l/VhFV6ojjul+F08qW4Odwto2hylxe3d4dlmE429fp6lVdv3FeLpZ7n/OZ9cbj774pGxcEy+kf4j/mTvz87FuubJ3GU/udkn1crTi0WKpyqMEwWSaUlax5+K/aHalo/Zvv8XV51oNgsfy2z/b4xGMt8vz2Wq2opb3e7vJystptDsck3h2U9xLvtvqj7u7zsc98nmJD+Q9UqVvzZof3ll6p/lYxUy+9FsV5PfqnW4/7wQUvUxMiA4n8dK+M4/3Dp6rNq7W+yvYG6jF09n18FlGx9/uo0+MFJKwsHS08xbDfSPr036+q/e8tcViL3bHs4bO9/yz8dfi8q6VtWyi+3rjjclnm5CfgzLjKSjn25aifA3A/BKmeWj0gQiZUAR8dhnh1GJxz2RTc7A/n/o8w2lVo9//D0fnusmoisYuRz8FofYvZ4WuzrctYat7iB8zT9Xu84vXnq/YGaO2M3ettLtr4e8JllfmdCyQ8U4IXSF7JvxI0YpsEi/54UUDc2/DZgJ4gEQrYPXC88yyLjhe9VVu7vepLyuhgsvdgkNj829Kr+oHbLdYwPBBsOypmb93cVoxapxePqS2Rn+qkzs2VR+D7Y8mmpNKZ/7QaKOhq16MCYKWy7EsllfqZt20UrOzAQMgzYZ9nV1pPOldKyW9zvyu3n/L7+6ummcro3hyeN42vS6piUD4eCpNwapGe6T9fH+2IztFQS27aBVZCLCIHdkV1HHjcv4HOw4nSt6E7qHImsYDszsStdxU4qyhOvrY6UbgYR72MRsxu5uHmRi4EYuRiIDcpUI4ieIIGanJaajfm5wzBpG7tY59nhsLZvzg5czxw7Gxrb4xkPh+17NluUy7QoLVuG7Un6gQtT0j3QMjBaE0Q2g9cy+1O+z0ujBQb8R3rHwKrozPGLbbnP9yL0ABjPLkNh0NVuit8TLelCu17J1umca3m1qW3pV3N+Z3NAZFqeHo/+3LTqdX6yjV0HMZpr7XJbY1qFoVmUQmW96I4ORauv/mjhTS3OAQsuymCu5cpmQ2gbd+hONOQCdMZRZV5zSoEU+Bvedw/1DYsVYzjk57fsf/I9tCGINWE7o1NMe+JxpVe/3dY3GEuuJgZJjZkqsSMWALyENjPEfogRz5d7qS5eVwA8v7GHua0qk9k1Z5F4e5fnO5u6lRoBAuk/9+7M0a/b9c2T16V5G5IypO0Er9cWYJCprU+8RhZgZVEtiSVi4SJHCzeZbRuzIMO6jc4PSLrg1R0BuyyALu6maUhuvd3ePNk1jX0QLLo61K6O1hMthfqj2G83MQtinbnQcmYz+GL5gptrG+PHP3JsO3Lp6MxlsmfDlqCJFALiY/Z6pk1lHL3HQu+tnGkHQm/A8Z2wW12ssWrFFIG1Sp8tiCEHPRBoMdPENiE4xBvtYrEnOhTqI7Mh0cE9sVdJkA4r13pUxqyrxfBPoLe0DPuVtBHpB7EL/BXr7T3XyIh4OA12JDbWW4NW475Yfzb6u/FwNY/sYssupjlg93W2L/amhRs7mpoxUDxOppkfuzOWutm8exY7G6Fmdl1cOBubUtywyVipM11EX9UfJR63j5Z3zIVYE8cm5s6z/rLcbq6FLrTa6HynGTMdd1jkpc+NXJm3vgSuP6Hh7tB2NGwbmrYzI/2L/B62G9MYzcjmQtkEc+GHTMMKNDxSGSimab5VmwQzAvf2eJvZcGGx1REAZ4S2zx3s+gCg5ZyJ7hJgAAITqGAK/QkVLTQBCDHk3Urblmo+s3Ozve3x3Rj4Cj0CX3KsWg9e0noYGdGc6S39yEHXu+wPyZA1rikwEGx78rDz8/z8lJtz0hKwMFi2xDElidgRp4U28YwZtLySHsTgJP0xAnyTob710EPPnkMy3IFYV9Xm6CRgV6R8AZ/QXcuFFKJtEuHrpHiRQutqa3g66U1cWEiGLIzLoIsBF2NcKWmHWkeJZMCKTiyGHNjXwlw/EaPV+dxlSCLAkD9rKvK6imdGXs1WrnhgQpeBkSv20CRkFu9Cz971MYIMfFZeBV/Cp56GT0WEvNpxGwNwamlfz9OpXACO5Tj/jw9os/KgjyBzhQtQ2L7TcRkI5dckszhFUhLnlvKkqq/ncjwE2yiag47McLPLu4g6fzC57MjLuA3dF+vikJUPTe2Zb9svm4qDtkDUtqtY8rr3W1Mv5H1WlsW22mKPZVmReXWarHBSTdz9tma0KVZy3/3hVX5f0WqqvgzsnPD79w9NmZqKjWwjYOJtXq9kn0yAn71oHOTU6vLDHB3nlKN+9RqCMlMTA3JFlzo69KnIoWfPV1IgOrpBkGJbDsmoqVETiQc7dcD7bNxp6fnRZelws7k+QrHCnCnY+cZ66KnWQ7cxssCSWOmsioVs/X67uamG5VmtQTe3efnkeZkdjN5KqjVXXFzL1MUzT6njuOf11G+sjUsPKoO2+Fpdi8vTyj7X7pQ5OqlnNlI9F87QhZ49C1brj4/YlY8Y8GFfHQvU3JjASzkLczkLVxaZi8U7B7zyCb7iXkbG5gbdtCd9zQxsSM7PZ0bGrCHTNmTDo8CHsiHE2hyZ622V3h8t5fY3r+b6qTatzmC3sOHLYO+zAf/gaLeNS9BWTuLowjAvHKLlZt01ZTgfCQZJ4UYU4TE26goEeVDx5N4QKRCczgUJaIxNpPG5Vz3XoAhAEQoul8UUx4UyZGgAx5JZIy0gh+I4ndcBiDNlgZ02hNXfGeq1l2zCK/xhUdfmsaAUogQCuKKKEACh4mRadlf00kDH1sHxJ8WdB+Z7RBqyDlEVwblMt/TL5sPxeQl0QcFz3XAf6qEh5jVaW1A2bQp0LpYbD4jOufa7g0OFZGVhG1Ux1HMuDu/D6zxdGjLSEeqY8oYVnS4akaEkLRPCoNRzNx1q5nb3mjixSR654wxsW9CYOt/YIWJNnW6Z6X/17ri5KTNCR7sUTp+CBkcAQKkrI6mAD3bTTczMjIAHEsCtBu39Y30sj3bMbGTqfQwYYvEzcekCp7bmhrbGmotzwJFr0LSQRwto5hIHO0NcXO8J0q1u5mmIQgNzFkvELe7HaQih9tV218G6Q3q6ch/3YBCeHrbVQhkgP2PnwjQyY+UJgmmkrIoTsxB45mpNCePRiA0NhJ65MofyoXzlOIIkqUeymV3LPQSg3oPrSJrrm5EmnP02GlD+zBRWJIXO+NkVFGURkkZZwHT6MBdyhVIaxgASIK9iWD//xy0GoUuPE2BCxJc8EqASIOAHtu+ruqcvQsp4aYwgelEJ77OhGPO/ThS6dsOlwwpUTheCQraszo5ZaR6TAoV56dSgUSX+UYFhjWJSoLSf647UNezv9ESByjUeqgQrVFnHND7yjF6UCGxqYWwau5LkX/Pn6qfrjn880j796vNsXbVnobqTdYIRT6frPUbAzw5eGDo29mS4KOQ2dEiZFKXzd04eqPMFw152xtMFmKZOSqvPKGVg0TbgmBc7NCnbRe0BfJgPrbjTKyIVcmvf7lPArrPJlThNXQJYIIsqaT4Tcx7rWZCPwsJpFBZOozB3amvus7uREwuRTxZmPrXaDHDWYGcYaxT14ZEzzJE+bmG/s4b5pdjfYTiS7IgGNOVhSeGtOU7XWPlZWf40Iwv4ygOOAgT1jgwEHREOYsWKUKApF9E2OgG1UxSe4FJUnopOuRsGchltIlDSyv0Q1FyM1wWE1pfpdQUh0CUVY+xe/f0VzgcDqGwfDU1efYdwMFS+ZCwuKbiDj5gklCI29kxcnt3GBnM9AqJqDhKzaQFx5ByCD0nA4zF2HrHJJ3ezeHdbcBk26yQ7RKsYL2l00awK3SJphzfB1V9jsw47VkiqPuqAg4tFRIlLviBbdC2KDjAEJbbdIVvzBYBuaA0OC+TjK5S5tKEbU3IQFxXdMM2JyE6zNuyJmjLWjRGcgaCwAllwvk2zYiDT7uSOFzxxLqxCUTlmhu1MyHfdFpKYQTYMzDfgg/SrE5f+TrHbQZTzoZz4EKLqLvVROpyX54y4BGLqNEYpYkQW3Wso2WIBej1b64m0L8J6kMKVRJcxZ1m204sBlyOBY+99Xghn3n534+NJ+FzMKw89RfLVasGv/V0yD7eLMZF83hYl3Fo8lQRFuwyE2uG+Yqn66Bo26/M2Dfehw+iACxjODDA8ARh10AyQfmDbvi+M7obJ+HJbyb6IwQoRukRUVAaCKmpxbdSbkqhF9r8FHU64Zj3c8oCuphsL9Pojh+48GcMduJaFrYLDXhlL4cDe097N9bhsuu7X/N5a3SgCSsx4qgnzWyWF18WnNCiDd1TQqQCyZuM6fUb+XEOkfILJyWV9nHQrzqLQxGhDh9zR+/djgTXEfEVKtJx5oqbAdcyj0jqcqqsqdJX0qC6RqPPQzhwFd6GrFkd1wxsQ7XrDjAKlhEdy4RF5dqls03FBIs8g62lEeUT1iAlayqm8ujLHZbhNiTPWzFe+gMa781aIUlc7pp3VgMeAHoXi2dzxcIdQOx6hUS1EE/HMiksfNE1oWrD3G39Htz3Tt83SOGH9gjGyA/3y4VBemVB6Jpw05VTC3aCIDi2s7QmAaBDcvYsU9ckseA7KMXVaDomUNwK1TgAno6qXDRgUp+RaRDP2yfFCyDF5DOCLvbmZPQvA74sLuF1IISi0IYwqlzjgiIpv1XzkBnMOWEA+MFL9BvQd82eN8TFVKER6/wrZeV5mHweQuhAM0g6umbMBRiADOOTnl/a4bDYtwVdmBTRGYavICna+lguWgYbNotLPo8o2iJ0g/Y1dLhiItbaor0gmcEH0WKBci7s797jZt/3B+egCQnKuXLRbAO5SRIsYXRIhTjMGt1WIo1tQeu+zfH1bZjf5VX7v+WevCb5dJcdBhi+q8EjW0SP2N1hDgM8gZo5XURgv3mpBCDGkiBDm16s8GxzSIQSbOD2JGNJjwnNtLjozWJFPmD3iRr5rVRyTHXFLpSPvN1BLgeu25fUurMANaUQP/aqH3BjRCa59I8qgolvn7NGjoB65r/tvFaqLzp+SOmRogJpWnF4zV9Fyky1vMdgo884eWSuOkZBObAo5chsrGQhutVJMeRYnLSpokdU4sihsX+dosEqmFKlF6ekELOqWC69QMCHdGv6OhLTkQQ4t8jMnTJQG6iFePHVk7lOAqHZnhnZtML70qxNwT/ZSfK4R6npNAxZKPgu8Taf0Y3YhwhVfl7Ho6w6dqb4D8j0sdVkKFtTeMrj2epIJYmoU5Jz4HLNYyB5WeC5p3qPX7cLMugWzd5NIaeHUQK/YDWhsB+j7Ck6EG8EVDyAAO0KQ/lhEBW4OaB9B24GhYAzxJtLl2AOnN2OKR0Bs2CzXWXhmoD1dYI8rXDK4RBiegmg64bfDuIjTi/BGumyXP3lXPV/fSnf+3evNdF0UyOBiOhQdMqokyrXlDdct8g5G5pKbkFh4CyZRGAndY4kmf+F0crAYeqQSgy0GbvDY4HT7Tbo6FMIldDMxogwWSyU2zuabPCvX6OpsDf5vsdUQik9En1NOCLiVSI9Si8PgA1TrFskkrO+gx6hnBEUUa6zHqIkXIeCrgaatqDdcItyuS3u/FDHQJy1FajTnYNzHF+dtyBLT3rX/OEmcDW3Kqpi7nBkpcCkkI2PobkquMY/ZRQrdO8Bx4TEDSwnri7ksACn42zHlb7NU4NR/JGLa8YiJWjiRwcV2dA+TGwUzK3QJ0nWYtCSIG17YNBa1RoVRIXTsAkzDWq3OKCfKlGcFgcWM2RG7UrNvN9svBBMuYd4mqi3KsgA71JDoy1V+bU8338PPNfwToR3t8FA0I0SzGUlHBJxg74SALzytyRndbmho1wZy469YoPyEc/vqs6L7PJW36xW8FrQ8ca++e0a3XZqzQNx+SXaAt1+iCbscYvlqMJ7a2W4Ct4kNCWITXUN61NMxUgA1L1KoSPGOhKWJVmnFC/UuoohUKtxAoEZFbyIdagCXiTeRCkS4MUGMYw3C3to+MC/SQfMBiprXTZwmgtzoS6LiPYgRGGqgB1vFVeGhfQ1HBFn2WpRUk3Y5IsqpUUzXZNFAxMC/ois2I6AWwZkJMWDJ0IXVxgUjmBPttzEhNehicL2pwsghulUKyyG4zEqPQlLBp6A+rB6FpHArUM5Aj0JSSByIKYUUEQaodz2IFzkFz0zxgsUxF2Qfmhep0VuAcYZe1oJFJhckxt28SK3ChQ6VRxQpSUGXdWopUtKMqumP17sK1FoiAAhU8UnbPQz0jbYiFUqlkYcZKHCC5w69oUPEEcAM2hU9QSzEiahCt7B7ap45K0G3KdEJ4CMDUOH9T+Z14eJmK1TX0wq9wRqjzuAHyiluWDCJkTFnSsHE53EMjo4nOnHFhVcCbDFQrbvPWGmNs068eGKKobmgac4RTT20SdGMaJoRTXOGaFqXXuwmaTPAlgnXRGzZUE2KvELk/dZHUTQz0/HM/FFmm2J4kBQ6FW+dAs5HRui6dM6CYcK4lQFFHKKdaAXJ6MonY9uFygstCqS74OKhVRfSXFoUgqKI9JY2t5yiSGstqLS0qB9DEeobLepHaVZ6U6EoUsQ41mg8MuAAyRPqx3hlbEQurP+hXQvMizDJR4/zES/Cc2hIER2H64QU2+XG0PEAOQla5I6qBxGTWGACnC0tVpfa6aXAoYRDmg69Wj1WR8nrlET/0NXqeqyOgYbQBUV6rI5B/1ANTL39x6B/KJtab6Uy6B+KrtPb0gz6xyJnAQvGcYqedkYoYiz6F7PoX0yOc/MiNcMxuRaaF6lVGJPrVYFLHw0UGVEBtcQNFJlYFVBsBRv+qNqLlqI8Vg8FtmuH4Eo3o5s0O4qEtldo+zhVd51saiM5W7/fbm4qb+TXynW5efIq3xOdoRCz+DEQsxjtzHpJp+pfwJvX9V2iQsrhtTx6mlQEMCz6R4Tuo5Q/JggYJijq+8ALL/dq6xwyctP4g+hFEZbFSijz4gnLYmguaJpzRFOPZVE0I0TTBvBENPmZC/kZTT7UjojRUG8RKqoFRY+5AjRNQBNDc8rSTFmSKdtzWvy00odRF+JNWspoIaNlDIqYFnVhKEIB06IuDEUoU1rUhaEIxUiLulByQ6s/iiJFjGONxoMCDhA6oS5sTBsbJMfhOChXW4+6MD4AKh+rR10YPwVF9utRF8aXQqehepyF8feQsarFWRhAptGfzIspsOW1SAvxXru7UDI6JbEbRWM3isRu0K3L+h2ewW7QnR56k4RxSFEJOL0NxTjNKI9Qb+kxjj2KKNLboyz4wGE3JJTCbRe0mc97DiRFavQSFrtJWOwmYbGbhMVuEha7ATemGSgyogIKwxooMuIMMuINFBmVQwapdhTZ9Yjjm9yL1igE5OulAcdDWekz+1LbgLd7xxMauEnA5u4QEuB291bC2iAK3edsWFCMAaTQHREmFcdKO5daAOtl6WkKQBxW4jmzHEYN4Fdbt5gRp8YvRi+SGFJCt5ToWtLgUgzNmKa5oGkuaJpzRJMAJud0CxFqYUwyKdXqTN+vQbMw0KRFsqi2QnpeQpqmomkqmuaUpjlladJCqpVRjF0Rb9KySIsiLYm0INJyCMVQi10xFKHYabErhiIUKS12xVCkBYeXG3qJUxQpYhxrNKoWcLDaCbtiI7PYUC8ODWNTQWERRT12RbwI6zXosSviRRiGrseuiBfhqaQeuyJepE3wAJn+WuyKQsNSEg1r9xd6J2L3Ng4PUyQeFtJ4WEjiYeguWL1NwpjT6LYAvW3FGP2oAJXeHmRcE5S9prda2UAXDg8jw3ZoLClg4SluC6JdFt4LIilSo5eyeFjK4mEpi4elLB6WsngYuGrIQJERFVBi0UCREWcyJbqjyKgcMnCzo8ioRXBAgQER9shDoV2DiVyh96W2BXmgb9cCK1NcHFJKY08pjT2lNPaEbko1qRNWsjjsCRaQ19PkhYvCnlAii4kmK19jgpJgRAe2zBubKUTLnWqr+d7989NuwIob8+LpxIXFqTmaMU0zpmkuaJoLmuYc0dSXUKVoRjTNiKY5o/s+o2mGNM2QpqlomoqmqZc55NFQNGkxoqWIFiJahmgRoiWIFiBafqD46GAAiiIUHh1UQVGkRYeWHFpweLmhlzhFkSLGsUYjdAELbNMRcAEbAkfnRgZsciRdtS1AZdv0OBhjoKFbUfQ4GGNGolILehyM8SFRdL4eB2P8XHQUrcfBGF8c+Rt6HIyC1tqDFnZ347A1RWJrIY2thSS2NqOxtRmJraFbKvU2EuMuoOroekuOcWpQ1SW9vckmaHHYGpluRsdABWxYFY1LBSzUxW2UzB45JbG11veiWCOxtc6bIykyM9xSJN4MwQXTBorEmyG4DMRAkSlsSZby6ygySfNkwnFHkQkIJwNrO4rMMR152NFRZAwedtc4LXFaagRiw8oNtVl3NFnJoUyKjiYrO9Ce4UCUriVWprgiD/B6ST1NXqyoYhSofo18RFh5G4G1hTAhS9+Se5hYqA+f0RD4MNkfsvJQbG5/266ymlD1l4rubXafv8nK6r/Vd/vlt906e6gf/uye3j3s8uWL433Thfp/Hyab4/3HvHz96XlxeHh7yA5VG+Hkc7E6bMuH+vXq47dNnGTxqVhNnh/XTXrw5KftfbFpWp78VOzW2/vqeTV5V9znHyb32dd3x7JiKZpW+qG70+1Nw8Dy581tU4i25vTlzTJLkyT9FMbBTbLIgiiZfQySZJUFyWoVT+N8FWXz2ff/AxKdYTb0NwEA
```
</details>

**Expected behavior**
No crash

**Additional context**
I have deleted all my settings and saved games, trying to create the new game with the very default parameters.

**Comment by JackRainy** [comment]
@alexban011 , would you like to take a look at this?
Seems to be caused by #7290 .

**Comment by alexban011** [comment]
Ahh dammit,
Gonna have to take a look tomorrow. :D
