### ISSUE TITLE
NullPointerException on next turn

### ISSUE THREAD

**Issue by wiger3** [yairm210/Unciv#7893]
**Platform**
Windows 10 x64
Android arm64

**Version**
4.2.11

**Describe the bug**
When going to the next turn on the save file, the game crashes and throws a NullPointerException. Seems like a unit is trying to attack a tile that doesn't have an attackable unit on it?

**To Reproduce**
1. Load provided save file
2. Go to next turn
3. Crash

**Message:**
```
java.lang.NullPointerException
	at com.unciv.logic.battle.Battle.movePreparingAttack(Battle.kt:65)
	at com.unciv.logic.battle.Battle.moveAndAttack(Battle.kt:43)
	at com.unciv.logic.automation.unit.BattleHelper.tryAttackNearbyEnemy(BattleHelper.kt:30)
	at com.unciv.logic.automation.unit.BattleHelper.tryAttackNearbyEnemy$default(BattleHelper.kt:16)
	at com.unciv.logic.automation.unit.UnitAutomation.tryAttacking(UnitAutomation.kt:253)
	at com.unciv.logic.automation.unit.UnitAutomation.automateUnitMoves(UnitAutomation.kt:222)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateUnits(NextTurnAutomation.kt:884)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:85)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:277)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:591)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
	at com.unciv.utils.concurrency.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda-0(Concurrency.kt:164)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

```
**Save Mods:**
```
[Civ V - Gods & Kings]
```

**Save Data:**
[Pastebin](https://pastebin.com/nRH2uceC) (too long to post on github)

**Comment by nacro711072** [comment]
Can you re-upload saved data again? There is noting at the link you provided above (404 Not found)

**Comment by yairm210** [comment]
Okay, so! Here's the play-by-play
- Carthage Rifleman tries to attack a Great General
- It calculates that the best tile to attack *from* is a tile that to get to it it needs to go *through* the Great General
- It moves to the tile, killing the Great General on the way
- Once it arrives, it tries to attack the Great General - but it isn't there anymore!?

So what do we learn from this?
'tileToAttackFrom' has defensive bonus optimizations that are useless if you're going to attack a civilian unit
We should instead choose the closest tile so as to minimize movement.
This will also solve our current problem.
