### ISSUE TITLE
Crash on attack

### ISSUE THREAD

**Issue by Raiji96** [yairm210/Unciv#7920]
**Platform**
Windows 10 Pro 21H2 54 bit

**Version**
4.2.13 (Build 757)

**Describe the bug**
The game issued a crash log when attacking a scout with an archer (long bow).

**To Reproduce**
1. Urgently buy an archer (long bow)
2. Put it behind the trebuchet
3. Attack a scout through a trebuchet

**Message:**
```
java.lang.NullPointerException
	at com.unciv.logic.battle.Battle.movePreparingAttack(Battle.kt:65)
	at com.unciv.ui.worldscreen.bottombar.BattleTable.onAttackButtonClicked(BattleTable.kt:265)
	at com.unciv.ui.worldscreen.bottombar.BattleTable.access$onAttackButtonClicked(BattleTable.kt:36)
	at com.unciv.ui.worldscreen.bottombar.BattleTable$simulateBattle$3.invoke(BattleTable.kt:247)
	at com.unciv.ui.worldscreen.bottombar.BattleTable$simulateBattle$3.invoke(BattleTable.kt:246)
	at com.unciv.ui.utils.extensions.Scene2dExtensionsKt$onClick$1.invoke(Scene2dExtensions.kt:293)
	at com.unciv.ui.utils.extensions.Scene2dExtensionsKt$onClick$1.invoke(Scene2dExtensions.kt:293)
	at com.unciv.ui.utils.extensions.OnClickListener.clicked(Scene2dExtensions.kt:282)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.unciv.ui.UncivStage.access$touchUp$s80204510(UncivStage.kt:15)
	at com.unciv.ui.UncivStage$touchUp$1.invoke(UncivStage.kt:72)
	at com.unciv.ui.UncivStage$touchUp$1.invoke(UncivStage.kt:72)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.UncivStage.touchUp(UncivStage.kt:72)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:70)
	at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:189)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:378)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:83)

```
**Save Mods:**
```
[Civ V - Gods & Kings, Civ V Leader portraits, AbsoluteUnits-main, ReSound-main]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```
(Save data in attachment)
```
</details>

**Expected behavior**
I expected the archer to finish off the scout (the unit had 30% hp left).

**Screenshots**
[save.txt](https://github.com/yairm210/Unciv/files/9790808/save.txt)

**Comment by nacro711072** [comment]
Your saved data seems broken, i couldn't open it. Have another one?

**Comment by nacro711072** [comment]
Perhaps it's relative with #7893. The target has been disappeared for some reason, but we still attempt to attack.

**Comment by yairm210** [comment]
Does look similar! But we'll need the game save to investigate

**Comment by yairm210** [comment]
Yeah, we can't investigate this at all. Closing until new save file added.
