### ISSUE TITLE
Please help turn 415 :(((((

### ISSUE THREAD

**Issue by K-FAM33** [yairm210/Unciv#7981]
**Platform:** Desktop
**Version:** 4.2.16 (Build 760)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.worldscreen.WorldScreen`

--------------------------------

OS: Windows 10
Java: Oracle Corporation 25.232-b09
	Max Memory: 910 MB

--------------------------------

**Message:**
```
java.lang.NullPointerException
	at com.unciv.logic.battle.Battle.movePreparingAttack(Battle.kt:65)
	at com.unciv.logic.battle.Battle.moveAndAttack(Battle.kt:43)
	at com.unciv.logic.automation.unit.BattleHelper.tryAttackNearbyEnemy(BattleHelper.kt:30)
	at com.unciv.logic.automation.unit.BattleHelper.tryAttackNearbyEnemy$default(BattleHelper.kt:16)
	at com.unciv.logic.automation.unit.UnitAutomation.tryAttacking(UnitAutomation.kt:254)
	at com.unciv.logic.automation.unit.UnitAutomation.automateUnitMoves(UnitAutomation.kt:223)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateUnits(NextTurnAutomation.kt:883)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:85)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:277)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:592)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
	at com.unciv.utils.concurrency.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda-0(Concurrency.kt:164)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```
**Save Mods:**
```
[Civ V - Gods & Kings]
```

**Comment by yairm210** [comment]
Please attach the save game data (load game - copy to clipboard - paste here)

**Comment by yairm210** [comment]
We can't debug this without a save file... Closing until we have something to work with
