### ISSUE TITLE
Please help me release

### ISSUE THREAD

**Issue by Ccokone** [yairm210/Unciv#7984]
I had the code, i can execute “_desktop:run_”. but how to release for windonws-64bit?

**Comment by yairm210** [comment]
You need to download an sdk if you want to build an exe, see https://github.com/yairm210/Unciv/blob/0858f8c0389c7f7d7379310471ab6b6d51efe553/.github/workflows/buildAndDeploy.yml#L158

**Comment by Ccokone** [comment]
> I had the code, i can execute “_desktop:run_”. but how to release for windonws-64bit?

Thanks yairm! I so sorry it doesn't work. My OS is Windowns-10, and then，after execute  _./gradlew desktop:packrWindows64_  , encounter a wrong. 



* What went wrong:
Execution failed for task ':desktop:packrWindows64'.
> execution failed with code 1: java -jar C:\Users\yuchaohuang\StudioProjects\unciv/packr-all-4.0.0.jar --platform windows64 --jdk jdk-windows-64.zip --executable Unciv --classpath C:\Users\yuchaohuang\StudioProjects\unciv/desktop/b
uild/libs/Unciv.jar --mainclass com.unciv.app.desktop.DesktopLauncher --vmargs Xmx1G  --output C:\Users\yuchaohuang\StudioProjects\unciv\desktop\packr

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':desktop:packrWindows64'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:188)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:186)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:174)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)

...

Caused by: java.lang.RuntimeException: execution failed with code 1: java -jar C:\Users\yuchaohuang\StudioProjects\unciv/packr-all-4.0.0.jar --platform windows64 --jdk jdk-windows-64.zip --executable Unciv --classpath C:\Users\yucha
ohuang\StudioProjects\unciv/desktop/build/libs/Unciv.jar --mainclass com.unciv.app.desktop.DesktopLauncher --vmargs Xmx1G  --output C:\Users\yuchaohuang\StudioProjects\unciv\desktop\packr
        at Build_gradle$6$2$1.invoke(build.gradle.kts:113)
        at Build_gradle$6$2.execute(build.gradle.kts:151)
        at Build_gradle$6$2.execute(build.gradle.kts:3)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:752)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:725)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.run(ExecuteActionsTaskExecuter.java:502)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)



![screenshot-20221104-101555](https://user-images.githubusercontent.com/5002368/199870818-2b0bc179-8ea6-407a-849e-35b5f3c9683c.png)

**Comment by yairm210** [comment]
Okay, it looks like it's failing on packr :

java -jar C:\Users\yuchaohuang\StudioProjects\unciv/packr-all-4.0.0.jar --platform windows64 --jdk jdk-windows-64.zip --executable Unciv --classpath C:\Users\yuchaohuang\StudioProjects\unciv/desktop/b
uild/libs/Unciv.jar --mainclass com.unciv.app.desktop.DesktopLauncher --vmargs Xmx1G --output C:\Users\yuchaohuang\StudioProjects\unciv\desktop\packr

Did you download the packr -4.0.0.jar?

**Comment by Ccokone** [comment]
Oh man，thanks very much. it worked!
