### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by i2324561w2** [yairm210/Unciv#7988]
**Platform**
Windows10 21H1 x64.

**Version**
Downloaded V4.2.16 from here.

**Describe the bug**
I pushed Next Turn, and after a minute of running on high CPU, it crashed.

**To Reproduce**
From the Autosave I loaded the most recent game and tried to reproduce it, but without success, so maybe it was just a one-time bug, I don't know.

Crash details:
<details><summary>Crash details</summary>

```
**Platform:** Desktop
**Version:** 4.2.16 (Build 760)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.worldscreen.WorldScreen`

--------------------------------

OS: Windows 10
Java: Oracle Corporation 25.232-b09
	Max Memory: 921 MB


--------------------------------


**Message:**
```
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.badlogic.gdx.scenes.scene2d.Actor.<init>(Actor.java:60)
	at com.badlogic.gdx.scenes.scene2d.ui.Widget.<init>(Widget.java:35)
	at com.badlogic.gdx.scenes.scene2d.ui.Image.<init>(Image.java:82)
	at com.badlogic.gdx.scenes.scene2d.ui.Image.<init>(Image.java:72)
	at com.unciv.ui.images.ImageWithCustomSize.<init>(ImageWithCustomSize.kt:15)
	at com.unciv.ui.images.ImageGetter.getImage(ImageGetter.kt:175)
	at com.unciv.ui.tilegroups.TileGroup.updateTileImage(TileGroup.kt:324)
	at com.unciv.ui.tilegroups.TileGroup.update(TileGroup.kt:379)
	at com.unciv.ui.tilegroups.WorldTileGroup.update(WorldTileGroup.kt:44)
	at com.unciv.ui.worldscreen.WorldMapHolder.updateTiles$core(WorldMapHolder.kt:572)
	at com.unciv.ui.worldscreen.WorldScreen.update(WorldScreen.kt:413)
	at com.unciv.ui.worldscreen.WorldScreen.render(WorldScreen.kt:797)
	at com.badlogic.gdx.Game.render(Game.java:48)
	at com.unciv.UncivGame.access$render$s2211858(UncivGame.kt:50)
	at com.unciv.UncivGame$wrappedCrashHandlingRender$1.invoke(UncivGame.kt:89)
	at com.unciv.UncivGame$wrappedCrashHandlingRender$1.invoke(UncivGame.kt:89)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.UncivGame.render(UncivGame.kt:392)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:83)

```
**Save Mods:**
```
[Civ V - Gods & Kings]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```
No save data: java.lang.OutOfMemoryError: Java heap space
```
</details>

```
</details>

**Comment by yairm210** [comment]
Cannot reproduce, and if you can't either, I'm going to mark this as a one-off. This looks like "too much data accumulated between Garbage Collection runs", which is odd to begin with, and I have no idea how to go about replicating it.
