### ISSUE TITLE
Crash after clicking 'next round'

### ISSUE THREAD

**Issue by nnamrrehdlopoel** [yairm210/Unciv#8003]
The game crashed after clicking 'next round'. Is it of any help to blindly post the Error log? If yes, here it is:

**Platform:** Desktop
**Version:** 4.2.13 (Build 757)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.worldscreen.WorldScreen`

--------------------------------

OS: Linux (amd64, 4.18.0-17-generic)
	Ubuntu 18.04.6 LTS
Java: AdoptOpenJDK AdoptOpenJDK-11.0.11+9
	Max Memory: 1024 MB

--------------------------------

**Message:**
```
java.lang.Exception: Unit Jet Fighter at TileInfo @(-3.0,23.0), Coast can't be put in tile (-3.0,23.0)!
	at com.unciv.logic.map.MapUnit.putInTile(MapUnit.kt:1022)
	at com.unciv.logic.map.UnitMovementAlgorithms.moveToTile(UnitMovementAlgorithms.kt:545)
	at com.unciv.logic.map.UnitMovementAlgorithms.moveToTile$default(UnitMovementAlgorithms.kt:441)
	at com.unciv.logic.map.UnitMovementAlgorithms.headTowards(UnitMovementAlgorithms.kt:316)
	at com.unciv.logic.map.MapUnit.doAction(MapUnit.kt:708)
	at com.unciv.ui.worldscreen.WorldScreen$getNextTurnAction$15$1.invokeSuspend(WorldScreen.kt:751)
	at com.unciv.ui.worldscreen.WorldScreen$getNextTurnAction$15$1.invoke(WorldScreen.kt)
	at com.unciv.ui.worldscreen.WorldScreen$getNextTurnAction$15$1.invoke(WorldScreen.kt)
	at com.unciv.utils.concurrency.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda-0(Concurrency.kt:164)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```
**Save Mods:**
```
[Civ V - Vanilla]
```

**Save Data:**
[see attached file
[Crash-log.txt](https://github.com/yairm210/Unciv/files/9995706/Crash-log.txt)
]

**Comment by yairm210** [comment]
Works fine for me, could be one of 2 things:
A. This is a bug solved in recent versions
B. The crash depends on specific actions you take during the turn

Therefore please
A. upgrade and see if it persists, and if so
B. try and replicate the crash and detail the actions required to get to it

**Comment by yairm210** [comment]
Since no answer was given, I'm assuming the former
