### ISSUE TITLE
Crash when buying a tile

### ISSUE THREAD

**Issue by jmuchemb** [yairm210/Unciv#8047]
**Platform:** Desktop
**Version:** 4.3.2 (Build 767)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings - No Religion, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.cityscreen.CityScreen`

--------------------------------

OS: Linux (amd64, 5.16.0-6-amd64)
	Debian GNU/Linux bookworm/sid
Java: Debian 11.0.14.1+1-post-Debian-1
	Max Memory: 3932 MB

--------------------------------

**Message:**
```
java.lang.NullPointerException
	at com.unciv.ui.cityscreen.CityScreenTileTable.update(CityScreenTileTable.kt:78)
	at com.unciv.ui.cityscreen.CityScreen.update$core(CityScreen.kt:160)
	at com.unciv.ui.cityscreen.CityScreen.<init>(CityScreen.kt:137)
	at com.unciv.ui.cityscreen.CityScreen.<init>(CityScreen.kt:37)
	at com.unciv.ui.cityscreen.CityScreenTileTable$askToBuyTile$2.invoke(CityScreenTileTable.kt:133)
	at com.unciv.ui.cityscreen.CityScreenTileTable$askToBuyTile$2.invoke(CityScreenTileTable.kt:134)
	at com.unciv.ui.popup.Popup$addOKButton$cell$1.invoke(Popup.kt:190)
	at com.unciv.ui.popup.Popup$addOKButton$cell$1.invoke(Popup.kt:187)
	at com.unciv.ui.popup.Popup$addButton$1.invoke(Popup.kt:144)
	at com.unciv.ui.popup.Popup$addButton$1.invoke(Popup.kt:144)
	at com.unciv.ui.utils.extensions.Scene2dExtensionsKt$onActivation$1.invoke(Scene2dExtensions.kt:193)
	at com.unciv.ui.utils.extensions.Scene2dExtensionsKt$onActivation$1.invoke(Scene2dExtensions.kt:191)
	at com.unciv.ui.utils.extensions.ActorAttachments.activate(Scene2dExtensions.kt:139)
	at com.unciv.ui.utils.extensions.Scene2dExtensionsKt.activate(Scene2dExtensions.kt:182)
	at com.unciv.ui.utils.extensions.ActorAttachments$addActivationAction$2.clicked(Scene2dExtensions.kt:150)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.unciv.ui.UncivStage.access$touchUp$s80204510(UncivStage.kt:15)
	at com.unciv.ui.UncivStage$touchUp$1.invoke(UncivStage.kt:72)
	at com.unciv.ui.UncivStage$touchUp$1.invoke(UncivStage.kt:72)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.UncivStage.touchUp(UncivStage.kt:72)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:70)
	at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:189)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:378)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:83)

```

**To Reproduce**

1. Load [crash.gz](https://github.com/yairm210/Unciv/files/10079336/crash.gz) (is gzip-compressed fine? btw, I couldn't paste because GitHub complains that the comment is too long).
2. Enter city 'Tamuin' (southern-most territory)
3. Buy the tile to the north of the city (see mouse pointer on the screenshot)
![Screenshot_20221123_224455](https://user-images.githubusercontent.com/11165223/203651362-b407edff-d35b-4d44-bccb-aeccf607298e.png)

**Comment by jmuchemb** [comment]
Note about the save: it was actually played with a custom ruleset that is basically `Civ V - Gods & Kings` without religion (main differences are: religion is off, piety branch is the one of vanilla, items with religion-related uniques are removed, a few buildings like temple are adjusted, no change at all in the code). I think that all the ruleset thing is not related to the crash and I edited the save to make it require `Civ V - Gods & Kings` so you can load it.

**Comment by jmuchemb** [comment]
I forgot to mention that I found a workaround: first buy all possible tiles in nearby city Tula, which I wanted to do anyway this turn.

**Comment by yairm210** [comment]
It;s worse than you thought.
Somehow, tile iron mine + tundra tile was in the list of 'tiles being worked by Tula', even though it *wasn't under the Civ's control*
So even without buying tiles, if you entered any city and clicked on that tile, it would crash

I have no idea what miraculous set of circumstances led to this happening - you can only work tiles under your control, so maybe tiles *left* the city's control somehow, but relinquishing ownership *also* unassigns worked tiles?

In any case we now clean up such occurrences

**Comment by yairm210** [comment]
I see, can you send me the autosave file of the turn before? Like before it finished razing?
Because reading the code, everything should have been unassigned 
Load game - show autosaves

**Comment by jmuchemb** [comment]
I knew I should have kept it. But it was at the beginning of November. Sorry.

I think I was playing with 4.2.16. I'll kept playing with 7a76f247708e78489df1fe7d4750f5a9e0f9963b reverted, so that it crashes if I reproduce the issue.
