### ISSUE TITLE
Crash during AI turn in UnitActions.getRepairTurns

### ISSUE THREAD

**Issue by jmuchemb** [yairm210/Unciv#8064]
**Platform:** Desktop
**Version:** 4.3.4 (Build 769)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings - No Religion, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.worldscreen.WorldScreen`
**Save:** [crash.gz](https://github.com/yairm210/Unciv/files/10099890/crash.gz)

--------------------------------

OS: Linux (amd64, 5.16.0-6-amd64)
	Debian GNU/Linux bookworm/sid
Java: Debian 11.0.14.1+1-post-Debian-1
	Max Memory: 3932 MB

--------------------------------

**Message:**
```
java.lang.NullPointerException
        at com.unciv.ui.worldscreen.unit.UnitActions.getRepairTurns(UnitActions.kt:508)
        at com.unciv.ui.worldscreen.unit.UnitActions.access$getRepairTurns(UnitActions.kt:36)
        at com.unciv.ui.worldscreen.unit.UnitActions$getRepairAction$1.invoke(UnitActions.kt:538)
        at com.unciv.ui.worldscreen.unit.UnitActions$getRepairAction$1.invoke(UnitActions.kt:535)
        at com.unciv.logic.automation.unit.WorkerAutomation.automateWorkerAction(WorkerAutomation.kt:166)
        at com.unciv.logic.automation.unit.WorkerAutomation$Companion.automateWorkerAction(WorkerAutomation.kt:110)
        at com.unciv.logic.automation.unit.UnitAutomation.automateUnitMoves(UnitAutomation.kt:153)
        at com.unciv.logic.automation.civilization.NextTurnAutomation.automateUnits(NextTurnAutomation.kt:872)
        at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:83)
        at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:277)
        at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:594)
        at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
        at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
        at com.unciv.utils.concurrency.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:83)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
        at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
        at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
        at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
        at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
        at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda-0(Concurrency.kt:164)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
``

**To Reproduce**

Just load save and next turn.

**Comment by itanasi** [comment]
Ah, found the bug. Squashed
