### ISSUE TITLE
Crash when clicking on a tile in city screen

### ISSUE THREAD

**Issue by jmuchemb** [yairm210/Unciv#8246]
1. Load [crash.gz](https://github.com/yairm210/Unciv/files/10311391/crash.gz) (too big to copy-paste)
2. Next turn
3. Enter city 'Lampang'
4. Buy the tile to the north of the city (see mouse pointer on the screenshot)
![crash](https://user-images.githubusercontent.com/11165223/209740942-ca2454bc-0bf9-4480-a16d-c179c94f325c.png)

```
version: 4.3.13

java.lang.NullPointerException
        at com.unciv.ui.cityscreen.CityScreenTileTable.update(CityScreenTileTable.kt:78)
        at com.unciv.ui.cityscreen.CityScreen.update$core(CityScreen.kt:145)
        at com.unciv.ui.cityscreen.CityScreen.tileGroupOnClick(CityScreen.kt:368)
        at com.unciv.ui.cityscreen.CityScreen.access$tileGroupOnClick(CityScreen.kt:37)
        at com.unciv.ui.cityscreen.CityScreen$addTiles$1.invoke(CityScreen.kt:304)
        at com.unciv.ui.cityscreen.CityScreen$addTiles$1.invoke(CityScreen.kt:303)
        at com.unciv.ui.utils.extensions.Scene2dExtensionsKt$onClick$1.invoke(Scene2dExtensions.kt:293)
        at com.unciv.ui.utils.extensions.Scene2dExtensionsKt$onClick$1.invoke(Scene2dExtensions.kt:293)
        at com.unciv.ui.utils.extensions.OnClickListener.clicked(Scene2dExtensions.kt:282)
        at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
        at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
        at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
        at com.unciv.ui.UncivStage.access$touchUp$s80204510(UncivStage.kt:15)
        at com.unciv.ui.UncivStage$touchUp$1.invoke(UncivStage.kt:72)
        at com.unciv.ui.UncivStage$touchUp$1.invoke(UncivStage.kt:72)
        at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
        at com.unciv.ui.UncivStage.touchUp(UncivStage.kt:72)
        at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:70)
        at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:189)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:378)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
        at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:87)
```

**Comment by jmuchemb** [comment]
This is a follow up of #8047 (I'm not allowed to reopen it). As written there, I kept playing with 7a76f247708e78489df1fe7d4750f5a9e0f9963b reverted but it wasn't necessary because it also crashes with it. And this time, I send a save at the end of the previous turn, and I also have previous saves if it can help.

Also as usual, I edited the save to change the ruleset to `Civ V - Gods & Kings`. Differences with the ruleset I play should not matter (if you wonder, happiness is 6 and not -7).
