### ISSUE TITLE
Crash bug on opening RekMOD policy screen

### ISSUE THREAD

**Issue by Jehar193** [yairm210/Unciv#8283]
**Platform:** Android
**Version:** 4.3.14 (Build 787)
**Rulesets:** [Civ V - Vanilla, RekMOD, Civ V - Gods & Kings, 5Hex Tileset]
**Last Screen:** `com.unciv.ui.worldscreen.WorldScreen`

--------------------------------

Device Model: CPH2059
API Level: 30

--------------------------------

**Message:**
```
java.lang.NullPointerException
	at com.unciv.ui.pickerscreens.PolicyPickerScreen.drawLines(PolicyPickerScreen.kt:454)
	at com.unciv.ui.pickerscreens.PolicyPickerScreen.getBranchGroup(PolicyPickerScreen.kt:399)
	at com.unciv.ui.pickerscreens.PolicyPickerScreen.<init>(PolicyPickerScreen.kt:244)
	at com.unciv.ui.worldscreen.WorldScreenTopBar$getStatsTable$2.invoke(WorldScreenTopBar.kt:121)
	at com.unciv.ui.worldscreen.WorldScreenTopBar$getStatsTable$2.invoke(WorldScreenTopBar.kt:121)
	at com.unciv.ui.worldscreen.WorldScreenTopBar$getStatsTable$addStat$action$1.invoke(WorldScreenTopBar.kt:98)
	at com.unciv.ui.worldscreen.WorldScreenTopBar$getStatsTable$addStat$action$1.invoke(WorldScreenTopBar.kt:97)
	at com.unciv.ui.utils.extensions.Scene2dExtensionsKt$onClick$1.invoke(Scene2dExtensions.kt:293)
	at com.unciv.ui.utils.extensions.Scene2dExtensionsKt$onClick$1.invoke(Scene2dExtensions.kt:293)
	at com.unciv.ui.utils.extensions.OnClickListener.clicked(Scene2dExtensions.kt:282)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.unciv.ui.UncivStage.access$touchUp$s80204510(UncivStage.kt:15)
	at com.unciv.ui.UncivStage$touchUp$1.invoke(UncivStage.kt:72)
	at com.unciv.ui.UncivStage$touchUp$1.invoke(UncivStage.kt:72)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.UncivStage.touchUp(UncivStage.kt:72)
	at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:426)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:472)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1593)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)

```
**Save Mods:**
```
[RekMOD]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```
H4sIAAAAAAAAAOVdXZPbNpb9K/24WyW4CPBbb44ziZOxxy7bE9dWqh/oFrubE4nsJSU7bZf/+4BfEpu8EA9AKLU1W0m12WoKogjwnHMvLg6+fUpK+X+W5NX62/fVTfY522Zfk31WyBd+/yZ/fyGP9uXhpn2pPecfyS5d/3B85yqtHuRfk7v0dVL/LOvT7ortJs2f36XNm+7KNNm/TYuHbVr/ep9Uf/uclm++5OnmTZndZXmyfZE8ZPtku75NtlW6eii22U3Wvvl/D2m1HzRdplv5liIfvnTI8mrw+z69ua///Zzd7Ivy8fSX7yv5pfZ1w/W32z+Ovt6nQ7bd/yB/bLL8Tp7zNtkmN+n199NXrFtN/3yQX1v+Xv9yWxzy+uwX2ef1+4cky1fZZs3jzU0S+D7bfEoC5vmfXBb5YcB4eMNvNzxyUzdYZdX4u8srSVfb4qbpgPW3P9fR6nHN+PdVXt/x18mmzDby1jwctt0Zp5vRfOts23yx0/vkYVgfiuYwlodOcxSdXoyOL8ajN/Hv16svRflHuvnwpGHn+7X8S3sbX9Qdm8ovvDo3Vtr7Qg0TeSu3RTn+hO4qgvrQPV3w6XDw98GhUH+38MlR9+fw1Ch3jq2Gp1abV53TYfdyfDw3fnrzxPA+Xps/A+04SKr9+zTNf9k9lMXndJfm+/W3G/lqtb4pds8Ouby7z/5VFfmzl0l1/zp5+C2tB7tYyRPLZoQ/uZ3tO/+VfE6ebZP87tl7eVJ+t/qcbA/p+oV8FK5u5BvT8vu1HO4P2+QxLT88PqTrl4ddkg+ex+q+OGw3bx7S/G392uPb7OYP2Zf1Jcv3lcWf2U42tv72/Kt8CKv1P4o8Xf2WbA5f28Ofm3ty9bIoN2n7yqvk6jf5yUnz24Knvf5ZvUurNClv7uWQ/P35XZndHLb7Q1k/wTQUqMfs8ELBocuaoeM3g4A1N94bHLcDjbUDKWx/CcYnBe1xPDgnHjfqD97rDxvt3jwY1u2xNzgefoA3OA6WjNcpZg8GQvPw/x/r3HZwgt3qyvsTNbdKHI/48ch7chQfz2uP3OMRf3IUHt/BneNbwuNR96J7fNFtX/zP66P94/u9ZJC3aSmRLNnWV/OyqGomO8soPWigTyav72o33ptjcXqggsEzNHjOhme7pyelf+L44BR+OqU5FoMWvcHx8JMGFzB8iAefNHg8B68Gg8/x/38MiF/KstE7yXZ1/LtstjiUN+n61/RLui0fz46Whn/AodL0d3uTuXd8/gbjp3m17TIenM4NTthwemy5f3rVP53rnloQTxsLTx8x+LTB5Qw+Iji1658Ow9MJ3n/Y8JCi81CW8rF/28iTTlZustvb5m2P67dS0tykqzvZ579s1kkU38b8Vopw/sljnrfhTL4SstjZSB0eJb4XfWrOfZuU8qfUPnUEkFTpu4McDOl+/S794/WbH1f5YfdJ3qTbF/3YqyRGtwqpCSPuiyrNT/J/rJ1kf9T/X6+qh1R+S9lCvknKTf/96hNlMy+a7y1H+I/FTnZDPYRX7+Wdz/eZ/HarHzM5Tnfy5ZvrVudLvbf+tkseZq79ptXnH7P9/W/ynDpQ8J65z7h39V9NmHMVRuF/r2Q7/fNUrZ9/kgFNku/rV99nX+VAuU+zu/v9WsRdHJJussNuVSbyH3krnNWXbLO/X3tywO6Kjfwu/sv0z6vmiUr31/K8Mv1JXoXs1epddnOfp1KHOs98OVDaj3zyYlXfIx6Ewhe+J7gn46TqPpH38p1Ut1K3ytCnlONn95CWTZN/+3Nf1tq4fX8ghn97f5/d7uWrbhsZSUj5ISt26XN5T9Z+HdpsNx9LeR9b7Vrtk3IvJfGrLv6SX+S6eeOrrNrLfq7v7odUQpEc+W9u0kYUV1kfqQm/gWnZ0zPneQ32z5/XMD5wnmhCkPnzeBsIzJ/otJHM7Ik8bnXm/ImdFJ4/sdPP8ycGrWSdP9FvhfT8iXW3sAg4se4XFgMniuaGA13D264B+qYLQoHOaWNQoHPa+BDonDYsBjqnjcqBzmn6hgOd0/QNBzqn6RsOdE7TNwLpm+bE2a6pTwJ6hbXNAd3C2isE+oU1X1oAHdNAFNBiA1EIlLkglAkQyjgIZQ4IZTxGoSxCoSxEoSxAocxHocxDocxFoUygUMZhKHNQKItRJItQJAtRJAtQJPNRJPNQJHNRJBMoknEMySAUOwIUAmUChjIXhTLhgQDlggAlQIDiIEA5GEDxGAWoCAWoEAWoAAUoHwUoDwUoFwUogQIURwHKQQEqRvEpQvEpRPEpQPHJR/HJQ/HJRfFJoPjEMXwCVRYDZdYRdhCAcmGA8rQAClFaLghkAgQyDgKZgwEZj0Egi1AgC1EgC1Ag81Eg81Agc1EgEyiQcRTIHBDIYhTHIhTHQhTHAhTHfBTHPBTHXBTHBIpjHMMxUGMxUGQd4QkBMhcGMg8FMuGC8CRAeOIgPDkYPPEYhKcIhKcQhacAhScfhScPhScXhSeBwhNH4ckB4SkG0SlC0SlE0SlA0clH0clD0clF0Umg6MQxdAIVFgMl1hF0EHhyYXjyYHjyteAJQXkBwhgHYczBYKyBJzRbhIoiBMYCFMZ8FMY8FMZcEsZeFEm1J9DJr6fumlP6CZ3178/3xXZ7Pd8Ab+HtOOuz/imr7uff1lfLmH5u3GLg6WPfZNvjL893xSHfNzOt51uJSIScnhd2CGl8uQGKnD6KnB6KnC6KnAJFTo4hJ6jpGCjqekCEoNOFodODodNHoVMIEBA5CIgOBog8BgExAgExBAExAAHRRwHRIwGRgBG3BURd9BEkPL7dyp/V6qbI91lel2U6BNT5gw97nWRfUxDrAhQ8fi6Tqtom+UZ5IbEKO18nZXWv3140xtL3+6YCRLOZsAXT6WX9esjvtqn+dQW0Lp3eYb9DV81h4NFYOz3R7bAW7EEVtCKPMIbBoHJloHQ9QisCwvBkbAetCAj7MAgHWiCMpEY5CNYOBtY8BsE6AsE6BME6AMHaB8HaI8FahcHCHry16DwE9RfJfr/VB6QWsL1BQ7+URT5WiS4I4JO+B4GaAv6XmcmNiVS4b9ZcOIb9F8Xtbap/mwNSRM+/z1eKakMe8yY0QAQFMfhxM2LA7bhDVwwIVLZzjDJAyc5AzX5kAoQz4FnvlgkgzvBhzghQzhAcZAIHYwIeg0wQgUwQgkwQgEzgg0zgUUygAni+IEcgtBgCkuHuzJMHsIMzZgeqndc1aCQZkVg14IOITAWDSL0M+LPBarPneVOAfNWUb0+hPJpj3pkO8kk+mHmTR2t9CIUnY33mXWKC3R/v5S2dH8d9GKATZrQobvzssD4iMG9BkegmzuzrCc5+QSW8I0Tgw0QQwEQQahEBUqTlYITBY5AwIpAwQpAwApAwfJAwPIowFEQw6ZEf0yot9wZg01VSEyP7TVJllREtDB/qHx/TiobM1U+FPN4bhCaOHe7pl2laS5X0C0hPKZz7NH2wGinYi2MCy/krf0XNhyKEg2eriNbypFnZ87HIN2m5/qkTClfF7dX/FIf9PUFUuvQmaHoDxmnPcNgtJh7hpwRGpb6ovj/b0JHMqIFPtabksgmWHlXa0z75e5n8keyLhGI5hA/h+t+O1xAGDGAGDFEGbPgKKVeKQV6LQF4LQV4LQF4D11pxcq2Vgq/guGVm7PJ2QRZIVnONcRX1Uc/BHPM5qvDKoLF4THDUXAAZFNGrwchT6fVgIHFQPLSEOIZy92VRVlI0jFJGgVkmavJEzr+vW4S2VF4olqihvKEXT41jKavKg01jLvmcT5J68hFYxihLIjRFxZGST5AkHLyGruMThHlCmHkiLeZBCvljkKEikKFCkKECiqEIpiCX0BHnkUvoFMwjzsfRCN+gDIHQjTOT70CjH/SawChI/CXp+t6pZ9IYHQnOtNa770D3gWRAehkhyFj2IjHP7owSvUIRCXIMpo/6xYtaIf4skw1nj35IcvkfkUOAQ0QsEcKO4drpo7OqyDWDq35qCZSoSiaDuVCZCUQmpOBFmB3DIVwYwlwYoVzYMBdyXgQyXAgyXEAxnIK54OzwZIiKKb09mS//XJSPwJMppuw3lGzPt4ddltfeImayjYRQTq4CRZjQZtzlXCB66A0bT5nMNC1XZZFsakef3h/Hbmazd1ec/RQT9u2d687CGxj+obQLcin16CwpPwguFQnRq3ARbo2WJDknjBubfcFZ4jWIVlkfrtoZpWw6L/ghTfSvSl0tSN91ZaC4hIjhxcYM9nXp6BUh4ggm4liLiCGvighk7BBk7IBibAUTI4zt6TC2IrbE8mycXIcMFs6hCcVXyR9pNSVGg1mLznV3REFQM0OhPTC9Xe2ybbZPysd/5lntstvazL3uzxSrXXf4Ot0Vrbnutwkr8tqhrnFI+5iUZVaUq6Lz1BsSZTE4lteyK+o2qsb9kGgRY3PDmbohgv2c7qpLfVgwpvX6w8xo2B6reypWX0C7k6caoV1druYWuVoxtWkgctkxzD47I4BR6wQT5kLaY5UlFtLOXUW/ZmqkrMGkEMHTvh5PEy3ApkUd+yI8HcE8HaM83a6NRNduI+wbUOyrYFV4nWA/AJr9DpLcEPU7b9Ye9d+ndQ3cGPVb79licDxCfeVz3jm/WgKo3nTWVnOkhwCtLkgbAYUcmATq0/NIF4HpaZG5SpgwJULEphF1MKZicvGB1WB2eWFSZ3+weOmFq2Jh07sptKZ+EarV4+dHGyvkWB9B24xXn2SgknLzpSg26H3H+Bcu0ZtrztOjc+CG+hNGp5Nw40U+QNO9r9f5rBVB6bCjakfUCKXHMKV3k3Qwp6OGBxD5ByD5+yD5d0bt5yYIx4v85x591y77CrvsS1pfIHnoOein6RZgZdIUg/4m90n1Q7HfF7t3ta/4u+xzt3/M8A/H18ZcTE3k0aClnlDVXQjQ+W5YDT1VpZLGmXl3TMkmSUmlzYdhrnvi+mEx1z2qydKp9zG+yUwz+gZaFCquX0LFtgoQmafH7HNSpLctOd9toNqdghBTuNgB3dDbBy+I8qOO0M2z8TFM9B19ozVQEH0HKH37IH17IH27OrE7SLYGy+c46bOCsOoQds1qprpdfnTQCihlWsZZRzp+ld7uz1AyN5qxVbU+JwIChQiACwJodxlkGYiAQqjlLG6AX7RTDUjQ2gVmVovLWBdmL46a+1nsRdVRk9Jq6nnGWHMJCSs1MkGn3E7yiHgCjJU6650drQ2S3mdb10iBwTucdOwLuSQ4OFHD3jotUcMWLqiHC8ToHsXoCqam1C/J1Oq55sndUCeOTXjcORNsGyNzPOJ5g+mt6AzJQzeP9PhRxrm64bgmEfsaRKyZCJgwLxWAGNUmuWMe1yzeBZmY6uUlITQVl+jngimqh+Z1DR5C1k1uW7sPzFWF3uhaVYxTPVIAEGHhVqq/q4fm9i358FkqVfsf6bL4GR3PFM6jc8ND4S8PdGe/sQ/YnwSzxzCzd3wNUTvsgNTSMGy0gxgn9BsCH8ceZlPZ7TKMsfKHQ74pk/PB81BE/3Qox8U6iMVCOCOhacYnrZVm1HZsNbXebf1rC7XCUc59yapEbC7ZcI2lMlReqCLGVG5JMZz5FKUN1SL5J8bCwVYVP9fSC3P8PpeJguh+aBBCVz4tS6IrJ+kNY0N3kkBYVHBuTtX0eu5zauAcJfuqmQHD2xRoCQk4JufLy0BYv93W+dzNDHWxftfT8ytF54VFJxe880SsFg+QzsD3lWh0BurjhPgUtzoDdryYUwzuWLXUmGGgOnS94Djp0wXmByYpCCwDECxNAc+ImUghZtDZNmwlaagQOUtq2PCFLFiVGuxKhE2421uO7ipUjOHF9e5ml5gi79SFdnh2pj7B2hhkysSGBXFhsYSBuSq1YlSMp7WUfm6ewR/PeBjkKlDhoIvOTL0ZinHfRhPB8aE83N5uKQM/44KMfmtisMPnREknJsarCQAVAlo7n8QEut/0VEyoNMIEOYhvC7o4up3mOJtAR2SCtj1ecyO1xQVploaJhJlSRNSrBJAKFCwZ1siGCuVhCJuB3TyKP8qjXCAs9RYXTIxVgoXISOUmt2QywZYUUhRFmvKsXiIEVQLe7KAxZiPl4gWT9XMTVwCT4gVfJS6Mav96l29bCMOUO/+Y3LBIKS8MsxmKvcFBfgfC7p7RkT2pObwVEOPwVpYt+aObKkMqwW1VgsW5hyca4Z9lkmdTQxjP3lPcOr3gKhWRDXg1L6YnIrPoENAPlgKRUEeKzNxB0ooPEwgG9W+eRkkGRvoGc6E6Fn4Yxw+zcfrrACxqhJ7XhYUkse3KCjZZMmF6ZVpmAhCJG66ZgCh9LjwxJHa4NANidlsyIe5kghmrT9y1QFxXkz/MlWpRAOkHeDvXluvRrcwhUSC0RIFis2B8fgLM+D+ZorBe9hUreH/ZVAD1TBny81xBxkwTgYLiDZ7JzorwMglvT5F3MCd0e/JAWM0wcLw443irzVb7M2XaYFFobsnSFyV6F5q6M84G9JYIVnJ7rDcdXPLIMqUPvlE6QLm7mGk6ICKrJSBCN3QXRIa6ozltoaZ6mMDUVA9UF/ZUD6kCT08VIDkFF5UPApUPnJx50CnUmXL/0qXpY6pHfSihBlsnwvOLeAg0BIUAdAmhQmyYIEWgSCyYtOVryA5MHFic43Ctag0xmuIw3c3YZu3E0zmMy5I0V0x1GAL5Zesq2GQhyYUWhDJvrF3UU97mi4VZ565oIjCWqhTlrnGLdEUI3THTsRpbTXi0miNeOpjUSoR6rDSVCLDcsFcikGjxUNHSCgxEiQhSiagExuSjiZQQUqbb6gtxvrzDcFVOrMqD2K2YjybZkcWr+MfaIp4jNsMi6cBeksQfJUnspV07J8ezKImpDYviRdgt0OCKTImh7KAUzCLTnsspAVWJxhJhYTPXMrGusPv1e0dJG5lB1m/dcCJCaJUNJDHgsuq51qLJBE22/awqRzKar0CnZTFhQeGj+bM02d1Bw3JCQ7iI5cJFseu7Wo1AwsXXEy7IAg+BKhyOKhynVTh2yjLiscCpl4TajD6icdkHukrSdLImHAueSyzlCBQzQqZpEEsyZ+yVaU/mqCwzDeM4lWWmaadzm4LHaL8MpsrNaBhYMkFN+9CntitVDBWDxQoQpX+mUbQ82U4Ct4vCHCDCsQgxeESWOcu3EsOfsZb/udhu0vxKSqRN2jnMP3npjNG88kYs3AhlfOH0TiiaF059gHmtGTYG4hVle2LcXCvE7O2g2cmwyLyiQam5kI1/ee8yCksrSIX5qAprFRMirTgqrRxQWsVk7ggROH9BsjhU5YtM5qA7O1BruRW0ogvQL7ZmqlTGoyZ1q2KU5KFyaMB+AwZejIZUBeoVrGxi+ZrNy2UouqU49mLgzsfkkgkVmwmgQCW/TFIK/R6dF05Jtzy/pJwG+pRYpSYsf5uW/5csIjZ16euUgj13FEIyRE9C99vbFLDl5L3Rqnl+x8NFiI+LkEBPhCDGnhxVKw6oVmJQrERaaSBQX1wMqINxGsheasIfJ3yAundAh9hK76hsVU3aEuP8jr3kNB9JnEuamdn0dGOq1M+iTRvcOdQDpYnNNbR2nU7YcovXqRCxqWy6bUw1SSsaJ5BMqlZilT5ZVHeqb8862WFlQfGgMicAbGvcETqylzP34DyDj1O8wsBURccIbzsgb8cgbUcgbYcmOQbajRRYiqG93erEpdTAaLC1LL1I8rQ1MD2fOn3+dZ/eVF3usfvlTLp0YVb06RX9mtwdEt0LGhz//lFG4NUuya9HudHuY7QpXZWWNIzn8YLd46zFsKG8fkey/VjkG3krmlOu/p5k26S6n5K6wUJhpip8WZBdsLdEiHmjVMilUi6ktSsy9WKY+MDcoi6z6jVaUAED6YC52ai5Rlryt6kmeh9Xi1G+iQk8n1iz4o4OqA0498Y5CNCs04dlSIDLkFBPhiD7bzqgXolBuRKBciUE5QrtT4oojwUbMQD7NaGLfsa6hJz0MLoKI1fT1dR/3TI/U4RvHApzRdXHgmrKZZE/aD+pWryzJPR2LzopoB3oBhrZAISfHbMw03BJSjRWBMZhurBCz7ZqXHlnfGrwqPXeppea7uutTo/ta9vsKfkZ3t9RydRQaoG2KlUTNbI5lgMSdQzydATydEjytIJ/KSgj7y/Cy3M7VpjvKDfhaMuOiwaUL8bpDJpxzezAKAFgXJuG14CCvG1ggs6Egu+XeDP4f0HAa9cYhPmKsH/JJL3NOXpbvB9pTAFgXkyWbLJaUrZ1y3jvProkqdkRtM04XstjVEm+1POqR74ArXXkC9F0CNN0pEfTQJsxSOcRSOchSOcBSOe+TTr3VBUACzjWHmX3fp92om2lkyfcmuHOP0+Xt9osr1HUBSyIrS3WILujcoClu40xzzCj75+hdnPBoNrUZMFmSTZcMCMFuRutpYhHUf0l1kH1lkq2ll/yiaGo5ShY6TO6iMQNq3SVnA5tMuWTiXsld0MsH8IsH4EsH4PMHYHMHYLMHYDM7YPM7WkxN8i2rmEtF1AmZlrKh/Awzuqa4fAcFZMKwMyWZWVM7CAZW+R21zCc93TCeZq2fYq26VPbXUHMyNNmtB2dibbNFUO8euozoek7BPGopQU5vTOQrdZ6Q0+M4mHSXLI9NFc6cuqFvhDRBjDRhjDR0v6Y1JmxBtEKIJaOQEIOQUIOQEL2QUKmzSmnY4D2pgTjUsPJPIQcwT0CzDlwiEK2Nipmyvh6iQswVUJvPBetqqNfUItluTiuo0uLE+bB5fLnxmuOVPuLLrtx0ZmAfBlpoxktiKGtcaqOISYttzoXHUyb8c7SEmVWeF2Rklmh3Y0CmINDmIMjmINjkIMjkFlDkFkDkFl9kFk9kFlps8XpGBBaoS7hULSiasZ03ItnOVCMJ3OIOd1l+6IqA90lhGiVYd1xCAtbpUyIcFiTdlkjYN9umjowT1ODkalqfu6vIdvI7sR2vHpax3Zh02dnRRS2QdQIJ5RVy5pgc7nJ5XCKOS06TI7bn1g4Pt8edlk+LaNGV19St0Rp5AiTegCTegiTegSTeoySunB0SB0o5Q5B8g9A8vdB8vdA8keNCGEfQjKsHo8pnaXnsw/8gmw1yrs2iVxZRr6kupgKlZdwLOxfDpKsoccESLIWQ+boDGfrVAnoMnVMZb+XeYoZuRByI84Vo+w2VSClWhcMU60y2pzAsJLChjDxNk3KbYVSF7SFTgiTXASTHO02p6QusCgJoa4ApC4fpC4PpC4XpC7Y6A2iLmw9E6ODU+LEpRsdMp2aZXBdy2R1tvUFRB19oH5uIHtYdakOFSHkkvlCxA1yAvfDzOwvn4vyUdHGQr/Qhgu8mUXvr5Kr32QbSbfK/Pgr4hOq7TrlGM708rHnnIGPXstVUCaz9YYDILr1fEMzm7jTFOQ5HsLsFMHsFKPsJByYnbgOOwHfPABZzAdZzANZzAVZDHYAg1gMC74YHX1R3UHSGHGiS85JEo+Lp4qTDAucWO/LZZNILleyE47SoJdaqhKNgykia4uQjzZjNagNVuBivoecogFVQg6RXNyloF2F2LDtsIbFEAzY0FVGMLTHKLQL2kpKCdjg2gUEsH0QsD0QsF0QsAUI2Jj1ExZyMNRbmtEbk6mAGBkMHorYvhZiEw0oXaBNIX+8G9iyWmjVJuno14sVgYLpt2sQNLAzfaLaz49KXRlfb+eGdLxehT8LseLXeMrHXY3NE81tJFX5IjgoVxECrOA1XGFgPoCYI0aZQzgwc3CYOWhLIAVzAFfpgwzjgQzjggwjQIbB3HqwcIChhsAMnZFh6C7czEMpxicphjgxIHNYxIM52XWJ8GlSQPwSn+h4RdjiUbjhrIgSehUIw0tqVWIXRnGVCIZkdedKswwLITgKUNAMUdCMYNCMUdAUDgyatEuLEgqBh9QHodADodAFoVCAUMghKMSENkNNVhma4WfoPsDMQ7HQR7GQ9lYlTgxJLCRO7LbcxdALWijvUDBHnUgaf1AnCiqFQJ3oUlkDVUgOJSd9KhugQh04hQoLMAieYhSehAPDE4fhScDw5OrAE9CiB8KYC8KYAGGMQzCGqTmGmi8yNMXL0CIbRi9eUcET0sW0AaMKnpCBGKE4FqM41uAT1DMcBTKBApmLAhlpQKDCJ7h6HS4rgBOGsChCekY4MJBxGMgEDGQuCGQeCE8uCE8ChCcOwROmsBgmsXrYQZ4CtJCCoSsAGL3aXQU7yFNA+9mrYAcZXzGKT+2KHKhrSK82Fe5AAEWuyVbhDgRQ5FJrFe7AlbjwzDKcl4JlEQRQHAYoAQOUCwOUpwNQQOe4IJAJEMg4BGSYxmKYyOoBCnlc0Ll0hlYzM3SVMKMdt1QAhTwuEYpkMYpkLUBBXcNhKCN9p1UIBW/ZAkGZj0JZgEJZiEJZhEJZDEKZcFAo4yiU0QsylQAFXWW3GvP79ffv/waEGXrD0TkBAA==
```
</details>

**Comment by yairm210** [comment]
Resolved in 4.3.14-patch1
