### ISSUE TITLE
an error that I don't understand.

### ISSUE THREAD

**Issue by tuporis** [yairm210/Unciv#8404]
**Platform:** Android
**Version:** 4.3.21 (Build 795)
**Rulesets:** [The Undead, Civ V - Vanilla, RekMOD, Upside Down, Brave New World, Medieval Civilizations, AbsoluteUnits, DeCiv Redux, Community Maps, Civ6 mod, Extra Buildings, Latin American_Civs, Ancient Civilizations, Civ V - Gods & Kings, 5Hex Tileset, DeCiv in Alpha Frontier]
**Last Screen:** `com.unciv.MainMenuScreen`

--------------------------------

Device Model: STK-LX1
API Level: 29

--------------------------------

**Message:**
```
com.unciv.logic.UncivShowableException: Здание 'Personnel Office' можно построить и поэтому должно либо иметь явную стоимость, либо ссылаться на существующую технологию.
	at com.unciv.models.ruleset.Ruleset.updateBuildingCosts(Ruleset.kt:420)
	at com.unciv.models.ruleset.RulesetCache.getComplexRuleset(Ruleset.kt:576)
	at com.unciv.models.ruleset.RulesetCache.getComplexRuleset(Ruleset.kt:556)
	at com.unciv.models.ruleset.RulesetCache.getComplexRuleset(Ruleset.kt:538)
	at com.unciv.ui.newgamescreen.NewGameScreen.<init>(NewGameScreen.kt:54)
	at com.unciv.ui.newgamescreen.NewGameScreen.<init>(NewGameScreen.kt:49)
	at com.unciv.MainMenuScreen$newGameButton$1.invoke(MainMenuScreen.kt:160)
	at com.unciv.MainMenuScreen$newGameButton$1.invoke(MainMenuScreen.kt:159)
	at com.unciv.ui.utils.extensions.Scene2dExtensionsKt$onActivation$1.invoke(Scene2dExtensions.kt:193)
	at com.unciv.ui.utils.extensions.Scene2dExtensionsKt$onActivation$1.invoke(Scene2dExtensions.kt:191)
	at com.unciv.ui.utils.extensions.ActorAttachments.activate(Scene2dExtensions.kt:139)
	at com.unciv.ui.utils.extensions.Scene2dExtensionsKt.activate(Scene2dExtensions.kt:182)
	at com.unciv.ui.utils.extensions.ActorAttachments$addActivationAction$2.clicked(Scene2dExtensions.kt:150)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.unciv.ui.UncivStage.access$touchUp$s80204510(UncivStage.kt:15)
	at com.unciv.ui.UncivStage$touchUp$1.invoke(UncivStage.kt:72)
	at com.unciv.ui.UncivStage$touchUp$1.invoke(UncivStage.kt:72)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.UncivStage.touchUp(UncivStage.kt:72)
	at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:426)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:472)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1592)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1281)

```

**Comment by yairm210** [comment]
The 'Personnel Office' building can be constructed and must therefore either have a clear cost or reference existing technology.

This is a bug of the mod that introduced this building, not of the Unciv framework
Please notify the mod owner
