### ISSUE TITLE
Feature request: Port to Haiku

### ISSUE THREAD

**Issue by nephele-gh** [yairm210/Unciv#8432]
Hi!
I would like to ask if a port to Haiku could be considered, recently there has been interest in the Haiku forum (and of myself, I currently play unciv on linux by dual-booting)
https://discuss.haiku-os.org/t/porting-unciv-to-haiku/12558

Haiku has fairly good POSIX compatibility, we have openjdk11 ported but we do not have android studio.
A build fails fairly quickly with an unknown platform error.

I'd be happy to help in this regard, though note that I know basically no java or kotlin :)

An attempt to run the jar also fails fairly quickly with the same reason.

```
~/media/dl /system/lib/openjdk11/bin/java -jar Unciv.jar
Exception in thread "main" java.lang.LinkageError: Unknown platform: Haiku
        at org.lwjgl.system.Platform.<clinit>(Platform.java:91)
        at org.lwjgl.system.Library.<clinit>(Library.java:33)
        at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:100)
        at org.lwjgl.system.Pointer$Default.<clinit>(Pointer.java:67)
        at org.lwjgl.system.Callback.<clinit>(Callback.java:40)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:84)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:138)
        at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:87)
~/media/dl 
```

**Comment by yairm210** [comment]
Seems pretty clear that the OpenGL wrapper, lwjgl, doesn't support Haiku
Looking through their issues I don't see anything open about that - same thing with LibGDX - but this is 2 levels "below" Unciv, and definitely out of scope for us

Our official answer on this is "we support whatever LibGDX supports", and since a quick Google doesn't show anything in lwjgl or LibGDX that supports Haiku, neither can we :/

**Comment by nephele-gh** [comment]
Thanks for the explanation, I'll investigate if porting those is feasible :)
