### ISSUE TITLE
Mod refusing to start, no errors on mod checker

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#8444]
Windows 10 64-bit, itch.10 version 4.4.4

I've changed something in DeCiv Testbed that's causing the mod to not open. I get the "Maybe you put too many players into too small a map?" pop up when I try to start a new game. However, the mod error checker isn't seeing any errors.

I ran it in the terminal and I got this error message.

`java.util.NoSuchElementException: Collection is empty.
        at kotlin.collections.CollectionsKt___CollectionsKt.random(_Collections.kt:560)
        at com.unciv.logic.map.mapgenerator.MapRegions.placeStrategicAndBonuses(MapRegions.kt:1320)
        at com.unciv.logic.map.mapgenerator.MapRegions.placeResourcesAndMinorCivs(MapRegions.kt:836)
        at com.unciv.logic.map.mapgenerator.MapGenerator$generateMap$13.invoke(MapGenerator.kt:153)
        at com.unciv.logic.map.mapgenerator.MapGenerator$generateMap$13.invoke(MapGenerator.kt:152)
        at com.unciv.logic.map.mapgenerator.MapGenerator.runAndMeasure(MapGenerator.kt:199)
        at com.unciv.logic.map.mapgenerator.MapGenerator.generateMap(MapGenerator.kt:152)
        at com.unciv.logic.GameStarter$startNewGame$3.invoke(GameStarter.kt:66)
        at com.unciv.logic.GameStarter$startNewGame$3.invoke(GameStarter.kt:63)
        at com.unciv.logic.GameStarter.runAndMeasure(GameStarter.kt:144)
        at com.unciv.logic.GameStarter.startNewGame(GameStarter.kt:63)
        at com.unciv.ui.newgamescreen.NewGameScreen$startNewGame$2.invokeSuspend(NewGameScreen.kt:268)
        at com.unciv.ui.newgamescreen.NewGameScreen$startNewGame$2.invoke(NewGameScreen.kt)
        at com.unciv.ui.newgamescreen.NewGameScreen$startNewGame$2.invoke(NewGameScreen.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
        at com.unciv.ui.newgamescreen.NewGameScreen.startNewGame(NewGameScreen.kt:259)
        at com.unciv.ui.newgamescreen.NewGameScreen.access$startNewGame(NewGameScreen.kt:46)
        at com.unciv.ui.newgamescreen.NewGameScreen$4$5.invokeSuspend(NewGameScreen.kt:196)
        at com.unciv.ui.newgamescreen.NewGameScreen$4$5.invoke(NewGameScreen.kt)
        at com.unciv.ui.newgamescreen.NewGameScreen$4$5.invoke(NewGameScreen.kt)
        at com.unciv.utils.concurrency.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:83)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
        at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
        at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
        at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
        at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
        at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:164)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
`
Here's the tweaked mod that's causing the errors.
[DecivNotStarting.zip](https://github.com/yairm210/Unciv/files/10475309/DecivNotStarting.zip)

**Comment by yairm210** [comment]
I managed to start a game with testbed...?
What map setup do you have?

**Comment by yairm210** [comment]
These are mine
![image](https://user-images.githubusercontent.com/8366208/213941721-8469ddf5-4212-4826-8a95-af7223365db4.png)

**Comment by yairm210** [comment]
Tried several times, different configurations, never failed

**Comment by SpacedOutChicken** [comment]
Did you use the tweaked mod that I attached? Sorry if I didn't make it clear, but the error is in the mod I attached. I haven't pushed the changes to the main Github repository yet.

**Comment by yairm210** [comment]
Yes, I used ot

**Comment by yairm210** [comment]
Ahhh it's because I didn't have citystates enabled
Found the error

**Comment by yairm210** [comment]
You don't have any lategame revealed resources anymore :)

**Comment by SpacedOutChicken** [comment]
Can you help me understand why the attached mod is failing while regular DeCiv isn't causing the same error? I am confused.
