### ISSUE TITLE
Crash when open unciv

### ISSUE THREAD

**Issue by AdityaMH** [yairm210/Unciv#8570]
**Platform:** Android
**Version:** 4.4.9 (Build 806)
**Rulesets:** [Pix5 Tileset, Civ V - Vanilla, maps, RekMOD, Simple Music, AbsoluteUnits, Nat5 Music, Community Maps, Thin Bubbly Borders, Civ Army Color Style Sheet, Alpha Frontier, Gold UI, Nat5 Design, Civ5 Set, Civ V - Gods & Kings, TextDev]
**Last Screen:** `com.unciv.MainMenuScreen`

--------------------------------

Device Model: M2010J19SG
API Level: 29

--------------------------------

**Message:**
```
java.lang.Exception: Cannot create map - no Land terrains found!
	at com.unciv.logic.map.mapgenerator.MapLandmassGenerator$Companion.getInitializationTerrain$core(MapLandmassGenerator.kt:32)
	at com.unciv.logic.map.mapgenerator.MapGenerator.<init>(MapGenerator.kt:39)
	at com.unciv.MainMenuScreen$1.invokeSuspend(MainMenuScreen.kt:123)
	at com.unciv.MainMenuScreen$1.invoke(Unknown Source:8)
	at com.unciv.MainMenuScreen$1.invoke(Unknown Source:4)
	at com.unciv.utils.concurrency.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.$r8$lambda$nwZVoCWi6P2779l7sK5tCF-sQTA(Unknown Source:0)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```

**Comment by yairm210** [comment]
Did you change the files for the Vanilla or G&K terrains? That's what this looks like

**Comment by AdityaMH** [comment]
no, i'm just change civlopedia text for unit

**Comment by yairm210** [comment]
I think you somehow ruined the terrains.json file, because that's what this is saying - the default ruleset has no land terrains.
If you download a clean version of Unciv and take the terrain file from there it should work
