### ISSUE TITLE
Crash with NullPointer when pressing Air Sweep button

### ISSUE THREAD

**Issue by N1cc3** [yairm210/Unciv#8650]
**Platform:** Android
**Version:** 4.4.12 (Build 809)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings, 5Hex Tileset]
**Last Screen:** `com.unciv.ui.worldscreen.WorldScreen`

--------------------------------

Device Model: SM-G973F
API Level: 31

--------------------------------

**Message:**
```
java.lang.NullPointerException
	at com.unciv.logic.automation.unit.BattleHelper.getAttackableEnemies(BattleHelper.kt:93)
	at com.unciv.logic.automation.unit.BattleHelper.getAttackableEnemies$default(BattleHelper.kt:34)
	at com.unciv.ui.worldscreen.WorldMapHolder.updateTilesForSelectedUnit(WorldMapHolder.kt:665)
	at com.unciv.ui.worldscreen.WorldMapHolder.updateTiles$core(WorldMapHolder.kt:561)
	at com.unciv.ui.worldscreen.WorldScreen.update(WorldScreen.kt:423)
	at com.unciv.ui.worldscreen.WorldScreen.render(WorldScreen.kt:846)
	at com.badlogic.gdx.Game.render(Game.java:48)
	at com.unciv.UncivGame.access$render$s2211858(UncivGame.kt:50)
	at com.unciv.UncivGame$wrappedCrashHandlingRender$1.invoke(UncivGame.kt:91)
	at com.unciv.UncivGame$wrappedCrashHandlingRender$1.invoke(UncivGame.kt:91)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.UncivGame.render(UncivGame.kt:394)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:474)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1593)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1287)

```
**Save Mods:**
```
[Civ V - Gods & Kings]
```

**Save Data:**
https://drive.google.com/file/d/14ddajhIvpzDMsDZpTlP9TH7M2Fvjbarm/view?usp=drivesdk

**Steps to reproduce**
In saved game provided above select the triplane in Lyon and press Air Sweep. Boom crash.

**Comment by kazewolf1** [comment]
> 
What about the update for Google play?  Seems we had to wait on that longer that the other updated locations.

**Comment by N1cc3** [comment]
> Already fixed. Please update the game

Nice to hear it's already fixed!
I have the newest version available in Google Play. I'll continue the save when newer version with the fix arrives.
