### ISSUE TITLE
NPE On Triplane Air Sweep

### ISSUE THREAD

**Issue by master-bob** [yairm210/Unciv#8673]
**Platform:** Android
**Version:** 4.4.11 (Build 808)
**Version:** 4.4.12 (Build 809)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.worldscreen.WorldScreen`

--------------------------------

Device Model: LG-H910
API Level: 26

--------------------------------

**Message:**
```
java.lang.NullPointerException
	at com.unciv.logic.automation.unit.BattleHelper.getAttackableEnemies(BattleHelper.kt:93)
	at com.unciv.logic.automation.unit.BattleHelper.getAttackableEnemies$default(BattleHelper.kt:34)
	at com.unciv.ui.worldscreen.WorldMapHolder.updateTilesForSelectedUnit(WorldMapHolder.kt:665)
	at com.unciv.ui.worldscreen.WorldMapHolder.updateTiles$core(WorldMapHolder.kt:561)
	at com.unciv.ui.worldscreen.WorldScreen.update(WorldScreen.kt:423)
	at com.unciv.ui.worldscreen.WorldScreen.render(WorldScreen.kt:846)
	at com.badlogic.gdx.Game.render(Game.java:48)
	at com.unciv.UncivGame.access$render$s2211858(UncivGame.kt:50)
	at com.unciv.UncivGame$wrappedCrashHandlingRender$1.invoke(UncivGame.kt:91)
	at com.unciv.UncivGame$wrappedCrashHandlingRender$1.invoke(UncivGame.kt:91)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.UncivGame.render(UncivGame.kt:394)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:474)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1571)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)

```
**Save Mods:**
```
[Civ V - Gods & Kings]
```

**Save Data:**
[NPEOnTriplaneAirSweep-#8673-SaveData.txt](https://github.com/yairm210/Unciv/files/10726163/NPEOnTriplaneAirSweep-.8673-SaveData.txt)

Please let me know if I borked the save data transfer.

**Steps to Reproduce:**
1. Go to Yokohama, lower left side of the map
2. Select the Triplane
3. Select Air Sweep
4. Witness complete destruction in the form of an NPE

**Comment by vegeta1k95** [comment]
Please, update to latest version 4.4.14, it is fixed.

**Comment by master-bob** [comment]
Cool! I'll do so as soon as it hits the Fdroid. Cheers. 👍
