### ISSUE TITLE
Game crashes when performing "air sweep" by a jet plane

### ISSUE THREAD

**Issue by jcalve** [yairm210/Unciv#8682]
**Platform:** Android
**Version:** 4.4.12 (Build 809)
**Rulesets:** [The Undead, Modern Civilizations, Civ V - Vanilla, Tyretes Tileset, Brave New World, Medieval Civilizations, AbsoluteUnits, DeCiv Redux, 3rd and 4th Unique Component, Civ6 mod, Epic of Fantasy, Alpha Frontier, Ancient Civilizations, Civ V - Gods & Kings, Maid Empire]
**Last Screen:** `com.unciv.ui.worldscreen.WorldScreen`

--------------------------------

Device Model: MI 9
API Level: 29

--------------------------------

**Message:**
```
java.lang.NullPointerException
	at com.unciv.logic.automation.unit.BattleHelper.getAttackableEnemies(BattleHelper.kt:93)
	at com.unciv.logic.automation.unit.BattleHelper.getAttackableEnemies$default(BattleHelper.kt:34)
	at com.unciv.ui.worldscreen.WorldMapHolder.updateTilesForSelectedUnit(WorldMapHolder.kt:665)
	at com.unciv.ui.worldscreen.WorldMapHolder.updateTiles$core(WorldMapHolder.kt:561)
	at com.unciv.ui.worldscreen.WorldScreen.update(WorldScreen.kt:423)
	at com.unciv.ui.worldscreen.WorldScreen.render(WorldScreen.kt:846)
	at com.badlogic.gdx.Game.render(Game.java:48)
	at com.unciv.UncivGame.access$render$s2211858(UncivGame.kt:50)
	at com.unciv.UncivGame$wrappedCrashHandlingRender$1.invoke(UncivGame.kt:91)
	at com.unciv.UncivGame$wrappedCrashHandlingRender$1.invoke(UncivGame.kt:91)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.UncivGame.render(UncivGame.kt:394)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:474)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1573)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)

```
**Save Mods:**
```
[The Undead, Modern Civilizations, Ancient Civilizations, Medieval Civilizations, AbsoluteUnits, Civ V - Gods & Kings, 3rd and 4th Unique Component]
```

**Comment by alexban011** [comment]
Already resolved. Update your game
