### ISSUE TITLE
Crash on attempt to start new game

### ISSUE THREAD

**Issue by Durptron3000** [yairm210/Unciv#8755]
**Platform:** Android
**Version:** 4.4.19 (Build 818)
**Rulesets:** [The Undead, Anime Multiverse, My Uncivilized Pony, Civ V - Vanilla, Additional Music Ambient, capture GP, Repairing Improvements in older mods, Upside Down, No Fog Of War, Scouty Scout, Resource Recyclers, Barbarian xp farm, Civ V - Gods & Kings, Closer Cities Distance of 1, My Uncivilized Ponies, Maid Empire, Only Mod Civilizations, The Barbarians, Outpost Mod, Difficulty_Sandbox, Strategic Resource Visibility]
**Last Screen:** `com.unciv.ui.screens.mainmenuscreen.MainMenuScreen`

--------------------------------

Device Model: SM-S102DL
API Level: 30

--------------------------------

**Message:**
```
kotlin.UninitializedPropertyAccessException: lateinit property ruleset has not been initialized
	at com.unciv.models.ruleset.unit.BaseUnit.getRuleset(BaseUnit.kt:56)
	at com.unciv.models.ruleset.unit.BaseUnit.getType(BaseUnit.kt:36)
	at com.unciv.models.ruleset.unit.BaseUnit.matchesFilter(BaseUnit.kt:297)
	at com.unciv.models.ruleset.Ruleset.add(Ruleset.kt:165)
	at com.unciv.models.ruleset.RulesetCache.getComplexRuleset(Ruleset.kt:591)
	at com.unciv.models.ruleset.RulesetCache.getComplexRuleset(Ruleset.kt:574)
	at com.unciv.models.ruleset.RulesetCache.getComplexRuleset(Ruleset.kt:556)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.<init>(NewGameScreen.kt:51)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.<init>(NewGameScreen.kt:46)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen$newGameButton$1.invoke(MainMenuScreen.kt:165)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen$newGameButton$1.invoke(MainMenuScreen.kt:164)
	at com.unciv.ui.components.extensions.Scene2dExtensionsKt$onActivation$1.invoke(Scene2dExtensions.kt:193)
	at com.unciv.ui.components.extensions.Scene2dExtensionsKt$onActivation$1.invoke(Scene2dExtensions.kt:191)
	at com.unciv.ui.components.extensions.ActorAttachments.activate(Scene2dExtensions.kt:139)
	at com.unciv.ui.components.extensions.Scene2dExtensionsKt.activate(Scene2dExtensions.kt:182)
	at com.unciv.ui.components.extensions.ActorAttachments$addActivationAction$2.clicked(Scene2dExtensions.kt:150)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:18)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:90)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:90)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:90)
	at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:426)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:472)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1591)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)

```
Note: while I do have mods, none are set to be "permanent audio-visual" so I can't really deactivate any of them.

**Comment by yairm210** [comment]
Resolved in 4.5.0-patch3
