### ISSUE TITLE
Exception when gifting a city to ai opponent

### ISSUE THREAD

**Issue by dCSeven** [yairm210/Unciv#8830]
In the attached savegame, gifting the city Douglas to the Celts, leads to this exception.
(Next turn)
>Thanks for the game, it is really great :)

**Platform:** Android
**Version:** 4.4.19 (Build 818)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: SM-G781B
API Level: 33

--------------------------------

**Message:**
```
java.lang.Exception: Got an offer for city id c6aedbbf-8844-4962-97ef-2cbd659cca49 which does't seem to exist for this civ!
	at com.unciv.logic.trade.TradeEvaluation.evaluateBuyCost(TradeEvaluation.kt:139)
	at com.unciv.logic.trade.TradeEvaluation$getTradeAcceptability$sumOfTheirOffers$2.invoke(TradeEvaluation.kt:65)
	at com.unciv.logic.trade.TradeEvaluation$getTradeAcceptability$sumOfTheirOffers$2.invoke(TradeEvaluation.kt:65)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.SequencesKt___SequencesKt.sumOfInt(_Sequences.kt:3046)
	at com.unciv.logic.trade.TradeEvaluation.getTradeAcceptability(TradeEvaluation.kt:65)
	at com.unciv.logic.trade.TradeLogic.acceptTrade(TradeLogic.kt:148)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.respondToTradeRequests(NextTurnAutomation.kt:127)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:57)
	at com.unciv.logic.civilization.managers.TurnManager.automateTurn(TurnManager.kt:296)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:299)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:621)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:8)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:4)
	at com.unciv.utils.concurrency.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.$r8$lambda$nwZVoCWi6P2779l7sK5tCF-sQTA(Unknown Source:0)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```
**Save Mods:**
```
[Civ V - Gods & Kings]
```

Save game attaching the way it was supposed to do, isn't working here, due to the 2^16 Characters limit..
I attached the save.

**Comment by yairm210** [comment]
Ohhh that's the bug
Solved in 4.5.2, please upgrade :)
