### ISSUE TITLE
Crash when loading or starting a save

### ISSUE THREAD

**Issue by Skekdog** [yairm210/Unciv#8883]
**Platform**
Android 11 64bit

**Version**
4.5.7, Build 830, Github APK

**Describe the bug**
Game always crashes when loading an existing save, starting a new game or quickstarting. Attached error log contains mods but crash occurs even if all disabled 

**Error log:**
**Platform:** Android
**Version:** 4.5.7 (Build 830)
**Rulesets:** [Unciv Vanilla Music Pack, Civ V - Vanilla, Civ5 CityState Music, AbsoluteUnitsXL, Civ V - Gods & Kings, Civ6 mod, Civ 5 Icons]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: SM-A202F
API Level: 30

--------------------------------

**Message:**
```
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/geom/Rectangle2D$Float;
	at com.unciv.ui.screens.worldscreen.minimap.MinimapTileUtil.spreadOutMinimapTiles(MinimapTileUtil.kt:26)
	at com.unciv.ui.screens.worldscreen.minimap.Minimap.<init>(Minimap.kt:43)
	at com.unciv.ui.screens.worldscreen.minimap.MinimapHolder.rebuild(MinimapHolder.kt:59)
	at com.unciv.ui.screens.worldscreen.minimap.MinimapHolder.rebuildIfSizeChanged(MinimapHolder.kt:54)
	at com.unciv.ui.screens.worldscreen.minimap.MinimapHolder.update(MinimapHolder.kt:100)
	at com.unciv.ui.screens.worldscreen.WorldScreen.update(WorldScreen.kt:385)
	at com.unciv.ui.screens.worldscreen.WorldScreen.render(WorldScreen.kt:723)
	at com.badlogic.gdx.Game.render(Game.java:48)
	at com.unciv.UncivGame.access$render$s2211858(UncivGame.kt:125)
	at com.unciv.UncivGame$wrappedCrashHandlingRender$1.invoke(UncivGame.kt:143)
	at com.unciv.UncivGame$wrappedCrashHandlingRender$1.invoke(UncivGame.kt:143)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.UncivGame.render(UncivGame.kt:454)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:474)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1591)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)
Caused by: java.lang.ClassNotFoundException: java.awt.geom.Rectangle2D$Float
	... 18 more

```
**Save Mods:**
```
[Civ V - Gods & Kings]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```
H4sIAAAAAAAAAO1dbZPbNpL+K7r9dFcl+UTqheR8GzvJ2ldxPOXxnuvK5Q+0RM+wViJ1lOTE6/J/P/BNEskG0N0AZtcX7aaSmSGIbryw0f08DeDbp7gQ/6Rxtr/59n28Sr+km/Qf8SHNxR8+fBO/vxA/HYrjqv5TXea3eJvcPD+9OU72O/E0fkhex+W/i7JY8sdukxfJ+m3yIJ6Vf3nIN+sku31IqmoeiiQ+3CX5bpOUvz7G+5+/JMWb37Nk/aZIH9Is3ryId+kh3tx8jjf7ZLzLN+kqrV/+32OyP1wIK5JNWoq5/NMxzfYXvx9i0YRVvLl9Vf2WrB7L/35JV4e8+Hou932sbPTtNilELagWf8oPh3z7Nn14PNx8++Nm4s3HX28m/kxIz3e/Jp/rvy7KP4bf6+65mU+npv2UxYdjEW/e59k6KcQginEq0kzoOHpRxIek+DjO8kP6WbSiHeW4aufNt9Um3u9vVvn22TETDX62yR/S1bPLOfHs17x+7bZ6ZbzJz7WItkRlW+bfP34fp6vqj/eH+PCq/PE/X8a7XZol+/1H0fd/HG7+8j4ZPcZfktE63a9y0aJkPRqq+m9/EeNBUO+dGNZGtXKEqyG7E8OQFF8Bne7FdMpWybgp0Wr2NtkncbF6HOWfRx/aZ0LZ/UjIFsNwSNY29LrN0m28Gb087j/F2VqpYL8oqOmgkAOVhSx1VzYlYAWbZ/b1ep1mYtoo1KoLgFo1j+wrdR+L50qtmhKgWu0z+3q9iDdJto4LhWJtEVCz00P7qr0v0oO6y5oSoGLtM/t6vSsq66VSrC0CanZ66EC1x2T0/jFJNird2jKwcqenDj7MeJ9nSoPRlIA/zeaZfb2eF3n2D9HsvPi7eli7BUEte0UAZWW1t9X9T36s18IkO1QL4UEMyYcXZdNKj2WUFPFHuKIXx41Y7E8VfbhLk4Por8pV+jr6VMSZUPKYiWX673Y67s1OOFF7RYfVBcCOah7ZH82XebFPPsWrv4/epmv1ePaLgooOCrn4MMQYb2NNZ16Uknwg5+cOFooLJ1i1WFwUgxeMywL21bx7TDf5Pt89Kl28UyHYyzs/tq/gT0W8jUfCJxvd5clBaQ37RUFlB4UcDP2xKIRCKlXbIvCQtw/tq/ZzJmKeJCnU3/lFKVDBy+f2dXwllgTE4nJZDNSyU8DawvI6WafJF9q6Eh+KKtxVri3aal7kWxE/r9S1mDtEuSiqmrptEZk7VD908FWVBUb3SfElXSWqT+uyHPx9dUrY1/Svx3SzVq1MdQFQt+aRgzUzOYhJ+yLea2KETjl43eyUcLFybnfiReWiWZWQrJf1Mwe2c32s8RqV5WzLwHbz9NRBrz2mwiop18e2CNxv7UMX7trqUawXmkimKSNx1dqnLjygr3u1I9mUkPg+9TMHCMhBHZdWz2H04yCJR3kr3tski9P9Xqw1CWHRe1u1LN6k+63LBet2X66t+VYJq7VlYGDt9NQB5LfKj3tNmHIqA2t3euogjo8zXQBfl4Aj9+aZgy9SOJbl2jK6KxLlOtAtCH+f3SIuFvtsl/++TlSI4KmMZMlvn9rX7rf4S/qgW7TOhUD9Lh67AcVT8VtpOzTIeFtMCo+fCjhY+1eliVB/yKcy8Np/eurIt9scC6Xffi4k9+rqxy6ck2Sb7tXR+6mMxD1pn1pb115la2Fai5QUy/1SJMk6Vy9p2kpuj4d8VcQrNdioreZNURkNh4ur6P1YGxBelJJ+mrGzsLDSomJkR2XwqZxig7Kw+zQo5QDjOM29ppQK6OiXhdGOQSn7Wr9NP2tIuaYEqGH7zAWDuUkPcfF11Kih5DK7RSWsZq+QfZV/SYpDWULpN5wLgWpePHbgHKa6774pATuHqavv/eeNWOSLdJUeVLpdlIJX44vnTkK3eDu6y39Xju5FKVkYd3ruAFf/msVb4TGp8PSmCIyjtw/tIau5WM6y81psaqySz0X6IGrTmNdOOdhwdUo4MKvxOs1VGpbPYc2qJw40SnabeJXEnzbJ6C4uDiq3d1BW0of9Ug5s6qbMFlPZ06oAbEvrRy4GN90UeazEg09lJIPcPnUQam9iHT7RFoHD6/ahK0OfZ5qg61xKYejr5y4QlM0m1XXguZAERzk9doKlfyrxIw0H3RaSIertY2u2/vZQxsLWbP3dY1xshXk5Vkmqaiy3U1KC6XbLOEA96uZrA5ZOOTi46pRwsjYpk92q57K1yUmaWzkd00xMpNtiqyGJzuWkE/tcwglopHGhmxIywMiRC/3bcbURcka/pPu9BhnsloThwV4ZB3OwBDTU4FFbBJ6J7UM3XOVR2DUdW1mVkfKV9VOLwNbnvNhWSrcW9uNYuF9fk+Ld111y8/K4jbOLHQH7x/y4Wb/ZJdldBSXdpaK/iptDcUzG+0OZlN8gTzfL6dTa9oHy3/u2K5L1TeOCXa7oTT7cZaR0pksulq0mQ/nsR7XJwWc+ts2tPmXeXCzLZ3z+IuLuEuFncLeTsdXBpbvWuuVOWrJ66CcP0um6JusMiA4RoF5m5RDYukjZOs+/QYLUAA3pMSqXKXRN0kIb9Z++uDNze5k2dAkKXgbjp5iyXjjazQPj2wfxvJ5kncSeFlA6ZZ1ckBV963RKvK4Dpta4tkmyNWHakrmnlOMTK35O9B3sGGgTp7u5JReIejeIPLnMZ+Zx4HcwNs8U8acUt3fG3XaY1/kxO4zuRcH049WCXC3I1YL8QBbkPs8eHuP0iU3I1UpcrcTVSvw4VuJtvk2uJuJqIq4m4k9uIg5fS9whuRPDVSVyHr7evCqKJq1zrHQ00rUQfbUhVxtytSF/bhuiOAClOO73yYZy/MnVTFzNxNVM/LnMxMs4y6+IxdVGXG3En91G6MKR5rn4bvJjsSpPrhL/3sRppgxVbrOD+HZ2VwtztTBXC3O1MH0L8zIXlW0StQnZiFH6erUgVwtytSBXC8KxIK/zB9Hm/ePxakSuRuRqRP7ERuTjeFVNzsNdla55OjF5nX7+XPWOCHq227wQUscPwnS8Enbg86dgvlqEk3C9DCfzYOZNomTuTeZeHK3ma38VfF5VZcWME/8uZ8HNN6i+OkO0PIy4nysqbFvzz8fxfpeIL1WYubKb18I4iHks+uXnIr7p5Z22zSvrKZNYTxN0XNsSIfIn8bVkdYf9lAorV82z8bt0m4jeeUxLy1Na1OLw7lhkN9NxaUlfx7ubb9t4d9mcVWn5kvX79PD43+IPpZmcP1s8C0b//rycsqNwNv2PsXjnXnzWN98ek+pUaT8aZ/Xu+XV63I4LMWOO+xt/Ov49XR8eb+bz7+N92VZvGYSB7y2ixTL0x7+XRyu/exTfxmNphafPpmFU/W/5/dQZv54Pdv5Y6fyraIro10/xPnmXiKA1zW7+WgiLsBG9OBZmRbwk+kY0sGlzvZ5cFr8rI9m9pKww5Pu0zmMuT8ouz5H2ShtbvfpLUubwlSPwMt1sPvbqrRL6yiBZrBbPqyO3y7O136ZfWusvkVIK8fpKniuDXqq06r2h64XO61650DTR/b34SnfUJkqaYqDUH/ieJoygXx11jpkC7aBV56Rfjtr5gW4kS2EoWarpZlCBV8k/j+y74vj58ybZD3v1v47ZwyahDa+JbpVe4NiOfxEu0f7QV4U0cZrPlDhZJ4wP7w+j8TWbh/I5N2gE9QNx8OHNynpnQL3w1CONd1k3VLViPlF7BKoernlo9g0tyMzUgsi6Rqp5GxY9/3rzocxZ+6j60Njq1Zpxlh3S0oZtPd3CDD5f4urWs84/CeceO8lIktpP+iRJBE/i/5aWgeYLMbA5gxkETsSGTpDOxYm8GoXZkNt7mmzWijMz9A9m9Sx0ML8n8/rGFFwdNP+2rHqONqfU7phfzPNXIujO9gndQMuHa9Al1IUEajlxnaJ1t19396lTKlxkf/r9dlt2R1nCaI0xGlDSeoOclJ3Pt6IRJLXSx0S1TpKmFLoxqlUItf4SZ/qkXtjPk+b9o+gY4zXIhb878XvLKMGPICxR/SUU6hDNzEYtInxwwcDLxBg1UktQVtKG4oQeQ5gJbbNMYyNLTTZb8ulNxspz2OSBlWO4M4Z1VBfiLSgzG7dAl/UOqmU0D1sH0cDOK/Xc4AFQvSQ8QNbT+Mk1M2se2s1o/b/FpX9a5FnfEVuauodoZ8ontNzQx2q9REsdzfG1am/JrL0y//FyTF/ku115NiHYnurMkzj7W5Yebr41dNTr/EuyLev3x9vmx9fJNi9K8vjDt0s5i5LEqniV++Rw2CTFOG+455KILurthfn5x12Rb/OWEf+O7U3ap7RtOE7jJr2OC6EcoUUXP3+43e4e009pftx//N4dm8VTACweGCyzwgS84ZoQgiGVUz4jx4aYhuGWvokhvtkCIGbclfkiMsEiOZc91pwZIDWZ837M8SIVOgCoHX99QLl/5JCE0kiMP0XSGOWgyR2xTn/n8ab/LcyezPNeDIY/Lo0+EWJcQBPzQjuTFalV0tesS20ieN75Dbk64foJilDEirJ/NLLrix4KAo6AraHG8hQWMJOFIZC5oIDDkjqWZR1LXef+lOyT4mA9oiyFLyHEcpPn69Gu6ol+v0OqqPpnadQ/i1pDde8QhmzedLcB6m4pkh/0i2FUNZO1jBJIWvOH+94JpJir0HJpk0110iO+7LvD4+yoOFM6x8yWO6+evs1iVyZRPnkMRvr0jIKzfnOdBGitEAMPU0fuOJkLlx3jIhi3FmA7Hj/82NED6oEnbzHu9CDMFb+ctkyuU3OrMPVmvpc0FcuFuqrcLD58PDfMjJyoaBTjlLFB6GbGSZJjCShi16T2UGJ2jAcndfv57y6hdB0L0dcSzN2h6eU7poaXfaALEqLDApZ4Ho2unJM0u2Uvd+U+3XwZgOuMuHPeQXnEupHZD7KX5rTesk8Y/a2Is2pDRReU8pHgByGEDUrRQV99dQXpVrgMjWNym1V7UkbVXrVO1WXNgYYE8/mKL0HFX+Tx/qAaKWJTh+E+TeQCK5Lo18xrVcyRJHwq36AZai+dCKoP+9XQIZmpet4QDfUbhdVoaL2nPb/8BYuFYlAA7OiTw37CBgTM1CYH9ZdG43Zz3KbZ0BLOnMX9umF1E/hbjeWDp4jlA23+rQnUpZjfGq/dLNoPXKI+1oJ9xwPcHVzjlFBPBtw6Hs3GnjgF8qx9tz1V71f58cAc1lcPmdBy1HT3aJWX3QsY2qXDZPE2BYpPQ9CAEjMHfLCh4AlhHnCzAUl7OOeRiJHQs0MMsx5aOpcUHxC5S8NoXYuP9OEfuOOAqM0wpxJESAwbg/S/pXEkKjo4K0GLPwJGg7VwRiDL8uYSitouftqU7sB872KATNui60Xeq6rQ0CTFIQBTHPAVBONu7iFoxVxs3AvQWepyxc1SF2oVBnUQAJWwrCDkV1C+H7qDmIJaveHovYn36SBvRIkDBZWmhmjXoII3qyRWosAokUToaSHrFVVSjRYkG2hKyESn7iSby1rgKA1r3p+mYLhsnno/a9plMRHaWb4M1P0E6gqFkKnmlFlg6dcz9ukTRKzFm90WOMKJ/N7El59Lg6UxyGAi2nxTQ1ALOJ3z/vckH5r5ThgD64kMjSkmgg5HQeAiXLcRNOFBGDl964aDrEeF3TTzCqX7/RwgP7I9fdwVDrVTg4kTGTWUdpSGeUMXIKSkPR9mwQgXUSCLrwdZzNAU8xQhXZsM14sGrFAuGO3lpHnnN/qy0coyjQ2liI2Z8xVqGDqTbnjCEdWs/rYG08H6/4ciaDcc2nrWqPxqt6OLiOxMh73TRLdDP2Yf+EmcDX0gnHjwGGXBoqEVYY8FuD8+xGZ5ZSEBVaWscyGKhDFY5kJwTbejuOxgJYPEtHCsOLDJaLqG5gl7IQi+0oBLQ/A17O8EwrF2NB1NsuVCWZyFDb9lFUdlxREpDa98ZfAGtS0RcjIqNQkrTc6j9ku6fzREqCMNy6lEiQPDnlmCGtDAYS2MjVLQxlELC9k4G2HbGPUpwNac/gHM62k3aNftIXdxCMwM1NBCRifUBtinIMxhn/J1GzbClzTCcLX0wA7nHfSLHDcZNIhtnQk0OFCRdlZ6hyT5a75Zj94UyRPAOB6e6FLBgUFnV8Pw7IrAOuej+HDM4E3ppm5XqVZIr6vjAJdXsasxQdlxUw5O85rMx0902hF8+gMxBYtxiisKEaSDk+CuKNOkKTAYJKafuMce+w6oKbgXQuCeHQQo+meiP9ZAnuhpAB7MMthx2+qrkOS2ReqpGg5qB/P6oVHbblPcju7Y9NBbZQSNOXFMTYmaTwr/XwHrfcKDEPutdj5/DK+uiPrkG/NkLN2iFI1dHB5Qq292GnBEQDdPLgjF/mZxdY/b+zxbi9F+HhflxX9JMXpRlLekAe0ZeFT4MDGS8OUgIkeIPiOVD8yvN4L8dapaSw06RlPnMvS6P+QZ5hwzlXYGAGtkmFIagSlylPsgptUyMiVlpVYvDd/hrF80wZEFuSFDbgjKtZCHGzTKuINeA2PVCdDrsm2OXeiYpj82g3ghVRayeEolFxbm5ZykjhYo7kwqM4JiNpik4FnoNHxcixKju4IKEptUTIKI0YLIl5piKybnVLqouT95CO6npD6r1TVoMoR4mx9KOwGxeOIWXDO0edJP4Bat+mRwOinloA+VRdF5YVYwXUsneurBXPxBmabtWsj8dOZ9gIQbTfBK4g5uQsG91PuOUHDvjJ/nRASGDSJiMiIMgdAWku0n/QQshwACuJeX+yHpoVJVgiuzFeASyk2Z07ZA7hobnqIz/WdncVpD63pNgU7l4LZkjDimoxFvbce4fkbIPiN1joWF+aK7W+D/IRTca7dTLLiRZYQVEL3XKW1Z0URMetNJWDA5LZlZQ/6q+gxQ3EYh+zm3Vb0LJ9ubkKaHmEdBC9WmEl9bIYA8KG5OyZ72Yh5k0o9xYlzdJnQOL71RoT04vdbVzmkNVV0GoXejjC4xl1JhDd7gPVw1CF/hNYZJII2zMKgFAf8bSo7avtDkQCk+bD1VYCFFhto5ISjX0RUtDX9A0zBAa6hE+Q22CukBf2liEjJjjdonCwuzZS79unkAvqE6s8EooS9tUoDy2OaRQXmDEfcpitHhW/yY0uF29mfoSC3jaeeQn5hICQpToE66d8D0bomJbKeAacUzmZ9kjFnKzvXhYJZ6fH7AIxBPvAx4gY4VDH7JXwDpd5k/Hb/Q3mPg4ANe8kNT01YFsmjbCsh/yXS8TwcREL62Zn+vA0sUOsnOa3MLncx7Qu4jGWUCAVKDu3lR0IiB80Rq4KXTJzt8P3w6QNrTZY48Ua9IRgAJl5qeYu6NO4e/gIxK05ftfRPNb9gLJ/QDQSPY0B1unjlWqQbZETqWzegSULBZlyia2QGhqzuSngid9WSLi40D2cAL7nV7pHEqOzlAwvMkedSmCVqezH+yAX/LLuA0R4mVFzyYKx0gNqpYwvClZwOSYRgP3OtL1mVQg16oyWkOHryPHAEmo9Js1YvLoIp3x2xdxLgqaiQIe7q6ukEVKDTwHinaeK02nHgF0duG23oaN/ZSP/UueA6KXrutNjYgdRRFcl9G2D9WaWLGfmhvjoYcNbHZ7UGjJ5kZMNkJvRyMNPksmyWoAxn+pzV8YSp0DgvVg/wYoR2XqYg/pQqPaQYrQkT5sdPbUFnfVNnGyJ+n25t0aFeIbrRGZ4/0/dMZAcznh9YX7F48xWBiC2jMCXEHhCFJQdsGQs+2d7Dxg3IYk8o2WDrY57lw4PfJZj9GYPwyNsH45u7JHHLPjUiJ5nZYxN2VDpDk+p5Z8qQ0A6aWddynSdwsO63NX6x+RmJSCKrBScxZeSLWjwlqruuxlVunct0MkAl8e5rjOc1IBXtHqas4BkcHC9g+S+iUMMvPaqJmqJkFZydY2igUbaB1W7m1zJjbGG205PZqJ4lvjwtCNErFdhlD/shwtNLCXuq6KRfj11+p5u5v22SM8e2yPbXBzQZ6rXGbDU7SnowtUsycmdkaY2W6zJ6YurMzW2ZPOltmGuSHtjT5fO/CjtWc05AFeusW9oh6Y3ZQetuzmZvl1bcR2RpFtfoDj5+oJzb6IiuG3n6hpoZ8Uz4KPk8AOPPKu6yje7zVfZGO7uJ1PFTNEJ/wfBDk0HeJ6dErXgsI0RmmgedM57u06TEGEmo4WLftTd3OChEeBEr0dmJDOESvmx0H11J7g1oQpJ3JFe0NYyfrBz4/h1KKyHNF1nWNyKpiua6QMZyh6WgG1jsoAFWi3uNA7IclKFR/CuKQduiuElUNo3vhaqYQP0dTcoHtGQqTM4cV0XN2l+YUd7IWncHDGkultrDltkLaGUxTv9+HSLSIztI52Uru9dWXX4jL2iSvJfQuZcO3UGPHom6IbYd/kANgN+dXyQtiETzi3iBX294Mecz2YD7+IjYDvWd8Bc0tNm7y/5v7bk7zCHc5ljn/Z3KrvILaM+dBicya4SFty7H+kDYjJQMK/Uf0zCwd/IbgzxzkEIOX2xEJM2zSNJEww19gTFgx2rNZ7FPq0hNljHVuNw445oLbjREcMdrPPd3uihZQvs1WqfjvqDiWqg1C7s5NA/WuBTK5jsMgrWygl7n1NHVosUENlFC9bb0SIEGr10SaVmfKhsy6LNQPwob0tHbMhsz61gF21PWjKI2zrIzi7IejQHtqP8UwMqyA6sIsKwM3/zEHbv6kA6fZla0fxoUa6DGm3Gb9fDKWlpjbNRh6YT1ovYImFxB7s35GJoYi0esEBWPgPapkXYm7vWYQb0ZxEJvMYDXxjnBcTGAET4JEIIglIwJteMYR5SJFhHZGG8javRhd7SgjM/FqkFqTiNCHQNQNqzDswQpFbxg+FER0tJE+/qCTrO3U80HlWHQjNiJHsJCo3rJwn0vDWDrp2SnYEBt0YDRQ2ub5dJHpdA3tzYYQ3YdKErN7UP9wayaw2YGsamCq6tKm0VlitaGQTgtnH8uCYIXoFGhn+EmXSCqVhtcZe5FQuwqpgYiqB9qIov4FGwYNO880CuqrDEdBGpWRMdBsMLa0S9L1zLL0+zEcWP/HG9i+ytAlA5RxRdwrcJJpYThhL8cKB28vgVfFx88dphM8QSvqFtggrE4bMzWjo06QsHFU+6RNlLCfgiE/J4RFpb6Ms1y+W2fSbjK3SN62o6S8AM8o64DQvvZc3wsXcLezdCiVtqG0Ww/p+QMoWIOk8UKW8mAhRQBb7Sk9j7EnewmCVPTUAGyWBKgrIjHAMHsh6GUvGCQhMVoQjpG7ES6rfJ0/xOt0/3iUf6uhWWqDKmHA0o5jRCNkN1gb5p1JL1RhmWhEO5o7YBzt7pUf12dvhfYk2RF0nL/dmugmJwCb1qeHuWVMOp0gId6ZMfCu6+I0uZJKlEivjfbOwZ7TC5cciMQQTjvPqXrHSgrIHGSA9cIHI8UWPleTkHpVBplkbFUGNemFU9dApCb449D1Kg4cDQwlM3hJL8fQ5/Law3QMtnLN6WQjLkes0S7SZrwgDJbREZJtPEEXS0uxaiUxjCLxmLhWEsMCEhPYWkk0czfxatybaBwqSFtimjT6MczQ8B0634l1WRFsJ1Eb7Dfot3oq2RzJQZsMXhTVDOK+w4YstdPZHqjl+dppKrPY8KHECTg1nYCRskvYezFNVAqlKjG0CbHaUODnwHqnBaCadOTE0uxeEtSh05g6K2KDE4bXAHsM4Wm5UOdK/ksxSX2dXVKE8+FIQ1fE6Vle6WYVKxTvjzWAfZ3dc7xWrAnsl9B5MztM6tN039BfskiRwx6SldOHiYuaGhWj+uH9LgMwCeXbnZcRyYzUncdWCPEJnGZH3Tbc2eUeb3DHYVGpScPD0cwoSuqGawsLgqc7uK/qtMY41D8jVwMMUcq67Mys1SekQdnqE/2Xd39Fth3J1GIuLCV06bzPPds4LpVO55YEtDJ/nsjj2medl45Y5yWBdSZFOgGBZibybgGBfSbpHI4lR7WZ5yKEY/zpckTi9vJwPbeHCCK53QHmr3ZApuPeLij6VissWevyWq4JM0eMQdm6uRBtcIKnu0b0z3Rl7XsbcoIal67eFW3IphFp0AlMwmqwcSoAz4DebdDRCwYtvIBoYbZwIimygGhhtnAiLbyAaGG2cGIqwAIigtnCGRNOsigwhEPcL7h1U6+UhPplKEXkgxcQH6wxX9KziZiNpx202sgnXisIO8MYQR2XnGypFxxGd8FhdOGrw1CMKcN4MblZhqUi5hq1kqhv1XzIwDio9auYD9o7rX5ESQtQEoqlJkqacyTNGkkGX8qMI9fntNAHJZ3JWDUhTBTmgcIopP+07VsLPPTUVJtIqgyX/DXRJhxMO1sbHUNQNXrmd1c7+OBA39auVnKOmwbkX9qbebCltMewnozqj7NVr6+yS4JpMZiKdIIVXoIs4enzXmf8CARrX2f3DDlt7YFXcquM+A/1wfVVdk+I08ZL5QHRD8amyYZ9Irpslo9E9aKpIsiOZctu0xx7KoHdkrOIFH0M/WpAEtOOejdmi+Hj4PXVIqlB2iYdKkmoueWZeAo0khb0bKLhhBY38MXTEPnLFm5xwS2aHCsWjHtbCpwREgEEh+EVDWXIHG9yIPeBYm4+VvGGgavJjaQJsXQogj10sNO2qnipzt9Ra+aBSLkFzbxx92hKQpI/K0PMB/kGBEREe4dz2uoEPiQXQeNRIVtwO6MePCTThQpyTgqHUjFXBtrKgnXpcqwwg0sGM7i0xQwuGczg0hYzuGQwg0tbzOCSwQyC17SzhTMmtoS3YwgnMoBLaAXHfFW0l7wl5Npg5BCZPtjZQ5kJ4m7NJcjtoSQxLBKZ21tyuD34FjaUJIatYbJ0DMNCDubb/VG0t2rIn/gFVtg97Z1WP8a3Tpa04EhacCTNOZLmHEkzjqQZKAnFUBIl+RxJHkeSB0qi05MBb5ce/6pRYu9EjM6JGHLCYW8U8Scy84jJB0JtO6W1GLZEdNkc4wTbJrpsjrmCrRVdNseAwfaLLptj0mCLBnieKMaBJhu2cXqInWziqHKoIsjN4HAkEzJJ0rILRBcG3i2oPYPXBosBn+VrjRa4zPP+WxFn6XB3giQTQwlWUfkDGq7UJughky3JKsFZg3aQfO198jb3V2na2cRqZKzS9OK/gMRpqH2LAIxsle+EYABtDfmP9J/UfNjy13GxfyQ1PQLxBmsEAPGmnGmftABcPEtZFpWsQJMVc2plk7Vw/h2Za4FlIRixxRAKG5ooLNVglF7qg6CglSlU1U3EG9tbyMgUA7TlipF3zzhOcAIfZoigHjhZ6Qzcikxx0AkFssPKgYJYmBNdDnVUAgabEZBnTCOHOM0COXGhlkOEEgPyl97IIZqHQE5HqOUQmYeAbNUbOYx5TSUZ4I3bejlUkiFgkAywK4b6UIkkQ8AhGQIOyRBwSIaAQzIEHJIh4JAM8GVPKEkMy8CkCxi2gYwetHsRaG/VaCaUUPRqRbuDqarKY5kA4lt1/7AYTaqkJUfSgiNpwZE050iacyTNOJJmHEk+R5IPSkLRKaFJzOFx5E45LZwy+jJiCIoYckKGHJW1oJMgNNkq+0EnQWiyVRaFToLQZKtsDJ0EoclWWR06CUKTzbFDHDMEWyEM4UE0BlQ5VBHkZnBomwmZt2kJD6KTA+980c4YMrECn2upXAxOt2JaQHwm8C2YCPKB6KjDpwMo5UgyldQLJZwTRUXmsXsbEMi8p0aE9Tg99XyKkB6ERmCsy4JkI3KoXbs2En+Ig0eHtK04CLQawcNj0WpGyo8tsNwno0e1B0+9BWFGx73ndNBtAt9jg8CdOWeUMLIYyfi2IsFcFdSS8W06mkz2T4iOQMjAt0MGvh0y8O2QgW+HDHw7ZODbIQPfDhn4dsjAt0MGvh0y8G34KkO9HKrfGTLwbXAbHEYO4/uh4ttwDgDiO6Xi2xInBiGJZxIYNoGMb4ccfDvk4NshB98OOfh2yMG34atRUJIYtoGJVDOsAzksbTN8aW/VYBt0wDEZSa8wOJYRsCM/5MgP7MkPOPKXjXw6vk+VtOBIWnAkzTmS5hxJM46kGUeSz5HkcyR5HEkeR9KUI2nKkBQxBHGsSciQw7EaAUMOxzpwjAPHNnBMA8cycAwDxy5wzALHKnCMAssmcD5UqhyqCHIzOJzBhEwatGg70RFi7PrgHKU1gc/S0n4BZFQfvnVM+0WTz6dlnITL2ZU7gff/KnFATgrQBE42QmDkngEhP2EEmxEjqK0WYmogPFWE6RxwnOHZyNAIDvzNSNGQgS4c+JuxtZeILdVeMeNwZSJWNoHvTkfA35yDsxlb68kwu+KIEyX8zclNZCA3ZJidDmqTHRPixxwxYPaIAbNHDJg9YsDsEQNmjxgwe8SA2SMGzB4xYPaIAbODlyBh5BDNWsSA2SMGzA5u1sLIIa5GdG67kcP5TqkwO8cjqSXxTALDJpBh9ogDs0ccmD3iwOwRB2aPODA7fB86ShLDNpBh9vb4f7okHmAOHc3IA8xZZsNK6vvEr1x7H9oETK2rqspnWQwr8usVn0UM2pEfcuQH9uQHHPnLRj7ZtSZLWnAkLTiS5hxJc46kGUfSjCPJ50jyOZI8jiSPI2nKkcSxMhFDEMeahAw5HKsRMORwrAPHOHBsA8c0cCwDxzBw7ALHLHCsAscosGwC50OlyqGKIDeDQ6FMGKwqZwPGhLEDg3Oq1kR1rJaSfCC64/AFLwjygRhgLOhBCeegzgnjSFDOruAJY/8xJw9swsg444TcE0Zw3yQlcLwJKvTg0YGR2kFiZIEQgZ7a5WPsWyUCV7UTyzjYlMxJzOmcBOMi3YnqGl8lV8A58JexE5/MSdAPKuHki08YiekcYH7CYADIfhHRJZrSOYkaOKE2g85JNAANXQ5xltVyaC9V7xC/mloO7aXqHepZkVO66fCndE7Ch+9W0cuhJqdM6abdn9I5CR/eCKeXQ82bUuUUKL9Tsi1geBO1JJ5JYNgEqvPWSGJYBao72khi2AWqg91IYlgG8jGyU0ag4cPXE6MkMawDOXftdNS5HRyfHL62R4PYks8yJ/Ik/o/fv/8fttWLa4HpAQA=
```
</details>

**Comment by Skekdog** [comment]
This does not happen on Window 10, itch.io

**Comment by Gualdimar** [comment]
@WhoIsJohannes, looks like related to your replay implementation

**Comment by Gualdimar** [comment]
I have this issue too on Android.
Possible solution(can not test it now):
in `core/src/com/unciv/ui/screens/worldscreen/minimap/MinimapTileUtil.kt` replace `java.awt.geom.Rectangle2D` with `com.badlogic.gdx.math.Rectangle`

**Comment by WhoIsJohannes** [comment]
I'm sorry for the breakage. I can't take this in 3 or 4 hours earliest. If
it's more urgent, could somebody pick this up if it's a simple fix? How
would I test this? Should I run it with an Android emulator or something?
Sorry I didn't do that, I only tested desktop.

Il lun 13 mar 2023, 17:42 Gualdimar ***@***.***> ha scritto:

**Comment by WhoIsJohannes** [comment]
I just tried, it's a very minor change. The API of the other rectangle is
the same, so only the util needs to be changed, but because of my
inexperiedness with git and GitHub I can't figure out how to quickly
configure my pull request. I'll try again later if nobody did it until then.

Il lun 13 mar 2023, 18:03 Johannes Rummel ***@***.***> ha
scritto:

**Comment by yairm210** [comment]
I'm on it

**Comment by WhoIsJohannes** [comment]
Thanks! I'll spend some time on researching whether a test for preventing
this kind of regression is feasible.

Il lun 13 mar 2023, 19:15 SomeTroglodyte ***@***.***> ha
scritto:
