### ISSUE TITLE
Giving free cities cause crash

### ISSUE THREAD

**Issue by EmperorVboiuerfg** [yairm210/Unciv#9005]
**Platform**
Operating system type, major version, architecture (64/32 bit).

**Version**
4.5.11 patch1

**Describe the bug**
Giving free cities to civs cause crash

**To Reproduce**
1. Go to any game
2. Give city for free
3. See error

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**
Game will crash

**Screenshots**

**Additional context**
Game error here

**Platform:** Android
**Version:** 4.5.11-patch1 (Build 836)
**Rulesets:** [Naciones pa deciv ES, The Undead, Modern Civilizations, Wakanda for Unciv, Brave New World, Medieval Civilizations, Historica, DeCiv Redux, ph bonifacio unciv, Bamboo Deciv Expans, 3rd and 4th Unique Component, Extra Buildings, Elysium for DeCiv Redux, More Luxuries, Difficulty_Sandbox, More Fauna And Flora, AbsoluteUnits, Epic of Fantasy, Alpha Frontier, Future Expansion, Ukraine Mod, DeCiv Reworked, Malacca mod, Palengke, Civ V - Gods & Kings, Urban Area, The Barbarians, Fantasia, RekMOD, The Great Civ Rework, Community Maps, Thin Bubbly Borders, Barbarian xp farm, Singapore Nation Unciv, Kakaoalan, Latin American_Civs, Mitteleuropa and Balkans, Greece plus The Middle East, AquaExtension GAK, Mythical Civilizations, CivBE in Alpha Frontier, Civ V - Vanilla, Deciv Testbed, Shamsy Electric Technologies in AF, philosophy mod, WW2 Nations, Ancient Civilizations, Unciv modern armies, Closer Cities Distance of 1, 5Hex Tileset, Modern Russia unciv mod]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: CPH2333
API Level: 33

--------------------------------

**Message:**
```
java.lang.NullPointerException
	at com.unciv.logic.automation.Automation.afraidOfBarbarians(Automation.kt:216)
	at com.unciv.logic.automation.city.ConstructionAutomation.addMilitaryUnitChoice(ConstructionAutomation.kt:136)
	at com.unciv.logic.automation.city.ConstructionAutomation.chooseNextConstruction(ConstructionAutomation.kt:95)
	at com.unciv.logic.city.CityConstructions.chooseNextConstruction(CityConstructions.kt:597)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCities(NextTurnAutomation.kt:910)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:92)
	at com.unciv.logic.civilization.managers.TurnManager.automateTurn(TurnManager.kt:300)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:312)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:567)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:8)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:4)
	at com.unciv.utils.concurrency.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.$r8$lambda$nwZVoCWi6P2779l7sK5tCF-sQTA(Unknown Source:0)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```
**Save Mods:**
```
[More Fauna And Flora, More Luxuries, Thin Bubbly Borders, Closer Cities Distance of 1, Barbarian xp farm, philosophy mod, Difficulty_Sandbox, Fantasia]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

**Comment by yairm210** [comment]
Please attach a saved game

**Comment by CrsiX** [comment]
Using 4.5.4 as well as 4.5.12 on Linux64 I wasn't able to reproduce it. What I did:
1. Started a new game
2. Rushed to a settler
3. Founded a new city
4. Gave it to some other AI player by trade without any return

No game crash. Can you reproduce this crash with this procedure on your device?
Also, did you have some mods enabled in your play?

**Comment by EmperorVboiuerfg** [comment]
Yes, I was playing the Fantasia ruleset, might that be the reason?

**Comment by CrsiX** [comment]
That could be the case. But without a save game, it's almost impossible to reproduce and help track down the issue. That said, the error might not even be related to you giving a city for free to another civ.

**Comment by yairm210** [comment]
I'm closing this until it can be replicated. This is unworkable as-is
