### ISSUE TITLE
Unrecoverable Error, city takeover?

### ISSUE THREAD

**Issue by twilightrazor** [yairm210/Unciv#9014]
**Platform:** Android
**Version:** 4.5.11 (Build 835)
**Rulesets:** [Future Expansion, Gold UI, Pix5 Tileset, Civ V - Vanilla, Wakanda for Unciv, Brave New World, Civ V - Gods & Kings, Civilization II Music, 3rd and 4th Unique Component, Extra Buildings]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: SM-G965U
API Level: 29

--------------------------------

**Describe the bug**
Unrecoverable Error. I do have word wrap enabled.
It did crash while trying to takeover a capital earlier in the playthrough. Maybe the AI tried?

**To Reproduce**
Steps to reproduce the behavior
Load the save and End Turn

**Expected behavior**

**Screenshots**

**Additional context**

**Message:**
```
java.lang.NullPointerException
	at com.unciv.logic.city.CityStats.getStatsFromTradeRoute(CityStats.kt:101)
	at com.unciv.logic.city.CityStats.updateBaseStatList(CityStats.kt:445)
	at com.unciv.logic.city.CityStats.update(CityStats.kt:484)
	at com.unciv.logic.city.CityStats.update$default(CityStats.kt:476)
	at com.unciv.logic.city.CityConstructions.updateUniques(CityConstructions.kt:465)
	at com.unciv.logic.city.CityConstructions.updateUniques$default(CityConstructions.kt:461)
	at com.unciv.logic.city.CityConstructions.removeBuilding(CityConstructions.kt:458)
	at com.unciv.logic.civilization.Civilization.moveCapitalTo(Civilization.kt:777)
	at com.unciv.logic.civilization.Civilization.moveCapitalToNextLargest(Civilization.kt:795)
	at com.unciv.logic.city.managers.CityInfoConquestFunctions.moveToCiv(CityInfoConquestFunctions.kt:276)
	at com.unciv.logic.city.managers.CityInfoConquestFunctions.conquerCity(CityInfoConquestFunctions.kt:109)
	at com.unciv.logic.city.managers.CityInfoConquestFunctions.puppetCity(CityInfoConquestFunctions.kt:146)
	at com.unciv.logic.city.City.puppetCity(City.kt:466)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.onConquerCity(NextTurnAutomation.kt:1001)
	at com.unciv.logic.battle.Battle.conquerCity(Battle.kt:598)
	at com.unciv.logic.battle.Battle.attack(Battle.kt:145)
	at com.unciv.logic.battle.Battle.attackOrNuke(Battle.kt:90)
	at com.unciv.logic.battle.Battle.moveAndAttack(Battle.kt:46)
	at com.unciv.logic.automation.unit.BattleHelper.tryAttackNearbyEnemy(BattleHelper.kt:29)
	at com.unciv.logic.automation.unit.BattleHelper.tryAttackNearbyEnemy$default(BattleHelper.kt:15)
	at com.unciv.logic.automation.unit.UnitAutomation.tryAttacking(UnitAutomation.kt:278)
	at com.unciv.logic.automation.unit.UnitAutomation.automateUnitMoves(UnitAutomation.kt:182)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateUnits(NextTurnAutomation.kt:888)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:85)
	at com.unciv.logic.civilization.managers.TurnManager.automateTurn(TurnManager.kt:300)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:312)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:567)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:8)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:4)
	at com.unciv.utils.concurrency.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.$r8$lambda$nwZVoCWi6P2779l7sK5tCF-sQTA(Unknown Source:0)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
**Save Mods:**
```
[Future Expansion, Civ V - Gods & Kings, 3rd and 4th Unique Component, Extra Buildings, Wakanda for Unciv, Brave New World]
```

**Save Data:**
<details><summary>Show Saved Game [Used pastebin as save exceeded character length]<./summary>

```
https://pastebin.com/p2YCSN0d
```
</details>

**Comment by Skekdog** [comment]
Update to at least 4.5.11-patch1 or 4.5.12
