### ISSUE TITLE
Locked out of the game after changing the tileset to 'Default'

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#9020]
**Platform**
Android 13

**Version**
4.5.11-patch1, Google Play

**Describe the bug**
I was browsing the installed tilesets. When I clicked on 'Default', the game got an unrecoverable error, which now doesn't let me change anything.

**To Reproduce**
1. Go to Menu
2. Click on Tilesets
3. Choose Default

**Additional context**
<details><summary>Error message</summary>
```
**Platform:** Android
**Version:** 4.5.11-patch1 (Build 836)
**Rulesets:** [LynxRo Tiles, Pix5 Tileset, More Fauna And Flora, Civ V - Vanilla, Wakanda for Unciv, Resourceplus, Resource Recyclers, AbsoluteUnits, Unciv Europe Map Example, Medieval Civilizations, Community Maps, Unciv Colorblind Friendlier, LOTR Unciv, Smoky Skies Redux, LOTR reworked, Civ V - Gods & Kings, More Luxuries, Maid Empire, Great Community Maps, 5Hex Tileset, Fantasia]
**Last Screen:** `com.unciv.ui.screens.mainmenuscreen.MainMenuScreen`

--------------------------------

Device Model: SM-A236B
API Level: 33

--------------------------------


**Message:**
```
java.lang.NullPointerException
	at com.unciv.models.tilesets.TileSetCache.getCurrent(TileSetCache.kt:14)
	at com.unciv.ui.components.tilegroups.layers.TileLayer.setHexagonSize(TileLayer.kt:29)
	at com.unciv.ui.components.tilegroups.layers.TileLayer.setHexagonSize$default(TileLayer.kt:24)
	at com.unciv.ui.components.tilegroups.layers.TileLayerOverlay.<init>(TileLayerOverlay.kt:15)
	at com.unciv.ui.components.tilegroups.TileGroup.<init>(TileGroup.kt:49)
	at com.unciv.ui.components.tilegroups.TileGroup.<init>(TileGroup.kt:19)
	at com.unciv.ui.screens.mapeditorscreen.EditorMapHolder.addTiles$core(EditorMapHolder.kt:53)
	at com.unciv.ui.screens.mapeditorscreen.EditorMapHolder.<init>(EditorMapHolder.kt:45)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen$1$2.invokeSuspend(MainMenuScreen.kt:136)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen$1$2.invoke(Unknown Source:8)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen$1$2.invoke(Unknown Source:4)
	at com.unciv.utils.concurrency.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.$r8$lambda$nwZVoCWi6P2779l7sK5tCF-sQTA(Unknown Source:0)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:467)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1593)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1287)

```
</details>

**Comment by jahodovykolac** [comment]
Okay, is there a way I can fix it?

**Comment by jahodovykolac** [comment]
I understand that, though a quick patch to be able to delete that mod would be welcome

**Comment by jahodovykolac** [comment]
That is a bit unpleasant, but understandable. Thank you for your help anyways

**Comment by jahodovykolac** [comment]
Game launched just fine, everything is working as should be, thank you!
