### ISSUE TITLE
Crash or bug?

### ISSUE THREAD

**Issue by EmoticonOrden** [yairm210/Unciv#9048]
Game crashes at 200 AD, I play with REKMOD and CCCP-Unciv

Here is error message:
`
**Platform:** Desktop
**Version:** 4.5.10 (Build 834)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings, RekMOD-master, CCCP-Unciv-main]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

OS: Linux (amd64, 6.0.0-0.deb11.6-amd64)
	Tails
Java: AdoptOpenJDK AdoptOpenJDK-11.0.11+9
	Max Memory: 1024 MB

--------------------------------

**Message:**
```
java.lang.NullPointerException
	at com.unciv.logic.civilization.managers.ReligionManager.chooseBeliefs(ReligionManager.kt:332)
	at com.unciv.logic.civilization.managers.ReligionManager.chooseBeliefs$default(ReligionManager.kt:329)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.chooseFreeBeliefs(NextTurnAutomation.kt:581)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.chooseReligiousBeliefs(NextTurnAutomation.kt:541)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:89)
	at com.unciv.logic.civilization.managers.TurnManager.automateTurn(TurnManager.kt:296)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:312)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:565)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
	at com.unciv.utils.concurrency.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:164)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```
**Save Mods:**
```
[RekMOD-master, CCCP-Unciv-main]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```

**Comment by yairm210** [comment]
Please try downloading the latest version of rekmod
If the problem persists, please attach a save file - we can't debug the problem without it

**Comment by EmoticonOrden** [comment]
i opened another ticket with save file
