### ISSUE TITLE
Crash or bug?

### ISSUE THREAD

**Issue by ydraac** [yairm210/Unciv#9056]
**Platform:** Android
**Version:** 4.5.11-patch1 (Build 836)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: Redmi Note 9S
API Level: 31

--------------------------------

**Message:**
```
java.lang.IllegalArgumentException: Can't capture our own unit!
	at com.unciv.logic.battle.Battle.captureCivilianUnit(Battle.kt:621)
	at com.unciv.logic.battle.Battle.conquerCity(Battle.kt:573)
	at com.unciv.logic.battle.Battle.attack(Battle.kt:145)
	at com.unciv.logic.battle.Battle.attackOrNuke(Battle.kt:90)
	at com.unciv.logic.battle.Battle.moveAndAttack(Battle.kt:46)
	at com.unciv.logic.automation.unit.BattleHelper.tryAttackNearbyEnemy(BattleHelper.kt:29)
	at com.unciv.logic.automation.unit.BattleHelper.tryAttackNearbyEnemy$default(BattleHelper.kt:15)
	at com.unciv.logic.automation.unit.UnitAutomation.tryAttacking(UnitAutomation.kt:278)
	at com.unciv.logic.automation.unit.UnitAutomation.automateUnitMoves(UnitAutomation.kt:182)
	at com.unciv.logic.map.mapunit.MapUnit.doAction(MapUnit.kt:480)
	at com.unciv.logic.civilization.managers.TurnManager.startTurn(TurnManager.kt:64)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:336)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:567)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:8)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:4)
	at com.unciv.utils.concurrency.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.$r8$lambda$nwZVoCWi6P2779l7sK5tCF-sQTA(Unknown Source:0)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```
**Save Mods:**
```
[Civ V - Gods & Kings]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

**Comment by ydraac** [comment]
solved, Disable automated units by moving on first turn

**Comment by yairm210** [comment]
But this is still a bug, please attach a save file

**Comment by yairm210** [comment]
Can't debug without a saved game, closing as irreproducible
