### ISSUE TITLE
Crash on next turn button click

### ISSUE THREAD

**Issue by SergeyKabaev** [yairm210/Unciv#9057]
**Platform:** Android
**Version:** 4.5.11-patch1 (Build 836)
**Rulesets:** [Higher quality builtin sounds, Unciv Vanilla Music Pack, Civ V - Vanilla, AbsoluteUnitsXL, Civilization4mod, Civ V - Gods & Kings, Community Maps, Civ V Leader portraits, 5Hex Tileset, Additional Music Various]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: SCM-W09
API Level: 29

--------------------------------

**Message:**
```
java.lang.NullPointerException
	at com.unciv.logic.automation.civilization.NextTurnAutomation.motivationToAttack(NextTurnAutomation.kt:741)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.offerPeaceTreaty(NextTurnAutomation.kt:853)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:62)
	at com.unciv.logic.civilization.managers.TurnManager.automateTurn(TurnManager.kt:300)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:312)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:567)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:8)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:4)
	at com.unciv.utils.concurrency.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.$r8$lambda$nwZVoCWi6P2779l7sK5tCF-sQTA(Unknown Source:0)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

```
**Save Mods:**
```
[Civ V - Gods & Kings, Higher quality builtin sounds, Civ V Leader portraits, Unciv Vanilla Music Pack, Additional Music Various, 5Hex Tileset]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```
Skipped
```
</details>

**Comment by yairm210** [comment]
Please attach saved game

**Comment by yairm210** [comment]
That civ definitely has a city, so there's no reason it shouldn't have a capital - interesting...

**Comment by SergeyKabaev** [comment]
> Please attach saved game

Hi! Autosaved game is missing, sorry.


> Since the stacktrace fingers one of the `getCapital()!!` lines, I suppose it's possible this is the thing where 4.5.11-patch1 prevents the cause, but in this case the game was maybe played with 4.5.11 or earlier shortly before - and 4.5.11-patch1 has no backwards compatibility fix for the invalid state it prevents... Should we still code one?
> 
> @SergeyKabaev - how many turns _before_ that crash did you update to 4.5.11-patch1?

Near 300

**Comment by SergeyKabaev** [comment]
> That civ definitely has a city, so there's no reason it shouldn't have a capital - interesting...

My civilization captured one of the enemy capitals on the last turn. And when the capital was captured, the game also crashed

**Comment by yairm210** [comment]
Cam you send the autosave of that turn then?

**Comment by yairm210** [comment]
We can't debug this without a game.
Closing as irreproducible
