### ISSUE TITLE
[Great Unciv Rework mod] Crash when using worker "Construct improvement" button

### ISSUE THREAD

**Issue by ferrosa** [yairm210/Unciv#9110]
**Platform:** Desktop
**Version:** 4.5.16 (Build 841)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings, Community Maps, The Great Unciv Rework, 5Hex Tileset, Civ 5 Icons]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

OS: Linux (amd64, 5.15.0-67-generic)
	Ubuntu 22.04.2 LTS
Java: AdoptOpenJDK AdoptOpenJDK-11.0.11+9
	Max Memory: 1024 MB

Playing on XXL Europe with the Great Unciv Rework and two cosmetic mods (5Hex and Civ5 icons).
Modded yes, but this happens early enough in the game (first worker action) that it might point to a general issue.
Trying to construct anything by clicking the "Construct improvement" button crashes the game.

I've tried cutting the two cosmetic mods out of the savegame and moving them out of the mod directory, but continuing that still gets crashed by the construction button. So it's either the ruleset mod or the base game.

--------------------------------

**Message:**
```
kotlin.UninitializedPropertyAccessException: lateinit property lastTerrain has not been initialized
	at com.unciv.logic.map.tile.Tile.getLastTerrain(Tile.kt:100)
	at com.unciv.ui.screens.pickerscreens.ImprovementPickerScreen.<init>(ImprovementPickerScreen.kt:82)
	at com.unciv.ui.screens.worldscreen.unit.actions.UnitActions$addBuildingImprovementsAction$1.invoke(UnitActions.kt:393)
	at com.unciv.ui.screens.worldscreen.unit.actions.UnitActions$addBuildingImprovementsAction$1.invoke(UnitActions.kt:397)
	at com.unciv.ui.screens.worldscreen.unit.actions.UnitActionsTable$getUnitActionButton$1.invoke(UnitActionsTable.kt:49)
	at com.unciv.ui.screens.worldscreen.unit.actions.UnitActionsTable$getUnitActionButton$1.invoke(UnitActionsTable.kt:48)
	at com.unciv.ui.components.extensions.Scene2dExtensionsKt$onActivation$1.invoke(Scene2dExtensions.kt:191)
	at com.unciv.ui.components.extensions.Scene2dExtensionsKt$onActivation$1.invoke(Scene2dExtensions.kt:189)
	at com.unciv.ui.components.extensions.ActorAttachments.activate(Scene2dExtensions.kt:137)
	at com.unciv.ui.components.extensions.Scene2dExtensionsKt.activate(Scene2dExtensions.kt:180)
	at com.unciv.ui.components.extensions.ActorAttachments$addActivationAction$2.clicked(Scene2dExtensions.kt:148)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:18)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:90)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:90)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:90)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:70)
	at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:189)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:378)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:80)

```
**Save Mods:**
```
[Community Maps, The Great Unciv Rework, 5Hex Tileset, Civ 5 Icons]
```

**Save Data:**
<details><summary>Show Saved Game</summary>
Comment is too long (maximum is 65536 characters)
</details>
[Autosave-Germany-53.zip](https://github.com/yairm210/Unciv/files/11142820/Autosave-Germany-53.zip)

**Comment by Skekdog** [comment]
Update to 4.5.16-patch1

**Comment by LJE314** [comment]
por favor si logran una forma de solucionarlo avisenme tambien, thanks
