### ISSUE TITLE
Can't load save game where not originally participant

### ISSUE THREAD

**Issue by WhoIsJohannes** [yairm210/Unciv#9163]
If I try to load a savegame from a Multiplayer game on Desktop I get the following exception:

```
**Platform:** Desktop
**Version:** 4.6.0 (Build 845)
**Rulesets:** [Higher quality builtin sounds, More Fauna And Flora, Unciv Vanilla Music Pack, Civ V - Vanilla, Civ V - Gods & Kings, AbsoluteUnits, Civ V Leader portraits, More Luxuries, 5Hex Tileset]
**Last Screen:** `com.unciv.ui.screens.LoadingScreen`

--------------------------------

OS: Linux (amd64, 6.1.19-1-MANJARO)
	Manjaro Linux
Java: JetBrains s.r.o. 11.0.15+0-b2043.56-8887301
	Max Memory: 4096 MB


--------------------------------


**Message:**
java.util.NoSuchElementException: Key Spectator is missing in the map.
	at kotlin.collections.MapsKt__MapWithDefaultKt.getOrImplicitDefaultNullable(MapWithDefault.kt:24)
	at kotlin.collections.MapsKt__MapsKt.getValue(Maps.kt:349)
	at com.unciv.logic.GameInfo.getCivilization(GameInfo.kt:206)
	at com.unciv.ui.screens.worldscreen.WorldScreen.restore(WorldScreen.kt:552)
	at com.unciv.ui.screens.worldscreen.WorldScreen.<init>(WorldScreen.kt:207)
	at com.unciv.UncivGame$loadGame$2$3.invokeSuspend(UncivGame.kt:277)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
``` 

https://github.com/yairm210/Unciv/files/11193536/Rome.-.225.turns.txt

**Comment by WhoIsJohannes** [comment]
I can load it, too now, but it still behaved weirdly. I can't scroll properly in the big map and after I click on the minimap and try to scroll it forces me back to the center. Also I managed it to crash again after going to victory screen, resizing the window and going back to the world map.
