### ISSUE TITLE
Game won't start when spectating is disallowed

### ISSUE THREAD

**Issue by Scoobin** [yairm210/Unciv#9184]
I'm new to Unciv and I've been trying to start a multiplayer game by selecting current user, a friend, and two AI bots, with spectating disallowed. Every time I've done this, it has closed with an error about spectators being disallowed, which I'll paste below. But If I am a player, why am I being treated as a spectator? 

BTW I managed to get it working if I allow spectators so it seems that is the cause, but I don't understand if/how players are considered spectators. Isn't the feature to block random people from joining and watching?

I've been trying this for a few days and the app has updated a couple of times, most recently just now.

`**Platform:** Desktop
**Version:** 4.6.1 (Build 846)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.screens.newgamescreen.NewGameScreen`

--------------------------------

OS: Linux (amd64, 6.1.23-1-MANJARO)
	Freedesktop.org SDK 22.08 (Flatpak runtime)
Java: Flathub 21.9
	Max Memory: 3934 MB

--------------------------------

**Message:**
```
com.unciv.logic.UncivShowableException: You are not allowed to spectate!
	at com.unciv.UncivGame$loadGame$2.invokeSuspend(UncivGame.kt:255)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:164)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
**Save Mods:**
```
[Civ V - Gods & Kings]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```
H4sIAAAAAAAA/+Vda3PbxpL9K/q4W0XcIh7Eg9/82MTeG6+9trP5kPIHiIQkVChQC4K5UVz+74sHSVNkA+hzZqiqbOreciSKmNMzmOnpPtPT/XWR/56v8j/TKl8Xm/mvX+vf/yu9z+Yv0/I6LfO02EyqbHE3//pt8rBe5Ys82zQ/1197VT9QldtF92T92f9us031Li3S26xsfi+zVX5b//Hoo9v1apkVL267Rm7LLK0+ZOuHVdb8mm0e6m/XXz164Pd8Ua3Lx+NWt3mxOfq9SmsJFunqxdu2jT8eVusyW37MGuT6k2+Trw+r9DErPz8+ZPM32/u0mBz6+PhnWlT59n7Xxebfzcdsk6Xl4i5bzn99cVvmi+2q2pbZl79m/6v1w0/ZTTX/+sfcSSaPc8/9NrleV9X6/mN+e9d97vr1H1z/2+BYvS2Wefr3GKewHg5nJoyT1/xhN1D7cfmP4naVFsv/vyNz3NnPd9nVu/TxLz0PirQWL139si6WWVlrvHfrbVFdfcqLNP8CDMU/0+quXh/L7V95LEa6W0taPX6q0iqrO7belots/mFd/7tK8+JoKP57m11ni6tX9Zf/FoPxoZ43dfOr+vf5D2WeFcvV49FwvMtrhfBXHojTFVKbAmVe1H+8elXW3S9Hl4k8VG/WmypfZUcj9SZbbfLit/xvPVhH4/FD85dikf2Vx8PWKvq5/NuNwn6BfJlcH4zv5svL/Oam7fHj/EM9t5r5UX/tXfow/3qfPnxIy3q8qmbyNb9+yv+s5S7TZb7dzL3p5F/5srqbB8HkLmsNGS+pp2yjpbL6G/e1JE13s+UveXX3P3UbjXzBP8J/uFf/9nKbr5ZXcRD++2ST1QPvhrEbeJ4/8303+NbK8FO+qWqf4TrdZJ+zsqy3hfmPZbrZtBbRvtcvH+e//lyvg3K/h7xKq2qVTe7qh+tRbIdjXZvhRVZU82ljg643edUOVGN0tTZXbYyJGFX3yQ9Zswrr9/frm3y1+tIP/ekuyx50yA3wCe6HZuPbnLWuaM5CH1QossBnCD/UDW8qCuOPUwx7Helc0bT4uchrg3v9r6JeS7UaWJf1gq2XyPv9B+38/ZQ1k6icLLZlrTOrd+vfs/umIW/yUK7v14f1f7/7w7vsvm6okepkfn371mqRJx9d/E3VKK0z4T0HVIPkiRMDWIInDbRWc/3DgETCepKl4NaTfuj2s13Vriyi5RU0qNP0L6W3iX7Vu354qBeNbtqAc1M57U3nkderl01e/H5BuqbiOQ2Z4vjQ2E2MZlMD6Bssbw8XGFA8JpK5gmSHNzKoaGjUywyF0TBI6leh7Q5r/nWmXfGOoKMVSuXNutxkm8PvL+6bVzQP9HOkXxfawXAEnXGZrdZktl9kCfp6bdm1ypjKnc5DB/gu3bxsGdaGeP2Y/14bd7XnpvQL/F5rYnxB/FymRUP6n0wmD+msfj3+57a4XWVH8C9W2/u8OMf3v49IyzmjQ+IEjWCBPAN7W/7+BwytAZOxFOtpT/xot2Zf6Jm4Ne/YeM3kEiaUhf5Qlla3BUPo9HvzevsJ7MmYqNpNjhbrAhL1SXN4v7/c1Y0CG3ivdtcPu8HmMuxsftf51brQahvBqwQ7Je0afS9ur0X1+gLbjsxMcJMFFRiNYdC7vwN7hn6o3qXl5k47KEMTxMiHDITZrFSXjK0RnK89mx3p1wzWN21ntj/aPgJ8nW2yshLsptV6vbx6aMf1C6X4GjQl2Pt0k2/MjIRA6Jt6EzUYYIm2PJxsPSUvDx/bpDCDdpRPWcygd+yNDbFZ34QVLbHTzcXU6ofesElfPaGvSqOz334X9mW5Q4A1JjcgS6i1V2ih4DWoadJgiBB79cxTfJXXrw95FwaGgETDGRidjiH5Jnm5GJ0Bbf+QfScZLXYMR8GcsrPVj6/RfWyVVlRglU0gInymOviExcUMTei1zS431Tq5UTP2hETL7+sNfbe5vygWef3fqzZiQN891P402fhmg1YpdYw/O9eNFqyRmaDbddasrv02EDQU21c10DwvP27ca7nZsen4ap2uTmnHyMwkm12kj4HQR2jOIzbZyE6D9I7aqf1n6Kzk0Jha4tAcNLbEewdobCRwfjQ0tcjtvEyteatHMzBwz3t1apwaHNEhfeCPqSRnyRKRY+Qy7Wx/+6S6Y0j2S6EMsA9g15BAqD+Tk3CBvDyd75/SFcCD9fgrpib1RZwVeaHLolI7Xu9qV5tV9kcz7H9JaqlUsROUYLQH0mPyaXtksvpDJrDoIPiP69Xy6n2p1AvhuaZDj9jCgeNzrQgqahQ1f0Jh30LcECdqGoj4BprnDR7vOhCN7gMWCOKwV1Jjj6tX/t59x4KJrt1d7Pc5GOzzMNOPbuiy9HYcift8lVdp+Xh8OrO/s/n0cGb/aXs280tzjWdtHl7ud8PYnM5I50QKSWwFuh9JIn1u0/tkHUpoHgCuo753e25wZH7vvCbrS9lDB4GK1nPtvXGt24WhIXz1eVeQs6peufQO5YktW9tbG+2+KDjv9oMzpWNMRMj+I8rejU/vXPaabGZtO0I0HxFY0+P79mqNw+t5mRb1/5AYnIvEl0hnF5AFP3iwojbItEd154qGcZUuE8wk6xioC6RnA2vqA87bcl2cun4hZikdEj48NVAOH9u0laL25fVZSipJLNlK3yU5//SZZnLUv24YxiWiTkiNO9B32as3HiYaUoXG4sBXiSLDYOlocI8zO5qKDEOHIowNh/bfaOhUAhDPsI24aSMG40SsG/WNFLFo1B9P6DZrCDSb5Y6p30/csxjOhJp897KfJLuYn6a6QNggeUBGTu0ZzRf2jj7A/Sjn0MWOoWe9nTgMyfucpXk7qicGrYyRWE+9fxL09s3I8fcHO8V7s77hfPIIuYzmjmcosCsIPBIG27eduuei2PZ3B2TtEetMJDu+l0SyjBscjkCW6LXNPn8QcD37dIs9iPhU1X9cL367Wt9c/Zhf1x/WXgIw28dPE0G5pSB0hNHojyI3EEq6fGl4w0q4YglaQFIk36kXIXmJ2quwQmSilThc6cjTJBZ68GyWeTeSe/YMDhXtfrbZO5VIqs0JlR7TseJtvF0fiGiO+CIBA7EwB8SNcT/4gw6EILJJciCBdkKOCOIh731wYgn9uIhDHwuq7dQmBhZ03OvpG1mhMUZynzmhzElarCfs4a4o272sM20SnhkDwdMnIeMX6QtuIcb9wRyg+2z/emmTYdpJxjfa7a3WgmxaTNhdb8ep8BowGTYyhfeZiC/GjOgRpTh06od8czfMYMoyAWSNKMDZ+L+o1k+1iWDUmYgyE0TRh4pgXv7sXFbDwNWOZeltc4RO0S+Y4FzykWnbUSUnz/yU/paN3iEV/DL5/VDujyeIRRIPXq9kFg/aO6YEG3vXZE2AaKAiZY8Rz0iQGJuNAEkkuVUMBxJhEgpROpBtztAdI1Em0pKGIktk+QajiH2AGOk9Z7JCQwi5Di5Gmkl3DsfehnD7EQ0sPnV1xiCF2G07vKZ0rmstbAc7ph5jCtRGOJ66Tm1CGiRkPuU79PdNeq2MMVXfl5ouxqJGuloxTwM1us+sxtYmvcEiIwLYCqlNzqNp0aEf5oks+WUJFBZlHrySCGtK56IOzf+3tZIuNtkzXnJNrJFwwLh5iJ3Kar3kfHsQXFWBRDy8BH2HZByLhndyvr3aOEFOhJ0ecViTc6vkAk5HIphXFnMgJOeGpMXIg4Rm45hjoMTkqglE2ySCV4FYfAkSnzOUjDzBQjvOApl7UuVq8y6703YnmPIj0bZw2kBn/OIDYSJIIsiB+KWnXOTrxwzirOUxGOQiTx/B7wyCoJEpaCiBohlXQKF3mYkMQGcEaGAKGhCg/gCoyVbpm753TxJM6/mdXcvS8j7YSPCUIPiaXFg0HVcIiaFXdmhM1ImH9H6RpWMBUSrWnCH+YkwWIZSOJP6YySRd1BQklvzhQ2G5py7x4WPrF0177pk+I2sqZZCCTs4cIfcTR0QTe76Up1ezjz0XCyrlShhbPeYpGqRLHCfv9Je7dPVkkCW7xiwXuxQbM/ZuhHAeVcJGE/8eZDWxJJGOKaeE9Aa0DNRJm5Sb7ChF9XyMVOcO2Q/u2Tlqtik7pEjCFCLbsMnadU/JrI2/bnV/IOoL6YrcsF4wTS2V7+zf01jwo4LZkMwGVFrbAMSlIYKNp0k/qnCNvH4oQSIi8XhKSlJimbOiebBO2vHkNKS09LUsk8Cwrk+9bkBvI5Jd3t2ve2qUd5/ZtMhbic/PqnYfPwcf2o2Z5YAqt3OuXcgSax+SnxmaIALHHQyYe7vtFExRfkCD0kd0JoG2R2MMKTaaSS/0SPwq+FDci6N15iIJVUn4GARARcQAhQOi6knQk+fHnLOZKeiM6GlgChoIoBdg8XxTOX1YToQ3NRDM6xcMITjlFpioT0k9QxGR0Bx8jtkjUsAa1rPf69UTnCDZKsTJXjyyEeRghfvXVvhgKd/hmCxC7kKjKEtgVklFADQ6XpVFnSEDZ5gsg8lSTXSilHJlTBghzctFEpBLd9bGZBu8QGcyUFKwEWZTmYZHwXTKKUE1GkousGXWbmiixg6209Dj5KIEIecEuwBfaKFHULHHQ4/ARGuuVGn9gp26BDso1Zq9gE0j1DqzJ74JUSgUYsDsWalIxBhjZSEUzhVygRKCKxlHodomQcHBuUqQnlyENIQT0PCMl3T1SY9F9k2+4GXYCejWGLBJoYd6Q/ycwf2k/V5mEBvouJ0j7kGmXfsQ+MxeWOz4uRtvFGnKIE0JpIQASgicWMKxbxzFhGiRJBpaogEFDQdAx8bj1frhQZt+JRRk0wVlyrIdK4J/ptXdfa00tnb42pkg6gXM5wDvnZ4PNS3aajQPfUECIhTUoAVJqxKUptyCDUuvXz5+T0UVKCoCT3yC5xAS/2vB4hADjDVsqCEJK6VW0DCcdMoThvUEGVghYad5+jypxI6Gz3zGiFKpGqxmi0VLG+ppTpBzFTJG2xFGynKlMcaghFsml5TPeE+QhBWuS9pwg6SoNJVZjrKueq/slNNT+SMMxdob/XjmJYECmVDanUsG8roeTIXqXofXy3siTqmBJdQ2YBBpuJMAWjiUodFf5vTQnEFx2kNHzILXXaGQDjGaqgqDBH0kZOolpAMDE0d1upLDcfsLZ2mDEKTwvCNZT4L0jv9i9fKMu0tIdHZ9xpUyFekPJ8gZgeZukm5VkawnrQmwAAbxqgXGkkqRFheleiXHhIj4c0WvaIzhk0KGeHB0s+0ICsx8ax8Cn9nLByJ5DJLLILkM0pRBmhJIiQSkoXSJ6IgzHGbFo0xbTAgbScLqFQUqYkSIGBLj2Sslo8FDQegTE/5VmV6PMsfyKJsM50yQTGnLysYnkt3urEO2yGKgQ+K6efn4Z1oDbO+huiygZpD0t970ORKRjQwR9wLIs5Q2BrMu4GkIsEGXNhgrPDWiks5FYJQ7OknFEwAVc40SM8zbFA0nFZd98VhnMcGIhu82OX2XEitrOGzZYtez1SBtLtTwsnW/NSTI8xAiz6HqLVLpPo1t1EuUU/fDpHoFGnNSTqHwfTXos3ASrLiQyg7OloWS29JNZYNiO2IUpcoHAkNNJN5V5dWBNwbR4RwpSgJEJ7iiI4uKIwzTaJfht7HDAV+hfz7zdDicHY5Zfa5QRNxKdatdH57jxoEr1DrDaF2p2JqtfcsV0pQb3wqW0qUL7h9BuwkZjNDsM66UxOmiLK5wX4qs37ET3kIlL5nnRULKXCFIQqc5Th76vC2WZXrBsUdz9LmiDa1RpHCojXitVcWloru7GFY2+lRHfGAWVPsQ+MxePhDJZ5A8BsljkFwGyWWQpgzSlEBKJCANq0zEpvTg9GnNUSJO4o/BMhJRv1gofKSDlw5FD82fHIl+/9zqgWi46/TZgWgojYYFnjcUhsbGtZYZ/PaU1OLsQgKL6pebbpJS1h98mLKfWu0ulbI4YJ/M9u+f2yxpsdtS+spaKIWxtPSOhBE+Vlmwwj0z+MCA2TGlDdOMbTcMOnSo3RhYNYADigrSO5QAl45yKP1HUwwlxdzOcqR7BBfx0Rkz3JEMfivkhJiYXEOnA/f53qXl5s7KtVmpJqSGiJe5fzvRgiFxOBBChwNmCcMi4rQgGjot0NPx4KGAUOwXRJWqo2i8DCz1spjfUuU2YR6AeLtf5Qg+TwwuzPoLIc4apgNm/QXeHIsLR98t+F4DgtcPCF4/OB9vHQ54szk4n3I6HJMQi7YFceCVDexkIN4dmKndlWpianDAKqBufxL8YRywIKorJc869xR7GFRJAHD7dKV7bEYCoFUqpCAE1aoHLS1XtM9OpjmWrdSVsigq5QDJY+l+shKJ0ECw1yFG2o0+1RE7mJHRPgQ+s5cPRAoYJJ9B8hkkj0HyGCSXQXIZpCmDNCWQEgIoEXB0OXtFHIr4PmlpdwhnI4HDjiQX+zdGs2JqMxI6ogqfPeC9zrTHnTuyW4k2Et9+wDcr7hey/TdiA0VlK1+CowK8RyeORA6ORKSLantkyUlaWzjcIMOvMY0h6XUrA8Pofkn12xgYanfol0XJwyJ4sNpmOGdHIp1HcJibUo4UEH9Kw0n7gPLWBBVxIMU2KNYpTN5KBjd0yUUsWanhPUcch2H/OCTI1vDcl1IUEUXp0+jcZVRUFEBJ0Bj2jKX6xhqbzqRunVjTRmWyEqYxTHoKiUNVcb7M7U3wvosUwKpylAjXFGYwcYYQ9loYD5ZylXEc9K3MCM5yRnCWM3xqts+gq2aGLzVXKAepwyHmAajiXCJ7vStke9LhYA+5wj0dHQ72kCscQ+pwsIdcadtXLlTsKVcqAaNEInQCzCOKKSVVSBwjSOgF2FgXg8pGn+rYBHD9tf4+tdBRpBmDFDBIAYPkM0g+g+QxSB6D5DJILoM0ZZCmBFJCACUCjo4bFXEobhSEjyR4g6Bgo5LZomIZ6YGkV4zOsxxR6YxIIekcHcelqCKOTkNJLQ0KM0xpoPCSrrJBsTHqTNJmo8fRjIoxm/soIKzOGHrSIQ6vmGhbRwq3VaT0gDlDKQ+Iip8DTUXimJoxYx3CYA4Z5i/EXYCI4Poi2KOJCa4vhv2zhOD6EtjbFCszq8whwuyC+T2hLo7GkIT5PSEVp8Y0hvk94ea4indjgk8IlxHm93A2Dba8GX+PcixxHPSthAS/FxL8XkjweyHB74UEvydUUNThgGpASGGuwyHmG8rvEYlvXCHUXocD8nvCyZcOB+T3iM19v1BBfo+pK+2K1axVSJRSQPk9Kd+gEonQCyRTR2gG2FUQI4xGn+rYB3AFtjwDtdRRpJBBmjFIMwYpYJACBslnkHwGyWOQPAbJZZBcBmnKIE0JpIQASgicmMCJCRxGPTDagVEOjG5gVAOjGRjFIOmFMaaMUQuSVhjDYZQCpROYhYrioBBwNxj+0iEOY5jwS4cIvWey6zhEdh3q+gZxUYQ5SHaII2vGdHYIIz1iOMUIdztiglOMYS8qITjFBPYJO5uAMSQIgwVmFYVi0iq2j7m8Q1wSgllFIROjiu1jLoARYRswq4jHtDHUmkNwePCOy/h+lJOJ46BvJSJYxYhgFSOCVYwIVjEiWEWhRqAOB1QDQr5nHQ6o1oTEFTocYl6jrCIR6e7iZ2w7HJBVJLb3/UIFWcWIYRUjhlVkamS7YmVuFRKlFlBWUUrkp0QiNAPJDxK6AXZ/xDio0ac6IgRcgy0TQi12FClikEIGKWSQZgzSjEEKGKSAQfIZJJ9B8hgkj0FyGSSXQZoySFMCKSGAEgKHURCMfmDUA6MdGOXA6AZGNTCagVEMjF5g1AKjFRilQOkEZqGiOCgE3A2G73WIIyAmctUhAvGZ2/kOkXaFyazuEJnVmYswDnHlhjn6d4ggA8btcAgHJ2YY2Rh32RKCkU1gD7SzChhTgjBZYE7WxTlZqdS1ytwjLg3BnKxQ8UXFlcIpDnFOlrgu6xD3cpnwQIeIQ2SISYdgQOG9nfFnKccZx0HfSkxwsjHBycYEJxsTnGxMcLJCVTodDqgGhHS7OhxQrQl5NHQ4oJrGbwrscIj1g3KyxFmoS2zw+4UKcrIxw8nGDCcbM5xszHCyTMVuV6wvrkKiFAPKyUrJ9JRIhG4g2VVCO8AuHRPQ5rgdiSSuwqr77XsKu7eLbChnbMst2Whp3xcrUsW9Uo0y1VbwIwY/7Mcf4a+pdBoo0oxBChikgEHyGSSfQfIYJI9Bchkkl0GaMkhTAmlA9Qzz10T8FIrDaI0BpTHMXxP55FAcRjcwqoHRDIxiYPQCoxYYrcAoBUonMAsVxUEh4G4wLLxDHMwx8dcOEYDNZJtwiNQ4TCJ0h0iETqVXIhI5MRfKHOLqGhPM4hBhM4wr6BBOZ8Lw5AnuRnd2AWNMEEYLzJS7OFPuMUy5hzPlUjFulQlLJPKCmXKhcouKwWaStBFXOGGmHL/hzoS8OkRsLUMXOwQvDVsR4PJMCKY8IZjyhGDKE4IpTwimPCGY8oRgyhOCKRdKt+lwQDUg5GjW4YBqDc9Cs8MB1TR+/2WHA247+NnxDodZpyhTzhgTHRKnEgidADPlCcOUJwxTnjBMOVOc3RWrwKuQKNWAMuVSDkklEqEdSM6b0A+wmzoQooly4l5rf3vi2gTbapuSWxrdXG3gd3s7dYpnBz9m8KN+/GHjEkYKGaSQQZoxSDMGKWCQAgbJZ5B8BsljkDwGyWWQXAZpQMsMUwMo0oA6GeQ6UJwBtTHI3aA4jHpgtAOjHBjdwKgGRjMwioHRC4xaYLQCoxQoncAsVBQHhYC7wZxhOMSxJnOnwCEuFTDZZBwiyRSTUtshUv0zhV0dorArk+TNIdLJMRdMHeIqKxOe5RCBYIwb7RAO+y4qgLEmUDrBZc4ZXPycwWPOGTz8nMFnzhl8/JxBKnSuMsuJ0iTwOQNeiYlJCOsQmWeZVBQOkfOCCeN2iHhxhmx3CFYftotAk2iKnzN0FAnaDfycYUfF4DhofdApPjXbZ9DaBVN8qXl4tcQdDliMAc8Ov8MBE8Hheal2OOA1SvxO1w4HDHfBT953OKBhTWzx+4XKaAROJRA6ATXedkiEVoDLBk8JI7ZDohQD+FSHRKkGtFALUxPLY6pveUwmW4/JmesxmSA8JueE1x+zy51NkG19mWyqtKzy4van9SJt2qy/9OXb5Da9zz6kZf1v3cRm/vVhlT42P/y6++nz40M2f7O9rzG6D94u59EyvvGmfuzcXKdLJ8j8wEkX2cLxvWUYxdPrMA7CRvjeBpJoGWRJMHXSxK0b8NKZc50ufOcmCoPrpbcI/aTu5dfm/18mv+eLphNNO7VYnxZ5VlT5Tb6YvNqu6s6mq8nr9X1etH2avM4fVuv7+ufF5HN+Xw9BvnlfrPIie1d/Oe8EmFflNpukxeO6yF6lxaeHbFGlVTa/SVeb7NtksS3LGuJD991D7al2pGrZ08X19GY2mzlRchPXsieJk0bLxEnSYJrd+Av3xk33A/+pGfLP27KYT7/9H9LoGqMAYQEA
```
</details>
`

**Comment by yairm210** [comment]
Solved in 4.6.1-patch2
