### ISSUE TITLE
Game crash per click "new step"

### ISSUE THREAD

**Issue by itine** [yairm210/Unciv#9248]
**Platform:** Android
**Version:** 4.6.3 (Build 850)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: 21081111RG
API Level: 33

--------------------------------

**Message:**
```
com.unciv.logic.map.mapunit.UnitMovement$UnreachableDestinationException: Great Merchant - The Ottomans Tile @(0.0,6.0), Grassland, Jungle, Trading post, Great Merchant - The Ottomans, Sipahi - The Ottomans cannot reach Tile @(-4.0,-16.0), Tundra, Fallout, Trading post
	at com.unciv.logic.map.mapunit.UnitMovement.getTileToMoveToThisTurn(UnitMovement.kt:322)
	at com.unciv.logic.map.mapunit.UnitMovement.headTowards(UnitMovement.kt:343)
	at com.unciv.logic.automation.unit.SpecificUnitAutomation.conductTradeMission(SpecificUnitAutomation.kt:282)
	at com.unciv.logic.automation.unit.UnitAutomation.automateCivilianUnit(UnitAutomation.kt:295)
	at com.unciv.logic.automation.unit.UnitAutomation.automateUnitMoves(UnitAutomation.kt:147)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateUnits(NextTurnAutomation.kt:973)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:86)
	at com.unciv.logic.civilization.managers.TurnManager.automateTurn(TurnManager.kt:313)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:316)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:568)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:8)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:4)
	at com.unciv.utils.concurrency.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.$r8$lambda$nwZVoCWi6P2779l7sK5tCF-sQTA(Unknown Source:0)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```
**Save Mods:**
```
[Civ V - Gods & Kings]
```

**Comment by yairm210** [comment]
Please attach a game save

**Comment by itine** [comment]
Already deleted
