### ISSUE TITLE
UnCiv crash: NullPointerException

### ISSUE THREAD

**Issue by marek22k** [yairm210/Unciv#9249]
**Platform:** Android
**Version:** 4.6.4-patch2 (Build 854)
**Rulesets:** [Policy mod, Civ V - Vanilla, Resource Recyclers, AbsoluteUnits, Modern Joke Religions, The Demon World, Extra Buildings, Better Pantheons Lite, Extra Units, Barbarian xp farm, Barbarians but Better, The North Pole, CS Rework, Better Pantheons, Civ V - Gods & Kings, 5Hex Tileset, Logicians, The Barbarians, Extra Promotions, Better Units and Natural Wonders]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: FP4
API Level: 33

--------------------------------

**Message:**
```
java.lang.NullPointerException
	at com.unciv.logic.automation.unit.UnitAutomation.automateCivilianUnit(UnitAutomation.kt:280)
	at com.unciv.logic.automation.unit.UnitAutomation.automateUnitMoves(UnitAutomation.kt:147)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateUnits(NextTurnAutomation.kt:973)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:86)
	at com.unciv.logic.civilization.managers.TurnManager.automateTurn(TurnManager.kt:313)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:316)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:568)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:8)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:4)
	at com.unciv.utils.concurrency.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.$r8$lambda$nwZVoCWi6P2779l7sK5tCF-sQTA(Unknown Source:0)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```
**Save Mods:**
```
[CS Rework, Resource Recyclers, Civ V - Gods & Kings, Modern Joke Religions, Extra Buildings, 5Hex Tileset, Extra Units, Logicians, Barbarian xp farm, Extra Promotions, Barbarians but Better]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```
https://paste.i2pd.xyz/?8a102e89f1a6b764#opwoVCVzJ8bUx3kkPTzRMfTt57gjYX5WLPL87fUzmKM
https://paste.debian.net/1278055/
```
</details>

**Comment by marek22k** [comment]
I started a new game and the error still occurs. Is there a workaround?
