### ISSUE TITLE
title

### ISSUE THREAD

**Issue by 1207978133** [yairm210/Unciv#9259]
**Platform:** Android
**Version:** 4.6.0 (Build 845)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings, Medieval Civilizations, Community Maps, 5Hex Tileset, WW2 Nations]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: M2012K10C
API Level: 31

--------------------------------

**Message:**
```
java.lang.NullPointerException
	at com.unciv.logic.automation.unit.BattleHelper.getAttackableEnemies(BattleHelper.kt:81)
	at com.unciv.logic.automation.unit.BattleHelper.getAttackableEnemies$default(BattleHelper.kt:35)
	at com.unciv.ui.screens.worldscreen.WorldMapHolder.updateTilesForSelectedUnit(WorldMapHolder.kt:685)
	at com.unciv.ui.screens.worldscreen.WorldMapHolder.updateTiles$core(WorldMapHolder.kt:581)
	at com.unciv.ui.screens.worldscreen.WorldScreen.update(WorldScreen.kt:365)
	at com.unciv.ui.screens.worldscreen.WorldScreen.render(WorldScreen.kt:674)
	at com.badlogic.gdx.Game.render(Game.java:48)
	at com.unciv.UncivGame.access$render$s2211858(UncivGame.kt:125)
	at com.unciv.UncivGame$wrappedCrashHandlingRender$1.invoke(UncivGame.kt:143)
	at com.unciv.UncivGame$wrappedCrashHandlingRender$1.invoke(UncivGame.kt:143)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.UncivGame.render(UncivGame.kt:456)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:474)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1581)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1280)

```
**Save Mods:**
```
[5Hex Tileset, Civ V - Gods & Kings, Community Maps]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```
H4sIAAAAAAAAAOS965Jbt5Ko+Sqcjphfh/Qs3IGKEydCli3L05altrSPo9uhH6vIVSpus8hqkiVb7dC7D5CJBWDhwiJ16d09Z8e2zSLx4ZpA4pr513W/t/9f99vD1V8f58v1+/Vm/R/9cb2zX/z2l/37qf103D8s8SsM83N/N1x9G8j5an2/2d31yw9Xfz3t74fZm90f26u/dsfbYf/Uhw7ff5z/c3+8veu3q4ervzx4XC9f7Fbrm/Wwt0m8vu33w+r77XD34UrMvxuWG/f3r/3+5fZvh6uF+oZQ8XE+iT1E+XH+v4ftejk0oi4iI9/IIjKM4ePH+XC4t4Xu3w0vevfvvSv98KeN1sbwy/DO/ua+ebfbrIbtk3eDjX/7cHc97F/e/BC/E/PD0QHP+/v79XY4HK5Ix5nF9kN/fDXs7jeDi+V+t1kv18MBP98/3D/ZDPuja4Pjh/vhKkQ4f99vHoarf/qnj/PHfnm23h+OtvmO/fLof0xaAcPYisA6gSZvhfpCqfuKPZX0NEgljqSlT0RThKrk8+383x+GwzFp2/2wWbtWTb96WG8Pyd8uJ+tlv3nyI/w1LG/df9+vl7aNP8RwNtnl+uia0/Wh44cnPz7bLR8OV6/2uxV2Jfh77n7LOtj1w3pz/Nb+a7XevrP8i50VqmF7nD+5u79dWzntj8N+/tP63e3xdvdwGOavj/3xYZjtbmb/Ntgon+42u8NheLib/7C3NTB7M9xZEZu//rDaDh9mL++HfT97DuAvw/LDcmNTmT218dtIn9gKcdlLovxpbeX5+GH+7e7uevb6dti4cM93tmMc+838hR0sjv3+w+zb3sbn0rN/zL/d7/rVsj8cnQzZ4K/6Tb8c5t+vb26Gjf8ukE+W/cp29PmLfv/7cJzbQWXfL38/zNOMvr7d254z/9kWb3n7hx1wjsN6O//bdv3edmpbg/M3rlb2w/z5sN+tl7Pv79dLW7rD0O+Xt7Of+uv5iweokddDf7/bH23tXe9dTn/tN5uDK+1qbX/9tt/+Pn+63ruGeW4Ht93eRXhn82nF5tlu7/7dQ0O7BGc/uA48G6N6MaycXEBqrx6ubWeevV7e7nab+ZP9Ydjayvp1t//9cLu7t1/cuTheH3fL32ff/7m87bc26hf98vZh9mq9tP+Z/9DvrbjOX9/bijvcru9nY8I/g5TbdKCMr3dW7mevNv0W2uzatnMIYOVgM7xzreKy6Uo696Lw1DbNZng7XyaC9y8Pg+0Vv9k6PQ6rGUZyeDu/2Q9DkEUrvO/Xq2H1bL+7e3O7Pjy1VX/1V9cv1Y0cxELIFV1wwvXCLFf9QnF2Y3/rVktlXC/Y9Hbo+3v/vv/GZvfdN6+Ptk3f+d6YSYzrPaeCQ7N9fPtxvt7aPNmB9HDIOtG0HFfScNslrZzZDuGG7sPuYW91xI/b5bC18hXGeT/AWwmDsX35sDk+7IfXMH7bYVtx+nF+s+nf2eQetscVaLlfh5927wcrEP9sM3hFbAD7m6svq06untkuYUXfiufmeHvFqJivV1fn1Nh8fXi5t4ORbUk7GrvOdmWLN8w3uyWU6eqvP6/Y/MOV+jjfOp31ymriAyiOjf/9Zrdb+Zxrnf5C+PxwPyzX/WZ9OD7ZjDHaWvt+axMc3ACWV/+PdnywI5uvf/LxYxwsr/66dw1g68nG4PrF+IMbPuzfP1lwu6LqsUhN1320PX29Pe4eTV9LZj7O/21nxca2up2CrA93j0KCaf1x/tSOJYejQ5zwnkYE4zwpqZP5Hw+2SM93mw9O+F/eXGGGQ5DDk+Pr3d3wame/fbLa3VshvPrNh5lmd/66X9q2sR3TjqgHK8vH9QbUBbartH0AP+nwicMnGr7jIRwNn8jkUwyHnwRKjP9EOvio4kcX0oT0TIgbP8nwifhP4996wiWRqfBl/CTCrz6gCPmT8UsdP9KA04CT+DOZfBkDJrGbUFBj1f4fdiAeVm9CfY/1M9ZwrPVpHcY2kZPaTH8xWUZiJYhJayk3fE2mBq/t7M+OFZfPC0b1NZkfVHTZj/vd1hX9ELQY6rRkKhHnDu25wRmKbr1d3a2tvnn5581uv5olijrowEemEHUVGXTbG6vT7IjzoaIg88kH1sHsRf/n+s7Wxbfrd7NvnWZFbfkp05B03uEVqhtSdrNfBquzbSbmP+/sZGT2nR2Xw8xkMhtBBdyalPzzfrizNY+Tk6qW9qJif3vY722SqaT8ePjbYdi/Ho6oL85Q4FbjmJVeycX1crVccEX1Ql/z5WJYSn49XJOeCn6pArfCfR+mui9tdd1sdn+4XvqZOpgL+kVU8Dllnuha148XzCvbl/vN4Ja9DXVLOjHRt6Klb6Edj/bbxxSRHZee7M8M+GLYu+7yaNCvosT1+UrcKld1qQ5X9DIFLlP1/cV084IEZbWg8HHhPrP4LQtaYMHjtzzogUXUgQsZP7L4kcaPUSktop7xAZwqWej4MSqYRZwt+HhpxFgWL4s5Sz4meRAxbNRmPoaFCHMTlRU+Kn0fA80+WjU4t917+2T57w9r13coKdQzyzLAqpXA84L5avzPU7OoTZ/c23XXbgbrkv4uqNqoWS9RpGdqy0xNeuVpB8j9uEXwqJr8+WFpx7RsLflltOMZKnCyHq+qvHT/4axl6bDUq2sq+4VkN8OCm+F60TMpF+am13YhQMTNcP0JWq254kwzeEXtMPj5uo4ydaGu+3bYWKlb5drunLp4fMEJIxzov5BMSwHyqQJU/yUVIP0aCpDI8zWgEuxiDcg5uUwFUrvo/SQdmCaSqMBxqPdKkPqxf1R/C1iYxY80fvQBqA+Av42BaQhAA0WCXol4EifzX44LLNBDLFcohJlMo4QIxrxnS2hWSXaBi8z/bGVSao8T67J+e9sfj/3W6Z6/DycVzGQ391JtU1+bJdom1y2VXcr/Qprlyy6mDLuxo+qKLIZ+xRa8kzeL3nT9wgxkxZfmul9J9mUWU6z7/B1NqfmFGubNh32uXc4p8jnbmQL3cUDDQDLN5R

**Comment by yairm210** [comment]
The game save you attacked is incomplete, can you reattach it?

**Comment by yairm210** [comment]
Looking over the code, this is truly baffling, I have no idea how this could happen
