### ISSUE TITLE
General error message after installing mods

### ISSUE THREAD

**Issue by Boombastic76** [yairm210/Unciv#9294]
**Platform**
**Platform:** Android
**Version:** 4.6.6 (Build 856)
**Rulesets:** [Higher quality builtin sounds, Policy mod, Modern Civilizations, Ruins Extended, AbsoluteUnitsXL, Brave New World, Historica, Medieval Civilizations, 3rd and 4th Unique Component, Leader Mission, Extra Buildings, Uncivilized Enhancer, Civ6 Icons, Higher Quality City Ambience Sounds, 4th Unique Component, Old Ancient Civilizations, More Luxuries, Only Mod Civilizations, Better Units and Natural Wonders, More Fauna And Flora, Unciv Vanilla Music Pack, Civ V - Vanilla, Additional Music Ambient, Repairing Improvements in older mods, Greek Civ Split, AbsoluteUnits, Slow Tech, Civ6 mod, Civ V Leader portraits, Upgradable Scouts, Civ6 Tileset, Better Pantheons, Upgradable Scouts BNW, Civ5 CityState Music, Ancient Civilizations, Policy Mod Plus, Nusantara Civilizations, Expanded Warfare, Civ6 Nations for Unciv, Civ V - Gods & Kings, Leaders Plus, The Great Unciv Rework, Additional Music Various, 5Hex Tileset, Better ruins, Better Workers, The Barbarians, Ruins Extended Classic Edition]
**Last Screen:** `com.unciv.ui.screens.mainmenuscreen.MainMenuScreen`

--------------------------------

Device Model: SM-G973F
API Level: 31

--------------------------------

**Message:**
```
java.lang.NullPointerException
	at com.unciv.models.ruleset.RulesetCache.getVanillaRuleset(Ruleset.kt:529)
	at com.unciv.models.ruleset.RulesetValidator.getErrorList(RulesetValidator.kt:132)
	at com.unciv.models.ruleset.Ruleset.checkModLinks(Ruleset.kt:462)
	at com.unciv.ui.popups.options.ModCheckTab$runModChecker$1.invokeSuspend(ModCheckTab.kt:101)
	at com.unciv.ui.popups.options.ModCheckTab$runModChecker$1.invoke(Unknown Source:8)
	at com.unciv.ui.popups.options.ModCheckTab$runModChecker$1.invoke(Unknown Source:4)
	at com.unciv.utils.concurrency.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.$r8$lambda$nwZVoCWi6P2779l7sK5tCF-sQTA(Unknown Source:0)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.ut**Platform:** Android
**Version:** 4.6.6 (Build 856)
**Rulesets:** [Higher quality builtin sounds, Policy mod, Modern Civilizations, Ruins Extended, AbsoluteUnitsXL, Brave New World, Historica, Medieval Civilizations, 3rd and 4th Unique Component, Leader Mission, Extra Buildings, Uncivilized Enhancer, Civ6 Icons, Higher Quality City Ambience Sounds, 4th Unique Component, Old Ancient Civilizations, More Luxuries, Only Mod Civilizations, Better Units and Natural Wonders, More Fauna And Flora, Unciv Vanilla Music Pack, Civ V - Vanilla, Additional Music Ambient, Repairing Improvements in older mods, Greek Civ Split, AbsoluteUnits, Slow Tech, Civ6 mod, Civ V Leader portraits, Upgradable Scouts, Civ6 Tileset, Better Pantheons, Upgradable Scouts BNW, Civ5 CityState Music, Ancient Civilizations, Policy Mod Plus, Nusantara Civilizations, Expanded Warfare, Civ6 Nations for Unciv, Civ V - Gods & Kings, Leaders Plus, The Great Unciv Rework, Additional Music Various, 5Hex Tileset, Better ruins, Better Workers, The Barbarians, Ruins Extended Classic Edition]
**Last Screen:** `com.unciv.ui.screens.mainmenuscreen.MainMenuScreen`

--------------------------------

Device Model: SM-G973F
API Level: 31

--------------------------------


**Message:**
```
java.lang.NullPointerException
	at com.unciv.models.ruleset.RulesetCache.getVanillaRuleset(Ruleset.kt:529)
	at com.unciv.models.ruleset.RulesetValidator.getErrorList(RulesetValidator.kt:132)
	at com.unciv.models.ruleset.Ruleset.checkModLinks(Ruleset.kt:462)
	at com.unciv.ui.popups.options.ModCheckTab$runModChecker$1.invokeSuspend(ModCheckTab.kt:101)
	at com.unciv.ui.popups.options.ModCheckTab$runModChecker$1.invoke(Unknown Source:8)
	at com.unciv.ui.popups.options.ModCheckTab$runModChecker$1.invoke(Unknown Source:4)
	at com.unciv.utils.concurrency.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.$r8$lambda$nwZVoCWi6P2779l7sK5tCF-sQTA(Unknown Source:0)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

```

**Comment by Boombastic76** [comment]
I installed them all at once, so it is hard to tell which caused it, at least for now. If I have further insight I will let you know.

**Comment by Boombastic76** [comment]
Yes, after checking the mods based on various set of rules and leaving back to main menu. By the way, I played some rounds with the majority of the mods activated. Now I experience a load error from an autosaved game. 

I will open a new thread for it.
