### ISSUE TITLE
An unrecoverable error has ocurred in Unciv

### ISSUE THREAD

**Issue by LeonardoCV7** [yairm210/Unciv#9320]
**Platform:** Desktop
**Version:** 4.6.6 (Build 856)
**Rulesets:** [Civ V - Vanilla, RekMOD, Civ V - Gods & Kings, 5Hex Tileset]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

OS: Windows 10
Java: Oracle Corporation 25.232-b09
	Max Memory: 910 MB

--------------------------------

**Message:**
```
java.lang.NullPointerException
	at com.unciv.logic.civilization.managers.ReligionManager.chooseBeliefs(ReligionManager.kt:346)
	at com.unciv.logic.civilization.managers.ReligionManager.chooseBeliefs$default(ReligionManager.kt:343)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.chooseFreeBeliefs(NextTurnAutomation.kt:672)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.chooseReligiousBeliefs(NextTurnAutomation.kt:632)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:90)
	at com.unciv.logic.civilization.managers.TurnManager.automateTurn(TurnManager.kt:313)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:316)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:568)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
	at com.unciv.utils.concurrency.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:164)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```
**Save Mods:**
```
[5Hex Tileset, RekMOD]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```
H4sIAAAAAAAAAOy9a5PbRpa/+VVq5zWpRd4T9U6W25d/W5bG8oxj16GYQJEoFdslsoZk2VY79N038+T9BoJFye2Z2Ah3iwXkk/c8eQHwO3/8Ou4Pm932+o/t4/ubcX9NFqv9OBzH9U+ ...
```
</details>

**Comment by yairm210** [comment]
You need to attach the entire saved game, what you have in the save data is just a very small portion of it with ... at the end
