### ISSUE TITLE
Instantly crash when open unciv

### ISSUE THREAD

**Issue by AdityaMH** [yairm210/Unciv#9363]
**Platform:** Android
**Version:** 4.6.10-patch1 (Build 863)
**Rulesets:** [Gold UI, Nat5 Design, Civ V - Vanilla, Brave New World, Civ V - Gods & Kings, Nat5 Music, DeCiv Redux, Civ5 Tileset, Thin Bubbly Borders, Civ 5 Icons, Map, Alpha Frontier]
**Last Screen:** `com.unciv.ui.screens.newgamescreen.NewGameScreen`

--------------------------------

Device Model: M2010J19SG
API Level: 29

--------------------------------

**Message:**
```
java.lang.NullPointerException: Attempt to read from field 'float com.badlogic.gdx.math.Rectangle.x' on a null object reference
	at com.unciv.ui.components.NativeBitmapFontData.getGlyph(Fonts.kt:122)
	at com.badlogic.gdx.graphics.g2d.BitmapFont$BitmapFontData.getGlyphs(BitmapFont.java:845)
	at com.unciv.ui.components.NativeBitmapFontData.getGlyphs(Fonts.kt:177)
	at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:178)
	at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:95)
	at com.badlogic.gdx.scenes.scene2d.ui.Label.computePrefSize(Label.java:162)
	at com.badlogic.gdx.scenes.scene2d.ui.Label.scaleAndComputePrefSize(Label.java:147)
	at com.badlogic.gdx.scenes.scene2d.ui.Label.getPrefWidth(Label.java:244)
	at com.badlogic.gdx.scenes.scene2d.ui.Value$3.get(Value.java:87)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.computeSize(Table.java:827)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.getPrefWidth(Table.java:432)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.getPrefWidth(Button.java:244)
	at com.badlogic.gdx.scenes.scene2d.ui.VerticalGroup.computeSize(VerticalGroup.java:117)
	at com.badlogic.gdx.scenes.scene2d.ui.VerticalGroup.getPrefWidth(VerticalGroup.java:295)
	at com.badlogic.gdx.scenes.scene2d.ui.Value$3.get(Value.java:87)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.computeSize(Table.java:827)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.getPrefWidth(Table.java:432)
	at com.badlogic.gdx.scenes.scene2d.ui.SplitPane.getPrefWidth(SplitPane.java:173)
	at com.badlogic.gdx.scenes.scene2d.ui.Value$3.get(Value.java:87)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.computeSize(Table.java:827)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.layout(Table.java:953)
	at com.unciv.ui.screens.pickerscreens.PickerPane.layout(PickerPane.kt:65)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.validate(WidgetGroup.java:113)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:108)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:111)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
	at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:129)
	at com.unciv.ui.screens.basescreen.UncivStage.access$draw$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$draw$1.invoke(UncivStage.kt:53)
	at com.unciv.ui.screens.basescreen.UncivStage$draw$1.invoke(UncivStage.kt:53)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.screens.basescreen.UncivStage.draw(UncivStage.kt:53)
	at com.unciv.ui.screens.basescreen.BaseScreen.render(BaseScreen.kt:83)
	at com.badlogic.gdx.Game.render(Game.java:48)
	at com.unciv.UncivGame.access$render$s2211858(UncivGame.kt:125)
	at com.unciv.UncivGame$wrappedCrashHandlingRender$1.invoke(UncivGame.kt:143)
	at com.unciv.UncivGame$wrappedCrashHandlingRender$1.invoke(UncivGame.kt:143)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.UncivGame.render(UncivGame.kt:456)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:474)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1577)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)

```

**Comment by AdityaMH** [comment]
actually only crash when press "Start New Game" in main menu.

**Comment by Wheelchair2** [comment]
It's definitely from a certain mod, if you remember the latest mod you downloaded or updated, try deleting it and then test starting a game again

**Comment by Wheelchair2** [comment]
> How do you figure that?

I have a mod of my own, which I messed up and caused the game to crash. OP's error message looked very similar to my error message when it crashed, which also happened after clicking "Start New Game"
However, whenever the mod is updated (if coding is fixed) it will be back fine

**Comment by Wheelchair2** [comment]
"unique": "[+50]% Strength <in [Friendly Land] tiles"
Can cause the game to crash
There were various other 'inputs' that could cause the game to crash, like maybe typing an input wrong in the "game.atlas" file (I'm not really sure about crashes in 'game.atlas,' but that's just my assumption) so perhaps, it's just an easily solvable problem in the mod's part...?

**Comment by Wheelchair2** [comment]
Oh no, I added it to a unit's unique. But making the unique a promotion before giving it to the unit works

**Comment by AdityaMH** [comment]
Also if you named a mod vanilla or gnk.
can lead to crash and a only fixing is just uninstall.
