### ISSUE TITLE
Crash after enhancing religion

### ISSUE THREAD

**Issue by microsynthera** [yairm210/Unciv#9389]
**Platform:** Android
**Version:** 4.6.9-patch2 (Build 861)
**Rulesets:** [Higher quality builtin sounds, Civ V - Vanilla, Medieval Civilizations, Community Maps, Thin Bubbly Borders, Gold UI, Higher Quality City Ambience Sounds, Smoky Skies Redux, Ancient Civilizations, Civ V - Gods & Kings, Project Paddy Field, Fantasia]
**Last Screen:** `com.unciv.ui.screens.pickerscreens.ReligiousBeliefsPickerScreen`

--------------------------------

Device Model: SM-T870
API Level: 33

--------------------------------

**Message:**
```
java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at com.unciv.logic.civilization.managers.ReligionManager.foundReligion$core(ReligionManager.kt:547)
	at com.unciv.ui.screens.pickerscreens.ReligiousBeliefsPickerScreen$1.invoke(ReligiousBeliefsPickerScreen.kt:78)
	at com.unciv.ui.screens.pickerscreens.ReligiousBeliefsPickerScreen$1.invoke(ReligiousBeliefsPickerScreen.kt:74)
	at com.unciv.ui.screens.pickerscreens.ReligionPickerScreenCommon$setOKAction$1.invoke(ReligionPickerScreenCommon.kt:68)
	at com.unciv.ui.screens.pickerscreens.ReligionPickerScreenCommon$setOKAction$1.invoke(ReligionPickerScreenCommon.kt:67)
	at com.unciv.ui.components.extensions.Scene2dExtensionsKt$onClick$1.invoke(Scene2dExtensions.kt:326)
	at com.unciv.ui.components.extensions.Scene2dExtensionsKt$onClick$1.invoke(Scene2dExtensions.kt:326)
	at com.unciv.ui.components.extensions.OnClickListener.clicked(Scene2dExtensions.kt:306)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:78)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:78)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:78)
	at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:426)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:472)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1593)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1287)

```
**Save Mods:**
```
[Higher quality builtin sounds, Higher Quality City Ambience Sounds, Ancient Civilizations, Medieval Civilizations, Civ V - Gods & Kings, Community Maps, Project Paddy Field, Thin Bubbly Borders]
```

**Comment by microsynthera** [comment]
duplicate of #9362
