### ISSUE TITLE
Crash when accessing installed mod details

### ISSUE THREAD

**Issue by microsynthera** [yairm210/Unciv#9390]
**Platform:** Android
**Version:** 4.6.12 (Build 867)
**Rulesets:** [Unciv Vanilla Music Pack, Civ V - Vanilla, Ancient Civilizations, Civ V - Gods & Kings, Community Maps, Thin Bubbly Borders, Additional Music Various]
**Last Screen:** `com.unciv.ui.screens.pickerscreens.ModManagementScreen`

--------------------------------

Device Model: SM-T870
API Level: 33

--------------------------------

**Message:**
```
java.text.ParseException: Unparseable date: "Caballero-Arepa"
	at java.text.DateFormat.parse(DateFormat.java:389)
	at com.unciv.ui.components.extensions.UncivDateFormat.parseDate(FormattingExtensions.kt:91)
	at com.unciv.ui.screens.pickerscreens.ModManagementScreen.addModInfoToActionTable(ModManagementScreen.kt:413)
	at com.unciv.ui.screens.pickerscreens.ModManagementScreen.addModInfoToActionTable(ModManagementScreen.kt:359)
	at com.unciv.ui.screens.pickerscreens.ModManagementScreen.refreshInstalledModActions(ModManagementScreen.kt:557)
	at com.unciv.ui.screens.pickerscreens.ModManagementScreen.installedButtonAction(ModManagementScreen.kt:630)
	at com.unciv.ui.screens.pickerscreens.ModManagementScreen.access$installedButtonAction(ModManagementScreen.kt:63)
	at com.unciv.ui.screens.pickerscreens.ModManagementScreen$refreshInstalledModTable$3.invoke(ModManagementScreen.kt:614)
	at com.unciv.ui.screens.pickerscreens.ModManagementScreen$refreshInstalledModTable$3.invoke(ModManagementScreen.kt:612)
	at com.unciv.ui.components.extensions.Scene2dExtensionsKt$onClick$1.invoke(Scene2dExtensions.kt:326)
	at com.unciv.ui.components.extensions.Scene2dExtensionsKt$onClick$1.invoke(Scene2dExtensions.kt:326)
	at com.unciv.ui.components.extensions.OnClickListener.clicked(Scene2dExtensions.kt:306)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:78)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:78)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:78)
	at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:426)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:472)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1593)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1287)

```

Reproduce: 
1. Install a mod. 
2. Click installed mod.

**Comment by yairm210** [comment]
Unbelievable, I already solved this and must not have committed it...
Thanks, will roll out patch :)

**Comment by microsynthera** [comment]
Now noticing the "remove mod" dialog does not appear. 
On the "Available Mods" listing: 
1. Download something. It says "Downloaded!" 
2. Click another mod, click back. 
3. The dialog will appear as if the mod is not downloaded at all.

**Comment by microsynthera** [comment]
> Unbelievable, I already solved this and must not have committed it... Thanks, will roll out patch :)

Ah, yes, i see

**Comment by yairm210** [comment]
I don't see your point on the 'download mod', what are you expecting to happen?
