### ISSUE TITLE
Bug: Mod window closed

### ISSUE THREAD

**Issue by Atmo26** [yairm210/Unciv#9391]
**Platform:** Desktop
**Version:** 4.6.12-patch1 (Build 868)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings, AbsoluteUnits, Epic of Fantasy, Barbarian xp farm, Better ruins, The Barbarians, Atmo's mod, Alpha Frontier, Fantasia]
**Last Screen:** `com.unciv.ui.screens.pickerscreens.ModManagementScreen`

--------------------------------

OS: Windows 10
Java: Oracle Corporation 25.232-b09
	Max Memory: 910 MB

--------------------------------

**Message:**
```
java.net.MalformedURLException: no protocol: none/master/preview.png
	at java.net.URL.<init>(URL.java:610)
	at java.net.URL.<init>(URL.java:507)
	at java.net.URL.<init>(URL.java:456)
	at com.unciv.ui.screens.pickerscreens.Github.download(GitHub.kt:49)
	at com.unciv.ui.screens.pickerscreens.Github.download$default(GitHub.kt:48)
	at com.unciv.ui.screens.pickerscreens.Github.tryGetPreviewImage(GitHub.kt:258)
	at com.unciv.ui.screens.pickerscreens.ModManagementScreen$addModInfoToActionTable$1.invokeSuspend(ModManagementScreen.kt:395)
	at com.unciv.ui.screens.pickerscreens.ModManagementScreen$addModInfoToActionTable$1.invoke(ModManagementScreen.kt)
	at com.unciv.ui.screens.pickerscreens.ModManagementScreen$addModInfoToActionTable$1.invoke(ModManagementScreen.kt)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by yairm210** [comment]
This is still an issue we need to fix
