### ISSUE TITLE
it stops me from downloading mods

### ISSUE THREAD

**Issue by passionated** [yairm210/Unciv#9416]
**Platform:** Desktop
**Version:** 4.6.12-patch1 (Build 868)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.screens.pickerscreens.ModManagementScreen`

--------------------------------

OS: Windows 10
	Windows 10 Pro Version 21H2 (Build 19044)
Java: Oracle Corporation 17.0.2+8-LTS-86
	Max Memory: 2008 MB

--------------------------------

**Message:**
```
java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:168)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:76)
	at com.unciv.ui.screens.pickerscreens.Github.download(GitHub.kt:57)
	at com.unciv.ui.screens.pickerscreens.Github.download$default(GitHub.kt:48)
	at com.unciv.ui.screens.pickerscreens.Github.tryGetPreviewImage(GitHub.kt:258)
	at com.unciv.ui.screens.pickerscreens.ModManagementScreen$addModInfoToActionTable$1.invokeSuspend(ModManagementScreen.kt:395)
	at com.unciv.ui.screens.pickerscreens.ModManagementScreen$addModInfoToActionTable$1.invoke(ModManagementScreen.kt)
	at com.unciv.ui.screens.pickerscreens.ModManagementScreen$addModInfoToActionTable$1.invoke(ModManagementScreen.kt)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by CrsiX** [comment]
This looks like a network problem, GitHub sometimes has network timeouts. Could you please retry it a few minutes later and see if the issue persists? I was able to download a mod just fine a few moments ago.

What exactly did you do: which mod/mods did you try to download?

**Comment by yairm210** [comment]
Definitely solvable with a try/catch

**Comment by passionated** [comment]
> 这看起来像是网络问题，GitHub有时会出现网络超时。您能否在几分钟后重试，看看问题是否仍然存在？不久前，我能够很好地下载一个模组。
> 
> 你到底做了什么：你尝试下载了哪些模组？

nothing at all. that just appear unreasonable
