### ISSUE TITLE
Crash durinf end of turn

### ISSUE THREAD

**Issue by stephanepapin** [yairm210/Unciv#9431]
**Platform:** Desktop
**Version:** 4.6.12-patch1 (Build 868)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

OS: Windows 10
Java: Oracle Corporation 25.232-b09
	Max Memory: 910 MB

--------------------------------

**Message:**
```
com.unciv.logic.map.mapunit.UnitMovement$UnreachableDestinationException: Worker - Mongolia Tile @(-22.0,3.0), Grassland, Spices, Plantation, Worker - Mongolia cannot reach Tile @(-17.0,10.0), Plains, Hill
	at com.unciv.logic.map.mapunit.UnitMovement.getTileToMoveToThisTurn(UnitMovement.kt:341)
	at com.unciv.logic.map.mapunit.UnitMovement.headTowards(UnitMovement.kt:362)
	at com.unciv.logic.automation.unit.WorkerAutomation.tryConnectingCities(WorkerAutomation.kt:258)
	at com.unciv.logic.automation.unit.WorkerAutomation.automateWorkerAction(WorkerAutomation.kt:179)
	at com.unciv.logic.automation.unit.WorkerAutomation$Companion.automateWorkerAction(WorkerAutomation.kt:112)
	at com.unciv.logic.automation.unit.UnitAutomation.automateCivilianUnit(UnitAutomation.kt:242)
	at com.unciv.logic.automation.unit.UnitAutomation.automateUnitMoves(UnitAutomation.kt:152)
	at com.unciv.logic.map.mapunit.MapUnit.doAction(MapUnit.kt:492)
	at com.unciv.ui.screens.worldscreen.status.NextTurnButton$getNextTurnAction$15$1.invokeSuspend(NextTurnButton.kt:165)
	at com.unciv.ui.screens.worldscreen.status.NextTurnButton$getNextTurnAction$15$1.invoke(NextTurnButton.kt)
	at com.unciv.ui.screens.worldscreen.status.NextTurnButton$getNextTurnAction$15$1.invoke(NextTurnButton.kt)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by yairm210** [comment]
Can you attach the game save for this? We can't work on this issue in this state

**Comment by yairm210** [comment]
Since no more data is forthcoming, closing as unworkable
