### ISSUE TITLE
Unable to convert value to required type: true

### ISSUE THREAD

**Issue by marek22k** [yairm210/Unciv#9439]
**Platform**
Operating system type, major version, architecture (64/32 bit).
Parrot OS (Debian 11-based)

**Version**
4.6.13 (Build 869)

**Describe the bug**
```
$./Unciv 
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
2023-05-23T08:31:35.384783Z [threadpool-daemon-1] [OnlineMultiplayerServer$checkServerStatus] [ERROR] https://uncivserver.xyz does not support server feature set | com.badlogic.gdx.utils.SerializationException: Unable to convert value to required type: true (com.unciv.logic.multiplayer.ServerFeatureSet)
	at com.badlogic.gdx.utils.Json.readValue(Json.java:1173)
	at com.badlogic.gdx.utils.Json.fromJson(Json.java:834)
	at com.unciv.logic.multiplayer.storage.OnlineMultiplayerServer$checkServerStatus$1.invoke(OnlineMultiplayerServer.kt:53)
	at com.unciv.logic.multiplayer.storage.OnlineMultiplayerServer$checkServerStatus$1.invoke(OnlineMultiplayerServer.kt:49)
	at com.unciv.logic.multiplayer.storage.SimpleHttp.sendRequest(SimpleHttp.kt:62)
	at com.unciv.logic.multiplayer.storage.SimpleHttp.sendGetRequest(SimpleHttp.kt:21)
	at com.unciv.logic.multiplayer.storage.SimpleHttp.sendGetRequest$default(SimpleHttp.kt:20)
	at com.unciv.logic.multiplayer.storage.OnlineMultiplayerServer.checkServerStatus(OnlineMultiplayerServer.kt:49)
	at com.unciv.UncivGame$create$1.invokeSuspend(UncivGame.kt:184)
	at com.unciv.UncivGame$create$1.invoke(UncivGame.kt)
	at com.unciv.UncivGame$create$1.invoke(UncivGame.kt)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x5200024
  Serial number of failed request:  2464
  Current serial number in output stream:  2464
```

**To Reproduce**
1. Install UnCiv (Download zip and extract it)
2. Click on New Game
3. Click on Start game
4. Open the menu
5. Click on Load game
6. Click on Load from external location
7. Select .json file (where the game is saved)
8. Crash

**Expected behavior**
Load the game

Game I try to load: [Logiker (621 Runden).json.txt](https://github.com/yairm210/Unciv/files/11541442/Logiker.621.Runden.json.txt)

**Comment by yairm210** [comment]
@touhidurrr any clue?

**Comment by touhidurrr** [comment]
regular json reader will fail trying to read minimal json. maybe try to read the json as minimal if regular fails? is regular json in 4.6.13?

**Comment by touhidurrr** [comment]
**Note 2:** minimal json readers might be able to read both regular and minimal jsons for their design. Although not completely sure about this and this might need some experimentation to check. @yairm210

**Comment by touhidurrr** [comment]
> [OnlineMultiplayerServer$checkServerStatus] [ERROR] https://uncivserver.xyz does not support server feature set | com.badlogic.gdx.utils.SerializationException: Unable to convert value to required type: true (com.unciv.logic.multiplayer.ServerFeatureSet)

Also, what does this mean? https://uncivserver.xyz/isalive is returning `true` as usual.

**Comment by yairm210** [comment]
Huh
That makes sense, and if that's the case then all we need to do it

I checked the json parsing for files and can confirm that json parser handles both types, but since here both "true" and true are valid jsons, that probably confused it

**Comment by yairm210** [comment]
Waaaitasecond, you're running with 4.6.13, which doesn't yet *have* the new json stuff
Which makes this super weird

**Comment by touhidurrr** [comment]
@marek22k can you kindly try to reproduce the error? It might be a temporary dns error or something.
Also what is your location? I heard that the server doesn’t work properly in China.

Also, @yairm210, why is importing a save file throwing `/isalive` errors. Curious.

**Comment by marek22k** [comment]
I am on another computer right now and have noticed the same behavior there. In addition to this, I also discovered another error: when I first tried (on both computers) to load the game, another error occurred. However, this one did not appear on both computers the second time I tried to load the game:
```
$./Unciv 
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
2023-05-23T17:20:59.522871Z [threadpool-daemon-1] [OnlineMultiplayerServer$checkServerStatus] [ERROR] https://uncivserver.xyz does not support server feature set | com.badlogic.gdx.utils.SerializationException: Unable to convert value to required type: true (com.unciv.logic.multiplayer.ServerFeatureSet)
	at com.badlogic.gdx.utils.Json.readValue(Json.java:1173)
	at com.badlogic.gdx.utils.Json.fromJson(Json.java:834)
	at com.unciv.logic.multiplayer.storage.OnlineMultiplayerServer$checkServerStatus$1.invoke(OnlineMultiplayerServer.kt:53)
	at com.unciv.logic.multiplayer.storage.OnlineMultiplayerServer$checkServerStatus$1.invoke(OnlineMultiplayerServer.kt:49)
	at com.unciv.logic.multiplayer.storage.SimpleHttp.sendRequest(SimpleHttp.kt:62)
	at com.unciv.logic.multiplayer.storage.SimpleHttp.sendGetRequest(SimpleHttp.kt:21)
	at com.unciv.logic.multiplayer.storage.SimpleHttp.sendGetRequest$default(SimpleHttp.kt:20)
	at com.unciv.logic.multiplayer.storage.OnlineMultiplayerServer.checkServerStatus(OnlineMultiplayerServer.kt:49)
	at com.unciv.UncivGame$create$1.invokeSuspend(UncivGame.kt:184)
	at com.unciv.UncivGame$create$1.invoke(UncivGame.kt)
	at com.unciv.UncivGame$create$1.invoke(UncivGame.kt)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fbd98a1d760, pid=227442, tid=227672
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (11.0.11+9) (build 11.0.11+9)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (11.0.11+9, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libpthread.so.0+0xa760]  pthread_mutex_lock+0x0
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/bandura/Downloads/hs_err_pid227442.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted
```
[hs_err_pid227442.log.txt](https://github.com/yairm210/Unciv/files/11546797/hs_err_pid227442.log.txt)
Otherwise, the following error has also occurred as before:
```
$./Unciv 
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
2023-05-23T17:21:55.566643Z [threadpool-daemon-1] [OnlineMultiplayerServer$checkServerStatus] [ERROR] https://uncivserver.xyz does not support server feature set | com.badlogic.gdx.utils.SerializationException: Unable to convert value to required type: true (com.unciv.logic.multiplayer.ServerFeatureSet)
	at com.badlogic.gdx.utils.Json.readValue(Json.java:1173)
	at com.badlogic.gdx.utils.Json.fromJson(Json.java:834)
	at com.unciv.logic.multiplayer.storage.OnlineMultiplayerServer$checkServerStatus$1.invoke(OnlineMultiplayerServer.kt:53)
	at com.unciv.logic.multiplayer.storage.OnlineMultiplayerServer$checkServerStatus$1.invoke(OnlineMultiplayerServer.kt:49)
	at com.unciv.logic.multiplayer.storage.SimpleHttp.sendRequest(SimpleHttp.kt:62)
	at com.unciv.logic.multiplayer.storage.SimpleHttp.sendGetRequest(SimpleHttp.kt:21)
	at com.unciv.logic.multiplayer.storage.SimpleHttp.sendGetRequest$default(SimpleHttp.kt:20)
	at com.unciv.logic.multiplayer.storage.OnlineMultiplayerServer.checkServerStatus(OnlineMultiplayerServer.kt:49)
	at com.unciv.UncivGame$create$1.invokeSuspend(UncivGame.kt:184)
	at com.unciv.UncivGame$create$1.invoke(UncivGame.kt)
	at com.unciv.UncivGame$create$1.invoke(UncivGame.kt)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x5800024
  Serial number of failed request:  1234
  Current serial number in output stream:  1234

```

**Comment by marek22k** [comment]
Furthermore, my internet connectivity should not actually affect the offline loading of the game.
Regarding my connection, I can say that I use DNS-over-TLS from Cloudlfare and my provider is FranTech (AS53667, located in Luxenburg).
```
$curl -v https://uncivserver.xyz/isalive
* Uses proxy env variable no_proxy == 'localhost,127.0.0.0/8,::1'
* Uses proxy env variable https_proxy == 'http://127.0.0.1:8118/'
*   Trying 127.0.0.1:8118...
* Connected to 127.0.0.1 (127.0.0.1) port 8118 (#0)
* allocate connect buffer
* Establish HTTP proxy tunnel to uncivserver.xyz:443
> CONNECT uncivserver.xyz:443 HTTP/1.1
> Host: uncivserver.xyz:443
> User-Agent: curl/7.88.1
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< 
* CONNECT phase completed
* CONNECT tunnel established, response 200
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=uncivserver.xyz
*  start date: Apr 30 01:22:33 2023 GMT
*  expire date: Jul 29 01:22:32 2023 GMT
*  subjectAltName: host "uncivserver.xyz" matched cert's "uncivserver.xyz"
*  issuer: C=US; O=Google Trust Services LLC; CN=GTS CA 1P5
*  SSL certificate verify ok.
* using HTTP/2
* h2h3 [:method: GET]
* h2h3 [:path: /isalive]
* h2h3 [:scheme: https]
* h2h3 [:authority: uncivserver.xyz]
* h2h3 [user-agent: curl/7.88.1]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x55fa236751e0)
> GET /isalive HTTP/2
> Host: uncivserver.xyz
> user-agent: curl/7.88.1
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 200 
< date: Tue, 23 May 2023 17:19:16 GMT
< content-type: text/plain; charset=utf-8
< content-length: 4
< via: 1.1 vegur
< cf-cache-status: DYNAMIC
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=Ksbcz4gykpyl3li4SYb%2FNS1wiCGLSAz2gcMNuCLJnHojsb50phMSOnOpgyogLCj7HXUVq2BD1Rx%2B3gMxPrdC87%2B%2B%2FM3GZ2EjYYJbcV8gtcTfJMHvfzT0BPAWZsgnDZr21%2Bm4MmbDrAWQbdo2jmA%3D"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< expect-ct: max-age=86400, enforce
< referrer-policy: same-origin
< x-content-type-options: nosniff
< x-frame-options: SAMEORIGIN
< x-xss-protection: 1; mode=block
< server: cloudflare
< cf-ray: 7cbef6815db130d5-FRA
< alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
< 
* Connection #0 to host 127.0.0.1 left intact
true
```
Maybe it's the Privoxy proxy, which is connected in between?

**Comment by marek22k** [comment]
Without Privoxy it does not work either. Something else I noticed: The error `Unable to convert value to required type: true` appears already at startup. The crash occurs only when loading the game with the following message:
```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x5a00024
  Serial number of failed request:  1148
  Current serial number in output stream:  1148
```

**Comment by yairm210** [comment]
https://github.com/adoptium/adoptium-support/issues/344
JRE version: OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (11.0.11+9) (build 11.0.11+9)

And that comes from us, presumably
This means that updating the JDK should probably solve this

**Comment by touhidurrr** [comment]
@marek22k can you try running `java -jar Unciv.jar` from the folder containing `Unciv.jar` and see if the error persists.

**Comment by yairm210** [comment]
Okay, looks like latest Adoptium build is working :)
Please try out https://github.com/yairm210/Unciv/releases/download/test-adoptium-jre/Unciv-Linux64.zip

**Comment by marek22k** [comment]
> @marek22k can you try running `java -jar Unciv.jar` from the folder containing `Unciv.jar` and see if the error persists.

This also results in an crash.



> Please try out https://github.com/yairm210/Unciv/releases/download/test-adoptium-jre/Unciv-Linux64.zip

```
$./Unciv 
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
2023-05-23T21:57:18.913493Z [threadpool-daemon-1] [OnlineMultiplayerServer$checkServerStatus] [ERROR] https://uncivserver.xyz does not support server feature set | com.badlogic.gdx.utils.SerializationException: Unable to convert value to required type: true (com.unciv.logic.multiplayer.ServerFeatureSet)
	at com.badlogic.gdx.utils.Json.readValue(Json.java:1173)
	at com.badlogic.gdx.utils.Json.fromJson(Json.java:834)
	at com.unciv.logic.multiplayer.storage.OnlineMultiplayerServer$checkServerStatus$1.invoke(OnlineMultiplayerServer.kt:53)
	at com.unciv.logic.multiplayer.storage.OnlineMultiplayerServer$checkServerStatus$1.invoke(OnlineMultiplayerServer.kt:49)
	at com.unciv.logic.multiplayer.storage.SimpleHttp.sendRequest(SimpleHttp.kt:62)
	at com.unciv.logic.multiplayer.storage.SimpleHttp.sendGetRequest(SimpleHttp.kt:21)
	at com.unciv.logic.multiplayer.storage.SimpleHttp.sendGetRequest$default(SimpleHttp.kt:20)
	at com.unciv.logic.multiplayer.storage.OnlineMultiplayerServer.checkServerStatus(OnlineMultiplayerServer.kt:49)
	at com.unciv.UncivGame$create$1.invokeSuspend(UncivGame.kt:184)
	at com.unciv.UncivGame$create$1.invoke(UncivGame.kt)
	at com.unciv.UncivGame$create$1.invoke(UncivGame.kt)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fa429711760, pid=241541, tid=241596
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.19+7 (11.0.19+7) (build 11.0.19+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.19+7 (11.0.19+7, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libpthread.so.0+0xa760]  pthread_mutex_lock+0x0
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/bandura/Downloads/hs_err_pid241541.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted
```

**Comment by yairm210** [comment]
Ohhhhhhh I see the problem, it's the *external location* specifically, I somehow missed that

Yes, the JFileChooser on Desktop is also causing problems for me

**Comment by yairm210** [comment]
I'm really, really not attached to the current desktop for picker. I'm game for anything
