### ISSUE TITLE
Sudden Crash

### ISSUE THREAD

**Issue by A1y0sh4** [yairm210/Unciv#9583]
**Platform:** Desktop
**Version:** 4.6.18-patch1 (Build 876)
**Rulesets:** [Civ V - Gods & Kings, Community Civs, Thin Bubbly Borders, The Great Unciv Rework, Civ V - Vanilla, Only Mod Civilizations]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

OS: Windows 10
Java: Oracle Corporation 25.232-b09
	Max Memory: 910 MB

--------------------------------

**Message:**
```
java.lang.NullPointerException
	at com.unciv.logic.civilization.Civilization.getEquivalentBuilding(Civilization.kt:497)
	at com.unciv.logic.automation.civilization.ReligionAutomation$tryBuyAnyReligiousBuilding$buildingToBePurchased$1.invoke(ReligionAutomation.kt:93)
	at com.unciv.logic.automation.civilization.ReligionAutomation$tryBuyAnyReligiousBuilding$buildingToBePurchased$1.invoke(ReligionAutomation.kt:93)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at com.unciv.logic.automation.civilization.ReligionAutomation.tryBuyAnyReligiousBuilding(ReligionAutomation.kt:431)
	at com.unciv.logic.automation.civilization.ReligionAutomation.spendFaithOnReligion(ReligionAutomation.kt:73)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:68)
	at com.unciv.logic.civilization.managers.TurnManager.automateTurn(TurnManager.kt:321)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:336)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:574)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```
**Save Mods:**
```
[Community Civs, Thin Bubbly Borders, The Great Unciv Rework, Only Mod Civilizations]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

</details>
[Autosave.zip](https://github.com/yairm210/Unciv/files/11736998/Autosave.zip)

**Comment by A1y0sh4** [comment]
Ok, thank you very much :)

**Comment by A1y0sh4** [comment]
> Can anyone confirm that The Great Unciv Rework also crashes Unciv when that Nobel Foundation is built?

No, it doesn't crash.
Do you need any additional file of information?

**Comment by A1y0sh4** [comment]
Ok, thank you very much
