### ISSUE TITLE
Crash when opening the Nation picker

### ISSUE THREAD

**Issue by Caballero-Arepa** [yairm210/Unciv#9584]
<details><summary>Details</summary>
<p>

**Platform:** Desktop
**Version:** 4.7.0-patch1 (Build 879)
**Rulesets:** [Naciones pa deciv ES, The Undead, Victoria II Music, Warfare Expanded Unciv Bucketeer, capture GP, RekMOD, The raiders, Brave New World, Tech Stopper _WW1_, Medieval Civilizations, Bamboo Deciv Expans, Civilization 6 Mod, Community Maps, DeCiv Redux, 3rd and 4th Unique Component, Thin Bubbly Borders, Barbarian xp farm, Uncivilized Enhancer, DeityPlus Difficulty, Tech Stopper _Renaissance _, Latin American_Civs, Tech Stopper  _Medieval_, Warfare Expanded Lite, Community Civs, Better ruins Lite, Only Mod Civilizations, Tech Stopper _Classical_, Tech Stopper _Industrial_, Difficulty_Sandbox, Honor Wonders, Civ V - Vanilla, Civ5Nations, Tech Stopper _WW2_, Civ style set by Bucketeer, Sheep Meta, Resource Recyclers, Civ6 Tileset, Alpha Frontier, CS Rework, Ancient Civilizations, Naciones pa Unciv ES, Civ V - Gods & Kings, Latam_Civs Beta, Closer Cities Distance of 1, Mapping Tools for Unciv, The Barbarians, Fantasia]
**Last Screen:** `com.unciv.ui.screens.newgamescreen.NewGameScreen`

--------------------------------

OS: Windows 10
Java: Oracle Corporation 25.232-b09
	Max Memory: 910 MB

--------------------------------

**Message:**
```
java.util.NoSuchElementException: Char sequence is empty.
	at kotlin.text.StringsKt___StringsKt.first(_Strings.kt:72)
	at com.unciv.ui.screens.newgamescreen.NationPickerPopup.updateNationListTable(NationPickerPopup.kt:233)
	at com.unciv.ui.screens.newgamescreen.NationPickerPopup.<init>(NationPickerPopup.kt:91)
	at com.unciv.ui.screens.newgamescreen.PlayerPickerTable.popupNationPicker(PlayerPickerTable.kt:310)
	at com.unciv.ui.screens.newgamescreen.PlayerPickerTable.access$popupNationPicker(PlayerPickerTable.kt:49)
	at com.unciv.ui.screens.newgamescreen.PlayerPickerTable$getPlayerTable$1.invoke(PlayerPickerTable.kt:205)
	at com.unciv.ui.screens.newgamescreen.PlayerPickerTable$getPlayerTable$1.invoke(PlayerPickerTable.kt:201)
	at com.unciv.ui.components.input.ClickExtensionsKt$onClick$1.invoke(ClickExtensions.kt:10)
	at com.unciv.ui.components.input.ClickExtensionsKt$onClick$1.invoke(ClickExtensions.kt:10)
	at com.unciv.ui.components.input.OnClickListener.clicked(OnClickListener.kt:34)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:78)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:78)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:78)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:70)
	at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:189)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:378)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:80)

```

</p>
</details>

**Comment by Caballero-Arepa** [comment]
It's happening only with the Community Civs mod selected.

The mod checker doesn't trow any errors, and I've tried different uniques but I don't know what is causing it.

**Comment by Caballero-Arepa** [comment]
I dont know if it has co-relation with #9583

**Comment by Caballero-Arepa** [comment]
> does one of yours have double blanks or trailing or leading, or the same in translated form?

No, I've deleted all changes made the last day and the problem persisted.

It has been confirmed that the problem relies on the version, as a guy in 4.6.9 doesn't experience the crash, while us at 4.7.0 do

**Comment by Caballero-Arepa** [comment]
Omg, that was it

**Comment by Caballero-Arepa** [comment]
Nah, don't worry, not a big deal

**Comment by yairm210** [comment]
I'm reopening, because the underlying issue is not solved
