### ISSUE TITLE
Crash when picking Nation

### ISSUE THREAD

**Issue by Alvin201777** [yairm210/Unciv#9603]
**Platform:** Android
**Version:** 4.7.0-patch1 (Build 879)
**Rulesets:** [Policy mod, Modern Civilizations, RekMOD, Brave New World, Modern Russia, Uncivilized Enhancer, Civ6 Icons, Latin American_Civs, Powerful GDR, Community Civs, Mitteleuropa and Balkans, Civ V - Vanilla, Sheep Meta, No Fog Of War, Resource Recyclers, Civ V Leader portraits, Civ6 mod, Better Pantheons Lite, philosophy mod, Civ6 Tileset, Civ Army Color Style Sheet, All units can be automated, Ancient Civilizations, Civ6 Stat Icons, Civ6 Nations for Unciv, Nusantara Civilizations, Civ V - Gods & Kings, Leaders Plus, The Great Unciv Rework, Closer Cities Distance of 1, VeryQuickSpeed, Community Civs New, Soviet Union, hack land]
**Last Screen:** `com.unciv.ui.screens.newgamescreen.NewGameScreen`

--------------------------------

Device Model: 23021RAA2Y
API Level: 33

--------------------------------

**Message:**
```
java.util.NoSuchElementException: Char sequence is empty.
	at kotlin.text.StringsKt___StringsKt.first(_Strings.kt:72)
	at com.unciv.ui.screens.newgamescreen.NationPickerPopup.updateNationListTable(NationPickerPopup.kt:233)
	at com.unciv.ui.screens.newgamescreen.NationPickerPopup.<init>(NationPickerPopup.kt:91)
	at com.unciv.ui.screens.newgamescreen.PlayerPickerTable.popupNationPicker(PlayerPickerTable.kt:310)
	at com.unciv.ui.screens.newgamescreen.PlayerPickerTable.access$popupNationPicker(PlayerPickerTable.kt:49)
	at com.unciv.ui.screens.newgamescreen.PlayerPickerTable$getPlayerTable$1.invoke(PlayerPickerTable.kt:205)
	at com.unciv.ui.screens.newgamescreen.PlayerPickerTable$getPlayerTable$1.invoke(PlayerPickerTable.kt:201)
	at com.unciv.ui.components.input.ClickExtensionsKt$onClick$1.invoke(ClickExtensions.kt:10)
	at com.unciv.ui.components.input.ClickExtensionsKt$onClick$1.invoke(ClickExtensions.kt:10)
	at com.unciv.ui.components.input.OnClickListener.clicked(OnClickListener.kt:34)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:78)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:78)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:78)
	at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:426)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:472)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1590)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)

```

**Comment by yairm210** [comment]
Copy of #9584
Leaving this open so others can see it

**Comment by Alvin201777** [comment]
> Copy of #9584 Leaving this open so others can see it

Still crash for me.
Latest version in playstore
