### ISSUE TITLE
Nukes seem to crash game

### ISSUE THREAD

**Issue by nirosh251** [yairm210/Unciv#9627]
**Platform:** Android

**Version:** 4.6.18-patch1 (Build 876)

**Rulesets:** [Policy mod, Warfare Expanded Unciv Bucketeer, RekMOD, capture GP, Brave New World, DeCiv Redux, Extra Buildings, wonders in different eras mod, CS Overhaul, Warfare Expanded Lite, Unciv WWII, Difficulty_Sandbox, Civ V - Vanilla, Resource Recyclers, philosophy mod, Never Obsolete Lite, MaOr BoWtS mod, Future Expansion, Snipers Unciv, Civ6 Stat Icons, Expanded Warfare, Civ V - Gods & Kings, Urban Area, Closer Cities Distance of 1, Extra Promotions, Outpost Mod]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: SM-G965W
API Level: 29

--------------------------------

**Message:**
```
java.lang.Exception: Can't reach this tile!
	at com.unciv.logic.map.mapunit.PathsToTilesWithinTurn.getPathToTile(UnitMovement.kt:919)
	at com.unciv.logic.map.mapunit.UnitMovement.moveToTile(UnitMovement.kt:527)
	at com.unciv.logic.map.mapunit.UnitMovement.moveToTile$default(UnitMovement.kt:496)
	at com.unciv.logic.automation.unit.SpecificUnitAutomation.tryRelocateToNearbyAttackableCities(SpecificUnitAutomation.kt:562)
	at com.unciv.logic.automation.unit.SpecificUnitAutomation.automateNukes(SpecificUnitAutomation.kt:545)
	at com.unciv.logic.automation.unit.UnitAutomation.automateUnitMoves(UnitAutomation.kt:180)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateUnits(NextTurnAutomation.kt:1002)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:87)
	at com.unciv.logic.civilization.managers.TurnManager.automateTurn(TurnManager.kt:321)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:336)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:574)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:8)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:4)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher.$r8$lambda$GFMOlD6QMgmLfgwAvPAW33Ob6HE(Unknown Source:0)
	at com.unciv.utils.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
**Save Mods:**
```
[Policy mod, Warfare Expanded Unciv Bucketeer, capture GP, Brave New World, Resource Recyclers, Extra Buildings, philosophy mod, Never Obsolete Lite, MaOr BoWtS mod, wonders in different eras mod, CS Overhaul, Warfare Expanded Lite, Snipers Unciv, Expanded Warfare, Civ V - Gods & Kings]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```


```
</details>

**Describe the bug**
Nukes seem to crash game. Game does not crash with nukes disabled

Example error report:

**To Reproduce**
Have the same mods, enable nukes then play as normal. 

```
</details>

**Expected behavior**
Normal gameplay

**Comment by yairm210** [comment]
Unworkable with no save, we can reopen if one it attached
