### ISSUE TITLE
Crash: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by marek22k** [yairm210/Unciv#9637]
**Platform:** Android
**Version:** 4.7.2 (Build 881)
**Rulesets:** [Policy mod, Great Farmer, The Demon World, Extra Buildings, Extra Units, Barbarian xp farm, The North Pole, Warfare Expanded Lite, Better Units and Natural Wonders, Civ V - Vanilla, Resource Recyclers, AbsoluteUnits, Modern Joke Religions, Better Pantheons Lite, Extra Wonders, Barbarians but Better, CS Rework, Better Pantheons, Civ V - Gods & Kings, CS Unique Components , 5Hex Tileset, Logicians, The Barbarians, Extra Promotions, Better Workers, Better ruins, Ruins Extended Classic Edition]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: FP4
API Level: 33

--------------------------------

**Message:**
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at kotlin.sequences.SequenceBuilderIterator.next(SequenceBuilder.kt:138)
	at com.unciv.logic.city.managers.CityInfoConquestFunctions.liberateCity(CityInfoConquestFunctions.kt:228)
	at com.unciv.logic.city.City.liberateCity(City.kt:494)
	at com.unciv.ui.screens.worldscreen.AlertPopup$addLiberateOption$1.invoke(AlertPopup.kt:437)
	at com.unciv.ui.screens.worldscreen.AlertPopup$addLiberateOption$1.invoke(AlertPopup.kt:436)
	at com.unciv.ui.components.input.ActivationActionMap.activate(ActivationActionMap.kt:55)
	at com.unciv.ui.components.input.ActorAttachments.activate(ActorAttachments.kt:40)
	at com.unciv.ui.components.input.ActivationExtensionsKt.activate(ActivationExtensions.kt:17)
	at com.unciv.ui.components.input.ActivationListener.tap(ActivationListener.kt:15)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener$1.tap(ActorGestureListener.java:52)
	at com.badlogic.gdx.input.GestureDetector.touchUp(GestureDetector.java:209)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener.handle(ActorGestureListener.java:125)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:87)
	at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:426)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:472)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1573)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)

```
**Save Mods:**
```
[CS Rework, Great Farmer, Resource Recyclers, Civ V - Gods & Kings, Modern Joke Religions, CS Unique Components , Extra Buildings, 5Hex Tileset, Extra Wonders, Extra Promotions, Extra Units, Logicians]
```

**Save Data:** https://gist.github.com/marek22k/4db37c08cdd324dee9256fb394aee184

**Comment by yairm210** [comment]
I always use .toList() to avoid concurrent modification, I don't think we need a special helper beyond that
