### ISSUE TITLE
Crash: java.lang.NullPointerException

### ISSUE THREAD

**Issue by marek22k** [yairm210/Unciv#9638]
**Platform:** Android
**Version:** 4.7.2 (Build 881)
**Rulesets:** [Policy mod, Great Farmer, The Demon World, Extra Buildings, Extra Units, Barbarian xp farm, The North Pole, Warfare Expanded Lite, Better Units and Natural Wonders, Civ V - Vanilla, Resource Recyclers, AbsoluteUnits, Modern Joke Religions, Better Pantheons Lite, Extra Wonders, Barbarians but Better, CS Rework, Better Pantheons, Civ V - Gods & Kings, CS Unique Components , 5Hex Tileset, Logicians, The Barbarians, Extra Promotions, Better Workers, Better ruins, Ruins Extended Classic Edition]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: FP4
API Level: 33

--------------------------------

**Message:**
```
java.lang.NullPointerException
	at com.unciv.logic.city.CityStats.getStatsFromTradeRoute(CityStats.kt:103)
	at com.unciv.logic.city.CityStats.updateBaseStatList(CityStats.kt:448)
	at com.unciv.logic.city.CityStats.update(CityStats.kt:487)
	at com.unciv.logic.city.CityStats.update$default(CityStats.kt:479)
	at com.unciv.logic.city.CityConstructions.updateUniques(CityConstructions.kt:499)
	at com.unciv.logic.city.CityConstructions.updateUniques$default(CityConstructions.kt:495)
	at com.unciv.logic.city.CityConstructions.removeBuilding(CityConstructions.kt:492)
	at com.unciv.logic.city.managers.CityInfoConquestFunctions.removeBuildingsOnMoveToCiv(CityInfoConquestFunctions.kt:76)
	at com.unciv.logic.city.managers.CityInfoConquestFunctions.moveToCiv(CityInfoConquestFunctions.kt:293)
	at com.unciv.logic.city.managers.CityInfoConquestFunctions.conquerCity(CityInfoConquestFunctions.kt:109)
	at com.unciv.logic.city.managers.CityInfoConquestFunctions.liberateCity(CityInfoConquestFunctions.kt:206)
	at com.unciv.logic.city.City.liberateCity(City.kt:494)
	at com.unciv.ui.screens.worldscreen.AlertPopup$addLiberateOption$1.invoke(AlertPopup.kt:437)
	at com.unciv.ui.screens.worldscreen.AlertPopup$addLiberateOption$1.invoke(AlertPopup.kt:436)
	at com.unciv.ui.components.input.ActivationActionMap.activate(ActivationActionMap.kt:55)
	at com.unciv.ui.components.input.ActorAttachments.activate(ActorAttachments.kt:40)
	at com.unciv.ui.components.input.ActivationExtensionsKt.activate(ActivationExtensions.kt:17)
	at com.unciv.ui.components.input.ActivationListener.tap(ActivationListener.kt:15)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener$1.tap(ActorGestureListener.java:52)
	at com.badlogic.gdx.input.GestureDetector.touchUp(GestureDetector.java:209)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener.handle(ActorGestureListener.java:125)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:87)
	at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:426)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:472)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1573)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)

```
**Save Mods:**
```
[CS Rework, Great Farmer, Resource Recyclers, Civ V - Gods & Kings, Modern Joke Religions, CS Unique Components , Extra Buildings, 5Hex Tileset, Extra Wonders, Extra Promotions, Extra Units, Logicians]
```

**Save Data:** https://gist.github.com/marek22k/ed320f41e67ae2103b782144d8c98aef

**Comment by marek22k** [comment]
The following scenario: I bought a city from another civ, which used to be a state city. I then did not keep the city, but liberated it. Then https://github.com/yairm210/Unciv/issues/9637 appeared. After that I restarted the game and tried again. After that this message appeared. I tried a few more times after that and more or less alternately this and the other message appeared.

**Comment by yairm210** [comment]
I solved this specific error, but there's a much larger error here - somehow, if you decide to keep the city, Kuala Lumpur is considered *the owner of the city* but it's not considered *their capital*

I really need more context on how you created this situation in the first place.
You traded Austria to get Kuala Lumpur city?
And then decided to liberate?
We need the save game of the previous turn then, because the problem is caused when Austria transferred the city to you, not when you actually liberate it

(The 'recieved X gold for capturing' messages in liberateCity need to be contingent on actual capture, which is not necessarily the case now that we allow liberating traded cities)

**Comment by marek22k** [comment]
> You traded Austria to get Kuala Lumpur city?
> And then decided to liberate?

That's exactly how it was. I never conquered the state city, apparently Austria did. I then wanted to liberate the state city without war, so I traded. I unfortunately already started a new game, which means I don't have the previous move, only the one 30 turns ago.

When I try it from this move, no error appears either.
[Logiker (581 Runden).json.txt](https://github.com/yairm210/Unciv/files/11845938/Logiker.581.Runden.json.txt) (.txt as GitHub does not allow .json)

**Comment by yairm210** [comment]
Loading from that save, and trading the Huns for the city and keeping it, no errors occur.
So I'm willing to consider this as solved for the future

**Comment by yairm210** [comment]
I'm like 80% certain this was caused by the "double capture" bug that was fixed a few versions ago
