### ISSUE TITLE
Immediate crash upon start new game

### ISSUE THREAD

**Issue by hackedpassword** [yairm210/Unciv#9653]
Load up unciv, first I can't continue my old game, will post image. So I hit start new game, immediate crash as stated below. 

**Platform:** Android
**Version:** 4.7.3 (Build 882)
**Rulesets:** [RekMOD, Ruins Extended, The Demon World, Thin Bubbly Borders, Nextgen Maps, NextgenMaps Labs, tGUR 1.9 experiment, Antiyoy maps, Better ruins Lite, LesserSpaceNations, Civ V - Vanilla, No Fog Of War, Resource Recyclers, Civ V Leader portraits, Alpha Frontier, Raze anything, All units can be automated, Civ V - Gods & Kings, Yet Another Resource Mod, The Great Unciv Rework, tGUR 2.0 experiment, Closer Cities Distance of 1, DeCiv in Alpha Frontier, Better Workers, Better ruins, Mapping Tools for Unciv]
**Last Screen:** `com.unciv.ui.screens.mainmenuscreen.MainMenuScreen`

--------------------------------

Device Model: SM-G973U1
API Level: 31

--------------------------------

**Message:**
```
com.unciv.logic.UncivShowableException: Building 'Revealer' is buildable and therefore must either have an explicit cost or reference an existing tech.
	at com.unciv.models.ruleset.Ruleset.updateBuildingCosts(Ruleset.kt:461)
	at com.unciv.models.ruleset.RulesetCache.getComplexRuleset(Ruleset.kt:630)
	at com.unciv.models.ruleset.RulesetCache.getComplexRuleset(Ruleset.kt:610)
	at com.unciv.models.ruleset.RulesetCache.getComplexRuleset(Ruleset.kt:592)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.<init>(NewGameScreen.kt:54)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.<init>(NewGameScreen.kt:49)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen$newGameButton$1.invoke(MainMenuScreen.kt:154)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen$newGameButton$1.invoke(MainMenuScreen.kt:153)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen$getMenuButton$1.invoke(MainMenuScreen.kt:103)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen$getMenuButton$1.invoke(MainMenuScreen.kt:101)
	at com.unciv.ui.components.input.ActivationActionMap.activate(ActivationActionMap.kt:55)
	at com.unciv.ui.components.input.ActorAttachments.activate(ActorAttachments.kt:40)
	at com.unciv.ui.components.input.ActivationExtensionsKt.activate(ActivationExtensions.kt:17)
	at com.unciv.ui.components.input.ActivationListener.tap(ActivationListener.kt:15)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener$1.tap(ActorGestureListener.java:52)
	at com.badlogic.gdx.input.GestureDetector.touchUp(GestureDetector.java:209)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener.handle(ActorGestureListener.java:125)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:87)
	at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:426)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:472)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1593)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1287)

```

**Comment by hackedpassword** [comment]
![Screenshot_20230623-191242_Unciv.jpg](https://github.com/yairm210/Unciv/assets/119975434/2e5a17df-2bc7-423c-9ba5-b92d73ea734c)

**Comment by SeventhM** [comment]
Huh, that's interesting

> surprised the severity for Buildings

It was always higher than a warning. Perhaps, it should be lowered back to a warning as the effects don't seem to break anything. What looks to have happened is more mods than I thought used -1 to get around what would've previously been not allowed

**Comment by hackedpassword** [comment]
> when a certain commit wasn't in

Is it possible to code for both scenarios? i.e. pseudocode: if var==0 {old way} elif var==-1 {this way} else {normal way}

**Comment by hackedpassword** [comment]
Gave gpt4 the problem, fed it the related commits. It had ideas but nothing conclusive. From those ideas, reviewing the commits, and not knowing cause-and-effect elsewhere, I see one potential fix:

```kotlin
if ((instanceX.varY <= 0)
```

Files where logic is changed from looking for 0 (then) to -1 (now), allow for zero or less than zero values.

No? Maybe?

**Comment by hackedpassword** [comment]
> gpt4? Is that an Unciv player on discord?

Yes, that guy. Not 100% reliable but great go-to for ideas. When not used as a McDonalds drive through, can be quite insightful.

Sounds sort of like back when I was using a gtk env, as a user not a dev. Funky stuff all the time causing headaches.

**Comment by SeventhM** [comment]
> gpt4? Is that an Unciv player on discord?

[Wikipedia link on gpt3](https://en.wikipedia.org/wiki/GPT-3)

> Files where logic is changed from looking for 0 (then) to -1 (now), allow for zero or less than zero values.

Fixing mod errors on our end is not in the question unless there is a good reason to do so, namely situations where it's clear what the intent of the mod. Situations like this could be a mod setting to -1 when it should've been 0 or it could be a mod forgetting to set a building to `unbuildable`. These things should not be assumed on our end. The actual solution here (short of asking mod makers to update mods) would likely be to drop this from being considered an error to just being a warning

**Comment by SeventhM** [comment]
> As I said, it's not RulesetValidator (Line 64) behind that, but Ruleset.updateBuildingCosts (Line 461)

While this is true, it's not the full story. RulesetValidator still claims it's an error rather than a warning (tested by removing the throw and checking it the column is null). I imagine when this was initial set up, it was set to throw anyways to keep consistency with what was perceived to be an error condition (a building being buildable without a cost). Even if you fixed the crash, it's still worthwhile to downgrade it from an error to a warning as there's apparently no actual crash worth error state. It's also inconsistent with other areas of the code

Did you know: the default cost of a building for a technology is 0. Before, you could also dance around the 0 check by creating a column that was inaccessible normally and not setting the cost to anything. I actually ran into this by accident before, and it doesn't even warn for this

**Comment by SeventhM** [comment]
Decided to investigate further. Looks like we need better validation of tech columns as well
![Untitled](https://github.com/yairm210/Unciv/assets/127357473/c538a22e-b09a-41fe-80bc-5fd873f89704)
No crash, no mod warning, nothing. I guess I know what to work on next

**Comment by hackedpassword** [comment]
> Ah, [_that_ GPT](https://github.com/yairm210/Unciv/blob/master/android/assets/jsons/Civ%20V%20-%20Gods%20%26%20Kings/Units.json#L1574), I should have known. Have enough Uhranium ready then.

LOL @SomeTroglodyte
