### ISSUE TITLE
Bug on Start New Game 

### ISSUE THREAD

**Issue by omega-particle** [yairm210/Unciv#9656]
**Platform**
Android
Pixel 6a

**Version**
Where you got the game and the exact version number.

**Describe the bug**
**Platform:** Android
**Version:** 4.7.3 (Build 882)
**Rulesets:** [More Fauna And Flora, Civ V - Vanilla, Brave New World, Medieval Civilizations, AbsoluteUnits, Community Maps, 3rd and 4th Unique Component, Extra Buildings, philosophy mod, Barbarian xp farm, Future Expansion, Canada, Ukraine Mod, Latin American_Civs, Ancient Civilizations, Civ V - Gods & Kings, Mitteleuropa and Balkans, More Natural Wonders, 5Hex Tileset, Greece plus The Middle East, The Barbarians]
**Last Screen:** `com.unciv.ui.screens.mainmenuscreen.MainMenuScreen`

--------------------------------

Device Model: Pixel 6a
API Level: 33

--------------------------------

**Message:**
```
com.unciv.logic.UncivShowableException: Building 'Free Terracotta' is buildable and therefore must either have an explicit cost or reference an existing tech.
	at com.unciv.models.ruleset.Ruleset.updateBuildingCosts(Ruleset.kt:461)
	at com.unciv.models.ruleset.RulesetCache.getComplexRuleset(Ruleset.kt:630)
	at com.unciv.models.ruleset.RulesetCache.getComplexRuleset(Ruleset.kt:610)
	at com.unciv.models.ruleset.RulesetCache.getComplexRuleset(Ruleset.kt:592)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.<init>(NewGameScreen.kt:54)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.<init>(NewGameScreen.kt:49)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen$newGameButton$1.invoke(MainMenuScreen.kt:154)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen$newGameButton$1.invoke(MainMenuScreen.kt:153)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen$getMenuButton$1.invoke(MainMenuScreen.kt:103)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen$getMenuButton$1.invoke(MainMenuScreen.kt:101)
	at com.unciv.ui.components.input.ActivationActionMap.activate(ActivationActionMap.kt:55)
	at com.unciv.ui.components.input.ActorAttachments.activate(ActorAttachments.kt:40)
	at com.unciv.ui.components.input.ActivationExtensionsKt.activate(ActivationExtensions.kt:17)
	at com.unciv.ui.components.input.ActivationListener.tap(ActivationListener.kt:15)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener$1.tap(ActorGestureListener.java:52)
	at com.badlogic.gdx.input.GestureDetector.touchUp(GestureDetector.java:209)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener.handle(ActorGestureListener.java:125)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:87)
	at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:426)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:472)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1573)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)

```

**To Reproduce**
1. Click on Start New Game

**Comment by hackedpassword** [comment]
Sounds like #9653
