### ISSUE TITLE
Creating Map Crash

### ISSUE THREAD

**Issue by Schoenios** [yairm210/Unciv#9658]
**Platform:** Android
**Version:** 4.7.2 (Build 881)
**Rulesets:** [Civ V - Gods & Kings, Medieval Civilizations, Community Maps, More Luxuries, Civ V - Vanilla]
**Last Screen:** `com.unciv.ui.screens.mapeditorscreen.MapEditorScreen`

--------------------------------

Device Model: SM-A105FN
API Level: 30

--------------------------------

**Message:**
```
java.lang.IllegalStateException: TileMap.setTransients called on existing tileMatrix of different size
	at com.unciv.logic.map.TileMap.setTransients(TileMap.kt:437)
	at com.unciv.ui.screens.mapeditorscreen.MapEditorScreen.newMapHolder(MapEditorScreen.kt:177)
	at com.unciv.ui.screens.mapeditorscreen.MapEditorScreen.loadMap(MapEditorScreen.kt:218)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorGenerateTab.generate$freshMapCompleted(MapEditorGenerateTab.kt:104)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorGenerateTab.access$generate$freshMapCompleted(MapEditorGenerateTab.kt:36)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorGenerateTab$generate$2$1.invokeSuspend(MapEditorGenerateTab.kt:129)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorGenerateTab$generate$2$1.invoke(Unknown Source:8)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorGenerateTab$generate$2$1.invoke(Unknown Source:4)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher.$r8$lambda$GFMOlD6QMgmLfgwAvPAW33Ob6HE(Unknown Source:0)
	at com.unciv.utils.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:467)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1591)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)

```

**Comment by Schoenios** [comment]
First I clicked on "Generate", then on "To new map", first on "Create on
map". After that I got the error message.


Sincerely L. Schönwälder

SomeTroglodyte ***@***.***> schrieb am So., 25. Juni 2023,
02:16:

**Comment by Caballero-Arepa** [comment]
I'm having this too

Steps I took: Create new map - Rectangular - Empty - Custom Size (any, in my case 57x88) - Create - Crash

<details><summary>Details</summary>
<p>

**Platform:** Desktop
**Version:** 4.7.5-patch1 (Build 885)
**Rulesets:** [New Building Icons, The Undead, RekMOD, Brave New World, Iron and Blood, Historica, Medieval Civilizations, DeCiv Redux, ph bonifacio unciv, Extra Buildings, Leader Mission, New minimal, Star Wars for Alpha Frontier, Community Civs, More Luxuries, Difficulty_Sandbox, Civ V - Vanilla, FantasyHex UI, Civ6 mod, Fire Emblem Civilizations, Epic of Fantasy, Alpha Frontier, Unciv IV mod, Ukraine Mod, Ancient Civilizations, Civ V - Gods & Kings, Latam_Civs Beta, Maid Empire, The Great Unciv Rework, Fantasia]
**Last Screen:** `com.unciv.ui.screens.mapeditorscreen.MapEditorScreen`

--------------------------------

OS: Windows 10
Java: Oracle Corporation 25.232-b09
	Max Memory: 910 MB


--------------------------------


**Message:**
```
java.lang.IllegalStateException: TileMap.setTransients called on existing tileMatrix of different size
	at com.unciv.logic.map.TileMap.setTransients(TileMap.kt:437)
	at com.unciv.ui.screens.mapeditorscreen.MapEditorScreen.newMapHolder(MapEditorScreen.kt:177)
	at com.unciv.ui.screens.mapeditorscreen.MapEditorScreen.loadMap(MapEditorScreen.kt:218)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorGenerateTab.generate$freshMapCompleted(MapEditorGenerateTab.kt:104)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorGenerateTab.access$generate$freshMapCompleted(MapEditorGenerateTab.kt:36)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorGenerateTab$generate$2$1.invokeSuspend(MapEditorGenerateTab.kt:129)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorGenerateTab$generate$2$1.invoke(MapEditorGenerateTab.kt)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorGenerateTab$generate$2$1.invoke(MapEditorGenerateTab.kt)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:208)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:80)

```

</p>
</details>

**Comment by Caballero-Arepa** [comment]
This was fixed recently, no?

**Comment by SeventhM** [comment]
> This was fixed recently, no?

If you're saying this was fixed, then I'm closing unless someone says otherwise
