### ISSUE TITLE
NPE when exploring with settler

### ISSUE THREAD

**Issue by glelouet** [yairm210/Unciv#9683]
**Platform:** Desktop
**Version:** 4.7.4 (Build 883)
**Rulesets:** [Capital Domination, Civ V - Vanilla, AbsoluteUnitsXL, Expanded Warfare Syntaxed, Brave New World, 3rd and 4th Unique Component, Extra Buildings, Barbarian xp farm, Warfare Expanded Lite, Civ V - Gods & Kings, Better ruins Lite, 5Hex Tileset, The Barbarians]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

OS: Linux (amd64, 5.19.0-47-generic)
	Freedesktop.org SDK 22.08 (Flatpak runtime)
Java: Flathub 21.9
	Max Memory: 20080 MB

--------------------------------

**Message:**
```
java.lang.NullPointerException
	at com.unciv.logic.map.tile.TileDescription.toMarkup(TileDescription.kt:73)
	at com.unciv.ui.screens.worldscreen.bottombar.TileInfoTable.updateTileTable$core(TileInfoTable.kt:34)
	at com.unciv.ui.screens.worldscreen.WorldScreen.update(WorldScreen.kt:360)
	at com.unciv.ui.screens.worldscreen.WorldScreen.render(WorldScreen.kt:721)
	at com.badlogic.gdx.Game.render(Game.java:48)
	at com.unciv.UncivGame.access$render$s2211858(UncivGame.kt:125)
	at com.unciv.UncivGame$wrappedCrashHandlingRender$1.invoke(UncivGame.kt:145)
	at com.unciv.UncivGame$wrappedCrashHandlingRender$1.invoke(UncivGame.kt:145)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.UncivGame.render(UncivGame.kt:458)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:80)

```
**Save Mods:**
```
[Capital Domination, Expanded Warfare Syntaxed, Brave New World, Civ V - Gods & Kings, 3rd and 4th Unique Component, Extra Buildings, Barbarian xp farm]
```

**Comment by glelouet** [comment]
sorry can't have, I made other game after this one.
Seems it was here

https://github.com/yairm210/Unciv/blob/a6e4b72cf48f67afcef546fea40b4ec051d8ef5f/core/src/com/unciv/logic/map/tile/TileDescription.kt#L73

But since it's a military unit (settlers are not) , then my guess was wrong.

**Comment by glelouet** [comment]
closed as can't reproduce.
