### ISSUE TITLE
UncivServer: Fail to create multiplayer game if MultiplayerFiles folder is not present

### ISSUE THREAD

**Issue by nrader95** [yairm210/Unciv#9697]
**Platform**
Linux x64

**Version**
4.7.4

**Describe the bug**
When creating new game and selecting it as multiplayer one and adding another human player, it failed for me.
The server log printed IO exception regarding contents in MultiplayerFiles folder. A folder i didnt have at all.
Creating the folder manually solved the problem. So i think the problem is that game (or game server, i'm not sure which one of them) is not checking if path to the multiplayer files exists before working with it.

**Comment by nrader95** [comment]
> Well, I would not be sure which either. So, tell us more - what server, or more importantly - "Creating the folder manually" - local or serverside?

Right, sorry. It was in console output of the server. And local or server-side is the same for my as i run both game and server on same machine, and having both game and server .jar files in same folder, too.

Heres the error:
`
[ERROR] Error while creating game | java.lang.Exception: Server returned HTTP response code: 500 for URL: http://localhost:8080/files/fd89aad5-ffa4-44ad-b49b-9833271e67ec
	at com.unciv.logic.multiplayer.storage.UncivServerFileStorage$saveFileData$1.invoke(UncivServerFileStorage.kt:20)
	at com.unciv.logic.multiplayer.storage.UncivServerFileStorage$saveFileData$1.invoke(UncivServerFileStorage.kt:14)
	at com.unciv.logic.multiplayer.storage.SimpleHttp.sendRequest(SimpleHttp.kt:69)
	at com.unciv.logic.multiplayer.storage.UncivServerFileStorage.saveFileData(UncivServerFileStorage.kt:14)
	at com.unciv.logic.multiplayer.storage.OnlineMultiplayerServer.tryUploadGame(OnlineMultiplayerServer.kt:105)
	at com.unciv.logic.multiplayer.OnlineMultiplayer.createGame(OnlineMultiplayer.kt:130)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invokeSuspend(NewGameScreen.kt:327)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invoke(NewGameScreen.kt)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invoke(NewGameScreen.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.startNewGame(NewGameScreen.kt:298)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.access$startNewGame(NewGameScreen.kt:53)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$7.invokeSuspend(NewGameScreen.kt:232)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$7.invoke(NewGameScreen.kt)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$7.invoke(NewGameScreen.kt)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
`

The weirs part is, if i specify server address in the game as http://localhost:8080 it worked 
But, if i change that to raw ip and port combo, like http://127.0.0.1:8080, it fails. (error above was for IP:Port combo despite mentioning the localhost alias)
Creating the MultiplayerFiles folder manually while having server address specified as http://IP:Port works too.

**Comment by nrader95** [comment]
Hmm, putting them separately seem to work too, apparently. Weird.

**Comment by nrader95** [comment]
Well i just tried putting them separately, and the results were the same. So its not an issue related to them sharing the same folder.

**Comment by nrader95** [comment]
I did move the .jar to different folder, opened terminal there to run it. So yeah.
So server seems to be simply not checking if the MultiplayerFiles exists for some cases, and fails because of that.
