### ISSUE TITLE
Crash on removing a nation from the random nation pool

### ISSUE THREAD

**Issue by AlecXanderLynn** [yairm210/Unciv#9711]
**Platform**
64 bit Fedora Linux, 6.2.13-200

**Version**
4.7.5-patch1

**Describe the bug**
Unciv crashes on the new game screen when the player attempts to remove a civilization from the random list of civilizations to pick from.

**To Reproduce**
1. Start a new game
2. Open advanced settings
3. Scroll down to and click "set available nations for random pool"
4. Click the "select nations" button
5. Click any amount of the banned nations to add them to the available nations
6. Click any available nation to add them to the banned nations list
7. Crash

**Expected behavior**
The available nation clicked should have been moved to the banned nation list without crashing.

**Comment by random271** [comment]
This is the crash log:

<details>
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at com.unciv.ui.components.input.ActivationActionMap.activate(ActivationActionMap.kt:54)
	at com.unciv.ui.components.input.ActorAttachments.activate(ActorAttachments.kt:40)
	at com.unciv.ui.components.input.ActivationExtensionsKt.activate(ActivationExtensions.kt:17)
	at com.unciv.ui.components.input.ActivationListener.tap(ActivationListener.kt:15)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener$1.tap(ActorGestureListener.java:52)
	at com.badlogic.gdx.input.GestureDetector.touchUp(GestureDetector.java:209)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener.handle(ActorGestureListener.java:125)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:87)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:70)
	at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:189)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:378)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:80)
</details>

Issue comes from `for (action in actions)`, after removing nation from 'available nations', another action is added and kotlin throws ConcurrentModificationException 

I don't know how that action is generated but the issue seems to in `update()` in `GameOptionsTable.kt`
```kotlin
updateNationListTable(availableNationsListTable, availableNations) {
      nation -> { addNationToPool(nation) }
}
updateNationListTable(selectedNationsListTable, selectedNations) {
       nation -> { removeNationFromPool(nation) }
}
```
Calling it this way crashes when removing, if I switch the order (first update with selectedNations) I get a crash when adding (same exception), if I make two separate functions for each case I don't get a crash anymore.
