### ISSUE TITLE
sudden crash at turn 139.

### ISSUE THREAD

**Issue by gerelio** [yairm210/Unciv#9740]
**Platform**
android

**Version**
play store/v4.7.6patch2

an unrecoverable error happens during the loading time after pressing next turn from turn 139 to 140, the game was running fine before. error report(copied from the lasterror.txt): java.lang.NullPointerException at 

com.unciv.logic.civilization.Civilization.getEquivalentBuilding(Civilization.kt:494) at 

com.unciv.logic.automation.civilization.ReligionAutomation$tryBuyAnyReligiousBuilding$buildingToBePurchased$1.invoke(ReligionAutomation.kt:93)
 at com.unciv.logic.automation.civilization.ReligionAutomation$tryBuyAnyReligiousBuilding$buildingToBePurchased$1.invoke(ReligionAutomation.kt:93)
 at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210) at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210) at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170) at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194) at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169) at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194) at com.unciv.logic.automation.civilization.ReligionAutomation.tryBuyAnyReligiousBuilding(ReligionAutomation.kt:433) at com.unciv.logic.automation.civilization.ReligionAutomation.spendFaithOnReligion(ReligionAutomation.kt:35) 
at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:68) 
at com.unciv.logic.civilization.managers.TurnManager.automateTurn(TurnManager.kt:321) at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:338) at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:598) at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt) at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt) at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173) at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173) at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17) at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33) at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33) at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173) at com.unciv.utils.CrashHandlingDispatcher.$r8$lambda$GFMOlD6QMgmLfgwAvPAW33Ob6HE(Concurrency.kt) at com.unciv.utils.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(D8$$SyntheticClass) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) at java.lang.Thread.run(Thread.java:818)

addons used in this save: REKmod, absoluteunitsXL, philosophy mod, policy mod, extra promotions, extra buildings, community maps, more luxuries, civ v leader portraits, expanded warfare and religionplus.

device/infinix-x600-lte
api level:23

**Comment by yairm210** [comment]
Please attach a save file

**Comment by gerelio** [comment]
https://drive.google.com/file/d/1taZ1m2bLWlDKiD_lUjlT9yk-KkZvsx3p/view?usp=drivesdk

**Comment by yairm210** [comment]
One of the mods is incorrectly defined, as you can see from this error when trying to start a new game with the same parameters:
![image](https://github.com/yairm210/Unciv/assets/8366208/c59149e2-6b71-4365-8a63-8a37f645c0d6)

I'll try to pinpoint this down to the specific mod
In any case we should solve the crash ;)

**Comment by yairm210** [comment]
![image](https://github.com/yairm210/Unciv/assets/8366208/b0c1bba6-0bc9-486f-b133-2c13c078fac4)

ReligionPlus is meant to go with G&K not Rekmod

The game should have warned you when creating the game to start with - it did for me
In any case it shouldn't crash though
