### ISSUE TITLE
Out of memory when creating new game with Alpha Frontier

### ISSUE THREAD

**Issue by Lwaht** [yairm210/Unciv#9745]
**Platform:** Android
**Version:** 4.7.6-patch2 (Build 888)
**Rulesets:** [Policy mod, Pix5 Tileset, Civ V - Vanilla, AbsoluteUnitsXL, Extra Buildings, Civ Army Color Style Sheet, Alpha Frontier, Future Expansion, CS Overhaul, Civ6 Stat Icons, Civ V - Gods & Kings, Soviet Union, Fantasia, Better Units and Natural Wonders]
**Last Screen:** `com.unciv.ui.screens.newgamescreen.NewGameScreen`

--------------------------------

Device Model: SM-A146P
API Level: 33

--------------------------------

**Message:**
```
java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 5131372 free bytes and 5011KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at kotlin.collections.CollectionsKt__CollectionsKt.arrayListOf(Collections.kt:114)
	at com.unciv.models.ruleset.unique.UniqueMap.addUnique(Unique.kt:367)
	at com.unciv.models.ruleset.unique.UniqueMap.addUniques(Unique.kt:372)
	at com.unciv.logic.map.tile.Tile.setTerrainFeatures(Tile.kt:835)
	at com.unciv.logic.map.tile.Tile.setTerrainTransients(Tile.kt:748)
	at com.unciv.logic.map.TileMap.setTransients(TileMap.kt:453)
	at com.unciv.logic.map.TileMap.setTransients$default(TileMap.kt:416)
	at com.unciv.logic.map.TileMap.<init>(TileMap.kt:105)
	at com.unciv.logic.map.mapgenerator.MapGenerator.generateMap(MapGenerator.kt:99)
	at com.unciv.logic.GameStarter$startNewGame$3.invoke(GameStarter.kt:72)
	at com.unciv.logic.GameStarter$startNewGame$3.invoke(GameStarter.kt:68)
	at com.unciv.logic.GameStarter.runAndMeasure(GameStarter.kt:152)
	at com.unciv.logic.GameStarter.startNewGame(GameStarter.kt:68)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invokeSuspend(NewGameScreen.kt:307)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invoke(Unknown Source:8)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.startNewGame(NewGameScreen.kt:298)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.access$startNewGame(NewGameScreen.kt:53)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$7.invokeSuspend(NewGameScreen.kt:232)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$7.invoke(Unknown Source:8)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$7.invoke(Unknown Source:4)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher.$r8$lambda$GFMOlD6QMgmLfgwAvPAW33Ob6HE(Unknown Source:0)
	at com.unciv.utils.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by Lwaht** [comment]
Ok, i'll try it. Thanks for fast respond

Pada tanggal Rab, 5 Jul 2023 2.01 PM, SomeTroglodyte <
***@***.***> menulis:

**Comment by Lwaht** [comment]
I choose medium, but in G&K ruleset it worked, sometimes in Vanilla also
not worked
Sorry i can send the screen record

Pada tanggal Rab, 5 Jul 2023 4.17 PM, SomeTroglodyte <
***@***.***> menulis:

**Comment by Lwaht** [comment]
Thanks for the explanation.

Pada tanggal Rab, 5 Jul 2023 5.03 PM, SomeTroglodyte <
***@***.***> menulis:

**Comment by Lwaht** [comment]
Uploading lv_0_20230705164305.mp4…

**Comment by Lwaht** [comment]
https://github.com/yairm210/Unciv/assets/128390812/99b9f64a-8b43-4b34-a4c8-fdd98a88bd97

**Comment by yairm210** [comment]
I've been thinking of a way to minimize memory consumption for this exact callstack for a while now

So I'll try to play around with it tomorrow to see if I can get results :D

**Comment by Lwaht** [comment]
No, i don't know anything about coding

**Comment by Lwaht** [comment]
https://github.com/yairm210/Unciv/assets/128390812/d2ca75ad-2bc7-419b-a9fc-c9ef4a3fa60e

It also happend on Fantasia ruleset
I don't know if another ruleset like, so i think you should check it out
