### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Garynych83** [yairm210/Unciv#9766]
**Platform:** Android
**Version:** 4.7.6-patch1 (Build 887)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: 22071212AG
API Level: 33

--------------------------------

**Message:**
```
java.lang.NullPointerException
	at com.unciv.logic.city.CityStats.getStatsFromTradeRoute(CityStats.kt:103)
	at com.unciv.logic.city.CityStats.updateBaseStatList(CityStats.kt:460)
	at com.unciv.logic.city.CityStats.update(CityStats.kt:499)
	at com.unciv.logic.city.CityStats.update$default(CityStats.kt:491)
	at com.unciv.logic.city.CityConstructions.updateUniques(CityConstructions.kt:499)
	at com.unciv.logic.city.CityConstructions.updateUniques$default(CityConstructions.kt:495)
	at com.unciv.logic.city.CityConstructions.removeBuilding(CityConstructions.kt:492)
	at com.unciv.logic.civilization.Civilization.moveCapitalTo(Civilization.kt:813)
	at com.unciv.logic.civilization.Civilization.moveCapitalToNextLargest(Civilization.kt:819)
	at com.unciv.logic.city.managers.CityConquestFunctions.moveToCiv(CityConquestFunctions.kt:263)
	at com.unciv.logic.city.City.moveToCiv(City.kt:498)
	at com.unciv.logic.city.managers.CityConquestFunctions.conquerCity(CityConquestFunctions.kt:103)
	at com.unciv.logic.city.managers.CityConquestFunctions.puppetCity(CityConquestFunctions.kt:136)
	at com.unciv.logic.city.City.puppetCity(City.kt:491)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.onConquerCity(NextTurnAutomation.kt:1142)
	at com.unciv.logic.battle.Battle.conquerCity(Battle.kt:621)
	at com.unciv.logic.battle.Battle.attack(Battle.kt:151)
	at com.unciv.logic.battle.Battle.attackOrNuke(Battle.kt:93)
	at com.unciv.logic.battle.Battle.moveAndAttack(Battle.kt:48)
	at com.unciv.logic.automation.unit.BattleHelper.tryAttackNearbyEnemy(BattleHelper.kt:30)
	at com.unciv.logic.automation.unit.BattleHelper.tryAttackNearbyEnemy$default(BattleHelper.kt:16)
	at com.unciv.logic.automation.unit.UnitAutomation.tryAttacking(UnitAutomation.kt:358)
	at com.unciv.logic.automation.unit.UnitAutomation.automateUnitMoves(UnitAutomation.kt:200)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateUnits(NextTurnAutomation.kt:1004)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:87)
	at com.unciv.logic.civilization.managers.TurnManager.automateTurn(TurnManager.kt:321)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:338)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:598)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:8)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:4)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher.$r8$lambda$GFMOlD6QMgmLfgwAvPAW33Ob6HE(Unknown Source:0)
	at com.unciv.utils.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```
**Save Mods:**
```
[Civ V - Gods & Kings]
```

**Comment by yairm210** [comment]
Copy of #9722
