### ISSUE TITLE
Crash: Failed to test plugin locally

### ISSUE THREAD

**Issue by marek22k** [yairm210/Unciv#9827]
**Platform**
Debian 11-based

**Version**
4.7.9 (Build 892)

**Describe the bug**
I can no longer test my mods locally, which is very annoying. Maybe there is a solution for this? The error was not there a few versions ago.

**To Reproduce**
1. Download a mod locally
2. Symlink the mod directory in the mods directory from UnCiv
3. Create a new game with the plugin

```
$./Unciv 
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
com.unciv.logic.MissingModsException: Fehlende Modifikation(en): UnCiv Logicians
	at com.unciv.logic.GameInfo.setTransients(GameInfo.kt:598)
	at com.unciv.logic.GameStarter$startNewGame$7.invoke(GameStarter.kt:114)
	at com.unciv.logic.GameStarter$startNewGame$7.invoke(GameStarter.kt:106)
	at com.unciv.logic.GameStarter.runAndMeasure(GameStarter.kt:152)
	at com.unciv.logic.GameStarter.startNewGame(GameStarter.kt:106)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invokeSuspend(NewGameScreen.kt:307)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invoke(NewGameScreen.kt)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invoke(NewGameScreen.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.startNewGame(NewGameScreen.kt:298)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.access$startNewGame(NewGameScreen.kt:53)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$7.invokeSuspend(NewGameScreen.kt:232)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$7.invoke(NewGameScreen.kt)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$7.invoke(NewGameScreen.kt)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
<details><summary>More details</summary>

```
$ tree
.
├── GameSettings.json
├── jre
│   ├── bin
│   │   ├── jaotc
│   │   ├── java
│   │   ├── jfr
│   │   ├── jjs
│   │   ├── jrunscript
│   │   ├── keytool
│   │   ├── pack200
│   │   ├── rmid
│   │   ├── rmiregistry
│   │   └── unpack200
│   ├── conf
│   │   ├── logging.properties
│   │   ├── management
│   │   │   ├── jmxremote.access
│   │   │   ├── jmxremote.password.template
│   │   │   └── management.properties
│   │   ├── net.properties
│   │   ├── security
│   │   │   ├── java.policy
│   │   │   ├── java.security
│   │   │   └── policy
│   │   │       ├── limited
│   │   │       │   ├── default_local.policy
│   │   │       │   ├── default_US_export.policy
│   │   │       │   └── exempt_local.policy
│   │   │       ├── README.txt
│   │   │       └── unlimited
│   │   │           ├── default_local.policy
│   │   │           └── default_US_export.policy
│   │   └── sound.properties
│   ├── legal
│   │   ├── java.base
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── aes.md
│   │   │   ├── asm.md
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   ├── cldr.md
│   │   │   ├── c-libutl.md
│   │   │   ├── icu.md
│   │   │   ├── LICENSE
│   │   │   ├── public_suffix.md
│   │   │   └── unicode.md
│   │   ├── java.compiler
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── java.datatransfer
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── java.desktop
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   ├── colorimaging.md
│   │   │   ├── giflib.md
│   │   │   ├── harfbuzz.md
│   │   │   ├── jpeg.md
│   │   │   ├── lcms.md
│   │   │   ├── libpng.md
│   │   │   ├── LICENSE
│   │   │   ├── mesa3d.md
│   │   │   └── xwd.md
│   │   ├── java.instrument
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── java.logging
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── java.management
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── java.management.rmi
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── java.naming
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── java.net.http
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── java.prefs
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── java.rmi
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── java.scripting
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── java.se
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── java.security.jgss
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── java.security.sasl
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── java.smartcardio
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   ├── LICENSE
│   │   │   └── pcsclite.md
│   │   ├── java.sql
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── java.sql.rowset
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── java.transaction.xa
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── java.xml
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   ├── bcel.md
│   │   │   ├── dom.md
│   │   │   ├── jcup.md
│   │   │   ├── LICENSE
│   │   │   ├── xalan.md
│   │   │   └── xerces.md
│   │   ├── java.xml.crypto
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   ├── LICENSE
│   │   │   └── santuario.md
│   │   ├── jdk.accessibility
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── jdk.aot
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── jdk.charsets
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── jdk.crypto.cryptoki
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   ├── LICENSE
│   │   │   ├── pkcs11cryptotoken.md
│   │   │   └── pkcs11wrapper.md
│   │   ├── jdk.crypto.ec
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   ├── ecc.md
│   │   │   └── LICENSE
│   │   ├── jdk.dynalink
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   ├── dynalink.md
│   │   │   └── LICENSE
│   │   ├── jdk.httpserver
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── jdk.internal.ed
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── jdk.internal.le
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   ├── jline.md
│   │   │   └── LICENSE
│   │   ├── jdk.internal.vm.ci
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── jdk.internal.vm.compiler
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── jdk.internal.vm.compiler.management
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── jdk.jdwp.agent
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── jdk.jfr
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── jdk.jsobject
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── jdk.localedata
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   ├── cldr.md
│   │   │   ├── LICENSE
│   │   │   └── thaidict.md
│   │   ├── jdk.management
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── jdk.management.agent
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── jdk.management.jfr
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── jdk.naming.dns
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── jdk.naming.ldap
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── jdk.naming.rmi
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── jdk.net
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── jdk.pack
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── jdk.scripting.nashorn
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   ├── double-conversion.md
│   │   │   ├── joni.md
│   │   │   └── LICENSE
│   │   ├── jdk.scripting.nashorn.shell
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── jdk.sctp
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── jdk.security.auth
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── jdk.security.jgss
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── jdk.unsupported
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   ├── jdk.xml.dom
│   │   │   ├── ADDITIONAL_LICENSE_INFO
│   │   │   ├── ASSEMBLY_EXCEPTION
│   │   │   └── LICENSE
│   │   └── jdk.zipfs
│   │       ├── ADDITIONAL_LICENSE_INFO
│   │       ├── ASSEMBLY_EXCEPTION
│   │       └── LICENSE
│   ├── lib
│   │   ├── classlist
│   │   ├── jexec
│   │   ├── jfr
│   │   │   ├── default.jfc
│   │   │   └── profile.jfc
│   │   ├── jli
│   │   │   └── libjli.so
│   │   ├── jrt-fs.jar
│   │   ├── jspawnhelper
│   │   ├── jvm.cfg
│   │   ├── libawt_headless.so
│   │   ├── libawt.so
│   │   ├── libawt_xawt.so
│   │   ├── libdt_socket.so
│   │   ├── libextnet.so
│   │   ├── libfontmanager.so
│   │   ├── libinstrument.so
│   │   ├── libj2gss.so
│   │   ├── libj2pcsc.so
│   │   ├── libj2pkcs11.so
│   │   ├── libjaas.so
│   │   ├── libjavajpeg.so
│   │   ├── libjava.so
│   │   ├── libjawt.so
│   │   ├── libjdwp.so
│   │   ├── libjimage.so
│   │   ├── libjsig.so
│   │   ├── libjsound.so
│   │   ├── liblcms.so
│   │   ├── libmanagement_agent.so
│   │   ├── libmanagement_ext.so
│   │   ├── libmanagement.so
│   │   ├── libmlib_image.so
│   │   ├── libnet.so
│   │   ├── libnio.so
│   │   ├── libprefs.so
│   │   ├── librmi.so
│   │   ├── libsctp.so
│   │   ├── libsplashscreen.so
│   │   ├── libsunec.so
│   │   ├── libunpack.so
│   │   ├── libverify.so
│   │   ├── libzip.so
│   │   ├── modules
│   │   ├── psfontj2d.properties
│   │   ├── psfont.properties.ja
│   │   ├── security
│   │   │   ├── blocked.certs
│   │   │   ├── cacerts
│   │   │   ├── default.policy
│   │   │   └── public_suffix_list.dat
│   │   ├── server
│   │   │   ├── libjsig.so
│   │   │   ├── libjvm.so
│   │   │   └── Xusage.txt
│   │   └── tzdb.dat
│   ├── man
│   │   ├── ja
│   │   │   └── man1
│   │   │       ├── java.1
│   │   │       ├── jjs.1
│   │   │       ├── keytool.1
│   │   │       ├── pack200.1
│   │   │       ├── rmid.1
│   │   │       ├── rmiregistry.1
│   │   │       └── unpack200.1
│   │   ├── ja_JP.UTF-8
│   │   │   └── man1
│   │   │       ├── java.1
│   │   │       ├── jjs.1
│   │   │       ├── keytool.1
│   │   │       ├── pack200.1
│   │   │       ├── rmid.1
│   │   │       ├── rmiregistry.1
│   │   │       └── unpack200.1
│   │   └── man1
│   │       ├── java.1
│   │       ├── jjs.1
│   │       ├── keytool.1
│   │       ├── pack200.1
│   │       ├── rmid.1
│   │       ├── rmiregistry.1
│   │       └── unpack200.1
│   ├── NOTICE
│   └── release
├── mods
│   ├── Logicians
│   │   ├── Contribute.md
│   │   ├── Credits.md
│   │   ├── game.atlas
│   │   ├── game.png
│   │   ├── Images
│   │   │   ├── BuildingIcons
│   │   │   │   ├── Archive.png
│   │   │   │   ├── City Hall Extension.png
│   │   │   │   ├── City Hall.png
│   │   │   │   ├── Community Food Center.png
│   │   │   │   ├── Decentralized network.png
│   │   │   │   ├── Intelligence service.png
│   │   │   │   ├── Private military company.png
│   │   │   │   ├── Self-help group.png
│   │   │   │   ├── Spy Training Center.png
│   │   │   │   └── Wall of fire.png
│   │   │   ├── NationIcons
│   │   │   │   └── Logicians.png
│   │   │   ├── ResourceIcons
│   │   │   │   └── Foobar.png
│   │   │   ├── UnitIcons
│   │   │   │   ├── Angry Dino.png
│   │   │   │   ├── Camelia.png
│   │   │   │   ├── Clever Mayor Alice.png
│   │   │   │   ├── Clever Mayor Bob.png
│   │   │   │   ├── Dino.png
│   │   │   │   ├── Dolphin.png
│   │   │   │   ├── Duke.png
│   │   │   │   ├── Experienced Mayor Alice.png
│   │   │   │   ├── Experienced Mayor Bob.png
│   │   │   │   ├── Experimental being.png
│   │   │   │   ├── Ferris.png
│   │   │   │   ├── Firefly.png
│   │   │   │   ├── Gnu.png
│   │   │   │   ├── Gooey.png
│   │   │   │   ├── Improved Moby.png
│   │   │   │   ├── Kernel.png
│   │   │   │   ├── Little Mayor Alice.png
│   │   │   │   ├── Little Mayor Bob.png
│   │   │   │   ├── Mastodon.png
│   │   │   │   ├── Mayor Alice.png
│   │   │   │   ├── Mayor Bob.png
│   │   │   │   ├── Moby.png
│   │   │   │   ├── Naive Mayor Alice.png
│   │   │   │   ├── Naive Mayor Bob.png
│   │   │   │   ├── New Mayor Alice.png
│   │   │   │   ├── New Mayor Bob.png
│   │   │   │   ├── Nuclear U-Boot.png
│   │   │   │   ├── Religious architect.png
│   │   │   │   ├── Sakila.png
│   │   │   │   ├── Scapy.png
│   │   │   │   ├── Slonik.png
│   │   │   │   ├── Smart Mayor Alice.png
│   │   │   │   ├── Smart Mayor Bob.png
│   │   │   │   ├── Spy.png
│   │   │   │   ├── U-Boot.png
│   │   │   │   ├── Wilber.png
│   │   │   │   ├── Wise Mayor Alice.png
│   │   │   │   ├── Wise Mayor Bob.png
│   │   │   │   ├── Xue.png
│   │   │   │   └── Yumi.png
│   │   │   └── UnitPromotionIcons
│   │   │       ├── Defense Tactics.png
│   │   │       ├── Emergency.png
│   │   │       ├── First aid.png
│   │   │       ├── Missile Defense Tactics.png
│   │   │       ├── Orientation.png
│   │   │       ├── Paratrooper training.png
│   │   │       ├── Retreat.png
│   │   │       └── Travel experience.png
│   │   ├── ImageSources
│   │   │   ├── Alice.svg
│   │   │   ├── Angry Dino.svg
│   │   │   ├── Archive.svg
│   │   │   ├── Bob.svg
│   │   │   ├── Camelia.svg
│   │   │   ├── City Hall Extension.svg
│   │   │   ├── City Hall.svg
│   │   │   ├── Community Food Center.svg
│   │   │   ├── Defense Tactics.svg
│   │   │   ├── Dino.svg
│   │   │   ├── dn42.svg
│   │   │   ├── Dolphin.png
│   │   │   ├── Duke.png
│   │   │   ├── Emergency.svg
│   │   │   ├── Experimental being.svg
│   │   │   ├── FerrisColored.svg
│   │   │   ├── Ferris.svg
│   │   │   ├── Firefly.svg
│   │   │   ├── First aid.svg
│   │   │   ├── Foobar.svg
│   │   │   ├── Gnu.svg
│   │   │   ├── Gooey.jpg
│   │   │   ├── Intelligence service.svg
│   │   │   ├── Kernel.svg
│   │   │   ├── Libre deer.png
│   │   │   ├── Libre deer.svg
│   │   │   ├── Logicians Nation.svg
│   │   │   ├── Mastodon.svg
│   │   │   ├── Missile Defense Tactics.svg
│   │   │   ├── Moby.webp
│   │   │   ├── Moby.xcf
│   │   │   ├── Nuclear U-Boot.svg
│   │   │   ├── Octocat2.png
│   │   │   ├── OctocatFinish.png
│   │   │   ├── Octocat.png
│   │   │   ├── Orientation.svg
│   │   │   ├── Paratrooper training.svg
│   │   │   ├── preview.svg
│   │   │   ├── Private military company.svg
│   │   │   ├── Religious architect.svg
│   │   │   ├── Retreat.svg
│   │   │   ├── Sakila.svg
│   │   │   ├── ScapyGreen.png
│   │   │   ├── Scapy.xcf
│   │   │   ├── Self-help group.svg
│   │   │   ├── SlonikBlack.png
│   │   │   ├── Slonik.png
│   │   │   ├── Spy.svg
│   │   │   ├── Spy Training Center.svg
│   │   │   ├── Travel experience.svg
│   │   │   ├── u-boot_logo.svg
│   │   │   ├── Wall of fire.svg
│   │   │   ├── Wilber.png
│   │   │   ├── XfceColored.svg
│   │   │   ├── Xue.svg
│   │   │   ├── YumiOld.png
│   │   │   └── Yumi.svg
│   │   ├── Inspiration.md
│   │   ├── jsons
│   │   │   ├── Buildings.json
│   │   │   ├── ModOptions.json
│   │   │   ├── Nations.json
│   │   │   ├── TileResources.json
│   │   │   ├── translations
│   │   │   │   ├── completionPercentages.properties
│   │   │   │   └── German.properties
│   │   │   ├── UnitPromotions.json
│   │   │   ├── Units.json
│   │   │   └── UnitTypes.json
│   │   ├── LICENSE
│   │   ├── preview.png
│   │   ├── README.md
│   │   └── test.sh
│   ├── UnCiv-Extra-Units -> ../../git/UnCiv-Extra-Units
│   ├── UnCiv-Extra-Wonders -> ../../git/UnCiv-Extra-Wonders
│   ├── UnCiv-Great-Farmer -> ../../git/UnCiv-Great-Farmer
│   └── UnCiv-Logicians -> ../../git/UnCiv-Logicians
├── SaveFiles
│   └── Autosave
├── Unciv
├── Unciv.jar
└── Unciv.json

90 directories, 432 files
$ cd mods/UnCiv-Logicians
$ ls
Contribute.md  Credits.md  game.atlas  game.png  Images  ImageSources  Inspiration.md  jsons  LICENSE  preview.png  README.md  test.sh
```
</details>

**Expected behavior**
Creates a new game

**Screenshots**
![pic](https://github.com/yairm210/Unciv/assets/46723399/c92dd8a5-e736-4f68-bbba-589a8beb7b69)

**Comment by marek22k** [comment]
Also does not work without symbolic link.

**Comment by marek22k** [comment]
Only works when I create the symbolic link without `-`:
```sh
$ ln -s ../../git/UnCiv-Logicians/ "UnCiv Logicians"
```

**Comment by marek22k** [comment]
> Took the liberty to edit your OP as it was intended. github markdown allowing some html elements is quirky. The details element for example absolutely needs an empty line after the summary (or after itself if it has no summary), or ~all hell breaks loose~ stuff disappears.

I don't use these tags that often. Thanks!

> And also just unreflected - why not go for and stay with all mod links having names _as if you'd published to github and downloaded from there_? Seems like a recommendable practice anyway.

The reason is quite simple. On Codeberg, where I primarily host my mods, they all have the prefix "UnCiv". This allows me to do the following:
```sh
ln -s ../git/UnCiv-* .
```
Then I don't have to link each mod individually. My update script for UnCiv, which I have "built", deletes the UnCiv folder with each update and creates it again. Thereby all mod symlinks are gone. (And yes, I could also write a script that links all my mods, but a command is just easier).
When I play UnCiv "seriously" on the PC, I use the Flatpak version myself.
