### ISSUE TITLE
Crash on next turn 

### ISSUE THREAD

**Issue by 3pticha** [yairm210/Unciv#9876]
**Platform:** Android
**Version:** 4.7.11 (Build 895)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: SM-X200
API Level: 33

--------------------------------

**Message:**
```
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1470)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.useGoldForCityStates(NextTurnAutomation.kt:309)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.useGold(NextTurnAutomation.kt:330)
	at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:83)
	at com.unciv.logic.civilization.managers.TurnManager.automateTurn(TurnManager.kt:326)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:376)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:598)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:8)
	at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:4)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher.$r8$lambda$GFMOlD6QMgmLfgwAvPAW33Ob6HE(Unknown Source:0)
	at com.unciv.utils.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```
**Save Mods:**
```
[Civ V - Gods & Kings]
```

[unciv_bug_report_Ethiopia.-.394.turns.txt](https://github.com/yairm210/Unciv/files/12241425/unciv_bug_report_Ethiopia.-.394.turns.txt)

**Comment by yairm210** [comment]
Managing to go to 'next turn' fine for me 🤔 

How is it for you if you just push the 'next turn' button without doing anything?
Did you do anything related to city states this turn?

**Comment by yairm210** [comment]
I'll try on Android, so far I've been trying and succeeding on Desktop

**Comment by yairm210** [comment]
Nope, working fine on my Android as well 🤔 
Very odd
Especially the place at which it fails, which seems to indicate something truly bizarre, I can only guess at what's happening here

**Comment by yairm210** [comment]
Going through it I'm sure you're right - that when allying with a civ we reveal new tiles that may reveal a new civ, and then the list of civs we started with is concurrently modified
If so this should be an easy fix and @3pticha can tell us if it's solved

Will release on version 4.7.13
