### ISSUE TITLE
Crash civ 6 Mod 

### ISSUE THREAD

**Issue by neomatixx** [yairm210/Unciv#9905]
**Platform:** Android
**Version:** 4.7.12-patch2 (Build 898)
**Rulesets:** [Civ V - Gods & Kings, Civ6 mod, Civ V - Vanilla, RekMOD, 5Hex Tileset, Civ6 Tileset]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: SHIFT6m
API Level: 26

--------------------------------
Crash occurs after i finished building the university of sankore

**Message:**

**Comment by yairm210** [comment]
Not enough information
No game attached, and no stacktrace
Please add both

**Comment by yairm210** [comment]
Closing due to lack of data

**Comment by neomatixx** [comment]
**Platform:** Android
**Version:** 4.7.13 (Build 899)
**Rulesets:** [Civ V - Gods & Kings, Civ6 mod, Civ V - Vanilla, RekMOD, 5Hex Tileset, Civ6 Tileset]
**Last Screen:** `com.unciv.ui.screens.mainmenuscreen.MainMenuScreen`

--------------------------------

Device Model: SHIFT6m
API Level: 26

--------------------------------


**Message:**
```
java.lang.NullPointerException
at com.unciv.logic.trade.TradeOffer.<init>(TradeOffer.kt:17)
at com.unciv.logic.trade.TradeLogic.getAvailableOffers(TradeLogic.kt:25)
at com.unciv.logic.trade.TradeLogic.<init>(TradeLogic.kt:17)
at com.unciv.logic.automation.civilization.NextTurnAutomation.respondToTradeRequests(NextTurnAutomation.kt:121)
at com.unciv.logic.automation.civilization.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:60)
at com.unciv.logic.civilization.managers.TurnManager.automateTurn(TurnManager.kt:326)
at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:376)
at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:596)
at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:8)
at com.unciv.ui.screens.worldscreen.WorldScreen$nextTurn$1.invoke(Unknown Source:4)
at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
at com.unciv.utils.CrashHandlingDispatcher.$r8$lambda$GFMOlD6QMgmLfgwAvPAW33Ob6HE(Unknown Source:0)
at com.unciv.utils.CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)

```

14.08.2023 15:19:28 Yair Morgenstern ***@***.***>:
