### ISSUE TITLE
I don't know why this bug keeps showing please help me... or at least explain it to me...

### ISSUE THREAD

**Issue by vnjery1** [yairm210/Unciv#9937]
**Platform**
Operating system type, major version, architecture (64/32 bit).

**Version**
Where you got the game and the exact version number.

**Describe the bug**

**Platform:** Android
**Version:** 4.7.14 (Build 900)
**Rulesets:** [Uncivilized Awakening, Victoria II Music, Modern Civilizations, Taube s Australia, Medieval Civilizations, Project Holy Roman Empire, ph bonifacio unciv, Modern Russia, 3rd and 4th Unique Component, Classical  World Scout Sapper plus Promotions, North Korea, Project Montenegro, Warfare Expanded Lite, Unciv Fermentation, American Civil War mod, Unciv City State Icons, Better ruins Lite, More Fauna And Flora, Resourceplus, AbsoluteUnits, Ice Breakers, Extra Wonders, Uncivilized Expansion, Civ Army Color Style Sheet, Warfare Edited, Hyperborea, vox populi pantheons, Future Expansion, WW1 Nations, Canada, Raze anything, Icon Reskin, BetterMountainFH, Diminishing Returns, Civ6 Stat Icons, Great Person Wonders, Expanded Warfare, Assyria buffed for Unciv, Urban Area, Better Workers, Kazan Khanate, Han Dynasty China, capture GP, Unciv America Buff, Project Manchuria, Community Maps, Yet Another Civilization Mod, Project Felipe, BabylonUI, Dimensiondogs scaling difficulties, Pakistan Nation Unciv, Agony In Anatolia Mod, Glorious Rome, Samnites, Super Sandbox, Byzantium Buffed, Power to People GnK, Greece plus The Middle East, Yet Another Music Pack, AquaExtension GAK, the Coexistence in harmony, Holy Warriors, ReligionPlus, LostTec, 6 Eras, Deminishing Returns Brutal Edition, Military and Religion Specialists, Project Tondo, Turkic Civilizations, Unciv Vanilla Music Pack, ComplexHistory, Greater Improvements, philosophy mod, MaOr Difficulties, WW2 Nations, Chaos Generation, Barbarians but Better, Dimensiondog s Districts, All units can be automated, Civ5 CityState Music, Ancient Civilizations, Nusantara Civilizations, 5HexNBNB, Yet Another Resource Mod, Illyrian Civilization, The Great Unciv Rework, Swamp Expansion, 5Hex Tileset, Better ruins, Leader Mission 2 Rising Power, Modern Russia unciv mod, Extra Promotions, Soviet Union, Horses and Iron mod, Policy mod, Higher quality builtin sounds, More Speeds, AbsoluteUnitsXL, Enlightenment, Brave New World, Scouty Scout, LM DLC War or Peace, Fix Iroquois, Extra Buildings, wonders in different eras mod, Project Kaigun, moREsources, Nat5 Design, Civ6 Icons, Future Edited, More Luxuries, Algeria, Hodgepodge mod, Unciv WWII, Re Add National Treasury BNW Unciv, Difficulty_Sandbox, useful alltech, Capital Domination, ReSound, Honor Wonders, Civ5Nations, Tyretes Tileset, Additional Music Ambient, Civ style set by Bucketeer, Greek Civ Split, Repairing Improvements in older mods, No Fog Of War, Resource Recyclers, Slow Tech, Useful Mountain, Civ6 mod, Better Pantheons Lite, unciv finland mod, Civ6 Tileset, More Challenges, High Explosives Lite, Ukraine Mod, Better Pantheons, Palengke, Super Quick Speed, Civ V - Gods & Kings, Leaders Plus, BB 2 m.crzr, Greece and The Middle East Music, Additional Music Various, The Barbarians, Outpost Mod, China Plus, RekMOD, Classical Harbors, Boosted Settler, Project Serbia, Leader Mission, useful allres, Uncivilized Enhancer, Longer Victories, Singapore Nation Unciv, Higher Quality City Ambience Sounds, Latin American_Civs, Dacia Unciv mod, Mitteleuropa and Balkans, Congress RP, Only Mod Civilizations, Fall of Rome, Strategic Resource Visibility, Unciv Religion Plus, Civ V - Vanilla, The Netherlands mod, MAP OF INDIAN SUBCONTINENT, Chronicle_Files, Rome Improvements, hexatopia, Chariot Archers are Mounted, Civ6 NLB Edition Tileset, Vichy France, CS Rework, Togglemod Sightbonus, Arial expanded, Project Lantaka, Civ6 Nations for Unciv, Cheaper National Wonders, Extra Difficulties for Religion enthusiasts, Closer Cities Distance of 0, Project Rikugun, Closer Cities Distance of 1, More Natural Wonders, Unciv The New Order The Great World War, Mapping Tools for Unciv]
**Last Screen:** `com.unciv.ui.screens.mapeditorscreen.MapEditorScreen`

--------------------------------

Device Model: V2110
API Level: 33

--------------------------------

**Message:**
```
java.lang.OutOfMemoryError: Failed to allocate a 160 byte allocation with 30496 free bytes and 29KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at com.unciv.ui.components.tilegroups.TileGroup.<init>(TileGroup.kt:50)
	at com.unciv.ui.components.tilegroups.TileGroup.<init>(TileGroup.kt:20)
	at com.unciv.ui.screens.mapeditorscreen.EditorMapHolder.addTiles(EditorMapHolder.kt:73)
	at com.unciv.ui.screens.mapeditorscreen.EditorMapHolder.<init>(EditorMapHolder.kt:46)
	at com.unciv.ui.screens.mapeditorscreen.MapEditorScreen.newMapHolder(MapEditorScreen.kt:181)
	at com.unciv.ui.screens.mapeditorscreen.MapEditorScreen.applyRuleset(MapEditorScreen.kt:236)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorModsTab.applyControls(MapEditorModsTab.kt:98)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorModsTab.access$applyControls(MapEditorModsTab.kt:24)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorModsTab$5.invoke(MapEditorModsTab.kt:66)
	at com.unciv.ui.screens.mapeditorscreen.tabs.MapEditorModsTab$5.invoke(MapEditorModsTab.kt:66)
	at com.unciv.ui.components.input.ActivationActionMap.activate(ActivationActionMap.kt:56)
	at com.unciv.ui.components.input.ActorAttachments.activate(ActorAttachments.kt:42)
	at com.unciv.ui.components.input.ActivationExtensionsKt.activate(ActivationExtensions.kt:17)
	at com.unciv.ui.components.input.ActivationListener.tap(ActivationListener.kt:15)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener$1.tap(ActorGestureListener.java:52)
	at com.badlogic.gdx.input.GestureDetector.touchUp(GestureDetector.java:209)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener.handle(ActorGestureListener.java:125)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:87)
	at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:426)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:472)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1582)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)

```
**To Reproduce**

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yairm210** [comment]
I'm guessing a huge map with loads of players
Probably bigger than the default sizes, and to the point where it warns 'you may get out of memory errors' when creating
If so, this is self-inflicted
